DataDog/dd-trace-go

- tracer/context.go
- tracer/example_context_test.go
- tracer/span.go
- tracer/span_test.go
- tracer/tracer.go
makes it easier to do things like:
```
foo(span.Context(ctx), ...)
```
@elijahandrews
> span: add Span.Context method

- tracer/contrib/tracegrpc/compile.sh
- tracer/contrib/tracegrpc/fixtures_test.go
Fixes the build, as seen e.g. in failures for https://github.com/DataDog/dd-trace-go/pull/17
> Update gRPC generated code to latest protobuf version

- circle.yml
- tracer/contrib/gin-gonic/gintrace/gintrace_test.go
- tracer/contrib/gorilla/muxtrace/muxtrace_test.go
- tracer/contrib/tracegrpc/grpc_test.go
- tracer/tracer.go
- tracer/tracer_test.go
- tracer/transport.go
- tracer/transport_test.go
Adds integration tests for the latest ``dd-trace-agent``. It targets the current implementation that is the ``v0.1`` API.
> [ci] integration tests

- tracer/contrib/gin-gonic/gintrace/gintrace_test.go
- tracer/contrib/gorilla/muxtrace/muxtrace_test.go
- tracer/contrib/tracegrpc/grpc_test.go
- tracer/encoder.go
- tracer/encoder_test.go
- tracer/span_test.go
- tracer/tracer.go
- tracer/tracer_test.go
- tracer/transport.go
- tracer/transport_test.go
* supports the ``datadog-trace-agent`` API ``v0.3``
* adds all integration tests for the JSON encoding
* it doesn't use a flat span list because it's incompatible with the new API
* in another PR we have to optimize the path to rebuild traces. We can easily remove this step if we refactor the code using channels. In the meantime I've added this step to prevent any changes to the current implementation because ``msgpack`` will be a big change and I don't want to introduce two big things to debug in case of errors
> [core] using the agent API v03

- tracer/contrib/gin-gonic/gintrace/gintrace_test.go
- tracer/contrib/gorilla/muxtrace/muxtrace_test.go
- tracer/contrib/tracegrpc/grpc_test.go
- tracer/encoder.go
- tracer/encoder_test.go
- tracer/tracer.go
- tracer/tracer_test.go
- tracer/transport.go
- tracer/transport_test.go
Adds support to the trace-agent API version ``0.3`` with msgpack format. The agent API also support JSON encoding if users want to send their traces manually.
If a 404 is hit, it means that the API is not available and so we have to downgrade the API to a stable version (``jsonEncoder`` with the ``v0.2`` API at the time of writing).
The flow is:
* use ``msgpackEncoder`` by default
* at the first call to the ``traces`` endpoint, read the status code
* if the response is a ``404``, downgrade the API and the encoder and re-try the call with the stable version
* in any other cases, keep the current encoder and API version.
A ``5xx`` or ``4xx`` doesn't mean we should change the encoder because we could have a different problem. Further improvements will come with a stable agent API + …
> [core] add support for Msgpack encoder

- tracer/transport.go
- tracer/transport_test.go
Previously, it wasn't possible to use a custom delivery url since `newHTTPTransport` was unexported. This adds an exported `NewHTTPTransport` that returns the opaque Transport type.
> Add exported NewHTTPTransport func

- tracer/span.go
- tracer/span_test.go
For parity with the [Ruby client](https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/span.rb#L67-L73), this will set the `error.type` and `error.stack` tags.
I just went with [debug.Stack](https://golang.org/pkg/runtime/debug/#Stack) for simplicity. The downside is that this includes some lines from within this package. It could be changed to use [runtime.Callers](https://golang.org/pkg/runtime/#Callers) to ignore the first part of the stack, like [honeybadger does](https://github.com/honeybadger-io/honeybadger-go/blob/master/error.go#L55)
> Populate error.type and error.stack tags

- tracer/span.go
- tracer/tracer.go
- tracer/tracer_test.go
It's technically possible to create a span without a service, and this is valid, it should inherit the service from its parent in that case. However root spans have no parent so it's impossible to infer/guess a valid name. This patch provides a default value (`go`) in that case.
Our go implementation (compared to our Python and Ruby) really makes it harder to have no service as it has explicit CreateRoot and CreateChild calls. Still, it's probably good to have similar behaviours in all languages.
> [span] adding a default 'go' service is none is given

- tracer/contrib/gorilla/muxtrace/muxtrace.go
- tracer/contrib/gorilla/muxtrace/muxtrace_test.go
- add missing `http.url` meta to the mux integration
- update tests accordingly
> Add http.url to mux integration

- circle.yml
- tracer/transport.go
- tracer/transport_test.go
**Breaking change**
The tracing client uses the port ``8126``. Using a Trace Agent older than version ``5.11.0`` will **not** work with the current version of the client.
> [core] drop legacy port 7777 in favor of 8126

- tracer/span.go
- tracer/tracer.go
- tracer/tracer_test.go
This should make the go client on par with the Python & Ruby ones, allowing application to set per tracer meta values (AKA tags).
> [tracer] allowing SetMeta at tracer level

- tracer/transport.go
- tracer/transport_test.go
Pre-sampling on the agent side requires this header to be here,
to know how many traces are in the payload without decoding the
payload for real.
> [presampler] Adding X-Datadog-Trace-Count header

- tracer/example_context_test.go
- tracer/tracer.go
- tracer/tracer_test.go
This PR addresses https://github.com/DataDog/dd-trace-go/issues/65
I've created `tracer.Span`, which is allows us to replace:
``` go
span := tracer.NewChildSpanFromContext("name", ctx)
ctx = span.Context(ctx)
```
with:
``` go
span, ctx := tracer.NewChildSpanWithContext("name", ctx)
```
> Add tracer.NewChildSpanFromContext

- tracer/contrib/tracegrpc/grpc.go
- tracer/contrib/tracegrpc/grpc_test.go
Previously we were parsing the service from the rpc endpoint but we were never actually using the service name that was provided.
Note that while the API doesn't change this will rename every service so we may want make this an option instead to enable it going forward. I'm open to whichever is preferred!
> grpc: Use provided service name for all spans

- docker-compose.yml
- tracer/contrib/elastictraced/elastictraced.go
- tracer/contrib/elastictraced/elastictraced_test.go
- tracer/contrib/elastictraced/example_test.go
- tracer/contrib/elastictraced/quantize.go
- tracer/contrib/elastictraced/quantize_test.go
TracedHTTPClient hooks into the http.Transport to trace requests and
capture spans for Elasticsearch. It's generic enough that it could be
used for other Elasticsearch clients that allow you to override the http
client.
The resource is quantized following the style used in [dd-trace-py](https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/elasticsearch/quantize.py)
The tests and example show the pattern for tracing the elastic client,
specifically using elastic.v5. Older versions do not support calling
`Do` with a `context` so they won't apply. But in theory this should be
compatible with new version going forward.
docker-compose is updated to run ES for the integration tests.
> elastic: Add traced HTTPClient for client

- tracer/contrib/elastictraced/elastictraced.go
- tracer/contrib/elastictraced/elastictraced_test.go
Attaches the `HTTPCode` in the span only if we don't have errors while reading the `Transport` response. We hit an `invalid memory address or nil pointer dereference` error.
> [elastictraced] check the StatusCode only if there are no errors

- tracer/contrib/elastictraced/elastictraced.go
- tracer/contrib/elastictraced/elastictraced_test.go
Fixes the resource names to be correct in the error case, fixing an issue introduced in #71
> elastic: Quantize span in both error and success cases

- tracer/span.go
- tracer/time.go
- tracer/time_windows.go
- tracer/time_windows_test.go
This switches from time.Now to GetSystemTimePreciseAsFileTime to improve the precision of the timestamps and duration computations from ~1ms to ~1µs. This comes at a performance cost since this call is much slower than the original one. I've run benchmarks in my VM and it makes a ~10x difference:
BenchmarkNormalTimeNow-2        100000000               12.7 ns/op
BenchmarkHighPrecisionTime-2    20000000               101 ns/op
This remain very fast, so I think the precision gain is worth the performance cost.
> Improve time precision on Windows

- tracer/span.go
Be explicit that `SetMetric()` doesn't create a Datadog metric.
> [docs] explicit that SetMetric() only add a tag

- tracer/context_test.go
- tracer/ext/system.go
- tracer/span_test.go
- tracer/tracer.go
- tracer/tracer_test.go
This PR automatically adds the process id of the current process as a metadata when creating a new root span.
> Add pid to root spans

- tracer/tracer.go
- tracer/tracer_test.go
when called on a specific tracer, it should create the span from this tracer, not from the default one
> fix NewChildSpanFromContext

- tracer/span.go
- tracer/span_test.go
I noticed that ddtrace-python had a method that allowed a user to update a Span's metadata with a map. I thought this feature would be similarly useful and easy to add.
> Added SetMetas(), similar to ddtrace-python's set_tags()

- tracer/span_test.go
Fix the test TestSpanSetMetas in span_test.go.
We now add by default the process_id to the span.Metas. This test would break by checking span.Metas lenght and L64 and L76
> Fix test (process_id in metas)

- tracer/contrib/sqltraced/parsedsn/mysql/dsn.go
- tracer/contrib/sqltraced/parsedsn/mysql/utils.go
If you do include a custom TLS config in the MySQL DSN, this code will return an error because it hasn't been registered in this particular tlsConfigRegister (and there isn't even a function available for doing so), even if you correctly register with the go-sql-driver/mysql driver. Since the TLS config isn't used in any of the trace metadata, we can just remove this bit.
> Remove tlsConfigRegister in MySQL DSN parser

- tracer/ext/tracer.go
- tracer/tracer.go
- tracer/transport.go
Adds the following headers so that Trace Agent can report it as a metrics:
```
'Datadog-Meta-Lang': 'go',
'Datadog-Meta-Lang-Version': 'go1.7',
'Datadog-Meta-Lang-Interpreter': 'gc',
'Datadog-Meta-Tracer-Version': 'v0.5.0',
```
> Add meta about lang in the payload header

- contrib/garyburd/redigo/redigo_test.go
- contrib/go-redis/redis/redis_test.go
- contrib/gocql/gocql/gocql_test.go
- contrib/google.golang.org/grpc/grpc_test.go
- contrib/olivere/elastic/elastictrace_test.go
- tracer/contrib/elastictraced/elastictraced_test.go
- tracer/contrib/go-redis/tracedredis_test.go
- tracer/contrib/gocql/gocqltrace_test.go
- tracer/contrib/redigo/redigotrace_test.go
- tracer/contrib/tracegrpc/grpc_test.go
- tracer/tracer.go
**Note:** it's a breaking change in the core API, but there is no other solution here to prevent this race condition from happening.
> Fix race condition while accessing DebugLoggingEnabled attribute

- tracer/encoder.go
- tracer/transport.go
Here we do **2 things**:
1. We use a **new buffer** before sending the encoder through the network to avoid race conditions (the new buffer uses the same underlying data, so there is no performance overhead)
2. We **stop fully reading the response**, to avoid those logs:
```
Unsolicited response received on idle HTTP channel starting with "HTTP/1.1 400 Bad Request\r\nContent-Type: text/plain; charset=utf-8\r\nConnection: close\r\n\r\n400 Bad Request"; err=<nil>
```
Actually, this *trick* is according to people able to improve the client performances by reusing persistent connections, but it's not documented in the official golang documentation. Moreover, we had those unwanted logs by doing this. So my point here is we should not use this unsafe trick in such an important part of the trace …
> Use a new buffer to avoid race conditions

- Gopkg.toml
- tasks/vendors.rb
The previous approach relied on `go get` and `godep` to get / update internal dependencies. Since we're vendoring, we don't need a vendor tool, but having `dep` to manage the `vendor` folder helps us keeping stable commits.
> [tools] add dep to manage vendor folder

- Gopkg.toml
- opentracing/config.go
- opentracing/config_test.go
- opentracing/context.go
- opentracing/context_test.go
- opentracing/span.go
- opentracing/span_test.go
- opentracing/tracer.go
- opentracing/tracer_test.go
- tasks/common.rb
- tasks/testing.rb
- tasks/vendors.rb
- tracer/span.go
Compatibility layer for [OpenTracing](http://opentracing.io/) specification. The PR implements:
* a OT-compatible `Tracer`
* a `Configuration` struct to configure a Datadog Tracer
* the `Span` and `SpanContext` implementation
* the compatibility layer for OpenTracing `Tags`
This PR is an initial work to support entirely OpenTracing. In the current state, the OT-compatible `Tracer` wraps our previous implementation, so internals are the same. To set the Datadog Tracer as a `GlobalTracer`, you should add the following code to initialize the `Tracer`:
```go
import (
// datadog namespace is suggested
datadog "github.com/DataDog/dd-trace-go/opentracing"
opentracing "github.com/opentracing/opentracing-go"
)
func Example_initialization() {
// create a Tracer configuration
config := …
```
> [opentracing] add Compatibility Layer

- opentracing/span.go
- opentracing/span_test.go
- opentracing/tags.go
Our system requires some extra tags to provide better stats. This change leverage the `Span.SetTag()` method so that it can be used to set internal Span values that are not part of the OpenTracing specification. For instance if you have an OpenTracing `Span` you can:
```go
span := opentracing.StartSpan("web.request")
span.SetTag("span.type", "http")                      // sets the Span.Type
span.SetTag("service.name", "db-cluster")             // sets the Span.Service
span.SetTag("resource.name", "SELECT * FROM users;")  // sets the Span.Resource
```
> [opentracing] add Tags compatibility layer for Service, Resource and SpanType

- README.md
- opentracing/doc.go
- opentracing/example_context_test.go
- opentracing/example_test.go
- opentracing/example_tracing_test.go
Provide a better `README` and more Godoc with examples (they're the same as the current state of [OpenTracing Go](https://github.com/opentracing/opentracing-go) documentation).
> [opentracing] provide more documentation

- opentracing/tracer.go
- opentracing/tracer_test.go
When creating an OpenTracing `Tracer`, the `datadog.DefaultTracer` is replaced with the underlying implementation. This is legit since it happens only if you want to use the OpenTracing API and integrations like `gin-gonic` will work properly using the OpenTracing tracer.
This implementation is temporary and will be removed once all integrations have been ported to the OpenTracing API.
> [opentracing] ensure that creating a new OpenTracing tracer replaces the DefaultTracer for integrations

- opentracing/propagators.go
- opentracing/tracer.go
- opentracing/tracer_test.go
Implements a `TextMapPropagator` for TextMap and HTTPHeaders `SpanContext` propagation. This is used to propagate/read `SpanID` and `TraceID` to/from another process. Usage is described in [OpenTracing documentation](https://github.com/opentracing/opentracing-go#serializing-to-the-wire).
> [opentracing] Inject and Extract method for Distributed Tracing

- README.md
- opentracing/example_test.go
- opentracing/span.go
- opentracing/tracer.go
- opentracing/tracer_test.go
In our documentation, suggest to use `ddtrace` instead of `datadog` as package namespace.
> [opentracing] change suggested namespace to ddtrace

- tracer/encoder.go
- tracer/encoder_test.go
- tracer/tracer_test.go
- tracer/transport.go
- tracer/transport_test.go
After several race conditions / unexpected panics due to reusing the underlying buffers via a pool of encoders, we need to make the following changes:
- **allocating a new encoder each time we flush** (= a new `bytes.Buffer`)  => performance overhead, but necessary since neither the `encoder` nor the `bytes.Buffer` is thread-safe.
- **removing the encoder pool** who was not used anyway, since the worker was working synchronously (flush traces -> encode traces -> send the encoder -> return the encoder -> new cycle for the worker). 
_Note:_ Since [we only flush every 2s](https://github.com/DataDog/dd-trace-go/blob/master/tracer/tracer.go#L16), allocating a new encoder at every flush is acceptable.
This PR needs to be merged to avoid the apps using our go tracer from panicking.
However, we …
> Fix encoder pool issues

- opentracing/span.go
- opentracing/span_test.go
The SetTag function accept an interface{} for the value parameter but it panic when the value is not a string.
> SetTag convert value to string instead of expected a string

- tracer/buffer.go
10k is quite low, we already get some real-world use cases with more than that.
Also, the upcoming Ruby PR has a setting of 100k, so it would make sense to have them use the same value: https://github.com/DataDog/dd-trace-rb/pull/247/files#diff-7bbc8937db718dfbfe46ab70654b47ccR19
> [tracer] increase span buffer from 10k to 100k

- tracer/ext/priority.go
- tracer/span.go
- tracer/span_test.go
Allow usage of `-1` as a priority sampling value, `2` was already handled, but negative values were blocked.
> tracer: dual sampling, make sure priorities -1 and 2 are handled

- opentracing/config.go
- opentracing/config_test.go
- opentracing/tracer.go
- opentracing/tracer_test.go
This change allows users to configure global tracer tags that will be
added to every span automatically.
It additionally improves documntation wording and styling to be more Go
idiomatic.
> opentracing: enable global tags

- opentracing/span.go
- opentracing/span_test.go
- opentracing/tags.go
This change allows setting a tag of name Error ("error") having a value
of error (but covers for other types to) which will in turn set the
error properties of the Span internally.
Fixes #144
> opentracing: set Span error when adding error tags

- opentracing/tracer.go
This fix is to use the propagated trace id when setting the `sampled` field in a propagated span. 
the `Sampled` function is called in `NewRootSpan` and determines whether or not a span is sampled based on its `TraceID`. However, when a trace is propagated from another process, its `TraceID` and `ParentID` become that of the parent SpanContext after the new root span is created. The TraceID that determines sampling should be the SpanContext's trace id propagated from the previous process in order to consistently have full sampled spans.  
Adding another call to `Sample` after setting the `TraceID` and `ParentID` ensures this.
> opentracing: sample propagated spans after setting trace id

- opentracing/config.go
- opentracing/propagators.go
- opentracing/propagators_test.go
- opentracing/tracer.go
- opentracing/tracer_test.go
This change introduces the possibility of customizing the [`opentracing.TextMap`](https://godoc.org/github.com/opentracing/opentracing-go#BuiltinFormat) propagator that is used in the tracer. A default implementation is provided which exposes a constructor that allows configuring the headers used when attaching values into the map.
If users would want to override the default TextMap propagator, an example configuration could be:
```go
cfg := ddtrace.NewConfiguration()
cfg.TextPropagator = ddtrace.NewTextMapPropagator("ot-baggage-", "x-trace-id", "x-parent-id")
```
This will prefix all baggage header keys with "ot-baggage-" and will define trace and parent map keys as "x-trace-id" and "x-parent-id".
> opentracing: allow customizing propagator headers

- .circleci/config.yml
This change fetches the project's dependencies before waiting for the
services to be up. This is a more logical chain of events and a better
use of time.
Further reduces build time by approx. 25 seconds.
> build: reduce build speed

- contrib/database/sql/sqltest/sqltest.go
This will allow us to see more details about the reasons behind the
crashings with a potentially flaky test.
> contrib/database/sql: improve error handling in tests

- ddtrace/tracer/encoder.go
- ddtrace/tracer/encoder_test.go
- ddtrace/tracer/tracer_test.go
- ddtrace/tracer/transport.go
- ddtrace/tracer/transport_test.go
The encoder was overly engineered. This change simplifies the implementation and adds some benchmarks.
> ddtrace/tracer: simplify encoder

- ddtrace/tracer/span.go
- ddtrace/tracer/span_test.go
- ddtrace/tracer/util.go
This change adds benchmarks for SetTag and increases the performance of
setting string values, which is our most common scenario.
```
name            old time/op    new time/op    delta
SetTagString-4     178ns ± 0%      99ns ± 0%  -44.16%
name            old alloc/op   new alloc/op   delta
SetTagString-4     16.0B ± 0%      4.0B ± 0%  -75.00%
name            old allocs/op  new allocs/op  delta
SetTagString-4      2.00 ± 0%      1.00 ± 0%  -50.00%
```
> ddtrace/tracer: increase performance of SetTag

- ddtrace/tracer/option.go
- ddtrace/tracer/textmap.go
- ddtrace/tracer/textmap_test.go
- ddtrace/tracer/tracer.go
Our propagator will support both text map, binary and possibly other formats, so it would be confusing (and counter intuitive) to call it _text map_. We won't be able to change this later if we want to keep backwards compatibility.
> ddtrace/tracer: rename TextMapPropagator to Propagator

- contrib/olivere/elastic/elastictrace.go
- contrib/olivere/elastic/elastictrace_test.go
As per the official documentation for (http.Request).ContentLength:
> For client requests, a value of 0 with a non-nil Body is also treated as unknown.
For this reason, it was an error to have it here and was stopping the
body to be recorded in cases where the length was unknown.
> contrib/olivere/elastic: remove max condition on peek function

- contrib/garyburd/redigo/redigo.go
- contrib/go-redis/redis/redis.go
- ddtrace/ddtrace.go
- ddtrace/internal/globaltracer.go
- ddtrace/mocktracer/mockspan.go
- ddtrace/mocktracer/mockspan_test.go
- ddtrace/tracer/span.go
- ddtrace/tracer/textmap_test.go
This change removes the possibility of misusing the API in multiple ways by chaining calls. It is a result of feedback from various teams going through the migration process.
Before, it was possible to do:
```go
span.SetTag("A", "B").
SetTag("C", "D").
SetTag("E", "F")
```
Now, the only possibility remains:
```go
span.SetTag("A", "B")
span.SetTag("C", "D")
span.SetTag("E", "F")
```
We should have only one way to do the same thing.
> ddtrace: remove possibility of chaining

- ddtrace/tracer/span.go
Removes a bunch of left-over return calls from https://github.com/DataDog/dd-trace-go/pull/215 that served no purpose.
> ddtrace/tracer: remove redundant return calls

- ddtrace/opentracer/tracer.go
- ddtrace/opentracer/tracer_test.go
This change alters the instantiation of the Opentracing method to one
that is more in line with other implementations in the wild, meaning
that now the call is named `New` and it returns the
`opentracing.Tracer` which can be used with
`opentracing.SetGlobalTracer` as per the official documentation.
This is more useful when using libraries such as `opentracing-contrib`
where the tracer is needed, and could potentially reduce some calls to
`opentracing.GlobalTracer`.
> ddtrace/opentracer: s/Start/New and return tracer

- ddtrace/tracer/errors.go
- ddtrace/tracer/spancontext.go
- ddtrace/tracer/spancontext_test.go
- ddtrace/tracer/tracer_test.go
This change ensures that once the span buffer reaches capacity, we will
not be handling nor flushing the trace anymore since we can no longer
keep track of the spans that are part of it. Otherwise, the flush
condition is met prematurely when not all spans in the buffer are
completed and we are open for a race condition: modifying a span while
flushing.
> ddtrace/tracer: prevent trace from acknowledging more spans after cap is reached

- tracer/ext/tracer.go
Bump to 0.6.1. It has no effect as this isn't the released tag.
We should bump it every time, right before a release.
> Bump tracer version

- contrib/gin-gonic/gin/gintrace_test.go
- contrib/google.golang.org/grpc.v12/grpc_test.go
- contrib/google.golang.org/grpc/grpc_test.go
- ddtrace/tracer/context.go
- ddtrace/tracer/context_test.go
This change provides for a safer API to SpanFromContext which assures
that the value `nil` is not returned anymore. This was confusing
and could potentially crash an app where one would attempt to call
methods on the span without formerly checking its non-nil value.
Now, when a span is not found, the second return value will be `false`
and the returned span will be a no-op, allowing users to call methods on
it without having to explicitly check that the span was found in the
context, if there is no interest to, while at the same time providing
the option to do so.
> ddtrace/tracer: improve SpanFromContext API

- contrib/gorilla/mux/mux.go
- contrib/gorilla/mux/mux_test.go
This PR fixes a bug reported here: https://github.com/DataDog/dd-trace-go/issues/173
This fixes a `nil pointer dereference` error, that was triggered when the `NotFoundHandler` or the `MethodNotAllowedHandler` were called.
> contrib/gorilla/mux: empty route bug fixed

- contrib/gocql/gocql/gocql.go
- contrib/gocql/gocql/gocql_test.go
- contrib/gocql/gocql/option.go
Adds `WithResourceName` option to `WrapQuery` to allow specifying the resource name (query statement) in performance-critical environments where repeatedly calling `query.String()` can become costly.
> contrib/gocql/gocql: add WithResourceName option.

- ddtrace/mocktracer/mocktracer.go
This used to create problems when testing code. Normal code was using
and expecting the default headers, but the mocktracer was not. It was
causing inconsistencies and problems.
> ddtrace/mocktracer: use the same propagation headers as the regular tracer.

- contrib/internal/httputil/trace.go
- contrib/internal/httputil/trace_test.go
Regular HTTP/1.x ResponseWriters implement http.Hijacker. This allows
for services such as WebSockets (among others) to make use of this
functionality and enable us to trace them.
This change adds support for http.Hijacker when the ResponseWriter
implements it.
> contrib/internal/httputil: implement http.Hijacker

- contrib/gorilla/mux/mux.go
- contrib/gorilla/mux/mux_test.go
This change adds all the methods returning `*mux.Router` to our internal (traced)
`*Router`, ensuring that they will return the same instance instead of the embedded
one.
Documentation has been copied from `gorilla/mux`
> contrib/gorilla/mux: wrap methods returning mux.Router.

- contrib/internal/httputil/trace.go
- contrib/internal/httputil/trace_test.go
- ddtrace/tracer/context_test.go
Adds support for distributed tracing and some tests ensuring that the parent is taken into consideration, both when it is in the context, as well as in the HTTP request's headers.
Additionally, it adds a test into the tracer asserting that the local context takes precedence of the `ChildOf` option when calling `StartSpanFromContext`, as it is stated in the documentation.
> contrib/internal/httputil: add support for distributed tracing.

- ddtrace/ddtrace.go
- ddtrace/internal/globaltracer.go
- ddtrace/mocktracer/mockspancontext.go
- ddtrace/tracer/spancontext.go
- ddtrace/tracer/spancontext_test.go
This change adds two new methods to the `SpanContext` interface,
allowing it to return the span and trace IDs in order for them to
potentially be used to correlate traces to logs.
> all: introduce correlation IDs into SpanContext.

- CONTRIBUTING.md
- README.md
This change improves the README so that the documentation section comes
before the testing one, since it has higher importance.
It also moves the contributing guildelines into their own file
(CONTRIBUTING.md) as this is standard for GitHub and will cause PRs to
be preceeded with a warning that this repository has contribution
guidelines, linking to this file.
> docs: improve documentation and add guidelines.

- contrib/gorilla/mux/mux.go
- contrib/gorilla/mux/mux_test.go
- contrib/internal/httputil/trace.go
This change adds an additional tag on the gorilla/mux router showing the
value of the host template.
Additionally, it modifies the internal httputil package to accept extra
tags for the created span.
Closes https://github.com/DataDog/dd-trace-go/issues/250
> contrib/gorilla/mux: add host information as "mux.host" when defined

- ddtrace/ext/tags.go
Most important tag names have their own constants. So should the `env` tag as it is quite central to our app.
> ddtrace/ext: add constant for setting the environment tag.

- ddtrace/tracer/transport.go
- ddtrace/tracer/transport_test.go
This change ensures that a larger flexibility is permitted when
specifying host[:port] address for the agent. Previously, unexpected
behaviour happened when specifying only the hostname, as an example.
Closes #210
> ddtrace/tracer: resolve agent addresses more accurately.

- contrib/gocql/gocql/gocql.go
It was possible to chain multiple methods returning Query, losing
tracing context in the process. This change adds these methods, ensuring
tracing works as expected.
Closes #260
> contrib/gocql/gocql: wrap missing methods returning gocql.Query

- .circleci/config.yml
- contrib/gocql/gocql/gocql.go
- ddtrace/tracer/span_msgp.go
This change makes `golint` return exit status 1 on errors and fixes all linting errors.
> build: make golint fail CI

- ddtrace/internal/globaltracer.go
- ddtrace/tracer/tracer.go
This change causes the internal tracer to cleanly exit, flushing any
remaining traces to the transport whenever `tracer.Stop` and
`tracer.Start` are called.
> ddtrace/tracer: always Stop the internal tracer when running Start/Stop

- contrib/gocql/gocql/gocql.go
This change updates the documentation for `WrapQuery` to clarify the
behaviour of "chainable" methods.
> contrib/gocql/gocql: clarify WrapQuery documentation.

- MIGRATING.md
tracer.WithServiceName is a StartOption and not a StartSpanOption, tracer.ServiceName is the right method.
idem for tracer.WithResourceName
> Fix MIGRATING.md StartSpan example

- contrib/gin-gonic/gin/gintrace.go
- contrib/gin-gonic/gin/gintrace_test.go
Use propagation features to try to get some span context in the incoming
request headers.
If the headers are not set, the comportment is the same as before
If a span is already present in the request's context, it will be
used primarily as the parent span.
> contrib/gin-gonic/gin: Extract parent span info from HTTP Headers

- ddtrace/tracer/option.go
Documentation states that passing a "nil" error to the `WithError`
option would not mark the span as erroneous. This is false under
circumstances when the error points to a nil pointer interface.
Since this is a subtle difference, the change removes this statement
from the documentation to avoid misleading beginners.
See: https://golang.org/doc/faq#nil_error
> ddtrace/tracer: remove false claim from documentation

- contrib/graph-gophers/graphql-go/example_test.go
- contrib/graph-gophers/graphql-go/graphql.go
- contrib/graph-gophers/graphql-go/graphql_test.go
- contrib/graph-gophers/graphql-go/option.go
Fixes: https://github.com/DataDog/dd-trace-go/issues/286
This adds GraphQL server tracing support.
>  contrib/graph-gophers/graphql-go: add graphql tracing support

- contrib/aws/aws-sdk-go/aws/aws.go
- contrib/aws/aws-sdk-go/aws/aws_test.go
- contrib/aws/aws-sdk-go/aws/example_test.go
- contrib/aws/aws-sdk-go/aws/option.go
Fixes https://github.com/DataDog/dd-trace-go/issues/284
This uses a `WrapSession` function:
```go
func Example() {
cfg := aws.NewConfig().WithRegion("us-west-2")
sess := session.Must(session.NewSession(cfg))
sess = awstrace.WrapSession(sess)
s3api := s3.New(sess)
s3api.CreateBucket(&s3.CreateBucketInput{
Bucket: aws.String("some-bucket-name"),
})
}
```
I used our existing boto integration as an example for many of the tags.
> contrib/aws/aws-sdk-go: add aws sdk integration

- contrib/database/sql/example_test.go
Added an example demonstrating the use of the SQL integration with a Sqlite database.
I have not yet found a the definition what can go into a Sqlite DSN.  Once that's found, additional metadata can be extracted for the traces.
> contrib/database/sql: Added an example showing how to use Sqlite.

- contrib/google.golang.org/grpc/client.go
Fixes https://github.com/DataDog/dd-trace-go/issues/301
Copying the metadata before modifying it should fix the issue.
> contrib/google.golang.org/grpc: fix race condition when setting metadata

- .circleci/config.yml
This cleans up the `.circleci/config.yaml` file and switches to the gometalinter, which should allow us to disable linting using a comment directive.
> .circleci: use gometalinter

- contrib/net/http/option.go
- contrib/net/http/roundtripper.go
- contrib/net/http/roundtripper_test.go
This pulls the http.RoundTripper out of https://github.com/DataDog/dd-trace-go/pull/298 into its own pull request. I attempted to make the relavant requested changes as well.
This fixes https://github.com/DataDog/dd-trace-go/issues/172
> contrib/net/http: add tracing for http.RoundTripper

- .circleci/config.yml
- contrib/go-redis/redis/redis.go
Fixes https://github.com/DataDog/dd-trace-go/issues/317. The `String` method on `Cmder` was removed.
> contrib/go-redis/redis: support newer versions of go-redis/redis

- ddtrace/tracer/tracer.go
**TODO**
**Change description**
Previously, we were attempting to save the payload as long as the size
allows it in order to attempt and send it again on subsequent retries to
minimize the loss of traces.
This has proven to be a bad approach because there were cases where the
trace agent did only partial reads from the payload before failing,
leaving the payload in a state where it was impossible to decode using
msgpack (part of the buffer was already read).
This fix is an intermediary easy solution to the problem (we have
experimented with different approaches too, see #275). We can potentially
experiment later on with retry policies.
Closes #276
> ddtrace/tracer: reset payload after every transport attempt

- ddtrace/tracer/textmap.go
Previously, we were using `Add` to inject propagation headers. This could
be problematic when a request is forwarded from another service and
already has headers injected. The resulting target may pick up the wrong
context. We should use `Set` to replace any existing values.
> ddtrace/tracer: replace headers when injecting

- contrib/google.golang.org/grpc/client.go
- contrib/google.golang.org/grpc/grpc_test.go
Closes https://github.com/DataDog/dd-trace-go/pull/327.
This adds a unit test to the work done by @osamingo. I confirmed that the test fails with the original code and passes with the new code.
> contrib/google.golang.org/grpc: add unit test for metadata

- ddtrace/tracer/textmap.go
- ddtrace/tracer/util.go
- ddtrace/tracer/util_test.go
For distributed tracing some languages are passing through int64s instead of uint64s. It's fairly straightforward to support both.
> ddtrace/tracer: support int64 ids for the text map reader

- contrib/go-redis/redis/redis.go
- contrib/go-redis/redis/redis_test.go
I'm experiencing problems using a traced client. The baseline is: I try to have the same code running when it's traced and when it's not, keeping an option "I want to trace this or not" at runtime.
As I view it one option is to consider the client is just a https://godoc.org/github.com/go-redis/redis#Cmdable be it traced or not.
Now I hit a problem, the `Pipeline()` func has the wrong prototype. While it's true `*Pipeliner` implements `redis.Pipeliner`, the signature is different and just because of that detail it's impossible to use `Client` as a generic Cmdable.
This patch changes the prototype. It *is* a breaking change, as I had to update a test. Indeed, caller
can not assume `Pipeline()` returns a concrete `*Pipeliner`. So a cast is required. But OTOH the client is a truely generic …
> contrib/go-redis/redis: make go-redis traced Client a true redis.Cmdable

- contrib/Shopify/sarama/example_test.go
- contrib/Shopify/sarama/headers.go
- contrib/Shopify/sarama/option.go
- contrib/Shopify/sarama/sarama.go
- contrib/Shopify/sarama/sarama_test.go
Fixes https://github.com/DataDog/dd-trace-go/issues/295
This PR implements wrappers for `Consumer`, `SyncProducer` and `AsyncProducer`. It also implements carriers for `ProducerMessage` and `ConsumerMessage` so that span contexts can be injected and extracted.
I modeled the naming and behavior after our dd-trace-java integration.
> contrib/Shopify/sarama: add support for tracing the sarama kafka package

- contrib/google.golang.org/grpc/client.go
- contrib/google.golang.org/grpc/grpc.go
- contrib/google.golang.org/grpc/grpc_test.go
- contrib/google.golang.org/grpc/server.go
send gRPC status code for ServerUnaryInterceptor and ServerStreamingIncetptor
fixed https://github.com/DataDog/dd-trace-go/issues/332
> contrib/google.golang.org/grpc: send gRPC status code in interceptor

- contrib/net/http/roundtripper.go
- contrib/net/http/roundtripper_test.go
This will facilitate integrating with libraries such as `go-github`
> contrib/net/http: add a convenience WrapClient method

- contrib/database/sql/conn.go
- contrib/database/sql/driver.go
- contrib/database/sql/stmt.go
- contrib/database/sql/tx.go
- contrib/mongodb/mongo-go-driver/mongo/mongo.go
- contrib/mongodb/mongo-go-driver/mongo/mongo_test.go
Instrumentation for some packages (such as `jmoiron/sqlx`) is tracing calls returning `driver.ErrSkip`, causing not only duplicate traces, but also APM errors where in fact there were none.
From [`(database/sql/driver).ErrSkip`](https://golang.org/pkg/database/sql/driver/#ErrSkip):
```go
// ErrSkip may be returned by some optional interfaces' methods to
// indicate at runtime that the fast path is unavailable and the sql
// package should continue as if the optional interface was not
// implemented. ErrSkip is only supported where explicitly
// documented.
var ErrSkip = errors.New("driver: skip fast-path; continue as if unimplemented")
```
This is not a user error and in these cases we should not perform any tracing. See #270 for a detailed overview of the problem.
Fixes #270 
**TODO**
> contrib/database/sql: only record spans for implemented driver methods

- contrib/julienschmidt/httprouter/example_test.go
- contrib/julienschmidt/httprouter/httprouter.go
- contrib/julienschmidt/httprouter/httprouter_test.go
- contrib/julienschmidt/httprouter/option.go
The httprouter integration did not allow for providing additional span options. I have applied the exact same logic from the gorilla/mux integration.
Closes #345
> julienschmidt/httprouter: support extra span options in httprouter

- contrib/k8s.io/client-go/kubernetes/kubernetes.go
- contrib/k8s.io/client-go/kubernetes/kubernetes_test.go
- contrib/net/http/roundtripper.go
This allows to provide the Kubernetes Audit-ID to the kube-apiserver [see](https://github.com/kubernetes/apiserver/blob/92e87e143ad53972f794f1070bec41711ebe4c99/pkg/audit/request.go#L54-L61).
With this change, we could then use datadog distributing tracing capabilities (audit logs) in the apiserver side.
> contrib/k8s.io/client-go: inject the traceID as kube auditID

- contrib/net/http/roundtripper.go
If the base round tripper start a new span, it will be a brothers rather than parent-child.
I think there are no reasons to ignore context.
> contrib/net/http: inherit context of StartSpanFromContext into base RoundTripper

- contrib/google.golang.org/grpc.v12/grpc.go
- contrib/google.golang.org/grpc/client.go
- contrib/google.golang.org/grpc/grpc.go
- contrib/google.golang.org/grpc/option.go
- contrib/google.golang.org/grpc/server.go
- contrib/mongodb/mongo-go-driver/mongo/example_test.go
- contrib/mongodb/mongo-go-driver/mongo/mongo_test.go
- ddtrace/ddtrace.go
- ddtrace/tracer/option.go
- ddtrace/tracer/span.go
- ddtrace/tracer/span_test.go
Traceback generation in Go is quite costly operation and as errors such as BE is throttled might occur very often the the application end up just burning CPU on generating the backtraces.
On top of that the gRPC backtraces are super long which put pressure on GC and also they are completely useless as they all end up in gRPC's stack not pointing to a caller
Address #354
> ddtrace/tracer: add NoDebugStack finishing option

- ddtrace/tracer/option.go
- ddtrace/tracer/option_test.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/transport.go
- ddtrace/tracer/transport_test.go
This allows customization of the transport layer, for instance adding
custom headers to every request or emitting to a unix socket. This is
useful when there is a load balancer in between the emitter and the
agent, for instance in a service mesh.
> tracer: allow overriding http.RoundTripper used to emit spans

- contrib/net/http/roundtripper.go
Our wrappers should only minimally augment components with telemetry and
should never touch original responses such as errors.
> contrib/net/http: never return other errors than the original

- .circleci/config.yml
- ddtrace/tracer/option.go
- ddtrace/tracer/sampler.go
- ddtrace/tracer/sampler_test.go
- ddtrace/tracer/span.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
- ddtrace/tracer/transport.go
- ddtrace/tracer/transport_test.go
Adds `WithPrioritySampling` option and a priority sampling to allow distributed traces to be sampled the same throughout the stack.
> ddtrace/tracer: added priority sampler

- ddtrace/tracer/option.go
- ddtrace/tracer/sampler.go
- ddtrace/tracer/sampler_test.go
- ddtrace/tracer/span.go
- ddtrace/tracer/span_test.go
- ddtrace/tracer/spancontext.go
- ddtrace/tracer/spancontext_test.go
- ddtrace/tracer/textmap.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
This is to improve the behavior that users observe when collecting distributed traces.
With a default to on, traces that are being sampled will have the parts produced by dd-trace-go submitted to the agent.
Currently, no option is provided to disable priority sampling, but code for the original behavior has been kept. This may be reconsidered in the future.
> ddtrace/tracer: priority sampling on by default

- contrib/gin-gonic/gin/gintrace.go
Removing a confusing documentation line describing an additional parameter. Since the tracer.StartSpanFromContext logic now finds a global tracer configured, its up to user to start a tracer and configure it themselves.
> contrib/gin-gonic/gin: remove confusing documentation line

- ddtrace/ext/tags.go
This change adds a new constant representing the event sampling rate
key for APM events.
> ddtrace/ext: add a key for event sampling rate

- contrib/go-redis/redis/redis.go
- contrib/go-redis/redis/redis_test.go
Fixes a race condition when using the client concurrently with `WithContext`.
Fixes https://github.com/DataDog/dd-trace-go/issues/387
> contrib/go-redis/redis: fix context race in client

- ddtrace/tracer/option.go
To create a bound contract add mention that when nil error is passed it has no effect on trace.
Fixes: https://github.com/DataDog/dd-trace-go/issues/393
> ddtrace/tracer: WithError is no-op with nil err

- contrib/google.golang.org/grpc/client.go
- contrib/google.golang.org/grpc/grpc.go
- contrib/google.golang.org/grpc/grpc_test.go
- contrib/google.golang.org/grpc/server.go
- Put `finishWithError` calls inside closure functions because the deferred
function's arguments are evaluated when the defer statement is
evaluated. More at https://golang.org/doc/effective_go.html#defer
Before this commit, `finishWithError` deferred with nil error (initial value)
and any other changes of the initial value were not added to span. This bug
affects only grpc streaming.
- Clean `tagCode` in case of disregarded error.
- Add tests for checking if span contains error.
> contrib/google.golang.org/grpc: Fix adding errors to spans and traces

- ddtrace/tracer/sampler.go
- ddtrace/tracer/sampler_test.go
- ddtrace/tracer/span.go
- ddtrace/tracer/span_test.go
- ddtrace/tracer/spancontext.go
- ddtrace/tracer/spancontext_test.go
- ddtrace/tracer/textmap.go
- ddtrace/tracer/textmap_test.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
This change adds the `_dd.origin` tag to local-level root spans that have a remote parent which propagated the `x-datadog-origin` header. Currently it is mainly used by the Synthetics product.
> ddtrace/tracer: add origin to span context

- ddtrace/ext/tags.go
- ddtrace/opentracer/option.go
- ddtrace/tracer/span.go
- ddtrace/tracer/tracer_test.go
This change adds a special tag called "span.name" (constant
ext.SpanName) to allow setting the operation name externally by means of
a tag when using vendor agnostic libraries like Opentracing or
OpenCensus.
> ddtrace/{ext,opentracer,tracer}: allow setting span name via tag

- contrib/go-chi/chi/chi.go
- contrib/go-chi/chi/chi_test.go
This change adds the request method to the resource and covers for the
case when resource is empty.
Closes https://github.com/DataDog/dd-trace-go/issues/404
> contrib/go-chi/chi: fix resource issue

- contrib/gocql/gocql/gocql.go
Some performance test shown that if the resourceName was not provided, the computation involved a cpu-expensive operation to compute it. We can just derive it from the statement directly.
For the record, on top of strconv and split involved here, the underlying q.String() calls fmt.Sprintf()
After digging with @furmmon, it seems related to https://github.com/gocql/gocql/issues/1108
> contrib/gocql/gocql: improve resource computation performance

- ddtrace/ext/tags.go
- ddtrace/tracer/span.go
- ddtrace/tracer/span_test.go
This change adds support for a new boolean tag ("analytics.event") to serve as
an alias for setting the event sample rate to 0.0 or 1.0.
For example:
```go
span.SetTag(ext.AnalyticsEvent, true)  // record this event
span.SetTag(ext.AnalyticsEvent, false) // don't record this event
```
> ddtrace/tracer: add an alias tag (analytics.event) for setting event rate

- contrib/gocql/gocql/gocql.go
- contrib/gocql/gocql/option.go
Allow adding NoDebugStack option to WrapQuery to prevent generating stack traces on errors.
Needed when a service makes a lot of calls to cassandra at bootstrap (to retrieve state for example) that should be able to retry quickly without blocking & using too much memory when generating errors stack traces.
> contrib/gocql/gocql: add NoDebugStack option

- contrib/google.golang.org/grpc/client.go
- contrib/google.golang.org/grpc/grpc.go
- contrib/google.golang.org/grpc/option.go
- contrib/google.golang.org/grpc/server.go
- contrib/google.golang.org/grpc/stats_client.go
- contrib/google.golang.org/grpc/stats_server.go
Sorry @gbbr & @ewang: I decided to just start hacking on this issue, because I really want to suppress the wast amount of `NotFound` errors for certain services at the company I'm working for. 😅
I hope this PR is fine for you / the maintainers. 🙂
Fixes #333
> contrib/google.golang.org/grpc: allow setting non-error codes

- ddtrace/tracer/textmap.go
- ddtrace/tracer/textmap_test.go
This permits using B3 headers for injecting and extracting traces when propagated between different programs.
It is backward-compatible with existing behavior, but provides support for either Datadog, B3 or both headers when they are propagated.
The environment variables `DD_PROPAGATION_STYLE_INJECT` and `DD_PROPAGATION_STYLE_EXTRACT` support values that are comma separated (current valid values are: `datadog` and `b3`). They are case insensitive. When extracting, the list order is presumed. 
This functionality is currently not being added to the API (eg: `PropagatorConfig`), but may be exposed in the future if needed.
> ddtrace/tracer: add support for DD_PROPAGATION_STYLE_INJECT + EXTRACT

- contrib/gomodule/redigo/example_test.go
- contrib/gomodule/redigo/option.go
- contrib/gomodule/redigo/redigo.go
- contrib/gomodule/redigo/redigo_test.go
github.com/garyburd/redigo has been archived and moved to github.com/gomodule/redigo .
contrib/garyburd/redigo is not deleted for backward compatibility purpose
Fixes #421
> contrib/gomodule/redigo: copied from contrib/garyburd/redigo

- contrib/database/sql/example_test.go
Two of the examples were discarding the span and not calling the
Finish() method on it.
Fixes #413
> contrib/database/sql: update StartSpanWithContext examples

- contrib/net/http/http.go
- contrib/net/http/http_test.go
- contrib/net/http/option.go
* Adds a new `spanopts ...ddtrace.StartSpanOption` parameter to the `WrapHandler` func.
Fixes #428
> contrib/net/http: Allow passthrough of http trace span options

- ddtrace/ext/tags.go
- ddtrace/tracer/span.go
- ddtrace/tracer/span_test.go
These are aliases for simplifying user-controlled sampling priorities.
> ddtrace/tracer: add manual.keep and manual.drop tags

- ddtrace/tracer/tracer.go
The os.Getpid() call is visible in profile flamegraphs of busy servers.
Memoize it as the PID won't change in the lifetime of a Go process.
> ddtrace/tracer: Memoize the PID

- ddtrace/tracer/span.go
- ddtrace/tracer/spancontext.go
- ddtrace/tracer/spancontext_test.go
- ddtrace/tracer/transport.go
This change fixes a race condition that would happen on rare occasions
when using the priority sampler and flushing asynchronous child spans of
a trace that would finish later than the root, usually at the same time
when the root was being flushed.
> ddtrace/tracer: fix a race condition happening with asynchronous flushes

- ddtrace/ddtrace.go
- ddtrace/tracer/option.go
- ddtrace/tracer/span.go
- ddtrace/tracer/span_test.go
- ddtrace/tracer/tracer_test.go
Adds option to limit the number of reported stack frames
as well as skip requested number of stack frames.
Fixes: https://github.com/DataDog/dd-trace-go/issues/435
> tracer: add option to skip and limit stack frames

- ddtrace/tracer/option.go
- ddtrace/tracer/span.go
- ddtrace/tracer/spancontext.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
This functionality is controlled by the `DD_TRACE_REPORT_HOSTNAME`
environment variable. When set to "true", the root spans will
automatically have a tag added containing the hostname.
> ddtrace/tracer: add hostname tag to root spans

- .circleci/config.yml
The redis package has new development on their master branch for a v7 release, and there are significant API changes. The current contrib may need a rewrite once that API is stable and released. In the meantime, this pins the version of redis that we test against, while still making sure users can choose their own version.
I'm assuming that any users who had been using master would have hit some of the breaking changes and already decided to pick a tag of their own to keep their bits working.
Committing a vendored version into the tree would override the version selected by those users, which isn't very good at the moment.
Once the redis package has a release or RC of v7, we can decide about different import paths for this package. Until then, I think the correct fix is just within our …
> circleci: vendor go-redis/redis for testing.

- contrib/labstack/echo/echotrace.go
- contrib/labstack/echo/echotrace_test.go
- contrib/labstack/echo/option.go
~~New option to~~ handle the framework error inside this middleware. This is an important feature to return the correct HTTP status code to APM.
> contrib/labstack/echo: Add error handling

- internal/version/version.go
A version bump PR to follow the release of 1.15.0.
It should be merged shortly after publishing that release so the CI check will still pass.
After that, active PRs may need rebasing.
> internal/version: bump version to 1.16.0

- ddtrace/ext/tags.go
- ddtrace/tracer/span.go
In accordance to the new [errors spec](https://go.googlesource.com/proposal/+/master/design/29934-error-values.md) coming in go1.13, this change ensures that when an error has details to display (such as a localized stack trace), they are printed as part of another tag called `error.details`. A special use case is added to provide support for `pkg/errors`, which respects the same logic by implementing `fmt.Formatter`. The `go1.13` approach takes precedence over `pkg/errors`.
Closes #445
> ddtrace/tracer: add error.details tag

- contrib/labstack/echo/echotrace.go
- contrib/labstack/echo/echotrace_test.go
- contrib/labstack/echo/option.go
New option to enable analytics for the Labstack Echo framework.
> contrib/labstack/echo: Add analytics option

- contrib/olivere/elastic/elastictrace.go
- contrib/olivere/elastic/elastictrace_test.go
- contrib/olivere/elastic/option.go
This adds a ClientOption for a custom function to use in naming resources. The default is set to use the existing `quantize` function.
Fixes #460
> contrib/olivere/elastic: add customizable resource naming

- contrib/olivere/elastic/elastictrace.go
- contrib/olivere/elastic/elastictrace_test.go
For contrib/olivere/elastictrace, when `elastic.SetGzip(true)` is used, the body that is reported to DataDog is a garbled mess.
This PR detects the gzip encoding and decompresses to the original string representation before calling `span.SetTag("elasticsearch.body", snip)`
Fixes #464
> contrib/olivere/elastic: handle gzipped body when reporting

- ddtrace/tracer/span.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_go11.go
- ddtrace/tracer/tracer_nongo11.go
This change ensures that the corresponding `runtime/trace` tasks are created for each span,
making it easier to investigate performance problems when using the `go tool trace` tool.
Updates https://github.com/DataDog/dd-trace-go/issues/468
> ddtrace/tracer: add execution tracer entries

- ddtrace/tracer/transport.go
- ddtrace/tracer/transport_test.go
This change adds the container ID as a transport header, when the
information is available and can be extracted as part of the
`/proc/self/cgroup` file.
> ddtrace/tracer: add Datadog-Container-ID when information is available

- ddtrace/tracer/payload.go
- ddtrace/tracer/payload_test.go
- ddtrace/tracer/transport.go
- ddtrace/tracer/transport_test.go
- internal/version/version.go
This change introduces a notification channel to allow waiting for the
HTTP transport to close the reader.
See: https://github.com/golang/go/blob/go1.12/src/net/http/client.go#L135-L137
> ddtrace/tracer: fix race condition in transport

- contrib/gin-gonic/gin/gintrace.go
- contrib/gin-gonic/gin/gintrace_test.go
- contrib/gin-gonic/gin/option.go
Addresses this issue: https://github.com/DataDog/dd-trace-go/issues/476 
Allows one to specify a custom resource namer function.
>  contrib/gin-gonic/gin: Add WithResourceNamer to gintrace

- .circleci/config.yml
- contrib/k8s.io/client-go/kubernetes/kubernetes_test.go
This change vendors klog v0.4.0 for the duration of the CI run. It's
temporary and should be removed once kubernetes/client-go#656 gets
resolved.
> circleci: vendor klog v0.4.0

- ddtrace/mocktracer/mockspan.go
- ddtrace/mocktracer/mockspan_test.go
This fix uses the same logic as in the regular tracer package.
If the specified id in WithSpanID is zero (or none is set), the
id gets chosen as usual with nextID.
Fixes #481
> ddtrace/mocktracer: respect tracer.WithSpanID when creating a new span

- contrib/database/sql/conn.go
- contrib/database/sql/conn_test.go
- contrib/database/sql/option_test.go
Added span tag context key for sql tracer.
It becomes possible to set the tag dynamically.
As an example, I want to know what queries are issued for each endpoint.
Fixes #485
> contrib/database/sql: add context key to support additional tags

- contrib/jinzhu/gorm/gorm.go
- contrib/jinzhu/gorm/gorm_test.go
- contrib/jinzhu/gorm/option.go
This provides a partial solution for connecting gorm spans in distributed traces.
A full solution cannot be provided because of jinzhu/gorm#1231 - it has no support for `context.Context`. The issue is nearly 3 years old.
At the moment, `gormtrace` does not produce traces directly, but activates tracing on the underlying `database/sql` interactions. That makes lots of independent traces, and can't be connected to a distributed trace.
This PR makes `gorm` produce the spans, and provides `WithContext` to pass in a `context.Context` from externally, eg: HTTP handler or GRPC call implementation.
Only the `gorm` span is connected to the distributed trace, the underlying SQL interactions still produce independent/detached traces. If gorm adds support for `context.Context` in the future, this can …
> contrib/jinzhu/gorm: connect traces using context

- .circleci/config.yml
- contrib/hashicorp/consul/benchmark_test.go
- contrib/hashicorp/consul/consul.go
- contrib/hashicorp/consul/consul_test.go
- contrib/hashicorp/consul/example_test.go
- contrib/hashicorp/consul/option.go
- ddtrace/ext/app_types.go
This PR adds tracing for [hashicorp/consul/api](https://github.com/hashicorp/consul/tree/master/api).
```Golang
// Get a new Consul client
client, err := NewClient(consul.DefaultConfig())
if err != nil {
panic(err)
}
// Create a new root span
root, ctx := tracer.StartSpanFromContext(context.Background(), "parent.request",
tracer.SpanType(ext.SpanTypeRedis),
tracer.ServiceName("consul.example"),
tracer.ResourceName("/home"),
)
defer root.Finish()
client = client.WithContext(ctx)
// Get a handle to the KV API
kv := client.KV()
// PUT a new KV pair
p := &consul.KVPair{Key: "test", Value: []byte("1000")}
r, err = kv.Put(p, nil)
```
This will send a root span named `parent.request` for the `consul.example` service, and a child span named `PUT` for the `consul` service, with the tag `consul.key …
> contrib/hashicorp/consul: add tracing for consul clients

- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
This change slightly simplifies concurrency, moves some test methods to
the test files, improves naming to be more consistent and adds more
documentation.
Eventually, what is now `flushChan` can also go away, but it's a bigger piece
of work that requires a lot of test rewriting.
> ddtrace/tracer: simplify channels

- ddtrace/tracer/metrics.go
- ddtrace/tracer/metrics_test.go
- ddtrace/tracer/option.go
- ddtrace/tracer/option_test.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
This change adds an option to enable reporting runtime metrics. It
reports the `runtime.MemStats` structure and the pause quantiles from
the `debug.GCStats` structure of the standard library.
To use the feature, simply start the tracer using the new `WithRuntimeMetrics`
option, and metrics will be sent to Datadog every 10 seconds. If your Datadog
Agent dogstatsd address differs from the default `localhost:8125` you may
change it using the added `WithDogstatsdAddress` option or the standard
environment variables `DD_AGENT_HOST` and `DD_DOGSTATSD_PORT`.
For example:
```go
tracer.Start(tracer.WithRuntimeMetrics())
```
> ddtrace/tracer: add go runtime metrics

- README.md
- internal/version/version.go
The docs suggest Go v1.9 is required.
That isn't correct after some changes in the tracer and contribs that use things from go 1.10, eg:
- `strings.Builder`
- `database/sql/driver.Connector`
Fixes #502
> README: update go version to 1.10

- .circleci/config.yml
This change ensures that whatever minimum version is specified in the
README can be built.
Updates #502
> circleci: use go1.10 as specified in the README

- .circleci/config.yml
This is to clear up the CI failures after changing the build image to `circleci/golang:1.10`.
Pinning to os-release within the container seem reasonable, and would handle any future changes to the build image.
> circleci: update cache key for librdkafka

- ddtrace/tracer/droppedspan.go
- ddtrace/tracer/droppedspan_test.go
- ddtrace/tracer/span.go
- ddtrace/tracer/spancontext.go
- ddtrace/tracer/spancontext_test.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
In environments with very high throughput, it can sometimes be optimal to enable client sampling. In these scenarios, it is critical that CPU and memory usage is minimal. In the current implementation, a span which is not elected by the local sampler will go through the same process as any other span: allowing tags to be added, buffering a trace in memory, etc. This is resource consuming.
This change introduces a no-op span which is returned every time a trace is dropped by the local sampler. When this span is propagated to another service, that service receives a sampling priority of `UserReject` to signal that trace to be dropped on the agent side, while allowing it to reach the agent for stats computations.
This change also brings out problems with the architecture of the sampler …
> ddtrace/tracer: return no-op spans when client sampler rejects trace

- .circleci/config.yml
- checkcopyright.go
- contrib/hashicorp/consul/benchmark_test.go
- contrib/hashicorp/consul/consul.go
- contrib/hashicorp/consul/consul_test.go
- contrib/hashicorp/consul/example_test.go
- contrib/hashicorp/consul/option.go
We keep forgetting to add copyright headers, so...
This change adds a script that will run on CI, checking that all files
have a copyright text in the first 1KB of source code.
Example:
> ci: add checkcopyright script to run on CI

- ddtrace/tracer/metrics_test.go
Sometimes 5ms isn't enough to schedule the goroutine and collect the initial sweep of metrics.
This failed on CI for head of v1 branch.
```
--- FAIL: TestReportMetrics (0.01s)
Error Trace:    metrics_test.go:35
Error:      	Should be true
Test:       	TestReportMetrics
Error Trace:    metrics_test.go:36
Error:      	"[]" does not contain "runtime.go.num_cpu"
Test:       	TestReportMetrics
...snip...
FAIL
exit status 1
```
This uses a channel to report back the `Guage` calls on the testGuage, making sure we get 30+ calls before doing checks.
> ddtrace/tracer: fix flake in metrics test

- .circleci/config.yml
- README.md
- contrib/hashicorp/vault/example_test.go
- contrib/hashicorp/vault/option.go
- contrib/hashicorp/vault/vault.go
- contrib/hashicorp/vault/vault_test.go
- ddtrace/ext/app_types.go
This PR adds an integration for Vault's Go library.
The vault code can be found [here](https://github.com/hashicorp/vault/tree/master/api) with docs [here](https://godoc.org/github.com/hashicorp/vault/api)
This code takes advantage of vault's configuration, which accepts an `*http.Client` instance that it will use for all communication with vault. The `func NewHttpClient() *http.Client` returns an `*http.Client` which can be put in vault's `*api.Config` before creating the vault client with `client = api.NewClient(config)`
```
api.NewClient(&api.Config{HttpClient: trace.NewHttpClient()})
```
The client provided by this package uses our `contrib/net/http` functions to wrap the `*http.Client`'s transport and inspect outgoing http requests and incoming responses.
If our `*http.Client` isn't …
> contrib/hashicorp/vault: add integration for vault api.

- ddtrace/tracer/span.go
- ddtrace/tracer/spancontext.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
This provides a small performance improvement on creating spans.
benchmark                old ns/op     new ns/op     delta
BenchmarkStartSpan-8     574           501           -12.72%
The call to `runtime.makemap_small` is eliminated in cases where the `Meta` and `Metrics` maps are not needed at start time.
> ddtrace/tracer: skip creating Meta and Metrics map when not needed

- internal/log/log_test.go
A race occurs when Reset is called in the tests because it was missing
synchronization. This change fixes it.
Closes #524
> internal/log: fix rare race in tests

- contrib/google.golang.org/grpc/client.go
- contrib/google.golang.org/grpc/grpc.go
- contrib/google.golang.org/grpc/grpc_test.go
- contrib/google.golang.org/grpc/server.go
- contrib/google.golang.org/grpc/stats_client_test.go
- contrib/google.golang.org/grpc/stats_server_test.go
- contrib/google.golang.org/grpc/tags.go
gRPC defines several method 'kinds' (https://grpc.io/docs/guides/concepts/)
* Unary
* Client Streaming
* Server Streaming
* Bidirectional Streaming
Customers wanted to know what kind of gRPC method is being called.
To achieve this, we add the "grpc.method.kind" tag to every request span.
Resolves #521
> contrib/google.golang.org/grpc: support differentiation between streaming and unary RPCs

- ddtrace/tracer/option.go
- ddtrace/tracer/option_test.go
Setting the `env` is confusing. 
The current way to set the env with the go API is to [set a global tag](https://godoc.org/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer#WithGlobalTag) with the key `env` when starting the tracer.
This PR adds a `StartOption` called `WithEnv` that will add the global tag.
> ddtrace/tracer: add the WithEnv StartOption to the tracer.

- contrib/net/http/option.go
- contrib/net/http/roundtripper.go
- contrib/net/http/roundtripper_test.go
While ServeMux and WrapHandler take a WithServiceName option,
WrapRoundTripper and WrapClient don't have something comparable.
It is possible to add a WithBefore option that sets the service name, but
that is not an ideal situation.
This commit adds the RTWithServiceName function, which will set the
service name for the RoundTripper.
> contrib/net/http: add RTWithServiceName option for RoundTripper

- contrib/go-redis/redis/redis.go
- contrib/go-redis/redis/redis_test.go
Client should be thread-safe, but WithContext currently sets the context on the existing client,
so multiple goroutines calling WithContext at the same time will race.
This commit casues WithContext to return a pointer to a new Client, meaning multiple
goroutines can use WithContext at the same time.
Resolves #387
> contrib/go-redis/redis: return a new client from WithContext to eliminate race conditions.

- contrib/README.md
It currently happens that libraries which we are integrating with are
releasing new major versions that we don't support. As a result, we need
to create new packages to support them. This implies not only creating a new
folder using the current convention, but also adding the version to the
path.
Since we've not done this until today, users will be tempted to use the
"versionless" paths for latest releases, which will be inaccurate.
This change adds a new convention to *always* specify the major version
number as a suffix to the path. This is also in line with the requirements
for modules.
> contrib: specify the need for the major version in the README

- ddtrace/tracer/span.go
- ddtrace/tracer/span_test.go
- ddtrace/tracer/util.go
- ddtrace/tracer/util_test.go
Make sure integers that are too large or too small to be precisely represented by a
float are represented as strings. This commit makes sure that integers greater than
2^53 or smaller than -2^53 are sent as strings in the meta field of a span.
> ddtrace/tracer: improve handling of integer tags.

- ddtrace/tracer/metrics_test.go
The Wait call in the TestReportMetrics test waits for 30 calls to the statsd client, but
we expect to see 35 calls. Waiting for only 30 causes a race between the stats reporter
and the asserts in the test which causes intermittent failures.
> ddtrace/tracer: fix bug in TestReportMetrics

- .circleci/config.yml
CI jobs failing because of an error:
```
../../confluentinc/confluent-kafka-go.v1/kafka/00version.go:44:2: error: #error "confluent-kafka-go requires librdkafka v1.3.0 or later. Install the latest version of librdkafka from the Confluent repositories, see http://docs.confluent.io/current/installation.html"
```
1.3.0 is the latest release at the moment.
> circleci: update librdkafka to v1.3.0

- ddtrace/tracer/spancontext.go
`spans_finished` was counting the number of traces rather than the number of spans.
This fixes that mistake.
> ddtrace/tracer: Fix miscounting of the spans_finished metric

- contrib/gocql/gocql/gocql_test.go
A recurring issue is flakes on PRs due to connection errors.
The default timeouts are fairly short (600ms) and in the CI's containerized environment, that timeout seems to get hit more frequently.
Making it > 3x longer seemed to solve things when running tests locally.
> contrib/gocql/gocql: make timeouts longer to fix CI flakes

- ddtrace/tracer/doc.go
- ddtrace/tracer/metrics_test.go
- ddtrace/tracer/option.go
- ddtrace/tracer/sampler.go
- ddtrace/tracer/sampler_test.go
- ddtrace/tracer/span.go
- ddtrace/tracer/tracer.go
(This is a followup PR from #539)
This PR allows users to define sampling rates for traces based on rules defined at compile-time or at runtime.
The rules currently match against
- service name
- operation name
- both
- neither
When the rule matches, the sampling rate defined by that rule is applied to spans.
Rules can be either exact-match (using helper functions), or more complicated matches can be provided using regular expressions.
The tracer can be configured in code with sampling rules via a StartOption: tracer.WithSamplingRules([]tracer.SamplingRule)
The slice is composed of rules defined directly by users or using helpers such as `tracer.ServiceRule()`
To configure these rules at runtime, and other properties of the rule-based sampler, there are environment variables that can be …
> ddtrace/tracer: add rule-based sampler

- ddtrace/tracer/metrics_test.go
- ddtrace/tracer/sampler_test.go
- ddtrace/tracer/span_test.go
- ddtrace/tracer/spancontext_test.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
This patch moves the flushing of payloads to the agent into its own goroutine.
This avoids blocking the rest of the tracer, decreasing the liklihood of dropping traces
due to network latency.
> ddtrace/tracer: send payloads asynchronously

- contrib/net/http/http.go
- contrib/net/http/http_test.go
- contrib/net/http/option.go
- internal/version/version.go
WrapHandler fails to set the EventSampleRate tag as ServeMux.ServeHTTP does.
Rather than relying on ServeMux.ServeHTTP and WrapHandler to individually set
the tag, we will have the defaults function set the tag in the config if the global analytics
rate is not NaN.
> contrib/net/http: cause the default config to set the analytics rate in spanOpts

- contrib/database/sql/conn.go
- contrib/database/sql/sql_test.go
- contrib/internal/sqltest/sqltest.go
This fixes a reported issue by implementing the `NamedValueChecker` on the tracer's wrapper for `driver.Conn`. 
From https://golang.org/pkg/database/sql/driver/#NamedValueChecker
>  The sql package checks for value checkers in the following order, stopping at the first found match: Stmt.NamedValueChecker, Conn.NamedValueChecker, Stmt.ColumnConverter, DefaultParameterConverter. 
Searching github, I wasn't able to find drivers that implemented `Stmt.NamedValueChecker`, so didn't attempt that.
Fixes #563
> contrib/database/sql: implement driver.NamedValueChecker

- ddtrace/tracer/metrics_test.go
- ddtrace/tracer/sampler_test.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
- internal/version/version.go
During a previous change released as part of v1.20.0 in PR #498, the
flush channel was accidentally made blocking. This would cause a
deadlock on occasion when flushing after the payload size became large.
Tests failed to catch this problem because they were not using the
constructor and instead had their own incorrect constructor. This
change also addresses that problem so that tests would now correctly
catch the issue.
Kudos to @knusbaum for catching this. Relates to #569
> ddtrace/tracer: fix regression when flushing based on size

- contrib/gin-gonic/gin/gintrace_test.go
- contrib/gin-gonic/gin/option.go
- internal/version/version.go
There was a mistake with setting the resource name for this integration.
We previously had used `(*gin.Context).HandlerName` to set the resource
which was wrong and returns the name of the function (e.g.
`main.main.func1`).
This change ensures that the resource name is set correctly, as in all
our HTTP integrations to method and path (e.g. "GET /path")
Updates #558
> contrib/gin-gonic/gin: correct resource name

- ddtrace/mocktracer/mockspan.go
- ddtrace/mocktracer/mockspan_test.go
Currently mockspan.Finish is not idempotent while span.Finish is. This prevents us from testing code which invokes Finish multiple times. Fix for #572
> ddtrace/mocktracer: (*mockspan).Finish must be idempotent

- ddtrace/tracer/context_test.go
- ddtrace/tracer/metrics_test.go
- ddtrace/tracer/option.go
- ddtrace/tracer/option_test.go
- ddtrace/tracer/payload.go
- ddtrace/tracer/span_test.go
- ddtrace/tracer/spancontext_test.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
This change cleans up the code slightly by getting rid of `syncPush`
which was a hack to help synchronize test code and the unnecessary
`flushChan`.
The cost is slightly more complex test helper functions, which do make
sense and arguably simplify readability of test code.
> ddtrace/tracer: remove syncPush and flushChan

- ddtrace/ext/tags.go
- ddtrace/tracer/textmap.go
Previously, unrecognized propagators would be silently ignored. This is a minor
change that causes a warning to be emitted.
Also,
ddtrace/ext: remove TODO from tags constant
> ddtrace/tracer: log a warning when an unrecognized propagator is encountered.

- contrib/google.golang.org/grpc/grpc_test.go
- contrib/google.golang.org/grpc/option.go
- contrib/google.golang.org/grpc/server.go
Fixes #576
In order to ignore health-checking-protocol requests from
server side interception, WithIgnoredMethods is added for specifying
full methods that users want to be ignored.
With this option, every request sent to server is checked if its full
method should be ignored. If so, no span will be created.
> contrib/google.golang.org/grpc: add WithIgnoredMethods

- .circleci/config.yml
`k8s.io/client-go` has `github.com/googleapis/gnostic` as a dependency.
Recently, gnostic renamed some packages to be consistent with go style (https://github.com/googleapis/gnostic/pull/155) 
This change breaks `client-go`, which will no longer build when clients are checked out with e.g. `go get k8s.io/client-go/kubernetes`.
`k8s.io/client-go` has not made it clear when/if they will fix their imports. They are closing issues opened against the repository with instructions on how to use go modules to circumvent the problem (https://github.com/kubernetes/client-go/issues/741, https://github.com/kubernetes/client-go/issues/743)
`go get gopkg.in/DataDog/dd-trace-go.v1/...` still works as expected. Unit tests still run, and I am still able to build against dd-trace-go. I have not tried …
> .circleci/config.yml vendor gnostic for k8s.io/client-go

- ddtrace/tracer/span.go
- ddtrace/tracer/spancontext.go
- ddtrace/tracer/spancontext_test.go
- ddtrace/tracer/textmap.go
- ddtrace/tracer/textmap_test.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
hasSamplingPriority and samplingPriority are often called together, one after another,
and both acquire locks. Combining them into a single call reduces contention and
overhead.
span's Finish method is often called with no options, but it still allocates a config
object. This patch avoids allocating the config object if there are no opts passed to
Finish.
This PR also causes finishedOne to increase `traceStartSize` when a finished trace is larger than the start size. This should decrease allocations happening while adding spans to a trace.
> ddtrace/tracer: performance improvements for sampling priority and span finish

- contrib/gin-gonic/gin/gintrace_test.go
- contrib/gin-gonic/gin/option.go
- internal/version/version.go
Reverts DataDog/dd-trace-go#574
With this change, `github.com/gin-gonic/gin@v1.2.0` is no longer supported. That is ok, but we want to cut a version without this fix.
This fix will be restored, targeting v1.21.1.
> Revert "contrib/gin-gonic/gin: correct resource name"

- internal/version/version.go
We've started merging changes for v1.22.0 into the v1 branch, so we should go ahead and bump the version string.
> internal/version: bump version to 1.22.0

- .circleci/config.yml
client-go recently merged an API-breaking change on master, and so instead we
check out the latest working release of kubernetes/client-go. This is a stop-gap
solution for the dependency management issue that should be addressed
with modules as we move towards v2 (#471)
> .circleci: checkout github.com/kubernetes/client-go v0.17.3

- contrib/gin-gonic/gin/option.go
This change adds a hacky implementation on top of *gin.Context, ensuring
that when a version prior to v1.4.0 (with no support for
`(*gin.Context).FullPath`) is used, the code continues to build and run.
> contrib/gin-gonic/gin: ensure build for <v1.4.0 versions too

- contrib/graph-gophers/graphql-go/graphql.go
- contrib/graph-gophers/graphql-go/graphql_test.go
>  contrib/graph-gophers/graphql-go: exposing operation name in the tracer

- ddtrace/tracer/metrics.go
- ddtrace/tracer/metrics_test.go
- ddtrace/tracer/sampler_test.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
This removes the exitChan and stopping channels and replaces them with a single channel
that serves both purposes. This is a minor change that mildly simplifies the shutdown process.
> ddtrace/tracer: simplify the shutdown process.

- ddtrace/tracer/rand.go
This probably has never occurred since `Seed` doesn't appear to be called anywhere, but it's a bug nonetheless. 
I'll also mention that it's worth using linters[1][2], which nicely assist catching these subtle bugs.
1. golangci-lint: https://github.com/golangci/golangci-lint
2. https://staticcheck.io/docs/checks#SA5007
> ddtrace/tracer: fix infinite recursion in (*safeSource).Seed call

- ddtrace/tracer/option.go
- profiler/doc.go
- profiler/example_test.go
- profiler/options.go
- profiler/options_test.go
- profiler/profile.go
- profiler/profile_test.go
- profiler/profiler.go
- profiler/profiler_test.go
- profiler/upload.go
- profiler/upload_test.go
This change adds support for Datadog Profiling.
The `profiler` package is used as a standalone package and must be started separately from the tracer. Because it is part of the same repository, it will be imported using the same domain:
```
import "gopkg.in/DataDog/dd-trace-go.v1/profiler"
```
To start the profiler, make sure you pass it your Datadog API Key:
```
if err := profiler.Start(profiler.WithAPIKey("123key")); err != nil {
log.Fatalf("Error starting profiler: %v", err)
}
defer profiler.Stop()
```
Various other options may be used and can be seen in the documentation: http://godoc.org/gopkg.in/DataDog/dd-trace-go.v1/profiler/
> profiler: add profiler package

- profiler/profiler_test.go
In CircleCI the TestProfilerPassthrough test seems to be flaky and run into the `"time expired"` failure frequently. 
The test previously was trying to read from the `p.out` channel, which was racing against the `send()` function and `uploadFunc`
This patch makes the test read from the correct `out` channel and eliminates an unnecessary loop.
> profiler: fix race in TestProfilerPassthrough

- ddtrace/tracer/option.go
- ddtrace/tracer/span.go
- ddtrace/tracer/tracer_test.go
This PR adds to the `StartSpanOption` API by adding a measured flag that can be set when creating a new span.
The unit tests cover:
- If a span is not marked as measured, it shouldn't have the flag.
- If the span is started with the `MeasureSpan` option, then the span should have the flag.
- A child span of a measured span should not inherit the measured flag.
> ddtrace/tracer: add measured span option

- .circleci/config.yml
k8s.io/apimachinery needs to match the one required by
k8s.io/client-go's `go.mod` file, otherwise errors are thrown (newer
versions require `go1.13`)
Fixes CI.
> circleci: vendor the correct k8s.io/apimachinery

- contrib/zenazn/goji.v1/web/example_test.go
- contrib/zenazn/goji.v1/web/goji.go
- contrib/zenazn/goji.v1/web/goji_test.go
- contrib/zenazn/goji.v1/web/option.go
This implements middleware for goji that will trace incoming requests.
Suggestions for improvements in the implementation are welcome.
Unfortunately it looks like out of the box, there's no easy way to get the route, so the resource will usually be just the method. If the customer uses the Router middleware, that puts the route in the context, which the tracer middleware then picks up and adds to the resource name.
> contrib/zenazn/goji/web: add goji integration

- ddtrace/tracer/spancontext.go
- ddtrace/tracer/spancontext_test.go
When creating a span, `ForEachBaggageItem` is called, which acquires a
mutex to check for and copy baggage items. Often no baggage is present,
and the expensive mutex `Lock()` and `Unlock()` are a waste. This commit
adds an atomic `int32` which is set whenever the first baggage item is set,
and checked in `ForEachBaggageItem` to see if any baggage is present
before doing the more expensive mutex Lock().
I first added a commit with benchmarks testing the performance of ForeachBaggageItem with and without baggage present. I then added my optimization and then used `benchcmp` to compare.
This results in a ~90% speed up for `ForeachBaggageItem` when there is no baggage:
```
% go test -v -test.bench BenchmarkBaggageItem -test.run OOO -benchtime 30s >f351755.txt
% go test -v -test.bench …
```
> ddtrace/tracer: optimize ForEachBaggageItem.

- contrib/google.golang.org/grpc/server.go
This commit changes the service name in a call to startSpanFromContex from
cfg.serviceName to cfg.serverServiceName(). Everywhere else in the grpc
server integration, the service name is taken from cfg.serverServiceName(),
except this one place which erroneously uses cfg.serviceName directly.
> contrib/google.golang.org/grpc: use service name from function

- contrib/gorilla/mux/mux.go
- contrib/gorilla/mux/mux_test.go
- contrib/gorilla/mux/option.go
Allows customizing the resource names reported to DataDog by specifying a `WithResourceNamer` option on the Mux router. The namer function takes in the `*mux.Router` itself and the `*http.Request` being handled and should provide enough context to produce a resource name for most use cases.
The default namer is still the one that uses the path template on the matched route.
Closes #618
> contrib/gorilla/mux: allow custom resource naming

- contrib/gorilla/mux/mux.go
- contrib/gorilla/mux/mux_test.go
- contrib/gorilla/mux/option.go
- contrib/internal/httputil/trace.go
- contrib/internal/httputil/trace_test.go
- contrib/julienschmidt/httprouter/httprouter.go
- contrib/net/http/http.go
- contrib/net/http/http_test.go
- contrib/net/http/option.go
- contrib/zenazn/goji.v1/web/goji.go
- contrib/zenazn/goji.v1/web/goji_test.go
- contrib/zenazn/goji.v1/web/option.go
- ddtrace/mocktracer/mockspan.go
By allowing span finish options to be passed to all of these integrations, we can disable things like stack traces on errors.  This code retains a slice of finishOptions that it can apply at the end of the span.  I'd suggest that this is more extensible better pattern than storing a boolean for noDebugStack.
Fixes #615
> contrib/gorilla/mux: add NoDebugStack option for datadog tracer

- contrib/gocql/gocql/gocql.go
Update gocql WithContext function to work with gocql PR 1228, from Oct 25, 2018, https://github.com/gocql/gocql/pull/1228. That PR modified Query.WithContext to make a copy of the query.
We also modify WrapQuery to use the context already in the query.
Closes #625.
> contrib/gocql/gocql: update with latest changes to WithContext

- contrib/internal/httputil/trace.go
- contrib/internal/httputil/trace_test.go
The net/http only respects the first call to WriteHeader, ignoring others.
This commit changes our responseWriter wrapper to do the same so we will
get accurate reporting of status codes and errors when users call
WriteHeader multiple times.
Fixes #623
> contrib/internal/httputil: only set status once with WriteHeader

- profiler/options.go
- profiler/options_test.go
This commit adds profiler support for the DD_ENV, DD_SERVICE, DD_VERSION,
and DD_TAGS environment variables. It also adds the WithVersion Option
Fixes #630
> profiler: add support for standard environment variables.

- LICENSE
This change ensures that github.com/google/licensecheck, the package
used by pkg.go.dev picks up both licenses in this file.
Closes #605
> LICENSE: write dual license

- ddtrace/tracer/option.go
- ddtrace/tracer/option_test.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
- ddtrace/tracer/transport.go
- ddtrace/tracer/transport_test.go
This change adds a new option `WithHTTPClient` and marks
`WithHTTPRoundTripper` as deprecated (now superseded). Additionally, the
default client timeout is increased to 2 seconds as it has proven to be
too short (see #181).
Closes #181
> ddtrace/tracer: add WithHTTPClient and increase default HTTP timeout

- contrib/bradfitz/gomemcache/memcache/memcache.go
- contrib/bradfitz/gomemcache/memcache/memcache_test.go
- contrib/bradfitz/gomemcache/memcache/option.go
Currently, the memcached tracer is just creating a span and does not
trace anything except env tag. This commit adds some tags of valuable
information for each memcached operations.
Fixes #640
> contrib/bradfitz/gomemcache: trace item info for memcached operations

- contrib/gocql/gocql/gocql.go
We shouldn't make assumptions about slice lengths when the length
doesn't depend on us. One innocent change in the gocql library could
cause havoc.
> contrib/gocql/gocql: avoid panics

- ddtrace/tracer/span.go
- ddtrace/tracer/span_test.go
This commit implements the `fmt.Formatter` interface to support log injection.
The formatter supports the `%s` and `%v` formats. `%s` is the same as `.String()` and `%v` outputs the trace_id, span_id, service name, and if set, the env and service version in a format suitable for writing in logs.
Fixes #637
> ddtrace/tracer: implement Formatter interface to support log injection

- .circleci/config.yml
Improving caching between builds.
Before caching fetch dependencies took anywhere from ~3m 5 to ~3m 20s
After caching fetch dependencies (+ restore cache) takes: ~2m 
Note: we can improve this by caching directories within gopkg.in specifically(like shopify/sarama) except datadog. I will follow up with more PRs if you folks are up for it.
> circleci: improve build speed

- ddtrace/tracer/span.go
- ddtrace/tracer/span_test.go
Reverts DataDog/dd-trace-go#639
> Revert "ddtrace/tracer: implement Formatter interface to support log injection"

- .circleci/config.yml
- contrib/internal/httputil/trace_test.go
Shows errors on circle CI instead of having to scroll forever.
This makes it easy to identify what broke
> circleci: better error messages

- internal/globalconfig/globalconfig.go
This change fixes the mutex acquisition in `SetServiceName`.
Closes #658
> internal/globalconfig: fix wrong mutex acquired for SetServiceName

- profiler/options.go
- profiler/options_test.go
- profiler/profiler_test.go
WithSite and DD_SITE will determine the apiURL that profiles are sent to.
I'm not sure if `WithURL` should be deprecated. Looking for feedback on this approach to implementing `DD_SITE` given we have `WithURL`.
> profiler: add WithSite option and DD_SITE environment variable.

- contrib/internal/httputil/trace.go
- contrib/internal/httputil/trace_test.go
- ddtrace/ext/tags.go
This is a proposed changed for #646
> contrib/internal/httputil: add HTTP host tag

- contrib/google.golang.org/grpc/grpc_test.go
- contrib/google.golang.org/grpc/option.go
- contrib/google.golang.org/grpc/server.go
- contrib/google.golang.org/grpc/tags.go
This change add tags for gRPC metadata and request parameters, along with option to ignore metadata fields
Closes #643
> contrib/google.golang.org/grpc: trace metadata/request for grpc calls

- contrib/bradfitz/gomemcache/memcache/memcache.go
- contrib/bradfitz/gomemcache/memcache/memcache_test.go
- contrib/bradfitz/gomemcache/memcache/option.go
- internal/version/version.go
This reverts commit 3f45f6d1a30653f2616fcb2df7affa978685c887.
This can be problematic for multiple reasons such as producing unexpectedly large quantities of data, and possible security issues. We do not want to provide APIs with unexpected or potentially dangerous behavior.
Thank you for the contribution, @mingrammer, and sorry about needing to revert. I am re-opening #640 so we can revisit this with a more targeted approach.
> Revert "contrib/bradfitz/gomemcache: trace item info for memcached operations (#642)"

- contrib/jinzhu/gorm/gorm.go
- contrib/jinzhu/gorm/gorm_test.go
contrib/jinzhu/gorm: add context getter for gorm.db
Allows access to the context added to a gorm.db added using WithContext
Resolves #666
> contrib/jinzhu/gorm: add context getter for gorm.db

- contrib/google.golang.org/grpc/option.go
`serverServiceName` method of `config` occurs a data race because it
accesses/writes `serviceName` field without locking. This change fixes it
by making `serviceName` field to be immutable.
Fixes #669
> contrib/google.golang.org/grpc: fix a data race in config

- contrib/bradfitz/gomemcache/memcache/memcache.go
- contrib/bradfitz/gomemcache/memcache/memcache_test.go
- contrib/bradfitz/gomemcache/memcache/option.go
Reverts DataDog/dd-trace-go#642
(Same as #663 but for v1 branch)
This can be problematic for multiple reasons such as producing unexpectedly large quantities of data, and possible security issues. We do not want to provide APIs with unexpected or potentially dangerous behavior.
Thank you for the contribution, @mingrammer, and sorry about needing to revert. I am re-opening #640 so we can revisit this with a more targeted approach.
> Revert "contrib/bradfitz/gomemcache: trace item info for memcached operations"

- ddtrace/tracer/span.go
- ddtrace/tracer/span_test.go
The backend prefers strings to integers when it comes to parsing
dd.trace_id and dd.span_id.
> ddtrace/tracer: add quotes to trace and span id in format

- .circleci/config.yml
That workspace sharing was just prolonging things and the build requirement too. Everything running in parallel now seems to be best.
> circleci: improve speed

- ddtrace/tracer/option.go
- ddtrace/tracer/option_test.go
Instead of only looking for Environment tag, send all global tags
for metrics recorded by the statsd client (runtime metrics).
This also removes the remapping of ext.Environment to hardcoded "env".
Fixes: #671
> ddtrace/tracer: send all global tags instead of just env

- .circleci/config.yml
- ddtrace/tracer/option.go
- ddtrace/tracer/option_test.go
- ddtrace/tracer/span.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
This commit adds support for setting env, version, and service vio DD_TAGS.
It also adds tests to ensure the correct precedence for the various ways to
set the variables.
The order of precedence for the various ways to set these variables in the
tracer is:
1. Tracer StartOption: If the tracer is configured with StartOptions that
set env, version, or service, those will be the values
2. Environment variables: DD_ENV, DD_SERVICE, DD_VERSION
3. From tags set by WithGlobalTag
4. As the tags version, env, and service from DD_TAGS
5. Default or empty (service: binary name, env: unset, version: unset)
> ddtrace/tracer: pick up env, version, service from DD_TAGS

- contrib/go.mongodb.org/mongo-driver/mongo/mongo.go
- contrib/go.mongodb.org/mongo-driver/mongo/mongo_test.go
This was reported to Datadog support. Without specifying a span type, the span renders as "custom".
Added the tag and updated the test to ensure it's set. This matches `contrib/globalsign/mgo`.
> contrib/go.mongodb.org/mongo-driver: add span type

- .circleci/config.yml
During the latest `google.golang.org/grpc` release (v1.30.0) the
deprecated `naming` package was removed, which in turn [breaks](https://github.com/googleapis/google-api-go-client/blob/v0.28.0/go.mod#L17)
`google.golang.org/api` when used as part of a repository having the
latest grpc.
This is a temporary change until the bigger problem is resolved.
See https://github.com/grpc/grpc-go/issues/3726
> circleci: pin down grpc@v1.28.0

- contrib/net/http/option.go
- contrib/net/http/roundtripper.go
- contrib/net/http/roundtripper_test.go
To allow users to customize a resource name tag in RoundTrip, I added RTWithResourceNamer to contrib/net/http.
I've not changed the default behavior to prevent unexpected exposure of sensitive information in URL.
Closes #689
> contrib/net/http: add support for a resource name customization to RoundTrip

- profiler/profile.go
- profiler/profile_test.go
This commit adds the goroutine profile type to the profiler.
This profile type reports stack traces for all running goroutines.
> profiler: add goroutine profile type

- ddtrace/ext/tags.go
- ddtrace/tracer/option.go
- ddtrace/tracer/tracer_test.go
- internal/globalconfig/globalconfig.go
- profiler/options.go
- profiler/options_test.go
- profiler/profile.go
- profiler/upload_test.go
This commit adds a `runtime-id` tag to the global tags in the tracer and the profiler. The `runtime-id` is a per-process random UUID that identifies a running process, and allows us to link traces and profiles from the same process.
> all: add runtime-id to profiler and tracer global tags.

- ddtrace/tracer/log_test.go
- ddtrace/tracer/sampler_test.go
The recent merge of #692 conflicted with tests from #685, causing failures in `ddtrace/tracer/log_test.go`
There were also tests added in #685 in `ddtrace/tracer/sampler_test.go` which fail in `go1.14` due to changes in json parsing.
> ddtrace/tracer: fix broken tests

- ddtrace/tracer/option.go
- ddtrace/tracer/option_test.go
This change adds support for the DD_TRACE_ANALYTICS_ENABLED environment
variable, which will enable App Analytics for web integrations.
> ddtrace/tracer: add support for DD_TRACE_ANALYTICS_ENABLED env. var.

- contrib/database/sql/conn.go
- contrib/database/sql/stmt.go
- contrib/database/sql/tx.go
- contrib/internal/sqltest/sqltest.go
contrib/database/sql: add query_type span tag
This change is to add the query type to the span tags (previously resource). This will help differentiate the spans whenever a `query` has been provided to `tryTrace` (e.g. Prepare and Query for a prepared statement). If a `query` has been provided then the `resource.name` gets set to the query and not the resource.
Extends #270
> contrib/database/sql: add query_type span tag

- contrib/gomodule/redigo/redigo.go
> contrib/gomodule/redigo: Don't pass nil contexts around in withSpan

- contrib/graph-gophers/graphql-go/graphql.go
- contrib/graph-gophers/graphql-go/graphql_test.go
- contrib/graph-gophers/graphql-go/option.go
Trivial fields are fields implemented by methods which can't return an error, they are usually just structure field reads. See the test.
With big object listings, the traces get very unreadable if you print a span for each field of each object.
In our use cases, this often reduces span counts in a trace by an order of magnitude.
> contrib/graph-gophers/graphql-go: Add WithOmitTrivial option.

- profiler/options.go
- profiler/options_test.go
- profiler/profiler.go
- profiler/profiler_test.go
This change adds a new check which verifies the sanity of the user provided API key and returns an error if the key is invalid.
ref: PROF-1571
> profiler: add API key check at initialization of Profiler object

- ddtrace/ddtrace.go
- ddtrace/tracer/option.go
- ddtrace/tracer/sampler_test.go
- ddtrace/tracer/span_test.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
- ddtrace/tracer/writer.go
- ddtrace/tracer/writer_test.go
- internal/log/log.go
This commit abstracts the handling of finished traces, and includes 2
handlers. One implements the usual behavior, sending traces to the trace
agent. The other supports sending traces in a serverless environment by
writing completed traces to the log.
Fixes #701
> ddtrace/tracer: add support for lambda tracing

- contrib/go-redis/redis/redis.go
- contrib/go-redis/redis/redis_test.go
Enable tracing of Pipelined and TxPipelined calls.
Fixes #720
> contrib/go-redis/redis: Enable tracing of Pipelined and TxPipelined

- contrib/garyburd/redigo/redigo.go
go 1.15 doesn't support to create context from nil parent.
> contrib/garyburd/redigo: support go 1.15

- contrib/net/http/roundtripper.go
- contrib/net/http/roundtripper_test.go
closes https://github.com/DataDog/dd-trace-go/issues/728
> contrib/net/http: Add error to span in round tripper

- ddtrace/tracer/option.go
- ddtrace/tracer/span.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
By default a stack trace is collected when a span is finished with an
error. This can be disabled by passing tracer.NoDebugStack to
span.Finish(). Sometimes it is desirable to disable this option globally,
which is now possible with the WithDebugStack StartOption that this commit
introduces.
> ddtrace/tracer: add WithDebugStack StartOption to configure stack traces.

- ddtrace/tracer/log.go
- ddtrace/tracer/log_test.go
When the tracer is running in a lambda environment, we should disable the
agent connectivity check on startup to avoid misleading error messages.
> ddtrace/tracer: disable agent connectivity check in lambda mode

- contrib/twitchtv/twirp/twirp.go
- contrib/twitchtv/twirp/twirp_test.go
Refactor the twirp serverhooks, so that the specific span that was started in `requestRoutedHook` is finished in `responseSentHook`. This way, other server hooks that modify the context may start new spans in the context without conflicting with this middleware.
Fixes #725.
> contrib/twitchtv/twirp: Add explicit reference to the request span

- contrib/go-chi/chi/chi.go
- contrib/go-chi/chi/chi_test.go
When the user doesn't call `w.WriteHeader(...)` or `w.Write(...)` in the request handler or any of the middlewares the status isn't set and `WrapResponseWriter.Status()` returns 0. This is well documented behavior: https://github.com/go-chi/chi/blob/cf97bef8b1405c9177bd88eca166ed4f16b9fc80/middleware/wrap_writer.go#L45
In such a case `net/http` library takes the matters into its own hands and writes 200 status code: https://github.com/golang/go/blob/7e9369a517d9ebf867748719948d8cbccec3bc57/src/net/http/server.go#L1618
Try this code:
```
package main
import (
"net/http"
"github.com/go-chi/chi"
"github.com/go-chi/chi/middleware"
)
func main() {
r := chi.NewRouter()
r.Use(middleware.Logger)
r.Get("/", func(w http.ResponseWriter, r *http.Request) {
})
http.ListenAndServe(":3000", r)
}
``` …
> contrib/go-chi/chi: Handle 0 status code correctly

- ddtrace/tracer/osinfo_default.go
> ddtrace/tracer: fix os version for builds on niche GOOS (e.g. freebsd, ...)

- contrib/go-redis/redis.v8/example_test.go
- contrib/go-redis/redis.v8/option.go
- contrib/go-redis/redis.v8/redis.go
- contrib/go-redis/redis.v8/redis_test.go
This is simply a port of contrib/go-redis/redis, but for go-redis.v8 with the new Hook mechanism.
> contrib/go-redis/redis.v8: support go-redis.v8

- contrib/Shopify/sarama/sarama_test.go
Starting in github.com/Shopify/sarama@v1.27.1, the default kafka version
that the client uses is 1.0.0 (sarama.V1_0_0_0) rather that the previous
0.8.2 (sarama.V0_8_2_0) Unfortunately, the Sarama client for Kafka 1.0.0
does not work with the mock broker, so this change breaks our tests. To
repair the situation, we specify that the client should use version 0.8.2.
If Sarama fixes their mock client in the future, we can use the default
version instead.
> contrib/Shopify/sarama: use sarama.MinVersion in tests.

- contrib/jmoiron/sqlx/sql.go
- contrib/jmoiron/sqlx/sql_test.go
This PR provides additional options to open database connection with sqlx.Open, same as following PullRequest.
https://github.com/DataDog/dd-trace-go/pull/466
It allow us to override some parameters, such as service name, for multiple database connection.
> contrib/jmoiron/sqlx: allow options to sqlx.Open

- profiler/upload.go
This brings it in line with the other pprof-based profilers
> profiler: set profiler upload timeout to 10s

- ddtrace/tracer/context.go
- ddtrace/tracer/context_test.go
Previously, StartSpanFromContext would "work" with nil ctx. Using the
ctx (e.g. ctx.Value) would later cause a segfault. With Go 1.15,
calling StartSpanFromContext now panics. Preserve the existing
behaviour by defaulting to context.Background(). Document this
behaviour. Add a test.
Without the fix, on Go 1.14 this new test panics with "runtime error:
invalid memory address or nil pointer dereference" when calling
context.Value. On Go 1.15 it fails with "cannot create context from
nil parent" when calling StartSpanFromContext.
> ddtrace/tracer: StartSpanFromContext should work nil ctx on Go 1.15

- contrib/Shopify/sarama/example_test.go
- contrib/Shopify/sarama/sarama.go
- contrib/Shopify/sarama/sarama_test.go
This is a continuation of now abandoned PR https://github.com/DataDog/dd-trace-go/pull/487 by @HatsuneMiku3939
Closes https://github.com/DataDog/dd-trace-go/issues/483
Quick recap:
1. Currently WrapAsyncProducer doesn't work at all. Like explained in https://github.com/DataDog/dd-trace-go/issues/483, here https://github.com/DataDog/dd-trace-go/blob/ecb0b805ef25b00888a2fb62d465a5aa95e7301e/contrib/Shopify/sarama/sarama.go#L207 both `msg.Partition` and `msg.Offset` are always 0. Here https://github.com/DataDog/dd-trace-go/blob/ecb0b805ef25b00888a2fb62d465a5aa95e7301e/contrib/Shopify/sarama/sarama.go#L223  `msg.Partition` and `msg.Offset` are set correctly and this line https://github.com/DataDog/dd-trace-go/blob/ecb0b805ef25b00888a2fb62d465a5aa95e7301e/contrib/Shopify/sarama/sarama.go#L226 …
> contrib/Shopify/sarama: Fix WrapAsyncProducer tracing support

- ddtrace/tracer/textmap.go
- ddtrace/tracer/textmap_test.go
Current solution were only supporting parsing 16 encoded lower-hex characters.
Update make sure the take the last characters before parsing, fixing the issue.
Fixes for issue https://github.com/DataDog/dd-trace-go/issues/779
> ddtrace/tracer: fix issue extracting B3 tracing ID of 128 bits

- contrib/cloud.google.com/go/pubsub.v1/pubsub.go
- contrib/cloud.google.com/go/pubsub.v1/pubsub_test.go
This adds a new options parameter, as well as a new option for `WrapReceiveHandler`, so that GCP pubsub receivers can set a custom service name for their traces.
This PR also introduces an options pattern for this library, so that other options can be added in the future.
For the unit test, I was somewhat lazy, in that I simply copied the existing test and modified it to utilize the new option.
This solution will work for my use-case, but it won't be sufficient in case the pubsub receiver is started in the context of another trace. I don't think it is common to set up new receivers dynamically, but I did want to call that out as a limitation to this solution.
Feel free to leave code review notes or make commits to this branch directly. Thanks!
Fixes #752. 
cc/ #721 @CAFxX @knusbaum @gbbr
> contrib/cloud.google.com/go/pubsub.v1: Add WithServiceName option

- .gitignore
- ddtrace/tracer/span.go
- ddtrace/tracer/span_test.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
- ddtrace/tracer/transport.go
Set top level flag directly in tracer. Not in agent.
That way, we don't need to have access to the whole chunk in the agent.
> ddtrace/tracer: mark top level spans

- ddtrace/tracer/span.go
We will rename the top level field set by the tracer to follow the tracer standard.
We will convert that field in the agent: https://github.com/DataDog/datadog-agent/pull/6941
> ddtrace/tracer: rename top-level field

- contrib/gin-gonic/gin/gintrace.go
- contrib/gin-gonic/gin/gintrace_test.go
- contrib/gin-gonic/gin/option.go
This change adds support for `globalconfig.ServiceName()` to the gin
trace middleware. Because this middleware does not follow the same pattern
as other http frameworks and requires a service parameter to be passed in
we use the empty string value as an indicator that the default service
name should be used.
Fixes #767
> contrib/gin-gonic/gin: support globalconfig.ServiceName()

- ddtrace/tracer/option.go
- ddtrace/tracer/transport_test.go
- profiler/options.go
- profiler/upload.go
- profiler/upload_test.go
Some customers need to override networking over which the profiler sends data.
* Allow overriding the HTTP client and transport similar to facilities provided by the trace client
* As a convenience, provide an option to create a custom client and transport that accesses a Unix Domain Socket.
* Modified upload tests to exercise both default and custom HTTP clients.
> {profiler,ddtrace/tracer}: add UDS client options

- CONTRIBUTING.md
Add a link to the "[Style guidelines](https://github.com/DataDog/dd-trace-go/wiki/Style-guidelines)"
> CONTRIBUTING: add link to style guidelines

- ddtrace/tracer/span.go
- ddtrace/tracer/span_test.go
If tags were set with values of different types and the same key, both values were persisted, which is wrong
> ddtracer/tracer: tag keys must be unique across metrics and meta tags

- ddtrace/tracer/span.go
- ddtrace/tracer/span_test.go
It avoids to call fmt.Sprint, which uses reflection and is slower.
Fixes https://github.com/DataDog/dd-trace-go/issues/798
Benchmark:
```
go test -v -run=^$ -bench=^BenchmarkSetTag -benchmem -benchtime=10s -cpu=1 ./ddtrace/tracer
benchstat -delta-test none old.txt new.txt
name            old time/op    new time/op    delta
SetTagMetric      63.3ns ± 0%    64.8ns ± 0%   +2.37%
SetTagString      61.8ns ± 0%    61.4ns ± 0%   -0.65%
SetTagStringer     247ns ± 0%      77ns ± 0%  -68.87%
SetTagField       26.8ns ± 0%    26.8ns ± 0%    0.00%
name            old alloc/op   new alloc/op   delta
SetTagMetric       4.00B ± 0%     4.00B ± 0%    0.00%
SetTagString       4.00B ± 0%     4.00B ± 0%    0.00%
SetTagStringer     16.0B ± 0%      4.0B ± 0%  -75.00%
SetTagField        0.00B          0.00B …
```
> ddtrace/tracer: check if value implements fmt.Stringer in span.SetTag

- profiler/metrics.go
- profiler/metrics_test.go
- profiler/options.go
- profiler/options_test.go
- profiler/profile.go
- profiler/profile_test.go
- profiler/profiler.go
- profiler/profiler_test.go
- profiler/upload.go
- profiler/upload_test.go
go heap pprof profiles are accumulative and it's not possible to compute the number of allocations and gc pause time metrics by examining these pprofs alone.
To bring go to parity with other runtimes like the JVM, we compute these periodic metrics in context of collecting heap and cpu profiles.  These metrics are uploaded a json tuples.  Profiling intake and analysis services have corresponding changes to support this new payload and associate the metrics with corresponding profiles.
This work depends on https://github.com/DataDog/dd-trace-go/pull/781
> profiles: add custom metrics payload

- ddtrace/tracer/sampler.go
- ddtrace/tracer/sampler_test.go
- ddtrace/tracer/span.go
Fix to sampling rate name: since twl rules, `_dd.agent_psr` is they name to the priority rate pulled from the agent and applied to the root.
Fixing the limiter rate moving average
> ddtrace/tracer: fix rate limiter moving average

- contrib/go-redis/redis.v8/redis.go
- contrib/go-redis/redis.v8/redis_test.go
Fixes #803 
Introduce a new method, `WrapClient`, in the go-redis.v8 integration. This is [similar to the older go-redis integration](https://github.com/DataDog/dd-trace-go/blob/v1/contrib/go-redis/redis/redis.go#L61) in allowing a user to supply an already configured Redis client and have the tracing added to that rather than having the library build and return a client.
`redis.NewUniversalClient` can return a `Client`, `FailoverClient`, or `ClusterClient` instance. The important difference for this integration is the way that Redis addresses are available from a build client. A `Client` instance has a `Addr` field set to what's passed in to the constructor (e.g. `127.0.0.1:6379`), `FailoverClient` sets `Addr` to `FailoverClient` and `ClusterCleint` doesn't make this available at all. …
> contrib/go-redis/redis.v8: support wrapping a go-redis v8 client

- profiler/options.go
- profiler/options_test.go
Clients can modify block and mutex rates by invoking [runtime.SetBlockProfileRate](https://github.com/golang/go/blob/c3b4c7093ac46431b6e15cf1979bd9a251a400da/src/runtime/mprof.go#L380) and [runtime.SetMutexProfileFraction](https://github.com/golang/go/blob/c3b4c7093ac46431b6e15cf1979bd9a251a400da/src/runtime/mprof.go#L439) respectively, but this pull
* provides a convenience wrapper around those runtime methods in the profiler options API
* better documentation than the above-referenced runtime functions, [which are opaque](https://github.com/golang/go/issues/14689), to put it kindly.
> profiler: add options for block and mutex rates

- profiler/profiler.go
profiler.WithHostname might have existed at some point before the
profiler code was added to this repository, but it doesn't exist
anymore, so we shouldn't gaslight people with this confusing error
message.
> profiler: fix outdated error message

- profiler/profiler.go
- profiler/profiler_test.go
Hopefully this PR fixes a non-imaginary bug : ). PTAL
>  profiler: Start() doesn't unlock mutex on error

- profiler/profiler.go
The code currently seems to drop the new bat after going through the
trouble of making room for it by potentially dropping the oldest item
from the queue. As far as I can tell this doesn't make sense, and this
patch should fix it.
> profiler: improve enqueueUpload comments

- ddtrace/tracer/textmap.go
- ddtrace/tracer/textmap_test.go
Refactors `ctx.traceID` and `ctx.spanID` in `injectTextMap()` to format injected headers as exactly 16 characters long.
Fixes #695
> ddtrace/tracer: format injected traceid header with leading zeros

- profiler/options.go
@pmbauer PTAL.
@Kyle-Neale @gbbr you might have thoughts on backwards compatibility when it comes to changes like this. IMO it should be okay, but it's a bit of a grey zone.
> profiler: increase DefaultBlockRate

- ddtrace/tracer/option.go
- ddtrace/tracer/option_test.go
- profiler/options.go
DD_TAGS were split by commas only. Unless there is a comma in a string, tag list will be split by spaces. In either case, commas/spaces will be trimmed.
> ddtrace/tracer: updated DD_TAGS parsing to support space separation

- ddtrace/tracer/log_test.go
- ddtrace/tracer/spancontext_test.go
- ddtrace/tracer/tracer_test.go
Fix `TestLogFormat` in log_test.go by not checking tag contents. Update tests to pass in spancontext_test.go and tracer_test.go
> ddtrace/tracer: refactor log debug and format tests

- ddtrace/tracer/option.go
- ddtrace/tracer/option_test.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
Added DD_TRACE_SOURCE_HOSTNAME variable read to allow setting the hostname manually by the user. Hostname is added to each span as a meta tag of `_dd.hostname`
> ddtracer/tracer: set hostname meta tag on each span

- go.mod
> go.mod: add datadog-go@v4.4.0

- contrib/confluentinc/confluent-kafka-go/kafka/headers.go
- contrib/confluentinc/confluent-kafka-go/kafka/kafka.go
- contrib/confluentinc/confluent-kafka-go/kafka/kafka_test.go
> contrib/confluentinc/confluent-kafka-go - use GitHub package

- profiler/profile.go
- profiler/profile_test.go
The frames were showing up in reverse in the UI. Not sure why I wrote
the code to prepend instead of append the frames, but it's wrong and
this patch fixes it.
Fixes PROF-2908
**Screenshot of wrong stack frame order in goroutine wait profile:**
**Screenshot of correct stack frame order in goroutine profile:**
> profiler: fix goroutineswait profile frame order

- ddtrace/tracer/writer.go
- ddtrace/tracer/writer_test.go
Illegal characters, such as newlines, were not escaped in encodeSpan function, which ruined json structure. Closes #791
This, in turn, corrupted log collection
> ddtracer/tracer: marshalled span values in encode span

- .circleci/config.yml
- contrib/go-pg/pg.v10/pg_go_test.go
- internal/version/version.go
This change bumps the CI go version to `go1.14` due to a dependency failure which requires it (for redis.v8 and go-pg.v10):
```
../go/pkg/mod/go.opentelemetry.io/otel/trace@v0.18.0/config.go:119:2: duplicate method private
note: module requires Go 1.14
```
> .circleci: bump to go1.14

- contrib/globalsign/mgo/mgo_test.go
- contrib/globalsign/mgo/query.go
This change fixes an issue which caused an infinite loop due to a
programming error.
Closes #873
> contrib/globalsign/mgo: fix infinite loop

- contrib/go-chi/chi.v5/chi.go
- contrib/go-chi/chi.v5/chi_test.go
- contrib/go-chi/chi.v5/example_test.go
- contrib/go-chi/chi.v5/option.go
Most were copied from contrib/go-chi/chi.
https://github.com/go-chi/chi/blob/master/CHANGELOG.md#v500-2021-02-27
Closes #877
> contrib/go-chi/chi.v5: support go-chi/chi/v5

- contrib/confluentinc/confluent-kafka-go/kafka/headers.go
- contrib/confluentinc/confluent-kafka-go/kafka/kafka.go
- contrib/confluentinc/confluent-kafka-go/kafka/kafka_test.go
add support for missing public method `ReadMessage` of kafka consumer
closes #846
> contrib/confluentinc/confluent-kafka-go: ReadMessage method support

- profiler/options.go
- profiler/options_test.go
- profiler/profiler.go
- profiler/upload.go
Also add support for the DD_PROFILING_UPLOAD_TIMEOUT used by other
DD profilers such as Java.
The timeout is implemented using a request context, which allows
removing the timeout option from the defaultClient and WithUDS option.
defaultHTTPTimeout is promoted to DefaultUploadTimeout to be consistent
with the other default options.
The order of preference is:
1. DefaultUploadTimeout
2. DD_PROFILING_UPLOAD_TIMEOUT
3. WithUploadTimeout()
Implements PROF-2810
> profiler: Implement WithUploadTimeout

- ddtrace/tracer/span.go
This change removes the usage of `debug.Stack` in favour of a custom implementation, which significantly improves performance.
> ddtrace/tracer: always use custom stack trace retrieval code

- contrib/go-redis/redis.v7/example_test.go
- contrib/go-redis/redis.v7/option.go
- contrib/go-redis/redis.v7/redis.go
- contrib/go-redis/redis.v7/redis_test.go
Add support for go-redis v7. Used go-redis v8 as a model and adjusted methods accordingly to account for Context usage.
Fixes #857.
> contrib/go-redis/redis.v7: support for redis v7 package

- .circleci/config.yml
- README.md
- codecov.yml
Enable Codecov app integration with `dd-trace-go` to upload coverage reports for unit test coverage in the CircleCI `test-core` job. 
This PR modifies the CircleCI config file to utilize Codecov to add [GitHub Checks](https://docs.codecov.io/docs/github-checks-beta#yaml-configuration-for-github-checks-and-codecov) to each PR to automatically check if test coverage reaches a target percentage of the codebase. GitHub checks break down code coverage percentages for PR-specific changes, `core` and `contrib` tests.
Code coverage for this repo is hosted [here](https://codecov.io/github/DataDog/dd-trace-go).
> .circleci: add codecov

- profiler/profiler.go
Also remove a `printf` statement that seems like it was left in the code by accident.
> profiler: fix newlines breaking up log messages

- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
This change ensures that the Flush call is synchronous when the standard output trace writer is enabled.
> ddtrace/tracer: ensure Flush call is synchronous

- contrib/net/http/roundtripper.go
Adding a roundTripper.Unwrap() http.RoundTripper
Fixes #902
> contrib/net/http: add (*roundTripper).Unwrap to reveal the original RoundTripper

- ddtrace/tracer/span.go
- ddtrace/tracer/span_test.go
- ddtrace/tracer/tracer_test.go
Sets `noDebugStack` option in `errorConfig` so that `setTagError` only adds debug stack traces when this option is set as false. Added tests to check if tags set as errors properly acknowledge the `noDebugStack` option set by `WithDebugStack()`.
> ddtrace/tracer: add noDebugStack to config when setting error tags

- ddtrace/opentracer/tracer.go
- ddtrace/opentracer/tracer_test.go
Solves #813.
This implements the OpenTracing context extension. If a span was started by a Datadog OpenTracer, then the underlying object should be a pointer to a `opentracer.span`. If that is the case, we're able to use the context with the underlying Datadog Span (of the opentracer.span).
I've tested this locally to connect opentracing spans with Datadog spans assuming I set the `opentracing.SetGlobalTracer(datadogOpenTracer)`.
> ddtrace/opentracer: implement Context Extension

- ddtrace/opentracer/tracer.go
This change ensures that Opentracing spans using FollowsFrom references
will be considered as child spans.
Closes #376
> ddtrace/opentracer: consider FollowsFrom references as children

- contrib/database/sql/conn.go
There was an issue with go-mysql-driver that a connection returns an error "invalid connection."
article: https://github.blog/2020-05-20-three-bugs-in-the-go-mysql-driver/
And the author of the article fixed it https://github.com/go-sql-driver/mysql/pull/934.
If driver.SessionResetter is implemented, returns ErrBadConn instead of ErrInvalidConn, then it retries to establish a new connection again.
So I added ResetSession to tracedConn to avoid the error occurring.
> contrib/database/sql.tracedConn doesn't implement driver.SessionResetter

- contrib/Shopify/sarama/sarama.go
The client can still write to the `input` channel after the goroutine created by `WrapAsyncProducer` was already shut down. Therefore the channel should be closed. Otherwise, it will deadlock.
For references, it initially fixed here: https://github.com/signalfx/signalfx-go-tracing/pull/128
I had some very dirty test to reproduce it locally but it is not worth putting to the codebase. The test was complex and the bug is pretty obvious.
> contrib/Shopify/sarama: Fix possible deadlock in WrapAsyncProducer

- profiler/options.go
- profiler/profiler.go
- profiler/profiler_test.go
This is a backwards incompatible change, but deemed neccessary by the
profiling team. Since it's been analyzed to only impact a tiny minority
of users, it's done without a major version change.
UPGRADING:
If you are currently using profiler.WithAPIKey() or DD_API_KEY to upload
profiling data, please remove this configuration. dd-trace-go will now
default to upload through the datadog agent running at localhost:8126.
If your agent is running on another port, please use
profiler.WithAgentAddr() to configure the correct agent address.
The new profiler.WithAgentlessUpload() is not officially supported for
anything other than debugging/testing when hitting integration issues.
If you think you need it for your production environment, please contact
our support.
BACKGROUND:
Historically the …
> profiler: Disable agentless mode for WithAPIKey

- .circleci/config.yml
- ddtrace/internal/globaltracer.go
- ddtrace/tracer/log.go
- ddtrace/tracer/log_test.go
- ddtrace/tracer/option.go
- ddtrace/tracer/span.go
- ddtrace/tracer/span_test.go
- ddtrace/tracer/spancontext.go
- ddtrace/tracer/stats.go
- ddtrace/tracer/stats_payload.go
- ddtrace/tracer/stats_payload_msgp.go
- ddtrace/tracer/stats_test.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
- ddtrace/tracer/transport.go
- ddtrace/tracer/writer.go
- go.mod
This change adds a multitude of new features, such as support for feature flags, agent discovery, client-side stats computations and enabling the dropping of P0 traces in the client.
Support for feature flags by means of:
* `WithFeatureFlags` tracer start option.
* `DD_TRACE_FEATURES` environment variable which takes a list of comma or space separated flag tokens.
When the feature flag `discovery` is set, support for detecting features by means of the new agent (7.27.0) discovery endpoint added in https://github.com/DataDog/datadog-agent/pull/7344 and https://github.com/DataDog/datadog-agent/pull/7495 becomes enabled.
When `discovery` is enabled, if the agent supports client-computed stats and dropping p0's in the client, the tracer can now do this by means of the newly added concentrator …
> ddtrace/tracer: add support for agent discovery endpoint, feature flags, stats & drops

- internal/log/log.go
- profiler/profiler_test.go
I just noticed that d9472a0d caused the profiler package to always emit
some log output, regardless of `go test -v` being used or not. I'm very
sorry about this. IMO tests should never print to stdout unless
requested.
This patch is my attempt to fix this by making it easy for individual
tests to capture the log output (see UseLogger, RecordLogger). I've also
added DiscardLogger since it can be very convenient for tests that want
to ignore log output without capturing it. Arguably RecordLogger could
be used for this as well, but that would do a poor job of capturing the
intend of such code.
> internal/log: Improve API for testing

- README.md
Fixes #911
The grpc sub-pkg not compiling might still cause issues for some use
cases, but they are mostly related to local development. For our users
it's good enough to steer them away from the problem for now. But I'm
planning to come up with a solution for grpc as well.
> README: Fix go get instructions

- .circleci/config.yml
- go.sum
- gosum.go
[go 1.16](https://golang.org/doc/go1.16#go-command) made a change causing most go tools to act as if `-mod=readonly`
was set.
VS Code runs `go list` by default, so if this file is not up-to-date
contributors using go 1.16 will be greeted with editor errors right
away.
This problem exists for many other go workflows as well, so this patch
adds a CI check to make sure our go.sum stays up-to-date.
> CI: Check go.sum is up-to-date

- contrib/go-pg/pg.v10/pg_go_test.go
This test was always an integration test. We should mark it as such so it does not fail out of the box.
> contrib/go-pg/pg.v10: add INTEGRATION flag check for tests

- profiler/options.go
- profiler/options_test.go
- profiler/profiler.go
This env variable can be used to quickly look at the pprof files
produced by the profiler locally. This is useful when developing new
profile types that are not yet understood by the backend. It might also
be useful when working with customers who are experiencing uploading
errors.
> Implement DD_PROFILING_OUTPUT_DIR for dev/debug

- profiler/metrics.go
I noticed this issue when running the TestProfilerInternal test by
itself, which consistently produced the following error:
```
$ go test ./profiler -run TestProfilerInternal
--- FAIL: TestProfilerInternal (0.20s)
--- FAIL: TestProfilerInternal/collect (0.20s)
profiler_test.go:189: missing batch
FAIL
FAIL	gopkg.in/DataDog/dd-trace-go.v1/profiler	0.395s
```
The reason for this timeout is that the loop inside of maxPauseNs was
not hitting its termination conditions when stats.NumGC is 0. The reason
for this is subtle:
- i is uint32, so it will always be <= 0
- periodStart is "1729-02-04" when running the metrics profile for the first
time. This is caused by another issue which will be addressed in a
follow-up patch.
As far as I can tell this issue should not occur in the real world
because …
> profiler: Fix infinite loop in maxPauseNs

- codecov.yml
Based on what other Datadog teams are doing, and [recommendations from industry leaders like Google](https://testing.googleblog.com/2020/08/code-coverage-best-practices.html), we should reduce our coverage requirement to 90%.
Fixes #954
> codecov.yml: Decrease target coverage to 90%

- .circleci/config.yml
github.com/hashicorp/consul/api@v1.9.0 has broken compatibility with
versions of go less than 1.16. For now, we are pinning this to the previous
release, v1.8.1, until the issue is resolved.
See: hashicorp/consul#10470
> .circleci: pin github.com/hashicorp/consul/api to v1.8.1

- contrib/go-pg/pg.v10/option.go
- contrib/go-pg/pg.v10/pg_go.go
- contrib/go-pg/pg.v10/pg_go_test.go
> contrib/go-pg/pg.v10 add options, ServiceName

- contrib/net/http/http.go
- contrib/net/http/http_test.go
- contrib/net/http/option.go
This PR add option to skip endpoints for net/http
Fixed: https://github.com/DataDog/dd-trace-go/issues/947
> contrib/net/http: add WithIgnoreRequest option

- .circleci/config.yml
- contrib/gofiber/fiber.v2/fiber.go
This PR enables circle CI's [Collecting Test Metadata](https://circleci.com/docs/2.0/collect-test-data/) feature by producing JUnit XML. It's modeled after their [Language Guide: Go](https://circleci.com/docs/2.0/language-go/) docs.
The motivation behind this is to get [insights](https://circleci.com/blog/using-insights-to-discover-flaky-slow-and-failed-tests/) into flaky tests and to avoid having to scroll through the huge test result log output when a test fails. An example of this can be seen below or by following [this link](https://app.circleci.com/pipelines/github/DataDog/dd-trace-go/1509/workflows/058deb2d-8d99-4188-885c-2979cc3b9f7c/jobs/10249).
FWIW the [Insights](https://app.circleci.com/insights/github/DataDog/dd-trace-go/workflows/build-and-test/tests?branch=felix.geisendoerfer …
> circleci: record junit test results

- profiler/options.go
- profiler/profile.go
- profiler/profile_test.go
This is a safety mechanism for the new goroutineWaitProfile that
automatically disables the profile if the number of goroutines is too
high in order to avoid excessive stop-the-world pauses.
The default limit is 1000 which is somewhat arbitrary and should limit
STW pauses to ~30ms. It can be overwritten with
DD_PROFILING_WAIT_PROFILE_MAX_GOROUTINES.
WARNING: The goroutineWaitProfile is still experimental and not meant to
be used by users outside of datadog.
Fixes PROF-3234
> profiler: goroutineswait saw-stop mechanism

- profiler/profile.go
- profiler/profiler.go
- profiler/profiler_test.go
- profiler/upload.go
This PR fixes several issues that can cause the profiler's Stop() function to hang and delay the graceful shutdown of a client application. See https://github.com/DataDog/dd-trace-go/issues/960 for a user experiencing this type of problem.
> profiler: fix hanging on Stop()

- ddtrace/tracer/sampler.go
- ddtrace/tracer/span.go
- ddtrace/tracer/span_test.go
- ddtrace/tracer/spancontext.go
- ddtrace/tracer/spancontext_test.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
The current behavior is:
Drop the trace except if all spans should be kept.
This doesn't work if:
1. a downstream span has no error, is closed (so should be dropped) but then the rest of the trace ends up having an error so should be kept.
2. a span should be kept for app analytics (event sampling), but the trace is a p0 so the whole trace is dropped.
The PR inverses the behavior:
Keep the trace except if all spans should be dropped.
> ddtrace/tracer: Don't drop trace if some spans must be kept

- ddtrace/tracer/payload.go
- ddtrace/tracer/payload_test.go
- ddtrace/tracer/transport.go
- ddtrace/tracer/transport_test.go
- ddtrace/tracer/writer.go
This change removes the `(*payload).waitClose` mechanism added in #475
because it is no longer necessary since #549, where we've stopped
reusing payloads and started sending them async.
The change also removes the `(*payload).reset` method implementation to
further emphasise that this type of use is discouraged.
See also https://github.com/golang/go/blob/go1.16/src/net/http/client.go#L136-L138
Fixes #971
> ddtrace/tracer: remove the waitClose mechanism

- checkcopyright.go
Copyright headers, if used at all, should refer to the year(s) the code
was written or substantially updated. Update checkcopyright.go to accept
anything that looks like a year, year range or year list rather than
hard coding 2016.
> checkcopyright: accept year, year range, year list

- contrib/gofiber/fiber.v2/fiber.go
- contrib/gofiber/fiber.v2/fiber_test.go
The error returned from the fiber handler was being ignored by the middleware. It now correctly captures the error and
sets it on the span by default, falling back to the previous behavior if no error is present.
Fixes #978
> contrib/gofiber/fiber.v2: capture error from fiber handler

- contrib/go.mongodb.org/mongo-driver/mongo/mongo.go
The trace agent obfuscator expects mongo queries to be tagged as
"mongodb.query" in order to be obfuscated. They are currently tagged as
ext.DBStatement, meaning they will not be obfuscated.
Fixes #995
> contrib/go.mongodb.org/mongo-driver/mongo: query tag should be "mongodb.query"

- contrib/twitchtv/twirp/option.go
- contrib/twitchtv/twirp/twirp_test.go
PR to read serviceName from global config
Proposal:
https://github.com/DataDog/dd-trace-go/issues/989
>  contrib/twitchtv/twirp: serviceName should be read from global config

- ddtrace/opentracer/tracer.go
- ddtrace/opentracer/tracer_test.go
This change fixes so that the OpenTracing implementation returns standard errors
defined in opentracing-go, as opposed to returning errors defined in ddtrace/tracer.
Fixes #998
> ddtrace/opentracer: translate Datadog errors to OpenTracing errors

- contrib/olivere/elastic/elastictrace.go
`snip, err = ioutil.ReadAll(gzr)` was ineffectual assignment.
> contrib/olivere/elastic: fix ineffectual assignment

- .circleci/config.yml
- internal/appsec/waf.go
- internal/appsec/waf_test.go
Add the `appsec.event` span tag needed by the appsec backend to receives spans where appsec events happened.
> internal/appsec: add appsec.event span tag

- contrib/net/http/option.go
- contrib/net/http/roundtripper.go
- contrib/net/http/roundtripper_test.go
Allowing to provide additional options
when starting a new span with the round tripper.
Related issue: https://github.com/DataDog/dd-trace-go/issues/984
> contrib/net/http: add method RTWithSpanOptions

- FAQ.md
There are some questions that pop up repeatedly. Rather than giving ad-hoc
answers each time, which is tedious and may leave out some details, we can
point users to this document when they ask questions that get asked often.
> FAQ.md: create FAQ document

- ddtrace/tracer/log.go
- ddtrace/tracer/log_test.go
- ddtrace/tracer/option.go
- ddtrace/tracer/option_test.go
- ddtrace/tracer/span.go
- ddtrace/tracer/spancontext_test.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
- ddtrace/tracer/transport.go
- ddtrace/tracer/transport_test.go
This change alters the default HTTP transport client and Dogstatsd
connection so that it takes into account socket paths when available.
* /var/run/datadog/apm.socket for traces
* /var/run/datadog/dsd.socket for stats
User-config can and will override these when set.
Closes #985
> ddtrace/tracer: use UDS connection when relevant socket paths are available

- ddtrace/tracer/option.go
- ddtrace/tracer/tracer_test.go
TestTracerCleanStop is quite slow. Upon investigation, a major portion of
the cost is associated with the startup of the statsd client, which is not
important for the test to function. This change adds an unexported
StartOption to the package that uses a statsd.NoOpClient, which is much
cheaper, reducing the wall time of the test by about 90% in some cases.
> ddtrace/tracer: disable statsd client for long-running test

- ddtrace/tracer/stats_test.go
- ddtrace/tracer/tracer_test.go
- ddtrace/tracer/transport_test.go
This change introduces a wait time multiplicator that gets applied to
certain tests and scenarios when DD_APPSEC_ENABLED=true. This was
previously causing flaky tests.
> ddtrace/tracer: increase wait times for AppSec tests.

- contrib/gin-gonic/gin/gintrace.go
- contrib/gin-gonic/gin/gintrace_test.go
- contrib/gin-gonic/gin/option.go
This PR add's an option to ignore requests for contrib/gin-gonic.
Fixes: #1060
> contrib/gin-gonic: add option to ignore request

- internal/appsec/waf/waf_test.go
Fix the thread-safety of a test checking the concurrent releases
of the WAF context and its WAF handle. The WAF handle release method
should block until all its WAF contexts get released.
> internal/appsec/waf: fix test thread-safety

- .github/workflows/system-tests.yml
Do not run the system tests on external repo branches to avoid problems with DD_API_KEY.
A more advanced solution exists and should be discussed separately.
> system tests: run on repo branches only

- codecov.yml
Only run this check for pull requests, but skip it for merged commits. This
highlights patches with potential coverage problems during development, but
doesn't make our v1 (release) branch look like it fails CI checks as we
consider this check to be optional.
Example of the problem:
Example of how it will look once we apply this patch (from a [test repo](https://github.com/felixge/codecov-test) I played around with):
**Example PR:**
**Example Commit on main branch:**
> codecov: add only_pulls option for patch check

- ddtrace/ddtrace.go
- ddtrace/internal/globaltracer.go
- ddtrace/mocktracer/mocktracer.go
- ddtrace/tracer/context.go
- ddtrace/tracer/option.go
- ddtrace/tracer/tracer.go
Remove StartSpanFromContext method from ddtrace.Tracer interface to
avoid breaking users that implement this interface.
Revert tracer.StartSpanFromContext to its old behavior of inherting the
span contained in the passed context. This makes sure that users who
write tests that rely on the default NoopTracer see the same behavior as
previously.
This reverts commits 5f95c9f and 6661a9d.
> revert: StartSpanFromContext for Tracer interface

- ddtrace/tracer/log.go
- ddtrace/tracer/log_test.go
- ddtrace/tracer/tracer.go
- internal/traceprof/traceproftest/app.go
Fix a nil-pointer reference crash when clients create root spans without passing a context.
Add hotspots/endpoints to tracer startup message to help debugging.
> v1.35.0 fixups

- profiler/example_test.go
WithAPIKey is used for agentless uploading, which we don't officially support.
On top of that, the example doesn't have WithAgentlessUpload so the user would
get a warning if they ran the example code as-is.
> profiler: remove WithAPIKey from example

- ddtrace/tracer/option.go
- ddtrace/tracer/tracer.go
- internal/traceprof/traceproftest/app.go
- internal/traceprof/traceproftest/traceprof_test.go
See PROF-4730 (dd internal) for more info.
This should be the last missing thing before v1.35.0 can go out 🥳
> tracer: profiler endpoints for spans without type

- contrib/gocql/gocql/gocql.go
- contrib/gocql/gocql/gocql_test.go
- ddtrace/ext/cassandra.go
I lost my first commit somehow, but it got included in the second one...
Adds:
- Support for calling Iter.Scanner() in such a way that the Iter's trace actually closes
- Support for Batch queries including calling WithContext and adding Query's to the batch after it has been wrapped
- batch.ExecuteBatch(session) error function which inverts the session.ExecuteBatch(batch) error signature to execute the batch with tracing
- Test coverage
Additionally:
WrapQuery was incorrectly using context.Background() instead of the passed query's Context method that could already have a parent trace attached to it.
@gbbr I [screwed up the other pr](https://github.com/DataDog/dd-trace-go/pull/1111#issuecomment-1007156770) somehow trying to rebase... here's another one with the commits cherry picked …
> contrib/gocql/gocql: support Scanner and Batch

- .circleci/config.yml
The new gorm v1.22.5 introduced some regressions in our tests (https://app.circleci.com/pipelines/github/DataDog/dd-trace-go/2532/workflows/06f37dbb-2d0b-4548-aaea-95de1345291a/jobs/17965) that I couldn't easily explain so far:
1. I see nothing obvious while debugging: the tracer correctly reports the SQL statement gorm has built.
2. I see nothing obvious neither when looking at the gorm diff: https://github.com/go-gorm/gorm/compare/v1.22.4...v1.22.5 (couldn't find any release note)
Given the test failure logs, it looks like a regression to me. So we should confirm and report it to them if that's the case, and in the meantime we can enforce our gorm version to v1.22.4 to unlock the failing pull request CIs.
> circleci: enforce gorm to v1.22.4

- contrib/labstack/echo.v4/echotrace.go
- internal/appsec/dyngo/instrumentation/httpsec/http.go
- internal/appsec/dyngo/instrumentation/httpsec/tags.go
This set of commits adds response headers collection, similar to what already exists for request headers
- Add a Headers field to HandlerOperationRes and make sure to fill it roperly
- Retrieve the response headers through http.ResponseWritter public API.
- Add a parameter to SetSecurityEventTags for the function to also process response headers in the same call.
- Also make sure header normalization uses lower case to catch all headers, since http.ResponsWritter.Header() doesn't unify headers case
> internal/appsec: send http response headers on security events

- CODEOWNERS
- contrib/google.golang.org/grpc/appsec.go
- contrib/google.golang.org/grpc/appsec_test.go
- contrib/google.golang.org/grpc/server.go
- contrib/google.golang.org/grpc/stats_server_test.go
- internal/appsec/dyngo/instrumentation/grpcsec/grpc.go
- internal/appsec/dyngo/instrumentation/grpcsec/grpc_test.go
- internal/appsec/dyngo/instrumentation/grpcsec/tags.go
- internal/appsec/dyngo/instrumentation/grpcsec/tags_test.go
- internal/appsec/dyngo/instrumentation/httpsec/tags.go
- internal/appsec/dyngo/instrumentation/httpsec/tags_test.go
- internal/appsec/waf.go
First version of the appsec integration into gRPC by monitoring the
messages an RPC handler receives. To do so, the security rule address
`grpc.server.request.message` is introduced in the WAF, and a new
set of instrumentation gateway operations are now available in `grpcsec`.
More details in the specification at https://datadoghq.atlassian.net/wiki/spaces/APS/pages/2278064284/gRPC+Protocol+Support
> contrib/google.golang.org/grpc: add appsec monitoring of received rpc messages

- ddtrace/tracer/option.go
- ddtrace/tracer/option_test.go
- ddtrace/tracer/transport.go
- ddtrace/tracer/transport_test.go
If the env var `DD_AGENT_HOST` is set and the trace-agent is not running
on localhost, then the call to the agent's `/info` endpoint fails as its
using the wrong hostname.
> ddtrace/tracer: Use DD_AGENT_HOST to set trace agent hostname before querying the trace-agent for its features

- internal/appsec/appsec_disabled.go
- internal/appsec/config.go
- internal/appsec/config_test.go
- internal/appsec/waf.go
Along with exhaustive config testing to avoid such problems.
> internal/appsec/config.go: fix waf timeout configuration

- contrib/go-chi/chi.v4/appsec.go
- contrib/go-chi/chi.v4/chi.go
- contrib/go-chi/chi.v4/chi_test.go
- contrib/go-chi/chi.v4/example_test.go
- contrib/go-chi/chi.v4/option.go
- contrib/go-chi/chi.v5/appsec.go
- contrib/go-chi/chi.v5/chi.go
- contrib/go-chi/chi.v5/chi_test.go
- contrib/go-chi/chi/appsec.go
- contrib/go-chi/chi/chi.go
- contrib/go-chi/chi/chi_test.go
Note that I tried using the `http.TraceAndServe()` function but it currently lacks the following features that I felt would be better in a separate PR:
1. Configurable status code error tag
2. Computing the resource name after the call to the HTTP handler (because it's not available before).
> contrib/go-chi/chi: add appsec monitoring

- .circleci/config.yml
The default WAF timeout being 4 ms, we experienced some test failures on CircleCI due to timeouts. This patch changes the circleci config so that the WAF timeout is set to 1 s instead, which should be more than enough.
> .circleci/config.yml: set the waf timeout to a large value

- ddtrace/ext/tags.go
- ddtrace/tracer/option.go
- ddtrace/tracer/sampler.go
- ddtrace/tracer/span.go
- ddtrace/tracer/span_test.go
- ddtrace/tracer/spancontext.go
- ddtrace/tracer/spancontext_test.go
- ddtrace/tracer/textmap.go
- ddtrace/tracer/textmap_test.go
- ddtrace/tracer/tracer_test.go
- ddtrace/tracer/util.go
- ddtrace/tracer/util_test.go
- internal/appsec/dyngo/instrumentation/grpcsec/tags.go
- internal/appsec/dyngo/instrumentation/grpcsec/tags_test.go
- internal/appsec/dyngo/instrumentation/httpsec/tags.go
- internal/env.go
- internal/samplernames/samplernames.go
- Introduced a notion of trace level tags.
- Introduced a notion of propagated trace level tags.
- Introduced a new trace level tag `_dd.p.upstream_services` that holds the services changed sampling decisions.
> ddtrace/tracer: propagate _dd.p.upstream_services tags

- internal/appsec/appsec.go
- internal/appsec/config.go
- internal/appsec/config_test.go
- internal/appsec/dyngo/instrumentation/grpcsec/grpc.go
- internal/appsec/dyngo/instrumentation/grpcsec/grpc_test.go
- internal/appsec/limiter.go
- internal/appsec/limiter_test.go
- internal/appsec/waf.go
- RFC: https://docs.google.com/document/d/1X64XQOk3N-aS_F0bJuZLkUiJqlYneDxo_b8WnkfFy_0/edit
- Goal: adding a ceiling to the number of traces AppSec can force the APM intake to ingest
- Add rate limiting mechanism to report at most 100 traces/sec to APM if those traces hold appsec events
- Introduce DD_APPSEC_TRACE_RATE_LIMIT to appsec config
- Add testing for rate limier
- internal/appsec/limiter.go: lock-free rate limiter implementation using a ticker to refill the token bucket
- internal/appsec/limiter_test.go: unit/validation testing
- internal/appsec/waf.go: use limiter for http/grpc traces rate limiting
- internal/appsec/config.go: add DD_APPSEC_TRACE_RATE_LIMIT env var handling
- internal/appsec/config_test.go: add testing cases for DD_APPSEC_TRACE_RATE_LIMIT usage
- …
> internal/appsec: rate-limit appsec traces to 100 per second

- contrib/go-chi/chi.v4/chi.go
- contrib/go-chi/chi.v5/chi.go
- contrib/go-chi/chi/chi.go
Fix a nasty - and classic - mistake with the value `next` being modified in the handler as a value in the current scope while it actually is from the outer function closure scope.
It resulted in calling the httpsec middleware several times. It was caught by system tests and this is fixes the issue (ie. system tests working).
> contrib/go-chi: fix closure mistake

- contrib/google.golang.org/grpc/grpc_test.go
This benchmark attempts calls the gRPC interceptor with a few
different set of inputs, to try and measure the current overhead of
this operation. If this looks good, the goal would be to use this to
confirm that some small tweaks actually have the desired effect.
This was motivated when I noticed that the Datadog gRPC interceptor
is about 0.5% of total CPU time, and about 0.4% of all allocations
in one production application, as measured by the Datadog continuous
profiler. I think there are a few easy small wins that are possible.
I want to make sure we can measure the impact of these changes.
> contrib/google.golang.org/grpc: benchmark for unary interceptor

- ddtrace/tracer/textmap.go
- ddtrace/tracer/textmap_test.go
The new B3 flag allows a user to add B3 header propagation without an environment variable.
Fixes #1144
> ddtrace/tracer: Add B3 flag to PropagatorConfig

- .circleci/config.yml
gofiber >= v2.27.0 has a transitive dependency on a newer version of
golang.org/x/net that requires Go >= 1.15, breaking our build
> .circleci: pin gofiber to version 2.26.0

- contrib/gin-gonic/gin/appsec.go
- contrib/gin-gonic/gin/gintrace.go
- contrib/gin-gonic/gin/gintrace_test.go
- Add call to `useAppsec` in _gintrace.go_ when AppSec is enabled
- Add testing of AppSec functionalities in _gintrace_test.go_
- Add _appsec.go_ file that holds AppSec handling for gin
> contrib/gin-gonic: add AppSec support to gin framework

- contrib/gorilla/mux/mux.go
- contrib/gorilla/mux/option.go
Based on user feedback we had that didn't want to totally replace their gorilla/mux imports by ours, we would like to propose them the alternative of rather importing our contrib to wrap their gorilla router instead. To do so, we introduced a new function called `WrapRouter()` that wraps the given gorilla mux router with our wrapper.
Note that a pure gorilla middleware is not a good option for us because they do not get called when the route is not found, leading the missing all the 404 on routes that were not found on the router. This impacts both the APM tracing and the AppSec monitoring. So the current solution with `WrapRouter` instead is the best possible solution to be able to monitor every request entering the router.
> contrib/gorilla/mux: add router wrapper

- .circleci/config.yml
The gorm.io/gorm.v1 contrib tests are failing due to some dependency overriding the gorm version we have pinned. This PR is attempting to figure out why.
> .circleci: pin gorm version

- ddtrace/tracer/textmap.go
- ddtrace/tracer/textmap_test.go
The feature will be redesigned. It is still not used by the backend so there is no drawback in disabling it.
> ddtrace/tracer: disable Datadog internal tag propagation

- go.mod
- go.sum
To address dependabot vulnerability alert (https://github.com/DataDog/dd-trace-go/security/dependabot/2)
> go.mod: update github.com/gin-gonic/gin to v1.7.0

- go.mod
- go.sum
sqlx v1.3.0 was bugged and made our backend service tests fail due to the resulting upgrade to v1.3.0.
This PR downgrades to v1.2.0 which doesn't have this issue.
> go.mod: downgrade to sqlx v1.2.0

- contrib/gofiber/fiber.v2/example_test.go
- contrib/gofiber/fiber.v2/fiber.go
- contrib/gofiber/fiber.v2/fiber_test.go
- contrib/gofiber/fiber.v2/option.go
This PR fixes resource naming in gofiber/fiber.v2 module. It also adds the functionality to automatically extract and set the route parameters as a span tag on `http.path.<parameter>`.
fixes: #1197
> proposal: contrib/gofiber/fiber.v2: resource name should use route instead of path

- CONTRIBUTING.md
Semver releases are identified via `MAJOR.MINOR.PATCH` syntax.
grpc is known to break APIs that they consider experimental in MINOR releases.
> CONTRIBUTING.md: Fix wording

- internal/appsec/config.go
- internal/appsec/config_test.go
- internal/appsec/waf_test.go
Now enable the obfuscation of matched parameter values by default so
that it obfuscates sensitive data that might be contained into raw
payload values.
> appsec/config: default obfuscator config update

- internal/appsec/waf.go
- internal/appsec/waf/types.go
- internal/appsec/waf/waf.go
- internal/appsec/waf/waf_test.go
- internal/appsec/waf_unit_test.go
The 1st goal was actually fixing the fact the gRPC rule metrics were
sent on every request instead of the first one only. This was due to
the sync.Once variable not being at the right place.
I then realized we should read the AtomicU64 values using atomic.LoadUint64
to be totally safe regarding the atomic operations (atomic stores involves
atomic loads to safely read).
I finally refactored a bit further the helper functions for tags.
> internal/appsec/waf: metrics fixes

- contrib/net/http/roundtripper_test.go
This test would fail periodically as the "test" server span could appear in the finished spans list when it was unexpected. It doesn't appear the test span was useful in anyway (or tested anything) so I simply removed it which will prevent this failure mode from re-occurring.
> contrib/net/http: fix flaky roundtrip test

- contrib/miekg/dns/dns_test.go
This test was a bit flaky. It was possible for the `Exchange` function to return before the DNS server closed its span. This meant that occasionally the test would only see one span when it expected to see two.
~~I couldn't find a better way to fix this than to add a sleep before grabbing the finished spans, but if anyone sees a better way let me know.~~
> contrib/miekg/dns: fix flaky test

- profiler/profiler_test.go
TestProfilerPassthrough starts a profiler via the internal
profiler.run() method and doesn't stop it. The internal profiler
functions assume that only one profiler is actually running. The other
profiler tests muck with internal variables such as lookupProfile,
assuming there's only one profiler running, in a way that causes tests
to randomly fail or report data races when run multiple times, e.g via
go test -race -count=10
Running the tests in a random order might surface the same issues.
The immediately correct thing to do is stop the profiler at the end of
the test. Looking at the bigger picture, the real correct thing to do
is test this library in a way that's not so heavily dependent on the
internal implementation details of the library.
> profiler: stop profiler in TestProfilerPassthrough

- ddtrace/tracer/option.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
Removed limitation of having service name match the name defined when starting the tracer for version tracking.
Closes #1161
> ddtrace/tracer: add WithServiceNameMatch option

- README.md
If you try to view the contributions guide from clicking the link at https://pkg.go.dev/github.com/DataDog/dd-trace-go, the links will send you to the raw files at raw.githubusercontent.com instead of nicely formatted Markdown on github.com. Changing absolute links that point to our own Markdown files to instead be relative links should resolve this issue.
See https://github.com/golang/go/issues/52683 for context.
> README: change links to internal docs to be relative links

- profiler/profiler_test.go
TestAllUploaded starts the mutex profiler. Currently the profiler
doesn't re-set the profile rate when Stop is called. This causes
TestSetProfileFraction/on to fail if it's run after TestAllUploaded
since the test checks that the old rate is different than the new rate,
but in both cases the rates are the default rate.
This commit changes the test to start by setting the rate to 0 and then
checking that it's either the default value or still 0 after starting
the profiler. This makes the test more isolated and not influenced by
what other tests do to the mutex profile fraction.
Fixes #1279
> profiler: make TestSetProfileFraction more isolated

- profiler/profile.go
- profiler/profile_test.go
- profiler/profiler.go
- profiler/profiler_test.go
The upcoming C allocation profile will work by starting a profile,
waiting for the profile period to elapse, then stopping and collecting
the output. This won't work if the profiles are collected synchronously
since the CPU profile is also collected this way, meaning there won't be
enough time in a single profile period to collect both. So the profiles
need to be collected concurrently.
> profiler: collect profiles concurrently

- FAQ.md
Remove section obsoleted by https://github.com/DataDog/dd-trace-go/pull/1188
> FAQ: Remove go.mod section

- profiler/options.go
- profiler/upload_test.go
The profiler is tagging profiles with the "pid" tag whereas other Datadog
products use a different tag – "process_id".
Based on internal discussions, we decided to align on "process_id".
See PROF-5111 for more details.
> profiler: rename pid tag to process_id

- go.mod
- go.sum
sketches-go@v1.0.0 contains some bugs which are fixed in v1.2.1
Fixes #1021
> go.mod: update DataDog/sketches-go to 1.2.1

- profiler/profiler_test.go
The test needs to be re-evaluated as it should never have passed in the first place. See issue #1294.
> profiler: disable TestStopLatency

- ddtrace/tracer/textmap.go
- ddtrace/tracer/textmap_test.go
Synthetic tests set the header `x-datadog-parent-id` to 0. Currently, the tracer mishandles this and considers that the span id is not set when it is 0. 
This PR makes sure that header `x-datadog-parent-id` of value 0 is handled correctly when the origin is synthetics.
See APMGO-242
> ddtrace/tracer: handle parent-id header of 0 for synthetics

- contrib/emicklei/go-restful/restful.go
- contrib/gin-gonic/gin/gintrace.go
- contrib/go-chi/chi.v5/chi.go
- contrib/go-chi/chi/chi.go
- contrib/gorilla/mux/option.go
- contrib/internal/httptrace/httptrace.go
- contrib/julienschmidt/httprouter/httprouter.go
- contrib/labstack/echo.v4/echotrace.go
- contrib/labstack/echo/echotrace.go
- contrib/net/http/trace.go
- contrib/urfave/negroni/negroni.go
- ddtrace/ext/app_types.go
- ddtrace/ext/tags.go
Refactor the start and finish of http request spans into functions
shared across contribs so that the expected set of http request span
tags are properly implemented.
The new standard `http.useragent` is added in this PR as a first example of span tag addition spread out to every HTTP integration.
> contrib: refactor http request span tags

- go.mod
- go.sum
This commit updates: github.com/gogo/protobuf, github.com/valyala/fasthttp
These both had severe security issues in the versions listed in our go.mod
file. We are updating them here to ensure that dd-trace-go will never pull
a vulnerable dependency into a user's project.
> go.{mod, sum}: update several modules to avoid security flaws

- ddtrace/tracer/tracer_test.go
Apparently 200ms is not enough in all cases for async things to happen,
resulting in flaky tests. This increases the timeout to one second. If it
is not enough this can be increased more. Since these are not performance
tests we don't really care how long it takes.
Fixes #1324
> ddtrace/tracer: increase small timeout to avoid flaky tests.

- ddtrace/tracer/option_test.go
Doing a deep comparision (through `assert.Equal`/`assert.NotEqual`) of
`*http.Client`s in these tests can trigger a race detector warning:
```
=== FAIL: ddtrace/tracer TestDefaultHTTPClient/socket (0.00s)
==================
Read at 0x000001e0a080 by goroutine 123:
[ ... elided ... ]
reflect.DeepEqual()
/usr/local/Cellar/go/1.18.3/libexec/src/reflect/deepequal.go:237 +0x3f9
github.com/stretchr/testify/assert.ObjectsAreEqual()
/Users/nick.ripley/go/pkg/mod/github.com/stretchr/testify@v1.7.0/assert/assertions.go:65 +0x184
github.com/stretchr/testify/assert.NotEqual()
/Users/nick.ripley/go/pkg/mod/github.com/stretchr/testify@v1.7.0/assert/assertions.go:694 +0x204
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.TestDefaultHTTPClient.func2() …
```
> ddtrace/tracer: address race detector warning from TestDefaultHTTPClient

- README.md
Adds a comment reminder (so users won't see it, but editors will) to update the public documentation when updating the supported versions
> README: reminder to update public docs

- contrib/internal/httptrace/httptrace.go
- contrib/internal/httptrace/httptrace_test.go
- ddtrace/ext/tags.go
This change follows the RFC update: https://datadoghq.atlassian.net/wiki/spaces/APS/pages/2118779066/Client+IP+addresses+resolution.
In case multiple IP related headers are found in a request, we need to record information for the backend in the span tags.
Added tags:
- http.request.headers.*
- _dd.multiple-ip-headers
Changes:
- Change the behaviour of `getClientIP` so that it builds the list of IP headers encountered while retrieving the client IP.
- If the list compiled by `getClientIP` holds more than one element, the new tags are set with information from this list
- `genClientIPSpanTags` abstracts this decision logic and returns a map of tag key/values to set for the span
- Add an env var to disable client ip collection altogether
> contrib/internal/httptrace: record errors in span tags while retrieving client IP

- go.mod
- go.sum
See https://github.com/gin-gonic/gin/releases/tag/v1.7.7, resolves a
vulnerability. This is a direct dependency as a library for which we
provide an integration and should be updated according to our version
policy to address the vulnerability.
Resolves #1340.
> go.mod: update github.com/gin-gonic/gin to v1.7.7

- .circleci/config.yml
Pull requests from forks (as opposed to branches within this repository)
don't have access to secrets. This means they can't access the API key
needed to upload CI results to the Datadog CI app. This causes CI
pipelines from external contributors to fail, even if the actual tests
pass. Only attempt the CI upload if we actually have an API key.
> circleci: don't upload CI results without an API key

- contrib/labstack/echo.v4/echotrace.go
- contrib/labstack/echo.v4/echotrace_test.go
- contrib/labstack/echo.v4/option.go
contrib/labstack/echo.v4: introducing a SkipFunction option to selectively bypass tracing
This allows the user to provide a function which will make the decision on whether to trace a request, based on its echo.Context. This is of use to me because I'd like to stop tracing load-balancer checks every 15s.
I can see that there has been some interest in this feature for other frameworks:
- [net/http](https://github.com/DataDog/dd-trace-go/issues/947)
- [gorilla/mux](https://github.com/DataDog/dd-trace-go/issues/790)
- [labstack/echo](https://github.com/DataDog/dd-trace-go/issues/735)
> contrib/labstack/echo.v4: add WithIgnoreRequest

- go.mod
- go.sum
See https://github.com/gin-gonic/gin/releases/tag/v1.7.7, resolves a
vulnerability. This is a direct dependency as a library for which we
provide an integration and should be updated according to our version
policy to address the vulnerability.
> go.mod: update github.com/gin-gonic/gin to v1.7.7 (#1341)

- ddtrace/tracer/log_test.go
For release branches / tags if the version.Tag was set to something like `v1.39.0-rc.1` it would cause these startup log tests to fail even though it's a totally valid version tag. I've added `(-rc\.[0-9]+)?` to the version matching regex so that these tests will pass for release candidate tags. (Nick recently ran into this issue in a different branch here: https://github.com/DataDog/dd-trace-go/pull/1361)
> ddtrace/tracer: Add support for -rc.X suffixes in version tags to startup-log tests

- ddtrace/tracer/span.go
- ddtrace/tracer/span_test.go
Because we don't lock spans when flushing, a race condition occurs when `SetOperationName` is called on a finished span. Although this should not happen, this PR defend's against it in the case of an error in user code. 
With the fix, calling `SetOperationName` on a finished span is a no-op.
Test: Without the fix, `TestSpanModifyWhileFlushing` fails when run with the `-race` flag.
> ddtrace/tracer: fix race in SetOperationName

- profiler/profile.go
- profiler/profiler.go
- profiler/profiler_test.go
- profiler/upload.go
There are multiple places where additional tags are appended to the tag
slice (p.cfg.tags) for uploading the profiles or emitting statsd
metrics. All of these appends are writing to the same backing memory,
causing the tags after the user-supplied tags to be clobbered. For
example:
// function 1
tags := append(p.cfg.tag, "service:foobar")
// function 2
tags := append(p.cfg.tag, "profile_type:cpu")
Function 2 could override the "service:foobar" tag added by function 1
with the "profile_type:cpu" if the two functions run concurrently.
This manifests as the "service:<name>" tag getting overwritten in user
profiles. The agent sees the missing tag and adds
"service:unnamed-service".
Instead, we should always use a new copy of the tags slice if we want to
add more tags.
> profiler: don't clobber tags when uploading profiles or metrics

- profiler/profile.go
- profiler/profiler.go
- profiler/profiler_test.go
- profiler/upload.go
This is a cherry-pick of hotfix v1.39.1
There are multiple places where additional tags are appended to the tag
slice (p.cfg.tags) for uploading the profiles or emitting statsd
metrics. All of these appends are writing to the same backing memory,
causing the tags after the user-supplied tags to be clobbered. For
example:
// function 1
tags := append(p.cfg.tag, "service:foobar")
// function 2
tags := append(p.cfg.tag, "profile_type:cpu")
Function 2 could override the "service:foobar" tag added by function 1
with the "profile_type:cpu" if the two functions run concurrently.
This manifests as the "service:<name>" tag getting overwritten in user
profiles. The agent sees the missing tag and adds
"service:unnamed-service".
Instead, we should always use a new copy of the tags slice if we want to …
> profiler: don't clobber tags when uploading profiles or metrics (#1377)

- profiler/options.go
The tracer will disable startup configuration logging if the
`DD_TRACE_STARTUP_LOGS` environment variable is set to "false", "0", or
any other false-y value accepted by strconv.ParseBool. Do the same thing
for the profiler.
> profiler: respect DD_TRACE_STARTUP_LOGS environment variable

- profiler/internal/immutable/stringslice.go
- profiler/internal/immutable/stringslice_test.go
- profiler/options.go
- profiler/options_test.go
- profiler/profile.go
- profiler/profiler.go
- profiler/upload.go
After being bitten by a bug which was in part caused by implicitly
relying on append() creating a slice backed by new memory rather than
sharing the same allocation, we should regard the configured tags as
read-only. See PR #1377.
This commit adds a small immutable package with a StringSlice type which
wraps the slice and provides fresh copies on any access or modification,
and uses the package for the configured tags.
> profiler: make configured tags read-only

- profiler/upload.go
PR #827 introduced a randomized wait duration before retrying a failed
profile upload. This was done to reduce the likelihood of flooding the
backend with uploads. The wait was done to be an average of half the
profiling perdio. However, PR #961 lost this behavior when introducing
interruptible sleeps. This commit restores the lost behavior.
Fixes #1395
> profiler: randomize wait duration before retrying upload

- ddtrace/tracer/stats.go
- ddtrace/tracer/stats_test.go
The trace stats were not being sent on tracer.Stop() /
tracer.stats.Stop() so any unsent buckets would never be sent.
The fix is to add an option to force the bucket out on stop.
> ddtrace/tracer: force trace stats flush on Stop

- ddtrace/tracer/example_test.go
The previous example would not work by default if
copied into a fresh main() function since it was
reading a test.json file that wouldn't exist.
The new example uses context to create child spans,
which is a common use case for connecting spans. It
will also run by default if someone has the datadog
agent setup and running locally.
> ddtrace/tracer: update example to be usable by default

- .circleci/config.yml
- appsec/example_test.go
- contrib/cloud.google.com/go/pubsub.v1/example_test.go
- contrib/confluentinc/confluent-kafka-go/kafka/example_test.go
- contrib/miekg/dns/dns_test.go
- contrib/segmentio/kafka.go.v0/kafka_test.go
- ddtrace/tracer/span_test.go
This also fixes the issues found by `go vet`
> ci: Move to non-deprecated linting tools

- contrib/segmentio/kafka.go.v0/kafka.go
Closes #1397 
Writer topic might be empty, in that case topic name should be read from the message
> contrib/segmentio: reading topic name from message if writer topic is empty

- contrib/net/http/option.go
- contrib/net/http/roundtripper.go
- contrib/net/http/roundtripper_test.go
- go.mod
- go.sum
> contrib/net/http: Add new option to RoundTripper to ignore outgoing request

- contrib/internal/httptrace/config.go
- contrib/internal/httptrace/httptrace.go
- contrib/internal/httptrace/httptrace_test.go
- ddtrace/ext/tags.go
References PRs #1350 and #1346 
- multipleIPHeaders is documented to be used internally, so I removed it from ext/tags.go list of public API tags
- removed links to internal resources 
TODO:
- add a page of public documentation on DD_TRACE_HEADER_TAGS at https://docs.datadoghq.com/tracing/trace_collection/library_config/go/ or https://docs.datadoghq.com/tracing/trace_collection/tracing_naming_convention/#http-requests
> Removed links to internal resources

- LICENSE-3rdparty.csv
- profiler/internal/cmemprof/LICENSE-go
- profiler/internal/cmemprof/pprof.go
- profiler/internal/cmemprof/pprof_test.go
Since the C allocation profile might contain samples from shared
libraries, the profile should have appropriate mappings for the
different libraries, rather than a single "default" mapping. In
addition, even if we don't have function & file information for a
sample, we can at least show the library it came from.
> profiler/internal/cmemprof: add full mappings to the profile

- contrib/internal/httptrace/httptrace.go
- contrib/internal/httptrace/httptrace_test.go
- contrib/internal/httptrace/ip_default.go
- contrib/internal/httptrace/ip_go119.go
The `inet.af/netaddr` package internally imports a package
(`go4.org/unsafe/assume-no-moving-gc`) which is designed to panic when imported
for newer Go versions. As of Go 1.19, the `inet.af/netaddr` has been added to
the Go standard library under the `net/netip` package. We can prefer this
package for versions of Go >= 1.19, and fall back to `inet.af/netaddr` for
older Go versions.
The packages have nearly identical APIs. This PR abstracts away which package
is being used, and selects either the standard library version or the
`inet.af/netaddr` version depending on the `go1.19` build tag.
> contrib/internal/httptrace: don't use inet.af/netaddr if Go >= 1.19

- go.mod
- go.sum
This fixes a compatibility issue for some dd-go apps that rely on chi.v1 APIs (which were forced to upgrade to v3.3.2 because of our dependency).
> go.mod: downgrade chi to v1.5.0

- ddtrace/tracer/context.go
We've had a few issues / questions about the exact behavior here both internally and externally. I also mis-understood the exact interplay here myself, I think this makes it much clearer to a first time reader but am happy to take notes / other possible wordings.
> ddtrace/tracer: Clarify StartSpanFromContext as it has caused confusion

- profiler/profiler_test.go
Several of the tests are slow, particularly due to running the CPU
profiler, which takes ~200ms to stop. Don't run the CPU profiler for a
test if we don't actually have to.
These changes bring the test time from 15 seconds to 7 seconds on my
laptop.
> profiler: speed up several profiler tests

- internal/telemetry/client.go
This matches how we do it everywhere else
> internal/telemetry: give user config priority over environment

- go.mod
- go.sum
Backport commit from release-v1.41.x.
> [backport] go.mod: downgrade chi to v1.5.0 (#1419)

- ddtrace/tracer/span_test.go
- ddtrace/tracer/spancontext.go
- ddtrace/tracer/spancontext_test.go
- ddtrace/tracer/textmap.go
- internal/samplernames/samplernames.go
When an upstream service started the trace but did not propagate a sampling decision maker we should not propagate any data.
> ddtrace/tracer: do not propagate unknown sampling decision

- profiler/options.go
- profiler/options_test.go
- profiler/profiler_test.go
This allows overriding the value used for the `"host"` tag, consistent
with the `WithHostname` tracer option.
Fixes #1441
> profiler: add WithHostname option

- docker-compose.yaml
- test.sh
This adds:
* a flag (-l) to test.sh to run the linter
* a flag (-t) to test.sh to download the test tools
* a lower version number in docker-compose.yaml so this runs in older
docker-compose versions.
> test.sh: add linter, minor improvements

- internal/telemetry/client.go
Accessing Client.seqID atomically lead to alignment errors on 32-bit
architectures, e.g.:
$ env GOARCH=arm go test -exec=/usr/bin/qemu ./internal/telemetry
--- FAIL: TestClient (0.02s)
panic: unaligned 64-bit atomic operation [recovered]
panic: unaligned 64-bit atomic operation
goroutine 17 [running]:
testing.tRunner.func1.2({0x300328, 0x3b0728})
/home/vagrant/sdk/go1.18.3/src/testing/testing.go:1389 +0x27c
testing.tRunner.func1()
/home/vagrant/sdk/go1.18.3/src/testing/testing.go:1392 +0x3f4
panic({0x300328, 0x3b0728})
/home/vagrant/sdk/go1.18.3/src/runtime/panic.go:838 +0x23c
runtime/internal/atomic.panicUnaligned()
/home/vagrant/sdk/go1.18.3/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Xadd64(0x94c054, 0x1) …
> internal/telemetry: fix seqID atomic alignment bug

- internal/telemetry/client_test.go
- profiler/options_test.go
- profiler/profile_test.go
- profiler/profiler_test.go
Now that we've bumped our minimum supported Go version to 1.17 (see #1410) we
can use [testing.T.Setenv](https://pkg.go.dev/testing#T.Setenv). This function
is a test helper which sets an environment variable, and restores it to its
previous value when the test ends (including un-setting the variable if it was
un-set). There are a few reimplementations of this in the tests which can now
be removed.
> profiler, internal/telemetry: use testing.T.Setenv

- profiler/profiler.go
This is mainly motivated by a support case where the user did
profiler.Start(...)
profiler.Stop()
instead of
profiler.Start(...)
defer profiler.Stop()
and wasn't getting any profiles. Explicitly logging when the profiler is
stopped makes that easier to catch. Only log if startup logging is also
enabled to avoid log spam.
> profiler: log when profiler is stopped

- profiler/profiler_test.go
- profiler/upload_test.go
The http.Request type has methods for dealing with multipart requests,
and we can use them to simplify the request handlers for some of our
tests.
> profiler: simplify multipart request handling in tests

- profiler/profiler_test.go
- profiler/upload.go
- profiler/upload_test.go
Upgrading to format v2.4 lets us add custom attributes to uploaded
profiles, which have more rich type information than tags and allow for
better querying & sorting in the Datadog UI.
Along the way, consolidate some of the duplicated testing code for
creating test servers in the profiler and upload tests.
> profiler: upgrade to v2.4 upload format

- contrib/database/sql/injection_test.go
- ddtrace/tracer/sqlcomment.go
- ddtrace/tracer/sqlcomment_test.go
This makes an important update following the latest RFC proposals which adopts `traceparent` for trace context propagation instead of the ddtid, ddsid and ddsp tags. traceparent follows the [w3c trace context standard format](https://www.w3.org/TR/trace-context/#tracestate-header). 
A few related tweaks:
* I also renamed a few constants to match the more standard naming of "parent" instead of "client".
* I made the benchmark include the `Inject` in addition to the serialization of the comment. The reason being that `traceparent` includes some string formatting and I wanted to compare the performance before and after we switched to the formatted `traceparent`. You'll see that we get a hit from having a formatted value. It seems like an acceptable tradeoff. I did try an optimized version …
> contrib/database/sql: move trace context info to w3c trace context tags

- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
- internal/version/version.go
Fixes an issue where if using client side stats not all dropped p0 traces and spans would be counted.
Note this PR is against the release-v1.41.x branch so it can be released as a hotfix for v1.41
> ddtrace/tracer: Always count dropped p0 traces and spans

- ddtrace/tracer/metrics.go
- ddtrace/tracer/payload.go
- ddtrace/tracer/payload_test.go
- ddtrace/tracer/span.go
- ddtrace/tracer/span_test.go
- ddtrace/tracer/spancontext.go
- ddtrace/tracer/spancontext_test.go
- ddtrace/tracer/stats.go
- ddtrace/tracer/stats_test.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
- ddtrace/tracer/transport.go
sync/atomic has several issues. Among them is that it causes a panic when a
64-bit field isn't correctly aligned. Alignment must be manually ensured
and is easy to forget.
Instead, we will use 32-bit atomic integers which do not require manual
alignment. We can eventually trade them out for Go's new atomics APIs that
were introduced in go1.19, but we have to wait until 1.18 falls out of our
supported versions.
Fixes #1418
> ddtrace/tracer: switch atomics to 32-bit

- contrib/net/http/http.go
`http.route` tag should contain the matched route template and not the full http path. This information is not available in the `http.Handler` struct thus I chose to remove this line instead of fixing the function to provide this data.  If users want to send full http server information (including `http.route`) they should probably use `NewServeMux()` instead of `WrapHandler`
> contrib/net/http: don't set request path in Route field.

- ddtrace/tracer/sqlcomment.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
This resolves an issue that _could_ cause collisions due to `random` only using a 32 bit seed. Even though we're generating a nice cryptographically secure 64 bit seed it actually is only using 32 bits. This means that if a customer is running a large number (e.g. > 30k) of go service instances that generate spans, there is a possibility for a traceid / spanID collision.
To resolve this we XOR the generated 64 bit number with the span start time, this keeps the random numbers evenly distributed but reduces the likelihood of a collision should two instances of a service get the same random seed.
> ddtrace/tracer: better trace and span ID randomness

- .github/workflows/system-tests.yml
System tests don't run correctly on 3rd-party PRs, meaning that they will never be green. We should disable them so that we can merge green PR's and they don't confuse us or contributors.
> .github/workflows: disable system tests for 3rd-party PRs.

- internal/telemetry/client.go
- internal/telemetry/client_test.go
This change decouples the heartbeat signal and flushing data to the backend, and adds support for a configurable DD_TELEMETRY_HEARTBEAT_INTERVAL environment variable.
See https://github.com/DataDog/instrumentation-telemetry-api-docs/blob/main/GeneratedDocumentation/ApiDocs/v1/producing-telemetry.md#configurable-interval for more details.
> internal/telemetry: support DD_TELEMETRY_HEARTBEAT_INTERVAL

- ddtrace/tracer/doc.go
Clarify that some of the sampling rules apply to spans, not to traces.
> tracer: update sampling rules docs

- profiler/profiler.go
- profiler/profiler_test.go
If a user sets a profile period shorter than the default CPU duration,
but neglects to update the CPU duration, CPU profiling will still take
the default duration, exceeding the expected profile period. Add a check
to clamp the CPU duration at the configured period.
> profiler: clamp CPU duration at profile period

- profiler/profile.go
- profiler/profile_test.go
- profiler/profiler.go
Our profiler library does post-processing of profiles, such as computing
deltas for heap, block, and mutex profiles, which has non-zero CPU
overhead. Right now there's no guarantee that that work will be captured
in the CPU profile. Add synchronization so that the CPU profiler will
only be stopped after all other profiles are completed.
> profiler: ensure that CPU profile records profiler work

- profiler/internal/pprofutils/delta.go
- profiler/internal/pprofutils/delta_test.go
- profiler/profile.go
- profiler/profile_test.go
- profiler/profiler.go
Wrap up delta profiling in a type with a `Delta` method. This type holds
any information about the previous profile needed to compute the delta
with the newest profile. The profiler keeps an instance of type for each
profile type which supports delta profiling. This better encapsulates
the implementation details of delta profiling, and facilitates upcoming
implementation changes.
As part of this change, pull the logic for merging in "extra" profiles
out of the delta profiling code path. This logic was implemented for C
allocation profiling, and the extra data was passed through to delta
profiling mainly for efficiency. However, merging in extra data is
orthogonal to delta profiling and we can find other ways to make that
more efficient if we need to.
> profiler: wrap delta profiling in a type

- .github/workflows/system-tests.yml
The system-tests cron jobs [have been skipped](https://github.com/DataDog/dd-trace-go/actions/workflows/system-tests.yml?query=event%3Aschedule+branch%3Amain) since https://github.com/DataDog/dd-trace-go/pull/1476 was merged. This is an attempt to fix it.
Note: I'm not familiar with Github Actions, if folks think of a simpler approach please comment!
> .github/workflows: do not skip system-tests cron jobs

- .github/workflows/parametric-tests.yml
Parametric tests allow testing the tracers with different parameters, read more [here](https://github.com/DataDog/system-tests/tree/main/parametric).
This PR adds a job in the CI to continuously run these tests, it's similar to [how we run system-tests](https://github.com/DataDog/dd-trace-go/blob/main/.github/workflows/system-tests.yml) but in a different workflow to easily mark it not required or even disable it temporarily if needed.
> .github/workflows: add parametric tests

- profiler/internal/fastdelta/fd.go
- profiler/internal/fastdelta/fd_test.go
While looking at the internal testing that's going on, I noticed a lot of allocations caused by a `sort.Slice()`.
I think we can easily get rid of them by applying this PR. The benchmarks says this will reduce allocated objects by ~60% and CPU time by 10%.
Let me know what you think.
```
name                                  old time/op    new time/op    delta
FastDelta/testdata/heap.pprof-12         924µs ± 2%     827µs ± 3%  -10.53%  (p=0.008 n=5+5)
FastDelta/testdata/big-heap.pprof-12    12.2ms ± 4%    10.9ms ± 4%  -10.29%  (p=0.008 n=5+5)
name                                  old alloc/op   new alloc/op   delta
FastDelta/testdata/heap.pprof-12         289kB ± 0%     226kB ± 0%  -22.00%  (p=0.008 n=5+5)
FastDelta/testdata/big-heap.pprof-12    2.44MB ± 0%    1.71MB ± 0%  -29.77% …
```
> fastdelta: remove sort allocations

- codecov.yml
As long as we don't correctly report our coverage to codecov, we should disable the CI status and replace it by a simple PR comment for now. This avoids having the CI status being KO due to codecov.
> codecov: replace ci status by a pr comment

- codecov.yml
The comment is far too spammy. The minor changes in coverage due to
normal variance from running CI on an oversubscribed system are much
more distracting than informative. The coverage reports will still be
uploaded for now, assuming any developers want to see them.
> codecov: disable the coverage comment

- .github/workflows/unit-integration-tests.yml
This is required for 3rd-party authors who do not have access to secrets.
> .github: allow upload steps to fail

- ddtrace/tracer/time_windows.go
https://github.com/DataDog/dd-trace-go/pull/1509 introduced nowTime for non-Windows GOOS setups in order to allow for mocking out parts of our implementation for testing. This PR didn't include the implementation of nowTIme in Windows.
> tracer/time: implement nowTime in Windows

- profiler/internal/fastdelta/fd.go
Avoid calling sort.Sort which allocates due to the slice to interface conversion.
Also simplify the hashing a bit, no need to hash the location list and then re-hash it again, it can all go into the same hash right away.
```
$ benchstat before.txt after.txt
name                                  old time/op    new time/op    delta
FastDelta/testdata/heap.pprof-12         923µs ± 1%     833µs ± 1%   -9.75%  (p=0.000 n=9+10)
FastDelta/testdata/big-heap.pprof-12    11.6ms ± 1%    10.5ms ± 2%   -9.32%  (p=0.000 n=9+9)
name                                  old alloc/op   new alloc/op   delta
FastDelta/testdata/heap.pprof-12         199kB ± 0%     175kB ± 0%  -12.02%  (p=0.000 n=10+10)
FastDelta/testdata/big-heap.pprof-12    1.80MB ± 0%    1.53MB ± 0%  -15.11%  (p=0.000 n=10+10)
name …
```
> fastdelta: reduce allocs by up to 90%

- .github/workflows/unit-integration-tests.yml
Sets the hostname (through `DD_HOSTNAME`) for the agent container in the
integration tests.
As of Agent version 7.40.0, the agent won't start unless it can
determine its hostname. This breaks our CI, so we need to set a hostname
explicitly. See https://github.com/DataDog/datadog-agent/releases/tag/7.40.0
> CI: give agent continer a hostname

- profiler/internal/fastdelta/fd_test.go
Add a test that repeatedly generates real heap profiles, each time
creating more garbage, and checking the fidelity of the delta against
the original implementation. This is useful for stressing the implementation
and possibly shaking out more bugs. It also exercises the code in a
more realistic way, since the profiles will be different each time (which is
more like what a real app will do). We can also profile this test.
The garbage is created using mutual recursion so that there are many new
unique call stacks for each iteration. This is inspired by seeing
sorting in a profile where left and right recursive merging lead to an
exponential number of unique call stacks.
I have actually seen this fail one time (out of 50 runs). Regrettably the failure
happened before I added code to write …
> profiler/internal/fastdelta: add real heap profile stress test

- go.mod
- go.sum
Remove the molecule replace directive and depend on the latest (unreleased) version instead.
The replace directive does not apply for upstream consumers, so this patch fixes the builds for anybody that depends on the main branch of dd-trace-go.
This problem was introduced in f7fee570a5bea245a4f7c1a3d051d918be01af66 by accident.
> go.mod: fix fastdelta molecule dependency

- profiler/internal/fastdelta/fuzz_test.go
Don't run the fastdelta fuzz tests on Windows using Go 1.18.
Reading the fuzz corpus from testdata/ during CI fails on Windows
runners using Go 1.18, due to carriage return/line feed issues. This is
fixed in Go 1.19 (see https://go.dev/cl/402074), but we can just skip
these tests on Go 1.18 + Windows.
Example failure: https://github.com/DataDog/dd-trace-go/actions/runs/3451647231/jobs/5761017411#step:6:353
> profiler/internal/fastdelta: skip fuzz tests on Go 1.18 + Windows

- internal/appsec/waf/waf.go
Fix function releasing the WAF results' memory. 
Memory leaks can happen due to a wrong condition in the function.
Running our reliability environment for a day and see the memory usage doesn't grow anymore.
> appsec/waf: fix memory release condition

- .gitlab/scripts/analyze-results.sh
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
We had the candidate and baseline flipped for comparison. This fixes it.
This also resolves an issue where the Concurrent benchmark wasn't actually waiting for the go routines to finish so it wasn't measuring anything useful. This is why the performance for the concurrent tracing benchmark appears significantly worse (and why the allocs "got better" due to goroutines existing across benchmark boundaries in main)
> repo/benchmarks: Fix the benchmarks

- profiler/profile.go
- profiler/profiler_test.go
> profiler: add the Name field back for the CPU profile

- ddtrace/tracer/textmap.go
- ddtrace/tracer/textmap_test.go
Adds b3multi as a supported propagator for trace context extraction and injection, which will act as a new alias for the existing b3 propagator.
This is to align with the OTel specification.
Set `DD_PROPAGATION_STYLE_INJECT` and `DD_PROPAGATION_STYLE_EXTRACT` to `"b3"` and ensure that any headers headers propagate as expected. Then do the same for setting it to `"b3multi"` and verify that the behavior didn't change.
> tracer: support `b3multi` alias for `b3` carrier

- contrib/google.golang.org/grpc/appsec_test.go
This change fixes the appsec-grpc-related late CI failures.
It does so by updating the checks that are made to see which WAF rules have been triggered.
Some rules used were removed in a previous rules update and were thus causing the tests to fail.
A greener CI :green_book:
> contrib/grpc: update security rules in appsec tests

- ddtrace/ext/tags.go
- ddtrace/tracer/span_test.go
What does this PR do?
Renames the `error.msg` tag to `error.message` tag in order to meet the requirements of naming across all tracers.
> ddtrace/ext: change `error.msg` to `error.message` for UNC

- .gitlab/benchmarks.yml
- .gitlab/scripts/analyze-results.sh
- .gitlab/scripts/post-pr-comment.sh
1. [Change threshold](https://github.com/DataDog/relenv-benchmark-analyzer#what-is-a-significant-difference) for marking a difference in benchmark results as a statistically significant.
2. Enable S3 bucket uploading, since permissions are already configured.
3. Change how PR-commenter acts on a new benchmark result - instead of minimizing a PR comment, replace it, like it is done in the most CI/CD tools and in dd-trace-js.
Improve benchmark workflows based on previous requests from #apm-benchmarking-platform channel.
Successful S3 bucket uploading: https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-go/-/jobs/201494066
> ci: QoL improvements for benchmarks

- contrib/labstack/echo.v4/echotrace.go
- contrib/labstack/echo.v4/echotrace_test.go
- contrib/labstack/echo.v4/option.go
- contrib/labstack/echo/echotrace.go
- contrib/labstack/echo/echotrace_test.go
- contrib/labstack/echo/option.go
This adds improved error detection to the echo integrations. Previously,
any returned error was recorded as an error in the echo span. This patch
causes the integration to inspect the returned error to determine if it is
a echo.HTTPError which it can use to discriminate between real errors (5xx
and up by default) or non-errors (below 5xx by default)
This also adds a WithStatusCheck Option which allows users to configure
which errors/statuses are reported as errors. 
Fixes #987
> contrib/labstack/{echo, echo.v4}: improve error detection

- ddtrace/tracer/textmap.go
- ddtrace/tracer/textmap_test.go
Deprecates `DD_PROPAGATION_STYLE_INJECT` and `DD_PROPAGATION_STYLE_EXTRACT`. Introduces new environment variables `DD_TRACE_PROPAGATION_STYLE_INJECT`, `DD_TRACE_PROPAGATION_STYLE_EXTRACT`, and `DD_TRACE_PROPAGATION_STYLE` (which generally applies to both inject and extract). They will take the following precendence: 
1. DD_TRACE_PROPAGATION_STYLE_INJECT
2. DD_PROPAGATION_STYLE_INJECT (deprecated)
3. DD_TRACE_PROPAGATION_STYLE (applies to both inject and extract)
4. If none of the above, use default values
Although the diff in `textmap_test.go` looks significant, the testing behavior didn't change drastically. The only difference is that all of the tests run repeatedly using a mix of environment variables to ensure that the correct precedence is used, and each of the 3 ways to configure …
> tracer: replaces INJECT/EXTRACT environment variable names

- .github/workflows/govulncheck.yml
Avoid bash script problem (especially due to the previous `echo $results | wc -l` always returning 1.
The bash script is always failing due to a mistake. To avoid it and make this CI more useful, we instead let govulncheck report its exit code along with its detailed output to make this workflow directly usable.
> ci/govulncheck: fix and simplify the bash script

- contrib/go-pg/pg.v10/pg_go.go
- contrib/go-pg/pg.v10/pg_go_test.go
ORMs by nature are internal spankind values which go-pg mistakenly was not.
Removes the spankind tag and updates tests such that it follows the theme of ORMs being internal
> contrib/go-pg/pg.v10: fix spankind value

- internal/appsec/remoteconfig.go
- internal/remoteconfig/remoteconfig.go
Properly handle many error cases that were not in the remote config client.
Especially the "no remote config update" case `{}` that is leading to a json parsing error in the repository `Update()`. 
Backport of `release-v1.45.x` changes
We are experiencing "unexpected end of JSON input" errors in staging and prod, since v1.44.0.
> internal/remoteconfig: client error handling (backport of release-v1.45.x fixes)

- .github/workflows/unit-integration-tests.yml
- ddtrace/tracer/metrics.go
- ddtrace/tracer/metrics_test.go
- ddtrace/tracer/option.go
- ddtrace/tracer/option_test.go
- ddtrace/tracer/sampler_test.go
- ddtrace/tracer/span_test.go
- ddtrace/tracer/stats.go
- ddtrace/tracer/textmap_test.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
- ddtrace/tracer/transport.go
- ddtrace/tracer/writer.go
- ddtrace/tracer/writer_test.go
Tests have been failing to clean up after themselves and causing memory usage issues during unit test runs.
One cause of this is failing to shut down a tracer after starting it, which is solved simply by defering tracer.Close() for those tests.
Other tests use newConfig() to generate a tracer config, which they use for various purposes. Unfortunately newConfig() actually creates a statsd client for the new config, which needs to be Close()'d in order to release its resources. It doesn't make much sense to need to Close() a config, or have to Close() something *in* a config, so this problem requires a more complicated solution. Instead, the config still calculates the statsd address, but the actual instantiation of the statsd client is moved into newTracer, where the worker routines and …
> ddtrace/tracer: clean up resources in tests

- internal/version/version.go
Bump the version constant to 1.47.0, following the 1.46.0 release.
> internal/version: bump to v1.47.0

- CODEOWNERS
Changes CODEOWNERS so that `internal/` gets the default ownership.
The stuff in `internal/` is shared across the different products, so `apm-go` seems like the appropriate ownership rather than just `tracing-go`.
> CODEOWNERS: give internal/ default ownership

- ddtrace/tracer/textmap.go
- ddtrace/tracer/textmap_test.go
This PR adds support for B3 Single header propagation via the `b3` header.
The multi-header approach is considered "old". The new single header is more compact which can free up additional headers in environments where the total number of headers is restricted.
The Unit tests here are pretty thorough. If desired, a test with two apps both using only `b3` to propagate trace info and verifying those traces appear in the datadog UI can be done.
There are also system tests however, they are currently broken due to a possible bug that is being resolved here: https://github.com/DataDog/system-tests/pull/753
> ddtrace/tracer/textmap: Add support for b3 single header propagation

- internal/env.go
- profiler/options.go
- profiler/profile.go
- profiler/profiler.go
- profiler/profiler_test.go
- profiler/upload.go
Add support for periodically collection runtime execution traces through runtime/trace. To manage the overhead, traces are collected for short durations and with lots of time between collections.
Collection is enabled by setting the `DD_PROFILING_EXECUTION_TRACE_ENABLED` environment variable to "true". By default, a 1-second trace will be collected roughly every 5000 seconds. The collection duration and period can be configured with the `DD_PROFILING_EXECUTION_TRACE_DURATION` and `DD_PROFILING_EXECUTION_TRACE_PERIOD` environment variables, respectively.
The execution tracer is an incredibly rich data source for understanding latency in Go programs.
This PR includes a small unit test, but we'll also want to try it out in our internal reliability environment.
> profiler: support periodic execution trace collection

- profiler/options.go
Log execution trace configuration at profiler startup. Missed in #1649
> profiler: log execution trace configuration

- profiler/profile.go
- profiler/profile_test.go
This should significantly reduce the profiler overhead when memory profiling is enabled.
If needed, the previous implementation is still available behind an environment variable:
DD_PROFILING_DELTA_METHOD=slowdelta
This option will be removed in a future release.
> profiler: enable fastdelta by default

- profiler/profile.go
- profiler/upload.go
Returns a copy of the fast delta profile bytes.
To fix a data race. The fast delta profiler re-uses
a bytes.Buffer for each profile computation. The underlying byte slice
from that buffer is passed on to be uploaded. This is flagged as a race
by the race detector. While delta profile computation and uploading
_shouldn't_ generally happen at the same time, this is still a logical
race. It could be a real problem if the upload fails a bunch, causing the
buffer to be corrupted when delta computation and uploading overlap.
The simplest fix for this race is to just allocate a new bytes.Buffer
for each delta computation.
This passes all the existing unit tests under the race detector, including the
ones which failed previously.
> profiler: return copy of delta profile data to avoid race

- contrib/aws/aws-sdk-go-v2/aws/aws.go
- contrib/aws/aws-sdk-go-v2/aws/aws_test.go
- contrib/aws/aws-sdk-go/aws/aws.go
- contrib/aws/aws-sdk-go/aws/aws_test.go
- contrib/net/http/roundtripper.go
- contrib/net/http/roundtripper_test.go
This PR ensures auth strings are not present in URLs before attaching them to spans in the `http.url` tag
Cherry-pick of #1662 for patch release on `v1.46.x` line.
> contrib/{aws/*,net/http}: fix encoding of http.url (#1662)

- ddtrace/tracer/metrics.go
- ddtrace/tracer/metrics_test.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
Flush() flushed buffered traces, but it did not flush stats. We added flushing for both the stats concentrator and the statsdClient when Flush() is called.
There were issues in parametric tests because Flush() did not flush stats. Fixes #1547
> tracer: enable stats flushing when Flush() is called

- README.md
Updates the directions for how to run integration tests locally
in our README.
We have the nice test.sh script now. We've also switched to GitHub
Actions so the CircleCI stuff is outdated.
> README: update how to run integration tests locally

- ddtrace/ddtrace.go
- ddtrace/example_test.go
- ddtrace/tracer/context_test.go
- ddtrace/tracer/option.go
- ddtrace/tracer/span.go
- ddtrace/tracer/spancontext.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
Adds support for generating 128 bit trace ids and exposing them from the Datadog API via a new `SpanContextW3C`. Future PRs will propagate this id for distributed tracing.
The downside of this approach is that if clients want to access the 128 bit trace ids in their code, they must type-cast (as shown in `example_test.go`). However, there is no other feasible approach while still maintaining backwards compatibility for the API. This can be cleaned up in v2.
Toggle `DD_TRACE_128_BIT_TRACEID_GENERATION_ENABLED` to generate 128 bit trace ids and ensure that you can access them programmatically in your tracer example.
> ddtrace/tracer: 128-bit support

- internal/remoteconfig/config.go
- internal/remoteconfig/remoteconfig.go
- internal/remoteconfig/remoteconfig_test.go
- Set the default polling interval to 5s
- Read the polling interval from the `DD_REMOTE_CONFIG_POLL_INTERVAL_SECONDS` env var
- Use the default value if reading the above env var fails
- Add testing for the new env var
Comply with the global RC specs
> internal/remoteconfig: configure poll interval through an env var

- ddtrace/tracer/tracer.go
Using the execution tracer's Log functionality, annotate execution trace tasks
corresponding to APM spans with their span IDs.
This PR also arranges for the pprof context.Context to hold execution trace
task info, so that there is a proper parent/child relationship between tasks
corresponding to the same relationship between APM spans.
Logs are the most efficient way to capture span IDs in the
execution trace right now, since we don't get any benefit from interning
what's effectively going to be a new value for each span. We do pay a
roughly 1 microsecond cost for collecting another stack trace (give or take 
depending on stack depth) plus another allocation to serialize the span ID.
We only pay that price if execution tracing is actually enabled, though.
Provide a mechanism for a trace …
> ddtrace/tracer: annotate execution trace with span IDs

- profiler/profiler_test.go
Fixes the [windows ci tests](https://github.com/DataDog/dd-trace-go/actions/runs/3994308804) broken by 0d7ea332e47bd82f4d84110ad14e5f179c989a47.
The problem was caused by the tracer starting up very slowly on windows due to slow network timeouts (see https://github.com/DataDog/dd-trace-go/commit/0013a52f2ded06043c29d8393c2519273dc25ec5).
This patch does not attempt to speed up the network timeout. This would require access to `withStatsdClient(&statsd.NoOpClient{})` which is a refactoring I don't have time for right now. But if we decide that we need faster windows tests at some point I'm happy to do this.
Green is good, red is bad.
I've tested this on Windows Server 2022, see screenshot.
> Fix windows CI

- ddtrace/ddtrace.go
- ddtrace/tracer/option.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
Remove the `WithTraceID128` API that was added to this feature branch (not currently in a dd-trace-go release or in main).
There isn't enough evidence that we need this API at this time, and the UX is confusing as it is. Currently, the only way to set the trace id programmatically is for root spans using `WithSpanID`, which then applies the trace id. Adding a separate API just to set the higher bits is likely to lead to confusion, and we should redesign this for v2 anyway.
> tracer: remove WithTraceID128

- ddtrace/tracer/span.go
- ddtrace/tracer/span_test.go
- ddtrace/tracer/tracer.go
Support `DD_TRACE_128_BIT_TRACEID_LOGGING_ENABLED` to only log 128 bit trace id values when enabled.
This is configurable to avoid potential backwards compatibility issues with internal systems during migration to supporting 128 bit trace ids.
Enable `DD_TRACE_128_BIT_TRACEID_GENERATION_ENABLED` and `DD_TRACE_128_BIT_TRACEID_LOGGING_ENABLED` and ensure that the trace id is logged as expected.
> tracer: support DD_TRACE_128_BIT_TRACEID_LOGGING_ENABLED

- internal/telemetry/client.go
rename the language name from `golang` to `go` in the instrumentation telemetry client.
The documentation for instrumentation-telemetry specified the value `golang` as the reported language name but this is not  uniform with the existing ways it's reported. Since this feature is not GAed in dd-trace-go, let's fix it before we have to care about backward compatibility.
> internal/telemetry: uniformize language name with other ways it's reported

- checkmilestone.go
This commit changes the `checkmilestone.go` program so that it does not allow merging when Milestone is `Triage`. 
This is to prevent PR's from being merged but not being associated with a release, and not showing up in release notes.
This PR is in milestone Triage. The milestone test should fail. Before merging, I will move it to the correct milestone and ensure that the CI passes.
> checkmilestone.go: do not allow merging into triage milestone

- contrib/net/http/example_test.go
- ddtrace/tracer/doc.go
Adds an example for connecting a net/http handler to an outgoing call using net/http Client
Recently had a colleague reach out trying to do this. In the process of helping them I realized our documentation for how to do this is lacking. I'm hoping adding this example and a link to it from the ddtrace docs will make this easier / less error-prone for customers.
No QA needed
> contrib/net/http: Adding an example for wrap client

- contrib/miekg/dns/dns.go
- contrib/miekg/dns/dns_test.go
Fixes span kind for dns server traces - this library is used both for DNS client and server and we were setting type client for both.
Also refactored tests and increased test coverage for some functions not covered by existing tests.
We want to set correct span kind for DNS server traces.
Updated existing tests.
> contrib/miekg/dns: fix span kind for dns server traces

- contrib/gin-gonic/gin/example_test.go
clarify that the middleware has to be registered before routes
> contrib/gin-gonic/gin/example: middleware must be registered before registering routes

- ddtrace/tracer/span.go
- ddtrace/tracer/tracer_test.go
Add the `usr.id` span tag even when the user id propagation is enabled.
At first, we thought the backend would enrich this span tag based on the propagated `_dd.p.usr.id` one, but having `usr.id` present is part of the feature:
1. `_dd.p.usr.id` is set alone when it was found in the HTTP header for propagated tags (note how anyone can set it)
2. `usr.id` must always be set when using the `SetUser()` function, so that we can know that the user id has been programmatically set.
- Go test from this PR
- System tests: https://github.com/DataDog/system-tests/blob/main/tests/test_identify.py (opening a PR to update them)
> ddtrace/tracer: add usr.id even with propagation

- ddtrace/tracer/option.go
- ddtrace/tracer/payload.go
- ddtrace/tracer/payload_test.go
- ddtrace/tracer/writer.go
- ddtrace/tracer/writer_test.go
This pull request implements trace writer retries when there is a failure. It does so by cloning the payload before sending it. Retries are optional and are enabled by default when running in AWS Lambda.
Note that this change introduces an extra allocation for every send attempt. However, it only does so when the tracer is configured for retries. Therefore, the extra allocation will only occur when run in lambda. I feel this is a reasonable trade off.
In very rare cases, we are seeing errors like
```
2022/12/19 21:09:41 Datadog Tracer v1.45.1 ERROR: lost 1 traces: Post "http://localhost:8126/v0.4/traces": read tcp 127.0.0.1:44108->127.0.0.1:8126: read: connection reset by peer ([send duration: 0.327196ms]) (occurred: 19 Dec 22 21:07 UTC)
2022/12/19 21:15:44 Datadog Tracer v1.45.1 ERROR: …
```
> ddtrace/tracer: enable trace writer to optionally retry on failure.

- ddtrace/tracer/option.go
Tries to make `TestWithUDS` pass on Windows.
We still need to give a full URL to the HTTP client, with the "http"
scheme, but we want the URL to somewhat resemble the UDS path. Windows
paths contain colons and back-slashes. Colons in particular cause
trouble because they're usually followed by a port. See this failure
for example:
https://github.com/DataDog/dd-trace-go/actions/runs/4068558554/jobs/7007255118#step:6:169
```
=== FAIL: ddtrace/tracer TestWithUDS (0.00s)
transport_test.go:299: 
Error Trace:	D:\a\dd-trace-go\dd-trace-go\ddtrace\tracer\transport_test.go:299
Error:      	Received unexpected error:
cannot create http request: parse "http://UDS_C:%5CUsers%5CRUNNER~1%5CAppData%5CLocal%5CTemp%5Csocket3746974948%5Capm.socket/v0.4/traces": invalid port …
```
> ddtrace/tracer: replace Windows path characters in fake UDS host

- ddtrace/tracer/rules_sampler.go
- ddtrace/tracer/span.go
- internal/samplernames/samplernames.go
Move `SamplerName` to meet the conventions of the rest of the repo.
> tracer: small refactor for single span sampling

- ddtrace/tracer/span_test.go
- ddtrace/tracer/spancontext.go
- ddtrace/tracer/textmap.go
- ddtrace/tracer/textmap_test.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
Supports 128-bit trace id propagation in B3 multi headers. Other carriers will be supported in future PRs, and TODOs have been added in the code where it is needed.
Also fixes the issue where a `spanContext` needed to have an associated span to access and store 128-bit trace ids. It is now a separate field of the `spanContext`. Now, the `_dd.p.tid` tag in the `Meta` map (upper 64 bits of 128-bit trace ID) is populated from the `spanContext` upon span finish.
Updates #909
> tracer: support 128-bit propagation of B3 multi header

- README.md
See title/diff.
As discussed in the guild.
Not applicable.
Not applicable.
> README: Clarify Legacy Go Compilation Guarantees

- ddtrace/tracer/textmap_test.go
- ddtrace/tracer/tracer.go
- ddtrace/tracer/tracer_test.go
Small refactor to tests to make it easier to test with 128-bit trace ids for other carriers.
These tests could probably be refactored even further to have less repetition, but for now, it's just extending them to support 128-bit trace ids.
> tracer: refactor tests to support 128-bit trace id propagation

- .gitlab/scripts/run-benchmarks.sh
Updates the benchmarking scripts so that we evaluate against our common ancestor with main.
Currently we baseline against `main`, this can cause confusion where the PR branch hasn't merged the latest changes from `main` in. This change was recommended by @ddyurchenko who shared this is how the JS team handles it.
no QA needed
> .gitlab/scripts: Benchmark against common ancestor, not latest in main

- internal/remoteconfig/remoteconfig.go
Add a new capability to the list of capabilities handled by the remote configuration client.
This capability, `ASMUserBlocking`, can be registered for apps that are capable of blocking requests based on the user
ID.
This is needed as part of the AppSec user blocking feature (see https://github.com/DataDog/dd-trace-go/pull/1706)
> internal/remoteconfig: add ASMUserBlocking capability

- contrib/gin-gonic/gin/gintrace.go
- contrib/labstack/echo.v4/echotrace.go
Explicitely call `appsec.Enabled()` every time we want to check that appsec is enabled, instead of calling
it once and only using the cached value.
Appsec can now be enabled at runtime through remote configuration meaning that the value returned by `appsec.Enabled()`
can change during execution. Explicitely calling `appsec.Enabled()` makes sure the actual value used in our conditions is accurate.
> contrib: stop caching appsec.Enabled() value for gin/echo

- appsec/appsec.go
- appsec/appsec_test.go
- appsec/example_test.go
- contrib/google.golang.org/grpc/appsec.go
- contrib/google.golang.org/grpc/appsec_test.go
- internal/appsec/dyngo/instrumentation/common.go
- internal/appsec/dyngo/instrumentation/grpcsec/actions.go
- internal/appsec/dyngo/instrumentation/grpcsec/grpc.go
- internal/appsec/dyngo/instrumentation/grpcsec/grpc_test.go
- internal/appsec/dyngo/instrumentation/httpsec/http.go
- internal/appsec/dyngo/instrumentation/httpsec/tags.go
- internal/appsec/dyngo/instrumentation/sharedsec/shared.go
- internal/appsec/dyngo/operation.go
- internal/appsec/remoteconfig.go
- internal/appsec/testdata/blocking.json
- internal/appsec/waf.go
- internal/appsec/waf_test.go
This change adds a new SDK to the appsec top level package, `SetUser()`. `SetUser()` wraps the existing `tracer.SetUser()`
and performs a WAF call to check if the user ID passed to `SetUser` is on a block list, in which case an error is returned,
instructing the SDK user to block the request execution as soon as possible.
Additionally:
- A new remote configuration capability is added - `ASMUserBlocking`, and registered during remote config initialization by appsec
- `TrackUserLoginSuccessEvent()` now uses `appsec.SetUser()` and returns an error if the user should be blocked
This is a planned feature.
The change includes integration tests to test both the high level API usage (in the appsec package) and
the internal mechanics (internal/appsec), as well as the gRPC integration …
> internal/appsec: request blocking based on user ID

- profiler/options.go
- profiler/profile.go
- profiler/profiler_test.go
Adds a size limit for controlling execution trace recording. The size limit can
be configured using the `DD_PROFILING_EXECUTION_TRACE_LIMIT_BYTES` environment
variable, and defaults to 5MB (discussion below).
The execution trace duration configuration is removed, and the profiler will
attempt to record for the full profiling period, until the size limit is
reached.
Size is a better proxy for tracer overhead than duration. Overhead comes from
recording events, and execution trace size scales with the number of events
recorded. By using size, we can get larger traces for lightly-loaded services,
and maintain reasonable processing latencies and bandwidth usage.
The 5MB default limit still deserves some discussion. I picked this after
locally testing and seeing a tolerable latency for trace …
> profiler: use size as the bound for execution trace recording

- profiler/profiler_test.go
- profiler/upload.go
Change the tag for profile uploads with execution trace data to
`go_execution_traced:yes`.
It's shorter and matches the tag we added for traced spans.
Unit test updated.
> profiler: make execution trace tag match the span tag

- contrib/labstack/echo.v4/appsec.go
- contrib/labstack/echo.v4/appsec_test.go
This change ensures that the error returned by the appsec echo middleware is always an `echo.HTTPError` (or nil).
This is needed so that the top level APM code doesn't override the response status span tag with `500`, which
happens if it encounters any other error type than `echo.HTTPError`
This fixes a bug spotted while enabling user blocking system-tests.
> contrib/echo: wrap appsec error in echo.HTTPError

- ddtrace/tracer/span.go
- ddtrace/tracer/span_test.go
When `DD_TRACE_128_BIT_TRACEID_LOGGING_ENABLED` is false, only the lower-order 64-bits of the TraceId should be logged.
When `DD_TRACE_128_BIT_TRACEID_LOGGING_ENABLED` is true, the format of the injected TraceId is conditional based on the higher-order 64 bits of the TraceId - specifically, when:
- zero - the injected TraceId will be its decimal string encoding (preserving the current behavior of 64-bit TraceIds)
- non-zero - the injected TraceId will be encoded as 32 lower-case hexadecimal characters with zero-padding as necessary
The logging requirements of the RFC recently changed, so this is to align with other tracers.
> tracer: fix trace id logging

- ddtrace/tracer/textmap.go
- ddtrace/tracer/textmap_test.go
This cherry-picks across the change made in #1759 
tested in unit test
> ddtrace/tracer/textmap: always extract baggage when using w3c for compat

- profiler/profile.go
- profiler/profiler_test.go
Sets the timestamp for the last execution trace recording at the beginning,
rather than the end, of recording.
Setting a tracing period matching the profile period will do the expected thing
of sending a trace with every profile upload, rather than every _other_ profile
upload.
The unit test has been updated. Previously, with a profile period of 1 second
and a trace period of 3 seconds, it took 5 uploads to see the expected 2
traces. But really it should only have taken 4.
> profiler: record timestamp at the start execution tracing

- contrib/database/sql/conn.go
- contrib/database/sql/sql.go
We would prefer to be able to type assert to this interface type, but we cannot type assert without the type being exported. The alternative would be to use reflection here.
In addition, we want to be able to, on occasion, access the underlying connection object, hence the addition of the WrappedConn() function.
This is an up-to-date-version of https://github.com/DataDog/dd-trace-go/pull/1566 , you can read this change  there.
> database/sql: Export TracedConn, as we need it when using the db.Conn Raw() API call.

- .github/workflows/system-tests.yml
This PR enables the APM end-to-end (E2E) tests in Github Actions CI.
At the moment, the default test is enabled for all variants, but the [Single Spans test is only implemented for the `chi` variant](https://github.com/DataDog/system-tests/blob/3a028228a56671e7fb10ff85cb6039f0efb45ec1/utils/build/docker/golang/app/chi.go#L136-L160). All other variants will still run the jobs, but are skipped (in system-tests terms they are expectedly failing).
Once we verify that this works well, we can implement the rest variants too, in follow-up PRs.
Examples of successful jobs:
- `chi`: https://github.com/DataDog/dd-trace-go/actions/runs/4366904885/jobs/7651749363
- Single Spans test runs and passes.
- `echo`: https://github.com/DataDog/dd-trace-go/actions/runs/4366904885/jobs/7651749157
- Single …
> .github/workflows: integrate APM E2E tests in Github Actions CI

- internal/osinfo/osinfo_linux.go
Fixes #1790
This might be a breaking change.
> Fix returned OS name on Linux

- profiler/profiler.go
- profiler/profiler_test.go
Document that Start will restart the profiler with the given configuration if
the profiler was already running. Add a test to lock in this behavior.
This PR also removes the TestStartStopIdempotent test. This test made no
assertions, and at any rate Start was not idempotent to begin with.
Start will first stop the profiler if it is already running, and the
re-start it with the given configuration. This behavior is not
documented. It is also not tested--the current test suite passes if
Start is changed to return early when the profiler is already active.
It is possible that there are apps out there which rely on this behavior
(some of our internal apps do), and it would be a breaking change for
these apps to make Start do nothing if the profiler is already started.
Given that there isn't a …
> profiler: document/test that Start restarts the profiler

- ddtrace/tracer/log_test.go
- ddtrace/tracer/spancontext_test.go
- ddtrace/tracer/textmap_test.go
- ddtrace/tracer/tracer_test.go
- ddtrace/tracer/writer_test.go
- internal/log/log.go
- internal/log/log_test.go
Some unit tests in the tracer assert based on the content or positioning of log messages ([example](https://github.com/DataDog/dd-trace-go/blob/68bff5f324e762ce8b7dce14411554a0423f2f24/ddtrace/tracer/log_test.go#LL28-L29C27)). When new log messages are added (e.g. by appsec) these tests will fail. To workaround this, we've previously introduced a `removeAppsec` method that removes strings which contain `appsec: ` from recorded logs. This PR introduces an alternate solution to directly ignore certain substrings using `RecordLogger` while logging.
More specifically, this PR:
- removes `testLogger` from the tracer package. `testLogger` has a near identical implementation to `RecordLogger` in the `internal/log` package, so we can just use `RecordLogger` instead.
- adds a `Ignore` method to …
> internal/log: allow RecordLogger to ignore certain logs
