DataDog/dd-trace-go

profiler/profile.go, profiler/profile_test.go
Deprecates the PprofDiff function. It will be removed in v1.50.0.
The PprofDiff function was added to our public API unintentionally as
part of #1511. The function is only meant for internal use. This was
missed during code review, likely due to the size of the change and the
fact that most of our attention was devoted to making sure the core
parts of the change were implemented correctly.
This is an exception to our normal v1 compatibility guarantees. It is
very unlikely that any of our users depend on this function. It serves
no purpose in the context of the profiler's public API, and anybody who
might have a reason to use this function would probably have already
found a way to do what they want using the
github.com/google/pprof/profile package.
N/A
=> profiler: deprecate PprofDiff

.gitlab/scripts/analyze-results.sh, .gitlab/scripts/config-benchmarks.sh, .gitlab/scripts/run-benchmarks-with-profiler.sh, .gitlab/scripts/run-benchmarks.sh
This PR adds profiler runs for benchmarks if regression was detected. This should add more confidence in results and allow to see what caused change in performance.
=> Add profiler runs on regression

ddtrace/tracer/span_test.go, ddtrace/tracer/spancontext.go, ddtrace/tracer/textmap.go
Fixes a few 128-bit bugs:
- guarantee that the propagating tags have been set before reading them during extraction
- only set `_dd.p.tid` if the top 64 bits is not empty or zero
- always set `_dd.p.tid` to 16 characters, with padding if needed
PR was a collaboration with @ajgajg1134 @knusbaum @lievan
=> WIP: tracer: 128-bit trace id bug fixes

ddtrace/tracer/textmap.go, ddtrace/tracer/textmap_test.go
Align the W3C trace context parsing with the RFC:
- `traceparent` header with version > 0 can be longer than 55 characters if str[55]=="-"
- The length of `traceparent` header with version == 0 has to be 55
Fixes `test_headers_tracecontext.py::test_traceparent_version_0xcc` in system tests.
`test_headers_tracecontext.py::test_traceparent_version_0xcc` passes in system-tests
=> ddtrace/tracer: fix traceparent length check

ddtrace/tracer/context_test.go, ddtrace/tracer/span.go, ddtrace/tracer/span_test.go, ddtrace/tracer/spancontext.go, ddtrace/tracer/spancontext_test.go, ddtrace/tracer/textmap.go, ddtrace/tracer/textmap_test.go, ddtrace/tracer/tracer.go, ddtrace/tracer/tracer_test.go
Refactor the spancontext `traceID` to be a `[16]byte` instead of a `uint64`. This is a marginal memory gain over storing the upper bits as a hex string at a slight cost of possibly needing to hex-encode more frequently. 
It's confusing to have the trace id split up across fields and as different types, it led to odd looking code occasionally where some bits of the ID would need to be encoded or decoded for the use-case at hand. I _believe_ this refactor is an improvement in readability, although admittedly this code is still a bit confusing. Notably `newContext` as the `span` type can't be changed as it's exactly marshalled to the agent in its current form.
The unit tests, system tests, parametric tests should sufficiently cover this refactor I believe, but given this touches a critical …
=> tracer: Refactor span context's TraceID to be a full [16]byte

internal/telemetry/client_test.go
Fix a flaky `TestAgentlessRetry` test. 
This test creates a server that acts as a fake agentless endpoint and waits for a request to verify telemetry is being sent to the agentless endpoint. The handler runs `received <- struct{}{}` when it receives the first request, which verifies agentless retry is working and the test then tries to close the server.
Sometimes, a second telemetry message triggers `received <- struct{}{}` before the server closes, but now there is no one waiting on the other side of the channel. This then causes `server.Close()` to be blocked.
Fix by 
1) ignoring all messages except for `app-started` in the server handler 
2) making the received channel buffered and have sending to the channel be non-blocking (thanks to @nsrip-dd)
In the `internal/telemetry` directory: …
=> internal/telemetry: fix flaky agentless retry test

ddtrace/tracer/option.go, ddtrace/tracer/span.go, ddtrace/tracer/span_test.go, ddtrace/tracer/tracer.go, ddtrace/tracer/tracer_test.go, internal/namingschema/namingschema.go
- Move `DD_TRACE_SPAN_ATTRIBUTE_SCHEMA` env variable read and parsing to `ddtrace/trace` package.
- Set `_dd.trace_span_attribute_schema` metric tag to the value of the selected `DD_TRACE_SPAN_ATTRIBUTE_SCHEMA` version (`0` or `1` currently). This tag is only set for root spans.
This tag is necessary so we can track the used schema version.
=> ddtrace/tracer: add attribute schema version config variable and tag

internal/appsec/dyngo/instrumentation/httpsec/tags.go, internal/appsec/dyngo/instrumentation/httpsec/tags_test.go
Fix the new `ClientIP()` algorithm so that it properly stops as soon as a global IP address is found in the HTTP headers. This patch fixes the `break` statement that was performed on the inner for loop instead of the outter, and therefore continuing to look at the next HTTP headers, therefore returning the last global IP address found.
=> httpsec/client-ip: stop walking the headers as soon as a global ip is found

.github/workflows/parametric-tests.yml, .github/workflows/system-tests.yml
The parametric tests app uses the opentelemetry package, which hasn't
been merged. This means it can't build on branches against main, so CI
is broken. Pin to before the tests were changed.
Fix CI.
=> ci: pin system tests until opentelemetry changes are merged

ddtrace/tracer/option.go, ddtrace/tracer/option_test.go, ddtrace/tracer/tracer.go, internal/hostname/providers.go
Adds env var "DD_CLIENT_HOSTNAME_ENABLED" which allows users to disable client hostname detection by setting this value to `false` (Note the value defaults to true)
Some customers may need to disable this if they have aggressive security tooling that alerts on access to cloud metadata APIs. 
unit tests are good!
=> tracer/option: Add envvar DD_CLIENT_HOSTNAME_ENABLED to config client hostname detection

contrib/go-redis/redis.v8/example_test.go
Closes #1629 
Make it clearer that one can wrap a ClusterClient to get tracing
None needed
=> contrib/go-redis/redis.v8: Add example for ClusterClient

.github/workflows/parametric-tests.yml
Reverts DataDog/dd-trace-go#1849
https://github.com/DataDog/dd-trace-go/pull/1839 is now merged, which adds support for the OTel API and will fix the issue with the imports.
=> Revert "ci: pin system tests until opentelemetry changes are merged"

internal/gitmetadatabinary.go
Move unknown VCS log to debug level so it doesn't appear to customers by default.
@sashacmc as FYI
Closes #1800 
no QA needed
=> internal/gitmetadata: Log unknown VCS as debug to reduce confusion

.gitlab-ci.yml, .gitlab/benchmarks.yml
Fixes the bug in .gitlab-ci.yml due to duplicate `include` key (and yet - it is valid yaml!)
Benchmarks should be run automatically for each branch again.
=> ci: restore automatic benchmark runs

go.mod, go.sum, internal/appsec/appsec.go, internal/appsec/config.go, internal/appsec/config_test.go, internal/appsec/remoteconfig.go, internal/appsec/remoteconfig_test.go, internal/appsec/ruleset_builder.go, internal/appsec/ruleset_builder_test.go, internal/appsec/waf.go, internal/remoteconfig/config.go, internal/remoteconfig/remoteconfig.go, internal/remoteconfig/remoteconfig_test.go
This change adds the capability to block any request by providing users with the ability to update the security
rules configs through remote configuration (ASM_DD, ASM and ASM_DATA products).
=> appsec: suspicious request blocking

.github/workflows/system-tests.yml
This adds some more scenarios to the list of system-tests scenarios being run by our CI:
- ASM_BLOCKING
- ASM_REQUEST_BLOCKING
- REMOTE_CONFIG_MOCKED_BACKEND_ASM_DD
- REMOTE_CONFIG_MOCKED_BACKEND_ASM_FEATURES
=> .github/workflows: run ASM and RC system-tests scenarios

internal/appsec/dyngo/instrumentation/httpsec/http.go, internal/appsec/testdata/custom_rules.json, internal/appsec/waf.go, internal/appsec/waf_test.go
This address is now sent to the WAF for further examination.
This address is not used by all the recommended ruleset, but with custom rules we will need to support it.
I added a test about a custom rule using this address.
=> internal/appsec: add server.request.method address

go.mod, internal/appsec/appsec.go, internal/appsec/config.go, internal/appsec/config_test.go, internal/appsec/dyngo/operation.go, internal/appsec/dyngo/operation_test.go, internal/appsec/limiter_test.go, internal/appsec/remoteconfig.go, internal/appsec/remoteconfig_test.go, internal/appsec/ruleset_builder.go, internal/appsec/waf.go, internal/remoteconfig/remoteconfig.go, internal/remoteconfig/remoteconfig_test.go
Atomic swapping of AppSec's instrumentations (currently HTTP WAF and gRPC WAF) by reviewing the way dyngo event listeners should be managed. Instead of allowing registering and unregistering event listeners, we rather simplified it so that we can simply atomically swap the root operation instead. This allows a cleaner approach where a root operation can be created async, along with the new set of event listeners, and later on live-swapped, with no more need to deal with concurrent event listeners swapping. The current implementation simply is an atomic pointer swapping.
Overall, this allows a cleaner "pure programming" approach, where an operation is no longer modified once running (assuming all its event listeners are registered on the start events, which is not enforced today), which …
=> internal/appsec/dyngo: atomic instrumentation swapping

appsec/appsec.go, internal/appsec/dyngo/instrumentation/httpsec/http.go, internal/appsec/testdata/blocking.json, internal/appsec/waf.go, internal/appsec/waf_test.go
#1901 appsec: add blocking SDK body operation
=> appsec: add blocking SDK body operation (#1901) 

.github/workflows/system-tests.yml, internal/appsec/ruleset_builder.go, internal/remoteconfig/remoteconfig.go
This change fixes 2 things:
- remove empty products from the remote config client products slice
- prevent rules data from being overwritten with an empty set when rulesManager compiles the rules
This is a bugfix.
=> remoteconfig: remove empty products and don't override appsec rules data

ddtrace/tracer/spancontext.go, ddtrace/tracer/textmap.go, ddtrace/tracer/textmap_test.go
Fix sampling priority and decision maker values extracted from tracestate (align with the spec)
Bug fix
- Unit tests
- [This test](https://github.com/DataDog/system-tests/blob/21687fc490bf326863fee1b738af3671da72bc97/parametric/test_headers_tracestate_dd.py#L509) in system-test passes (will remove the skip once this PR is merged).
=> ddtrace/tracer: reset decision maker during fallback behavior of w3c header extraction

.github/workflows/unit-integration-tests.yml, .golangci.yml, CODEOWNERS, contrib/gin-gonic/gin/appsec_test.go, contrib/gin-gonic/gin/gintrace_test.go, contrib/go-chi/chi.v5/chi_test.go, contrib/go-chi/chi/chi_test.go, contrib/gofiber/fiber.v2/fiber_test.go, contrib/gorilla/mux/mux_test.go, contrib/graph-gophers/graphql-go/graphql_test.go, contrib/labstack/echo.v4/appsec_test.go, contrib/net/http/example_test.go, contrib/net/http/roundtripper_test.go, contrib/twitchtv/twirp/twirp_test.go, contrib/urfave/negroni/negroni_test.go, contrib/zenazn/goji.v1/web/goji_test.go, ddtrace/tracer/log.go, internal/httpmem/httpmem_test.go
- Remove deprecated lint job
- Make all teams own linter rules
- Add bodyclose linter rule
- Apply bodyclose fixes
- Remove deprecated tooling
- Safer code by adding the bodyclose rule
- All teams own the linter rules to make sure every team approves any future changes in the linter rules
The CI passes
=> ci: update linter job and add bodyclose

ddtrace/tracer/propagating_tags.go, ddtrace/tracer/span.go, ddtrace/tracer/spancontext.go, ddtrace/tracer/textmap.go, ddtrace/tracer/textmap_test.go
This commit adds a few methods to trace to allow safe access to the tags and propagatingTags members of trace to the marshaling code.
Fixes #1944 
Spancontext marshaling was accessing tracer internal structures without a lock, resulting in a data race and panic.
=> ddtrace/tracer: ensure access to trace tags is concurrency-safe

ddtrace/tracer/propagating_tags.go, ddtrace/tracer/span.go, ddtrace/tracer/spancontext.go, ddtrace/tracer/textmap.go, ddtrace/tracer/textmap_test.go
This is a cherry-pick of PR #1948 
This commit adds a few methods to trace to allow safe access to the tags and propagatingTags members of trace to the marshaling code.
Fixes #1944
Spancontext marshaling was accessing tracer internal structures without a lock, resulting in a data race and panic.
=> ddtrace/tracer: ensure access to trace tags is concurrency-safe (#1948)

go.mod, go.sum
Upgrade the go-libddwaf pkg to v1.2.0, which ships WAF v1.9.0.
=> go.mod: upgrade go-libddwaf to v1.2.0

contrib/net/http/trace.go, contrib/net/http/trace_test.go
Do not set span fields when they are not configured so the tracer can `put` the defaults in.
Currently the TraceAndServe function sets service, resource, etc. whether or not they are configured, meaning we can easily end up with spans with service "unnamed-go-service" and blank tags/resource. 
This is becoming relevant for the autoinstrumentation, where the service, etc is not readily available, and we want sane defaults.
=> contrib/net/http: don't set empty string values as span tags

contrib/labstack/echo/echotrace.go
Add a warning and deprecation notice for contrib/labstack/echo v3. The old version is no longer under development it seems and has active security vulnerabilities that were addressed in the newer "v4" version that supports go modules. Customers should migrate off the v3 version to v4, and when we release dd-trace-go v2 we should remove support for v3. 
Customers who are interested in using labstack/echo might not know which version they should prefer when viewing our docs. This warning should help new implementors avoid relying on insecure / outdated software as well as notifying current users that support is deprecated.
no QA needed
=> contrib/labstack/echo: Add warning and deprecation notice

profiler/options.go, profiler/profiler.go, profiler/telemetry.go
Have the profiler check the execution tracing configuration environment
variables at the beginning of each profiling cycle. That way, the environment
variables can be updated at run-time.
Give initial users the flexibility to, for example, increase collection
frequency during periods where they suspect a performance issue is happening,
without requiring us to commit to a public interface for triggering or
reconfiguring trace collection.
TODO. The existing tests pass. Perhaps worth adding an additional test to see
if updating the configuration works.
=> profiler: support reconfiguring execution tracing at runtime

contrib/gomodule/redigo/redigo.go, contrib/gomodule/redigo/redigo_test.go
These changes stop to override the given context given as first argument to `DoContext()` when the last given argument is not a context.
=> contrib/gomodule/redigo: don't ignore the context given as first argument (#1935)

contrib/confluentinc/confluent-kafka-go/kafka/kafka.go, contrib/confluentinc/confluent-kafka-go/kafka/kafka_test.go, contrib/segmentio/kafka.go.v0/kafka.go, contrib/segmentio/kafka.go.v0/kafka_test.go, ddtrace/ext/tags.go
-This PR sets the `peer.service` precursor for confluentinc and segementio kafka integration spans which is the `messaging.kafka.bootstrap.servers` tag.
-Adds according testing and other modifications to meet requirements
=>  contrib: `peer.service` precursors for confluentinc/segmentio integrations 

contrib/google.golang.org/grpc/appsec_test.go
Appsec tests were failing because of unspecified security rules matching order. Because the attacks were complex they could be matched by several rules and it was not possible to know which would match first. This change simplifies the attack patterns to ensure that only one specific rule will match.
=> contrib/grpc: simplify appsec test attack patterns

contrib/go-chi/chi.v5/chi.go, contrib/go-chi/chi.v5/chi_test.go, contrib/go-chi/chi.v5/option.go
This PR introduces the WithResourceNamer option to chi.v5, which allows customizing span resource names.
The implementation is similar to #1950.
Improve span resource names and provide a generic solution for Issue #1198.
New unit tests, similar to those added in PR #1950, have been implemented to verify the new functionality.
- `TestCustomResourceName()` checks if the custom resource name is properly applied
- `TestUnknownResourceName()` ensures the default naming is used in case of unknown resource names.
And, the existing test, `TestWithModifyResourceName()`, guarantees backward compatibility.
=> contrib/go-chi/chi.v5: add WithResourceNamer option

.golangci.yml, internal/appsec/config_test.go, internal/appsec/dyngo/instrumentation/grpcsec/actions.go, internal/appsec/remoteconfig_test.go, internal/appsec/waf.go, internal/appsec/waf_test.go
This PR enables golangci-lint on the files with the `appsec` build tag
By removing the `appsec` build tag for testing purposes. We realized that the linter was skipping the files marked with the `appsec` build tag. This PR fixes this.
=> golangci lint for appsec

contrib/google.golang.org/grpc/grpc.go, contrib/google.golang.org/grpc/grpc_test.go, contrib/google.golang.org/grpc/option.go, internal/namingschema/service_name.go
To protect users who may be accidentally creating their GRPC server before calling `tracer.Start()` this PR falls back to dynamically fetching the service name for every span (as before), but if a service name is found it is cached (for a slight performance benefit).
GRPC is the only contrib here that is important as it previously did NOT cache the service name, unlike many of the other contribs where the caching was already occurring (meaning that those contribs would have had this same issue in the past, but because the behavior is changing here for grpc it can cause breakages for customers who did not know they needed to start the tracer first)
We found several applications that are creating their GRPC server before calling `tracer.Start()`. These applications would suddenly have a new …
=> contrib/google.golang.org/grpc: Fallback to dynamic service names if no global is found

ddtrace/opentelemetry/tracer.go, ddtrace/opentelemetry/tracer_test.go, ddtrace/opentracer/tracer.go, ddtrace/opentracer/tracer_test.go, ddtrace/tracer/telemetry_test.go, ddtrace/tracer/tracer.go, internal/telemetry/message.go, internal/telemetry/telemetry.go
Changes the metrics `otel.spans_created` and `tracer_init_time` to meet the telemetry naming specification.
- `otel.spans_created` changes to `spans_created` with `otel` as a tag instead
- `tracer_init_time` changes to `init_time`, and moves to a new "general" namespace
This is causing internal errors and triggering issues with monitors.
=> tracer: fix telemetry metrics to align with spec

ddtrace/opentelemetry/tracer.go, ddtrace/opentelemetry/tracer_test.go, ddtrace/opentracer/tracer.go, ddtrace/opentracer/tracer_test.go, ddtrace/tracer/telemetry_test.go, ddtrace/tracer/tracer.go, internal/telemetry/message.go, internal/telemetry/telemetry.go
Cherry-pick of https://github.com/DataDog/dd-trace-go/pull/2049
Changes the metrics otel.spans_created and tracer_init_time to meet the telemetry naming specification.
- otel.spans_created changes to spans_created with otel as a tag instead
- tracer_init_time changes to init_time, and moves to a new "general" namespace
=> tracer: fix telemetry metrics to align with spec (#2049)

ddtrace/tracer/span.go, ddtrace/tracer/spancontext.go, ddtrace/tracer/spancontext_test.go
Fixes race condition that can occur when `t.finished` and the `span.finished` state can become out of sync.
This wasn't an issue before because all spans in a trace had to have been finished before flushing would occur. Plus, the `span.finished` state was never actually looked at in `finishedOne` to know whether a span was safe to flush. With partial flushing, we need to know if a span is finished or not before flushing it and currently the only way to do that is to check the `finished` state of each span in a trace.
There was another way we could have solved this, which would be to lock the trace earlier up the call stack, e.g. in `(*span).finish`. However, that is going to increase the hold time on a write lock for no real benefit, further increasing contention. None of the code prior …
=> tracer: fixes race condition with partial flushing

internal/appsec/remoteconfig.go, internal/appsec/remoteconfig_test.go, internal/appsec/rules_manager.go, internal/appsec/waf.go, internal/remoteconfig/remoteconfig.go
This change:
- fixes a bug in RC updates processing where empty updates would override existing configs instead
of being ignore
- makes appsec export the custom blocking response RC capability
- updates the json representation of action entries to account for custom actions
=> internal/appsec: make blocking response configurable

ddtrace/tracer/span.go, ddtrace/tracer/span_test.go, ddtrace/tracer/spancontext.go, ddtrace/tracer/spancontext_test.go
Fixes and adds to the failing `TestPartialFlush` test by ensuring that the trace-level tags are always set on the first span in the chunk, regardless of whether partial flushing is used. 
Also does some refactoring of `finishedOne` to eliminate the need for multiple defer functions.
The refactors were done to make the code less ambiguous, since the defers had side effects that were unclear at first glance.
Unit tests cover this.
=> tracer: ensure trace-level tags are always set correctly

ddtrace/tracer/spancontext_test.go
Start spans in this test instead of creating them manually.
While working on partial flushing this test failed in weird and interesting ways because it calls finish on spans that never actually started. To avoid this, this PR actually calls start span instead of relying on the weird test function that allows creating a span directly.
the test should continue to pass
=> ddtrace/tracer: Fix TestSpanTracePushSeveral

.github/workflows/codeql-analysis.yml, .github/workflows/parametric-tests.yml, .github/workflows/system-tests.yml, .github/workflows/unit-integration-tests.yml
1. Use large runners for the `test-core`, `test-contrib` and `parametric-tests` CI jobs.
2. Enqueue `test-contrib` before `test-core` by relocating it in the YAML file.
3. Add a comment indicating that using large runners for "System Tests" didn't provide a noticeable benefit. We'll have to investigate other approaches for speeding up that pipeline.
As a result median CI time should be reduced from ~13.5 minutes to ~7.5 minutes (rough guess based on a few runs). We'll have to wait for a couple weeks before we can analyze the new P95 latency (I don't feel like writing a script to trigger hundreds of CI jobs now 😅).
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table> 
Using larger runners allows our tests to run faster because we're testing many …
=> Faster CI: Use Larger Runners

.github/workflows/parametric-tests.yml
1. Speed up "Patch dd-trace-go version" step from 30s to 10s by using a replace directive in go.mod instead of using `go get`.
1. Split "Run" step into "Build" and "Run" step and by moving away from the [legacy parametric/run.sh](https://github.com/DataDog/system-tests/blob/0e8f0a8bf815e522c7f033296408a7a5e81736b2/parametric/run.sh#L8) script.
1. Add "Cache venv" step to speedup build step from ~1m to ~10s 
1. Remove "Checkout Go" step that served no apparent purpose.
Together with #2068 this will allow running this pipeline as fast as [3min45s](https://github.com/DataDog/dd-trace-go/actions/runs/5371460197/jobs/9744234220) 🚀.
See `RFC: Faster CI for dd-trace-go 🚀` google doc.
=> Faster CI: Optimize APM Parametric Tests

go.mod
Runs `go mod tidy`
Missed in #2060 after adding a new dependency.
=> all: run go mod tidy

ddtrace/tracer/option.go, ddtrace/tracer/option_test.go, ddtrace/tracer/span_test.go, ddtrace/tracer/spancontext.go, ddtrace/tracer/spancontext_test.go, ddtrace/tracer/tracer.go, ddtrace/tracer/tracer_test.go
Requires `DD_TRACE_PARTIAL_FLUSH_ENABLED` to be "true" in order to enable partial flushing. This changes the behavior where previously if a customer set `DD_TRACE_PARTIAL_FLUSH_MIN_SPANS` it would automatically assume that partial flushing was enabled.
There are pros and cons to this approach. The benefit is that now a customer can just set `DD_TRACE_PARTIAL_FLUSH_ENABLED` and it will automatically use a default number of spans, so a customer doesn't have to decide on a reasonable default in order to use partial flushing. It also makes it very clear when it's enabled and disabled.
The downside is that a customer could be confused if they set `DD_TRACE_PARTIAL_FLUSH_MIN_SPANS` and partial flushing doesn't actually occur. We could get around this in a few ways. One approach would be to log …
=> tracer: use DD_TRACE_PARTIAL_FLUSH_ENABLED

.github/workflows/parametric-tests.yml, .github/workflows/system-tests.yml
1. Reuse [install_runner](https://github.com/DataDog/system-tests/blob/main/.github/actions/install_runner/action.yaml) action from the system tests repo. This reduces code duplication.
1. Use explicit build steps for runner, weblog and agent. This helps debugging performance.
1. Update to checkout v3. This is just house keeping.
Reduce duplication and make it easier to debug performance issues.
=> CI: Simplify System Tests

ddtrace/tracer/spancontext.go, ddtrace/tracer/textmap.go, ddtrace/tracer/textmap_test.go
- Do not set `_dd.p.tid` in the `datadog` propagator if the value isn't valid
- Inspired by https://github.com/DataDog/dd-trace-go/pull/1969
- This doesn't cover malformed `tid` in the `tracecontext` propagator: keep sending the malformed `tid` seems to be the expected behavior in that case, based on the parametric tests
- This doesn't cover sending the optional `_dd.propagation_error` tag
Enable test case `test_datadog_128_bit_propagation_tid_short` in parametric tests https://github.com/DataDog/system-tests/blob/main/tests/parametric/test_128_bit_traceids.py#L76
Unit tests + test case in parametric tests is enabled once this PR is merged
=> tracer: discard invalid _dd.p.tid in the datadog propagator

ddtrace/tracer/textmap_test.go
This PR adds `BenchmarkExtractW3C`, in line with having `BenchmarkExtractDatadog`.
Benchmarks reports increased resource usage compared to Datadog propagator. Similar behaviour is observed in Inject method benchmark
```
BenchmarkExtractDatadog-10       4332901               293.8 ns/op           349 B/op          5 allocs/op
BenchmarkExtractW3C-10            799790              1511 ns/op            1040 B/op         18 allocs/op
BenchmarkInjectDatadog-10        1560982               754.6 ns/op           296 B/op          7 allocs/op
BenchmarkInjectW3C-10              92199             12750 ns/op            4027 B/op        247 allocs/op
```
=> ddtrace/tracer: added W3C tracecontext extract benchmark

ddtrace/tracer/spancontext.go, ddtrace/tracer/spancontext_test.go, ddtrace/tracer/tracer.go, ddtrace/tracer/tracer_test.go, internal/version/version.go
Set the sampling priority of dropped spans by the tracer rate sampler. Previously an unset priority would cause the new partial flushing code to panic as it expected that a sampling decision would have already been made (and therefore that `trace.SamplingPriority` would be non-nil.
Not panic
Unit tests :)
=> ddtrace/tracer: Set Priority on rate dropped spans

ddtrace/opentelemetry/span_test.go
Adds a check to the `TestSpanContextWithStartOptions` OTel test which verifies that the payload contains two spans.
This test started failing while we were implementing partial flushing. We found that partial flushing was being triggered when it shouldn't have been, which led to the payload at the end only containing a single span, instead of 2 spans as would be expected. It took longer than necessary to realize that's why the test was failing though, so this just makes it easier to spot the root cause if this test fails in that way again.
=> ddtrace/opentelemetry: improve TestSpanContextWithStartOptions

contrib/emicklei/go-restful/v3/example_test.go, contrib/emicklei/go-restful/v3/option.go, contrib/emicklei/go-restful/v3/restful.go, contrib/emicklei/go-restful/v3/restful_test.go, go.mod, go.sum
Adds support for the [latest version of `go-restful`](https://github.com/emicklei/go-restful#using-go-modules).
The integration for previous versions can't be used with `v3`.
=> contrib/emicklei/go-restful/v3: add integration for newest version

profiler/options.go
The initial value was very conservative, especially considering that this feature is opt-in for now. We expect this new value to be a better tradeoff between overhead, data volumes and span coverage.
=> profiler: Reduce execution trace period to 15min

ddtrace/tracer/spancontext.go, ddtrace/tracer/spancontext_test.go, internal/telemetry/telemetrytest/telemetrytest.go
Add `trace_partial_flush.count` `trace_partial_flush.spans_closed` and `trace_partial_flush.spans_remaining` telemetry metrics
Be consistent with other tracers, better understand how partial flushing is being used and how it behaves under certain tracing worklaods
Added unit tests should be sufficient
=> tracer: Add telemetry events for partial flushing

contrib/gocql/gocql/gocql.go, contrib/gocql/gocql/gocql_test.go, contrib/gocql/gocql/option.go
Adds `WithCustomTag` option to `gocql`.
Allow users to set custom tags.
=> contrib/gocql: add WithCustomTag option

ddtrace/tracer/log_test.go, internal/version/version.go
Add a `-dev` pre-release suffix in `main`.
1. Ensure our semver ordering is always ascendent over time. For instance with the current change, `v1.54.0-dev` < `v1.54.0-rc.1` < `v1.54.rc2` < ... < `v1.54.0`
2. Allow enabling and executing system tests properly starting from `main` up to the release branch and final release. This is made possible thanks to the previous ordering guarantee where a new system test should now be enabled with the dev pre-release prefix such as `v1.54.0-dev` so that they get executed for all the subsequent version numbers.  
Note that before this change, we were doing the wrong assumption that a system test enabled in `main` for instance for  `v1.53.0` would be executed, since the release candidate was moving the version backward from `v1.53.0` to `v1.53.0-rc.1`.
=> version: add a semver pre-release suffix in the main branch

internal/utils.go, internal/utils_test.go
Improves `LockMap.Iter` performance for empty maps
```
goos: darwin
goarch: arm64
pkg: gopkg.in/DataDog/dd-trace-go.v1/internal
│ original.out │          withAtomic2.out           │
│    sec/op    │   sec/op     vs base               │
Iter/original-10   14.280n ± 1%   1.998n ± 0%  -86.00% (p=0.002 n=6)
│ original.out │        withAtomic2.out        │
│     B/op     │    B/op     vs base           │
Iter/original-10     0.000 ± 0%   0.000 ± 0%  ~ (p=1.000 n=6) ¹
¹ all samples are equal
│ original.out │        withAtomic2.out        │
│  allocs/op   │ allocs/op   vs base           │
Iter/original-10     0.000 ± 0%   0.000 ± 0%  ~ (p=1.000 n=6) ¹
¹ all samples are equal
```
Turns out doing RLock and RUnlock can still be slow especially when this code is in a HOT path. For most users this …
=> internal: Improve the Iter performance of LockMap on empty maps

contrib/internal/httptrace/httptrace.go, contrib/internal/httptrace/httptrace_test.go, internal/namingschema/op_client_server.go
This commit improves the performance of starting a span by reducing work
done, especially allocations.
We were seeing a large increase in memory and CPU usage while starting spans compared to previous versions.
=> contrib/internal/httptrace: improve performance of span starts

.gitlab-ci.yml
Includes fixes and improvements in benchmark analyzer and PR commenter, in particular:
* Fixes timeout in PR commenter due to Github GraphQL API changes;
* Fixes unit of measurement rounding in benchmark analyzer;
* Fixes incorrect display of instructions count.
Ensure that benchmarking pipeline is running smoothly and has latest updates.
=> Update benchmarks CI image

contrib/emicklei/go-restful.v3/restful.go, contrib/emicklei/go-restful.v3/restful_test.go
After #2092, where the integration was moved to the correct folder, I forgot to update the componentName as well.
This is a cherry-pick of #2132 onto the v1.53.x release branch.
=> contrib/emicklei/go-restful.v3: fix componentName (cherry-pick #2132)

contrib/internal/httptrace/httptrace.go, contrib/internal/httptrace/httptrace_test.go
This commit improves the performance of starting a span by reducing work done, especially allocations.
Cherry-pick of #2128
=> contrib/internal/httptrace: improve performance of span starts (cherry-pick #2128)

contrib/internal/httptrace/httptrace.go, contrib/net/http/http.go
This pull request addresses one major and one minor performance issue.
The major issue is in contrib/net/http, where (*ServeMux).ServeHTTP adds an element to it's spanOpts slice every time a request is served. This is both a race, and it grows the slice unbounded resulting in a memory leak, and a huge amount of CPU time spent copying the slice.
=> contrib/{internal/httptrace, net/http}: fix memory leak and request closure

.github/release.yml
Generate the release notes with a better state than GitHub's default where PRs are split by Datadog product according to the PR labels:
- no-changelog: do not include this PR in the changelog
- appsec: appsec-related change
- profiler: profiler-related change
- apm:core and apm:ecosystem: APM-related change
Note that GitHub doesn't allow to further customize the exact template, but only this list of top-level categories for now.
=> github: better initial generated notes with release.yml

ddtrace/opentelemetry/tracer_provider.go, ddtrace/tracer/option_test.go, ddtrace/tracer/textmap.go, ddtrace/tracer/textmap_test.go
Reverts DataDog/dd-trace-go#2072
We do not want to change the default context propagation at this time.
=> Revert "ddtrace/tracer: changed default tracecontext propagation order"

ddtrace/tracer/textmap.go, ddtrace/tracer/textmap_test.go, ddtrace/tracer/util.go
Ensures that `tracestate` and `traceparent` headers will not be injected by DD context propagation, and that a warning won't be emitted if those are present in the propagating tags (they'll just be skipped instead).
This PR also refactors some tests to avoid repetition. If it's just more confusing, I can refactor it back, so feedback is welcome.
Fixes #2112
There is no need to marshal W3C headers during the DD context propagation injection. If those headers are present, and someone wants to propagate them, then they should instead ensure that `tracecontext` is in their list of propagation styles.
=> tracer: don't log a warning if tracestate is present when propagating DD tags

.gitlab-ci.yml, .gitlab/benchmarks.yml
* Artifacts will be uploaded to Gitlab Artifacts for failed jobs too.
* If benchmarks in `go bench` crash, CI job will now fail too.
Improve benchmarking CI pipeline behavior based on requests from @katiehockman.
=> Update benchmarks CI image and artifacts uploading

go.mod, go.sum
This bumps up the version of `github.com/mattn/go-sqlite3` a few point releases. 
The current version listed in the `go.mod` has CVEs associated with it. While we are not vulnerable, it sets off false alarms. This will fix false positive security scans.
=> go.mod: bump version of mattn/go-sqlite3

.gitlab-ci.yml
Adds the [new partial flushing benchmark](https://github.com/DataDog/dd-trace-go/blob/2fffe7b8f634e97843c65939c0ee7fa4f6bb4521/ddtrace/tracer/tracer_test.go#L1894-L1905) to the benchmarking platform.
The feature branch has now been merged into main.
=> .gitlab-ci.yml: add partial flushing benchmark to the benchmarking platform

ddtrace/tracer/option.go, ddtrace/tracer/option_test.go
Allow controlling client-side stats via
- `WithStatsComputation` 
- `DD_TRACE_STATS_COMPUTATION_ENABLED`
- Before this PR, the only way to enable client-side stats is to configure `DD_APM_FEATURES=discovery`. This PR makes it easier and more intuitive to enable client-side stats.
- Client-side stats reduce the load on the agent as it enables dropping P0s in the tracer, this PR is a step toward enabling them by default in the Go tracer.
- [[Internal doc](https://docs.google.com/document/d/1xEJzAW_z4H4slBC4E0rafadX69lHuCHJ43c60eSgWr0/edit) with more context on client-side stats]
=> tracer: ease configuring client-side stats computation

contrib/database/sql/exec_trace_test.go, contrib/database/sql/stmt.go, contrib/database/sql/stmt_test.go
Uses the context passed to the execute/query call for a prepared statment,
rather than the context provided for _preparing_ the statement.
Fixes #2172
The context used to prepare a statement and the context used to execute
a statement need not be the same (see
https://pkg.go.dev/database/sql#DB.PrepareContext)
The execution trace task changes added in #2060 incorrectly used the
statement's context from preparation to derive the execution trace task. This
can lead to a statement unexpectedly failing with a "context canceled" error
when the context used to prepare the statement is canceled, but the context
passed to execute the statement isn't. We should be using the context provided
for executing the statement instead.
=> contrib/database/sql: use correct context for trace tasks in statements

ddtrace/tracer/telemetry.go, ddtrace/tracer/telemetry_test.go
Config telemetry was reporting inaccurate metric `stats_computation_enabled`, it was reporting whether the agent supported client-stats computation (`c.agent.Stats`) instead of whether the tracer was actually doing stats computation (i.e `c.canComputeStats()`). This commit fixes it.
Bug fix
=> ddtrace/tracer: fix inaccurate telemetry 'stats_computation_enabled'

.github/workflows/stale.yml
Introduce a github action to autoclose PRs with no activity for 30 days (A warning message and stale label will be applied after 20 days of inactivity)
We have a number of very old stale PRs that aren't being worked on. To reduce the manual burden on cleaning these out and encourage a smaller number of "open" PRs (read: we should close or merge PRs faster) let's close old stale PRs automatically.
=> .github: Introduce stale PR action to auto close old stale PRs

CODEOWNERS
Transfer ownership of code owned by appsec-go to asm-go to account for team renaming.
=> CODEOWNERS: rename appsec-go to asm-go

ddtrace/tracer/abandonedspans.go, ddtrace/tracer/abandonedspans_test.go
This PR fixes some flaky tests due to misplaced atomic variables' updates in internal counters that were used to avoid using `time.Sleep` in unit tests.
=> ddtrace/tracer: fix race condition in abandonedspans_test.go

ddtrace/tracer/abandonedspans.go, ddtrace/tracer/abandonedspans_test.go
Finally, a last fix to the `abandonedspans_test.go`, as the last race condition was found while checking if logs have been generated.
It was tested over 50K+ iterations over 2 days without reproducing again the error in the flaky test that failed yesterday: 
**Test execution link**: [TestReportAbandonedSpans](https://app.datadoghq.com/ci/test/AgAAAYpMGEY4oNocrgAAAAAAAAAYAAAAAEFZcE1HRVk0QUFCT2lHc2IzLXlGTTB1SgAAACQAAAAAMDE4YTRjMWItYjk3Zi00YTA4LTkyNDItMzQxZDM2ZjRlZGYy)  
**Service**: dd-trace-go  
**Branch**: [main](https://app.datadoghq.com/ci/test-branch/github.com%2FDataDog%2Fdd-trace-go/dd-trace-go/main?env=none)  
**First Flaked**: [283c0ac0ef4488df84a1d5ef9d6e940811fdc433](https://app.datadoghq.com/ci/test-commit/github.com%2FDataDog%2Fdd-trace-go/dd-trace-go/main/283c0ac0ef4488df84a1d5 …
=> ddtrace/tracer: fix race condition with RecordLogger in abandonedspans_test.go

go.mod, go.sum
Upgrades our gostackparse dependency to pick up commit [3d65ba9](https://github.com/DataDog/gostackparse/commit/3d65ba90c73f7636e503fa72101a2133e5260454).
Go 1.21 will change stack traces to include the ID of the parent
goroutine in a goroutine's stack trace, e.g.
```
goroutine 18 [running]:
< ... stack frames ... >
created by main.main in goroutine 1
```
(see go.dev/cl/435337). Unless we upgrade, we'll see
"in goroutine 1" in the root frames in the goroutines wait
profile.
This is picking up a change which is already tested in the upstream library.
=> profiler: upgrade gostackparse to support Go 1.21 tracebacks

contrib/net/http/http.go, contrib/net/http/http_test.go
cherry pick fix across for v1.54.1 
=> contrib/net/http: Copy span options and resource name to avoid data race (#2204)

profiler/profiler.go, profiler/profiler_test.go
When aws lambda runtime is detected, refuse to start profiler.
Profiling is not currently supported in aws lambda. Node and Python are currently in public beta. Because Go is not included in this, customers would get charged for profiles that are potentially inaccurate.
=> Disable profiling when run in AWS Lambda.

.github/workflows/pull-request.yml
Trigger required GitHub Actions checks on merge queue branch pushes (`mq-working-branch-**`).
Use our internal devflow `/merge` command on PRs to reduce waiting times.
=> ci: trigger on merge queue branch pushes

profiler/options.go, profiler/options_test.go, profiler/profiler.go, profiler/profiler_test.go
Remove `WithAPIKey` option 
https://github.com/DataDog/dd-trace-go/issues/866
TLDR: 
Agentless uploading is originally supported if customer set `DD_API_KEY` env variable, or use `WithAPIKey` option. [`WithAgentlessUpload` was introduced for debugging purpose](https://github.com/DataDog/dd-trace-go/pull/906/) when agentless mode is disabled for `WithAPIKey` option.
Due to business reasons we want to deprecate agentless support for public uses, only allow internal usage by explicitly set `DD_PROFILING_AGENTLESS` and `DD_API_KEY` env variable. 
This PR is to remove `WithAPIKey` and `WithAgentlessUpload` option.
More context: [Agentless vs Agent Uploading](https://docs.google.com/document/d/172cmlRA_GTSu2OjC_FL5PzO6EjCpRH5ddU1nP08-yF0/edit)
Unsure? Have a question? …
=> [V2 experimentation]profiler: remove WithAPIKey and WithAgentlessUpload

ddtrace/mocktracer/mockspan.go, ddtrace/mocktracer/mockspan_test.go
Use RLock in the mockspan String method to fix the "data race" error when running tests with -race flag. All other methods do use lock so this seems to be an oversight.
```
Write at 0x00c00039b650 by goroutine 16:
runtime.mapassign_faststr()
/usr/local/go/src/runtime/map_faststr.go:203 +0x0
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/mocktracer.(*mockspan).SetTag()
/home/circleci/project/vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/mocktracer/mockspan.go:130 +0x304
```
```
Previous read at 0x00c00039b650 by goroutine 28:
reflect.maplen()
/usr/local/go/src/runtime/map.go:1394 +0x0
reflect.Value.lenNonSlice()
/usr/local/go/src/reflect/value.go:1630 +0x26d
reflect.Value.Len()
/usr/local/go/src/reflect/value.go:1619 +0x11a
internal/fmtsort.Sort() …
```
=> ddtrace/mocktracer: use lock in String method

ddtrace/tracer/option.go, ddtrace/tracer/option_test.go
Added `WithAgentURL` option 
Proposal: https://github.com/DataDog/dd-trace-go/issues/368
Jira: https://datadoghq.atlassian.net/browse/AIT-8435
Have an option to supply full URL in `StartOption` in addition to the existing `WithAgentAddr`option.
=> [V2 experimentation] ddtrace/tracer: add WithAgentURL option

profiler/go_lt_1_21.go, profiler/options.go, profiler/profiler_test.go
Enable execution traces by default for go1.21+
We've verified that this is safe and has no performance impact on our internal fleet. Let's allow all customers to enjoy this feature without having to figure out how to turn it on.
=> profiler: enable execution traces by default for go1.21+

ddtrace/tracer/option.go
Explain in a code comment why we don't set a global service name if defaulted to binary name.
Address some confusing behavior that could be interpreted as bug (see https://github.com/DataDog/dd-trace-go/pull/2240)
=> tracer/option: document service defaulting

ddtrace/tracer/telemetry_test.go, internal/telemetry/message.go, internal/telemetry/option.go, internal/telemetry/telemetry.go, internal/telemetry/telemetrytest/telemetrytest.go, profiler/telemetry.go, profiler/telemetry_test.go
The PR fixes 2 bugs
- The profiler starts the telemetry client without passing any config so we end up without a valid agent url for telemetry. This is problematic typically when the profiler is used alone or if it starts before the tracer. The first 2 commits address this issue.
- The `app-client-configuration-change` requests contain invalid payloads, i.e used `conf_key_values` instead of `configuration`. This seemed to be [an inconsistency in the api docs that have been fixed](https://github.com/DataDog/instrumentation-telemetry-api-docs/commit/3067196e0175e5fe2aa1f971c02f182b3087c5c1#diff-fc5c86287b453d12d2fbb6b4e56c351add9831b1b54cd1fba88530348c5b173b) after telemetry was implemented in the tracer. Also took the opportunity to align the `remote_config` field with the spec. This is …
=> telemetry: fix profiler not passing config and align data model with spec AIT-7935

.github/workflows/multios-unit-tests.yml
Use windows-2019 runner when testing Go 1.19, since the windows-2022 image
has an incompatible C toolchain which breaks some of our tests.
This is a known issue, fixed in Go 1.20: https://github.com/golang/go/issues/51007
Keep CI green for Go 1.19.
=> ci: use older Windows for Go 1.19 tests

ddtrace/tracer/tracer_test.go
This test starts a set of goroutines which do things to spans after they have finished. Wait for these goroutines to complete before ending the test function. This ensures these goroutines are not running when other tests run. This avoids these tests accidentally capturing the logs from these goroutines, and avoids the race detector triggering on things they are doing.
This fixes a problem when running tests with -shuffle=on, and also fixes a race detector warning:
```
==================
Write at 0x000103d80470 by goroutine 74703:
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.setTestTime()
/Users/evan.jones/dd/dd-trace-go/ddtrace/tracer/abandonedspans_test.go:28 +0xf8
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.TestReportAbandonedSpans.func2() …
```
=> tracer TestUserMonitoring: Wait for goroutines before test completes

.github/workflows/parametric-tests.yml, ddtrace/opentelemetry/otel_test.go, go.mod, go.sum
bump otelhttp to v0.44.0
https://github.com/DataDog/dd-trace-go/pull/2273
=> go.mod: bump otelhttp to v0.44.0

ddtrace/tracer/option_test.go, ddtrace/tracer/sqlcomment_test.go, ddtrace/tracer/telemetry_test.go
This fixes tests with run with -shuffle=on. I am not sure if I caught all of them, since I just verified this experimentally by running the following command, rather than by trying to check all uses.
for i in $(seq 10); do
go test -shuffle=on -failfast -count=2 ./ddtrace/tracer || break
done
I was running the tests with this flag with the race detector to check for any other races on my fix I'm about to send separately.
=> tracer: call SetServiceName("") from tests to reset globals

contrib/gofiber/fiber.v2/fiber.go, go.mod, go.sum
1. Upgrades `gofiber/fiber` to [v2.50.0](https://github.com/gofiber/fiber/releases/tag/v2.50.0)
2. Fix the compilation issues after `gofiber/fiber` is upgraded 
Unfortunately, I couldn't find a good way to unit test this. Mostly, I want to make sure that `h.Add(k, v)` in line 57 is used, since it allows for appending multiple headers with the same value, instead of `h.Set(k, v)`, which would overwrite the values incorrectly. This shouldn't be all that essential though, since these headers are only used to extract the span context of the parent, which doesn't rely on headers that need multiple values (e.g. uses trace-id headers).
The only way I could see to test this would be to break out the creation of the `http.Header{}` type into a helper method, and doing a small unit test on the …
=> conbrib/gofiber/fiber: upgrade to v2.50.0 and fix breaking change

ddtrace/opentelemetry/span.go, ddtrace/opentelemetry/span_test.go
Passes a finish option to end a span as an error span if an error was provided.
Note that this won't have *all* of the information, since we don't support span events right now, so `RecordError` is a no-op. So all we have is the description, instead of the original error from the application.
Fixes #2272
=> opentelemetry: finish a span with an error if one is provided

internal/log/log.go, internal/log/log_test.go
Parses `DD_LOGGING_RATE` as `int64` instead of `uint64` to make sure, although it should contain a big value to happen, it doesn't yield unexpected results when converted to `time.Duration`.
Respects the current behaviour by taking into account that a zero value means to log immediately.
=> internal/log: fix potential integer conversion issue from parsed value

internal/appsec/rules.go, internal/appsec/rules.json
Update the recommended ruleset to its latest version 
=> appsec: update event rules 1.7.1 -> 1.8.0

ddtrace/tracer/dynamic_config.go, ddtrace/tracer/option.go, ddtrace/tracer/remote_config.go, ddtrace/tracer/remote_config_test.go, ddtrace/tracer/rules_sampler.go, ddtrace/tracer/sampler_test.go, ddtrace/tracer/tracer.go
AIT-8577
The PR introduces internal mechanisms to support dynamic configuration in the tracer. The targeted configs are trace sampling rate and header tags but the design is meant to be extended to support other configs in the near future.
The PR also implements a Remote Config callback function. Although the Remote Config work is incomplete will be done in subsequent PRs to keep the size of the current PR reasonable + it would require reviews from ASM and profiling.
New feature.
=> tracer: introduce dynamic configuration

internal/appsec/appsec.go, internal/appsec/remoteconfig.go, internal/appsec/remoteconfig_test.go, internal/remoteconfig/config.go, internal/remoteconfig/remoteconfig.go, internal/remoteconfig/remoteconfig_test.go
AIT-8578
Make the remote config client a singleton. Tracing and profiling will then be able to use it in addition to ASM.
It's a requirement to have a single shared instance of the remote config client per tracer.
=> remoteconfig: make rc client a singleton

go.mod, go.sum
Update the version of datadog-agent/pkg/remoteconfig/state to something stable that does not have `-devel.0.20230725154044-2549ba9058df` in its name.
This version is causing errors in our internal tooling, and prevents us from using anything above `1.52.0` in some of our internal repos.
=> [deps] update datadog-agent version to stable

.gitignore, test.sh
Adds support for Apple Silicon by setting the appropriate environment variable to force Docker images' platform to be x86 64 (`amd64`).
Easily run integration tests locally.
=> test.sh: add support for running on Apple Silicon

ddtrace/tracer/payload.go, ddtrace/tracer/tracer_test.go
Pre-size the payload buffer before encoding payloads.
Performance improvements.
```
goos: darwin
goarch: arm64
pkg: gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
BigTraces/Big_traces-10   115.1m ± 1%   114.0m ± 1%  -0.99% (p=0.019 n=10)
│     old.txt      │              new.txt               │
│ avgHeapInUse(Mb) │ avgHeapInUse(Mb)  vs base          │
BigTraces/Big_traces-10         78.71 ± 4%        77.80 ± 10%  ~ (p=0.436 n=10)
│   old.txt    │               new.txt                │
│     B/op     │     B/op      vs base                │
BigTraces/Big_traces-10   326.6Mi ± 0%   286.8Mi ± 0%  -12.18% (p=0.000 n=10)
│   old.txt   │              new.txt               │
│  allocs/op  │ …
```
=> tracer: pre-size payload buffer to optimize memory allocations

profiler/options.go, profiler/options_test.go, profiler/profiler.go, profiler/profiler_test.go
Users can set the version tag for profiles in three ways: via
`WithVersion`, the `DD_VERSION` environment variable, or via `WithTags`. A
service should only have one version tag at a time for profile
comparison with a "recent" version to work properly in the UI. Today,
all of these options can be used at once and the profiles for a service
can have multiple version tags.
To be consistent with the tracer, we should supply a single version and
it should be configured with the following priority order: first,
`WithVersion` is used. If that option is not set, then `DD_VERSION` will be
used. If either of those are used, then they get priority over any
version tags supplied via `WithTags`. That is, version tags are removed if
the version is explicity set.
Unsure? Have a …
=> profiler: use only one service version value

ddtrace/ddtrace.go, ddtrace/internal/globaltracer.go, ddtrace/internal/globaltracer_test.go, ddtrace/internal/tracerstats/stats.go, ddtrace/mocktracer/mocktracer.go, ddtrace/tracer/metrics.go, ddtrace/tracer/span.go, ddtrace/tracer/spancontext.go, ddtrace/tracer/spancontext_test.go, ddtrace/tracer/tracer.go, ddtrace/tracer/tracer_test.go, ddtrace/tracer/transport.go
This commit modifies the trace, span, and spancontext types to be independent of the `ddtrace/tracer.tracer` type. Previously this code would cast to the `*tracer` type and interact with its internals. Now, they communicate with a `ddtrace.Tracer` type through an established interface.
=> ddtrace/tracer: Separate trace/span types from the tracer struct

ddtrace/opentelemetry/span.go, ddtrace/opentelemetry/span_test.go, ddtrace/opentelemetry/tracer.go, go.sum
This PR adds support special span attributes, to match OTLP behavior. 
Specifically, name, service, resource, type and analytics.event.
For example:
- if `service.name` attribute is set on the span, it will be remapped to Datadog's `service` tag.
- if `analytics.event` attribute is set on the span, it will be remapped to Datadog's `_dd1.sr.eausr` tag.
Matching OTLP support behaviour.
=> ddtrace/opentelemetry: added support for special attributes mapping

ddtrace/opentelemetry/span_test.go, ddtrace/opentelemetry/tracer.go
Previously, we were setting `span.type` based on the `span.kind` attribute. Now, `span.kind` will map to `span.kind`.
=> ddtrace/opentelemetry: Fixed setting a wrong span field (span.kind)

ddtrace/opentelemetry/tracer_test.go, ddtrace/tracer/context_test.go, ddtrace/tracer/span_test.go, ddtrace/tracer/spancontext.go, ddtrace/tracer/textmap_test.go, ddtrace/tracer/tracer_test.go
Changes `DD_TRACE_128_BIT_TRACEID_GENERATION_ENABLED` default to `true`
_Note that `DD_TRACE_128_BIT_TRACEID_LOGGING_ENABLED` default does not change, and it remains `false`._
Better support W3C standards for TraceID
AIT-8848
=> tracer: enable 128-bit TraceID generation by default

ddtrace/tracer/textmap.go, ddtrace/tracer/textmap_test.go
Always forwards the `tracestate` from other vendors, regardless of whether the w3c trace context is during extraction.
Extraction will now iterate through the propagators in precedence order and for each propagator apply the following logic:
1. Attempt to extract a trace context from the incoming request headers. If there is no valid trace context, continue to the next propagator.
2. If this is the first propagator to extract a valid trace context, use this for the local trace context. Additionally, if the configuration is set to `DD_TRACE_PROPAGATION_EXTRACT_FIRST=true`, immediately return the local trace context as the result of the trace context extraction.
3. If this is not the first propagator to extract a valid span context (i.e. a local trace context has already been created), AND …
=> tracer: always propagate the tracestate header

.golangci.yml
ci: disable gci
See PROF-8609 for more info.
=> ci: disable gci

.github/workflows/system-tests.yml, .github/workflows/v2-nightly.yml
Fixes the CI workflows to work both in `main` and `v2-dev`.
This is part of the work to execute all workflows on `v2-dev` branch.
=> Minor fixes in CI workflows for v2 nightly

.github/workflows/multios-unit-tests.yml, .github/workflows/parametric-tests.yml, .github/workflows/system-tests.yml, .github/workflows/unit-integration-tests.yml, .github/workflows/v2-nightly.yml
Builds upon #2348 & #2359 to ensure nightly CI is run on `v2-dev`. Fixes for smoke and system tests on v2 will be done in a separate PR.
We need to catch any possible issue early, as we aim to dogfood dd-trace-go/v2 in around a month.
=> .github/workflows: improve nightly v2 CI workflows

ddtrace/tracer/dynamic_config.go, ddtrace/tracer/option.go, ddtrace/tracer/remote_config.go, ddtrace/tracer/remote_config_test.go, ddtrace/tracer/rules_sampler.go, ddtrace/tracer/sampler_test.go, ddtrace/tracer/telemetry.go, ddtrace/tracer/telemetry_test.go, ddtrace/tracer/tracer.go, internal/telemetry/client.go, internal/telemetry/telemetry.go, internal/telemetry/telemetrytest/telemetrytest.go, internal/telemetry/utils.go
AIT-8580
Report configuration changes applied via dynamic configuration. This required some refactoring of the current dynamicConfig implementation with an intent to keep it as generic as possible.
More logic was added to avoid unnecessary reconfigurations and unnecessary (or inaccurate) config change telemetry events in case of an attempt to reconfigure the same value.
This what an example payload looks like
```
{"api_version":"v2","request_type":"app-client-configuration-change","tracer_time":1699955789,"runtime_id":"9d6b96e5-6d6f-4d33-92e8-756b31d69776","seq_id":3,"debug":false,"payload":{"configuration":[{"name":"trace_sample_rate","value":0.7,"origin":"remote_config","error":{"code":0,"message":""},"is_overridden":false}]},"application":{"service_name":"my.go.service","env":"staging", …
```
=> tracer: report config-change telemetry in dynamic config

internal/env.go, internal/remoteconfig/config.go, internal/remoteconfig/config_test.go, internal/telemetry/client.go, internal/telemetry/client_test.go
Support float values for `DD_TELEMETRY_HEARTBEAT_INTERVAL` and `DD_REMOTE_CONFIG_POLL_INTERVAL_SECONDS`
These options are set to 0.2 in parametric tests to speed up the execution time.
https://github.com/DataDog/system-tests/blob/7cbb0153babff6b80cde7a6425ab41adcdffe014/tests/parametric/test_dynamic_configuration.py#L31-L32
=> {telemetry,remoteconfig}: support fraction of second intervals

.github/workflows/unit-integration-tests.yml, ddtrace/opentelemetry/telemetry_test.go, ddtrace/tracer/textmap.go, ddtrace/tracer/textmap_test.go
This PR switch default context propagation order from `tracecontext,datadog` to datadog,tracecontext
System test change: https://github.com/DataDog/system-tests/pull/1853
=> ddtrace/tracer: Switch default context propagation order

ddtrace/tracer/remote_config.go, ddtrace/tracer/remote_config_test.go
Skip configs if the service or env in the config do not match the tracer's.
Pass the test case `test_not_match_service_target` in parametric https://github.com/DataDog/system-tests/blob/7cbb0153babff6b80cde7a6425ab41adcdffe014/tests/parametric/test_dynamic_configuration.py#L156
=> tracer: check for (service,env) matching in dynamic config

ddtrace/opentelemetry/tracer.go, ddtrace/opentelemetry/tracer_provider.go, ddtrace/opentracer/tracer.go, internal/apps/unit-of-work/go.mod, internal/apps/unit-of-work/go.sum
This PR fixes the format of telemetry tags in opentracing and opentelemetry packages. Previously, the string with `integration_type` had redundant quotes, which were causing the telemetry processing to not recognise the integration type and mark it as `N/A`.
Missing metrics on the usage of opentelemetry package
=> ddtrace/opentelemetry,opentracing: fixed the format of telemetry tags 

.github/workflows/appsec.yml, .github/workflows/govulncheck.yml, .github/workflows/multios-unit-tests.yml, .github/workflows/parametric-tests.yml, .github/workflows/system-tests.yml, .github/workflows/unit-integration-tests.yml
Completes the implementation of nightly CI runs for v2. Builds upon #2348 #2359 #2360. 
We want to catch any regression during v2 development. Running this nightly will allow to detect them easily.
=> .github/workflows: integrate v2 CI nightly to run from main

ddtrace/tracer/remote_config.go, ddtrace/tracer/remote_config_test.go, internal/remoteconfig/remoteconfig.go
AIT-8976
Report the RC capabilities related to the APM_TRACING product used for dynamic configuration.
Declare what features can be supported by the tracer. This is important to exclude unsupported features like automatic logs injection.
=> tracer: report rc capabilities for dynamic config

internal/appsec/dyngo/instrumentation/httpsec/http.go, internal/appsec/testdata/user_rules.json, internal/appsec/waf.go, internal/appsec/waf_test.go
Adds a field to `HandlerOperationRes` in `appsec/internal/dyngo/instrumentation/httpsec/http.go` for response headers and send them to the WAF in `appsec/internal/waf.go`
API Security is around the corner and we need to build support schemas for user responses. As such, two new addresses were created:
- `server.response.headers.no_cookies`
- `server.response.body`
This PR does half the job since the second address will be tricker to implement.
=> appsec: support server.response.headers.no_cookies WAF address

ddtrace/tracer/dynamic_config.go, ddtrace/tracer/log.go, ddtrace/tracer/option.go, ddtrace/tracer/option_test.go, ddtrace/tracer/remote_config.go, ddtrace/tracer/remote_config_test.go, ddtrace/tracer/telemetry.go, ddtrace/tracer/tracer.go, internal/telemetry/utils.go
AIT-8977
- Make global tags dynamic: support custom global tags via remote config
- Report RC capabilities for custom tags 
- Report telemetry events on custom tag updates
Better onboarding UX
=> tracer: configure global tags via remote-config

ddtrace/tracer/remote_config.go, ddtrace/tracer/remote_config_test.go, internal/remoteconfig/remoteconfig.go, internal/remoteconfig/remoteconfig_test.go
Add a remote-config Subscribe function to register a product and its callback in a single call. This guarantees that the callback only receives updates for the corresponding product.
Make the API more ergonomic and easier to use.
=> remoteconfig: add Subscribe function

contrib/google.golang.org/grpc/option.go, contrib/google.golang.org/grpc/server.go
Remove unused config field `ignoredMethods`. Leftover from https://github.com/DataDog/dd-trace-go/pull/2385
=> contrib/grpc: cleanup ignoredMethods config

ddtrace/ddtrace.go, ddtrace/example_test.go, ddtrace/internal/globaltracer.go, ddtrace/mocktracer/mockspan.go, ddtrace/tracer/option.go, ddtrace/tracer/span.go, ddtrace/tracer/span_test.go, internal/appsec/_testlib/mockspan.go
AIT-8746
Add support for `span.StartChild`
fixes https://github.com/DataDog/dd-trace-go/issues/427
=> tracer: add support for span.StartChild

contrib/database/sql/sql_test.go, contrib/gopkg.in/jinzhu/gorm.v1/gorm_test.go, contrib/gorm.io/gorm.v1/gorm_test.go, contrib/jinzhu/gorm/gorm_test.go, contrib/jmoiron/sqlx/sql_test.go, ddtrace/tracer/metrics_test.go, ddtrace/tracer/writer.go
Closes #2411 
Closes #2412 
Closes #2413
- 2411 I just increase the timeout here since I don't see a great way to make this not flaky at all (and 1 second seems a bit fast for the sometime slow CI, running locally I was totally unable to get this to flake at all)
- 2412 revealed a more widespread issue where we tried to use `defer` in TestMain. This fails because the normal pattern for TestMain is to provide success/fail by calling `os.Exit` with the result of running the tests (otherwise the exit code is ALWAYS `0`). Calling os.Exit exits IMMEDIATELY meaning none of the deferred code is run. I did a search for this pattern and found a few places doing it so I altered them to not use defer.
- 2413 I just moved the timing call to BEFORE marking the go routine as done, this closes a race …
=> tracer: Reduce flakiness of tests

.github/workflows/test-apps.cue, .github/workflows/test-apps.yml
Makes the ref input optional so we (should) default to the triggering ref.
This is a small follow-up fix for https://github.com/DataDog/dd-trace-go/pull/2420
Fix scheduled workflow: https://github.com/DataDog/dd-trace-go/actions/runs/7167025415
=> internal/apps: make ref in workflow optional

.github/workflows/test-apps.cue, .github/workflows/test-apps.yml
Fix the argument types.
This is a small follow-up fix for https://github.com/DataDog/dd-trace-go/pull/2420
Note: This wasn't caught by my previous testing because GitHub Actions seems to ignore argument types for the default values of inputs as well as when manually triggering workflows. But if you call a workflow from another workflow, apparently it gets validated. Sigh.
Fix the scheduled workflow: https://github.com/DataDog/dd-trace-go/actions/runs/7167137526
=> internal/apps: fix argument types

.github/workflows/test-apps-schedule.yml, .github/workflows/test-apps.cue, .github/workflows/test-apps.yml
* Automatically add a `trigger:weekly` or `trigger:nightly` tag to scheduled test-app runs
* Allow specifying custom `DD_TAGS` when manually triggering test-app runs
* Switch from using individual bool inputs for selecting the scenarios to supplying them via JSON (because I ran into a GH Actions limitation, see commit message 😠)
* Clean up some unrelated stuff (pr_default option)
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table> 
Make it easier to find the data for nightly, weekly and manually triggered test-app runs in the trace explorer and profile search.
=> internal/apps: better tagging

README.md
Adds a useful example for how to run a single container from our docker-compose
This came in handy recently when I wanted to run just a single `mysql` unit test and didn't want to download / deal with the overhead of running every single container listed in our docker-compose
=> readme: Add example for running just one integration container

profiler/profiler_test.go, profiler/upload_test.go
Create a common helper for setting up a profiler hooked up to a mock backend
for testing.
This PR doesn't touch every single test, since some such as TestTryUpload and
TestProfilerPassthrough rely on manipulating profiler-internal stuff and would
be better handled in separate commits.
Many tests do the same thing: create an HTTP server running our mock backend
with a channel for receving profile uploads, start a profiler pointing to the
mock backend plus whatever other options we're testing, and then receive some
profile uploads, make assertions about them, and clean up at the end.
In general, I think this is a good pattern for testing the profiler. We should
ideally only test it using the public API, and only make assertions about the
observable output (i.e. what we send to our backend). …
=> profiler: deduplicate test profiler setup logic

profiler/profile.go, profiler/profiler.go, profiler/profiler_test.go
Randomize execution trace collection. Each profiling cycle we record an
execution trace with probability (profiling period) / (trace period). This
way we still maintain the same desired avarage data rate of one trace every 15
minutes by default.
Inline the shouldTrace function into the one place it should actually be
used. Prior to this commit, shouldTrace was called from two places: once
to decide whether to trace, and once as a double-check right before
starting the trace. The double-check is not particularly helpful, and if
we're making a decision randomly, then checking twice means we'd have to
win the "coin toss" twice to record data. So we inline the logic into a
single place, right before scheduling a trace.
This is tested by doing many "trials" of recording profiles with
different …
=> profiler: randomize when execution traces are collected

.github/workflows/smoke-tests.yml, internal/apps/setup-smoke-test/Dockerfile, internal/apps/setup-smoke-test/main.go
This makes sure that the "standard and most common" way of compiling and deploying Go apps is working when using dd-trace-go.
Add a new test app called `setup-smoke-test` which sets up dd-trace-go and all its products on a basic net/http server.
The Dockerfile is a parameterized multi-stage Dockerfile with docker args and multiple targets allowing us to cover the main setup of our users we do not want to ever break:
- `golang` docker image being used, with a matrix of:
- go version
- distribution: alpine or debian.
- with or without `go mod vendor`
- with or without CGO
- alpine with gcc and the C librray headers
- deployment docker image with a matrix of:
- bare alpine (musl-based distrib)
- bare docker (glibc-based distrib)
- alpine with libc6-compat
- amazonlinux
- docker's scratch …
=> ci: setup smoke tests

.github/workflows/smoke-tests.yml, go.mod, go.sum, internal/apps/go.mod, internal/apps/go.sum, internal/apps/setup-smoke-test/Dockerfile, internal/apps/setup-smoke-test/main.go
Reintroduce the `appsec` build tag when CGO is not enabled (`CGO_ENABLED=0`).
AppSec is indeed depending on `libdl.so.2` which is not available on commonly found golang deployment envs such as `alpine`, `scratch`, etc.
The only case impacted by this change is when deploying to `busybox` with `CGO_ENABLED=1`, where `libdl.so.2` isn't available. Such users can either:
1. Add the `datadog.no_waf` go build tag
2. Or disable CGO by recompiling with `CGO_ENABLED=0`
Avoid deployments breaking changes due to libdl's dependency from appsec when `CGO_ENABLED=1`.
=> appsec: reintroduce the appsec build tag when cgo is disabled

go.mod, go.sum, internal/apps/go.mod, internal/apps/go.sum
Upgrades go-libddwaf to 2.2.3 (released)
The previous pin refers to a commit that is no longer reachable.
=> appsec: use released version of go-libddwaf

contrib/database/sql/exec_trace_test.go, go.mod, go.sum
Upgrades `gotraceui` to [v0.3.0](https://github.com/dominikh/gotraceui/releases/tag/v0.3.0), that supports Go 1.21 traces.
Review and act on TODO comments as part of the cleanup for v2 release. 
=> AIT-9184: update gotraceui to v0.3.0.

contrib/database/sql/exec_trace_test.go, go.mod, go.sum
Reverts DataDog/dd-trace-go#2443 It was merged accidentally.
=> Revert "AIT-9184: update gotraceui to v0.3.0."

internal/container_linux.go, internal/container_linux_test.go, internal/container_stub.go
This PR adds build flags in the logic that retrieves the container id since it only works on linux.
It also only retrieves the cgroup node inode if the sender not in the host cgroup namespace. Indeed it would mean either that:
- We're not in a container and the inode we're sending is not related to a container
- We already have access to the container-id and it will be retrieved in the previous logic
Fix build and do not emit data if not necessary (limit perf impact)
=> [CONTINT-3554] Fix build on linux and do not send cgroup node inode if in host cgroup namespace

.github/workflows/needs-triage.yml
Adds a new GitHub workflow which automatically adds a `needs-triage` label to issues that are opened or re-opened, which is to be removed whenever triage is performed.
Every weekday (at 8am UTC, per the current configuration), the workflow lists up to 10 issues that have the `needs-triage` label and are more than 3 days old, and sends messages to Slack via a configrued WebHook to pester maintainers to triage them. The Slack message includes a link to the issue as well as the issue's ID, title, body, and creation timestamp.
Per the last guild meeting, we agreed it would be helpful to have some automation help us make sure new issues are looked at at least in a cursory manner, so we (for example) catch sensitive content (which should not be in GitHub issues) earlier rather than later.
For …
=> maitenance: new GitHub Triage Badger

.github/workflows/parametric-tests.yml
Currently Parametric only executes tests using latest tracer release. We add support to run snapshot version of the golang tracer (dev).
The idea behind this is to use the same approach to install dd-trace-go as is used by system-tests (maintainability reasons).
We are using the previously existing script to install the tracer: utils/build/docker/golang/install_ddtrace.sh.
This PR is a intermediate steps to avoid conflicts on the tracer pipelines during the "migration process".
I will create a new PR to clean the obsolete code after merge the system-tests PR: https://github.com/DataDog/system-tests/pull/1948
(Sorry for the msg of the first commit...copy-paste...)
=> Configure parametric test to get the golang tracer in same way as system-tests

ddtrace/tracer/remote_config.go, ddtrace/tracer/remote_config_test.go
AIT-9257
Handle RC deletion in dynamic configuration by reapplying the original configuration values.
The remote-config client signals a config deletion by sending a nil content as documented [here](https://github.com/DataDog/dd-trace-go/blob/5467e21a7b6ce6e8ddd02ed5efbe73216ae63dcd/internal/remoteconfig/remoteconfig.go#L425-L426)
```golang
// Set the payload data to nil for missing config files. The callbacks then can handle the nil config case to detect
// that this config will not be updated anymore.
```
Bug fix.
In addition to the unit test, this fix has been validated e2e manually and a parametric test case will be added in the future.
=> tracer: handle rc deletion in dynamic config

.github/workflows/needs-triage.yml
Remove the issue body from the triager bot Slack payload.
The full issue body can be quite long. The title and a link to the issue are
sufficient.
=> ci: don't send issue body in triager

v2/contrib/net/http/trace.go, v2/contrib/net/http/trace_test.go
Set set `span.kind` and `component` tags in `httptrace.TraceAndServe`
AIT-8749
=> contrib: set set span.kind and component in httptrace.TraceAndServe

CODEOWNERS
=> CODEOWNERS: Update for new gh team structure

.github/workflows/parametric-tests.yml
Clean System-tests/Parametric pipeline.
=> Clean parametric tests pipeline

.github/pull_request_template.md, CODEOWNERS
* Remove @DataDog/dd-trace-go-guild as the CODEOWNER for `go.mod` and `go.sum`.
Most PRs that touch go.mod or go.sum are only relevant for the team working on it. For example: https://github.com/DataDog/dd-trace-go/pull/2410
This change will avoid the @DataDog/dd-trace-go-guild team to be added to such PRs by default and allow anybody with review permissions on dd-trace-go to approve the PR.
=> CODEOWNERS: Reduce go.mod/go.sum related pings

ddtrace/tracer/sampler_test.go, ddtrace/tracer/span.go, ddtrace/tracer/spancontext.go, ddtrace/tracer/tracer.go
Previously, the sampling decision of the span could be updated if new tags were set or a resource name updated. Now, this is onlyu possible up to a moment where a context is injected / propagated to preserve the connections between spans and avoid broken traces with different sampling priorities. 
=> ddtrace/tracer: locking sampling decision after context propagation

internal/remoteconfig/remoteconfig.go, internal/remoteconfig/remoteconfig_test.go
[BACKPORT] main -> release-v1.59.x
JIRA: APPSEC-18227
A deadlock occurred when trying to modify the remote configuration client using its public API while a configuration update was happening. This was due to the global lock performed in the update goroutine. This change introduces several new RWLocks for various data structures in order to avoid the global lock, and allow updating data in the client while the client is updating its configurations.
=> remote configuration: fix deadlock when using client API during a configuration update (#2458)

ddtrace/mocktracer/mocktracer.go, internal/contrib/sqltest/sqltest.go
Tries to fix flaky test [TestAnalyticsSettings/defaults](https://github.com/DataDog/dd-trace-go/actions/runs/7441549595/job/20243802029) in v2-dev.
The issue is that sometimes an extra span appears. It usually belongs to a previous test, as if the span was finished after the test where it was generated itself.
Another flaky test biting the dust. Also, making sure that any extraneous span finished after the lifetime of its corresponding mock tracer won't interfere with the active test.
=> ddtrace/mocktracer: reset mock tracer on stop & don't add finished spans if not present

.github/workflows/needs-triage.yml
Stops adding the `needs-triage` label on issues created by members of the @DataDog/dd-trace-go-guild team.
We don't need someone from the guild reviewing issues by members of the guild.
=> Don't ask for triage of issues from @DataDog/dd-trace-go-guild

.github/workflows/needs-triage.yml
An appropriately authorized PAT is required to read group members of DataDog teams.
=> Use PAT to read team member list

ddtrace/tracer/log_test.go
Updates `TestStartupLog/errors` to handle the way that sampling rules work in #2448, as in v2 it causes to return an error when creating the tracer. The error is logged as before, but we don't need to run the tracer to create it.
Keeping v2 green.
=> ddtracer/tracer: update TestStartupLog/errors & TestLogSamplingRules to new sampling rules implementation in v2

ddtrace/opentelemetry/span_test.go, internal/telemetry/message.go, internal/telemetry/telemetry.go, internal/telemetry/telemetry_test.go
Export the `Products` field of the `ProductsPayload` struct, since this is required for the JSON marshaling to work properly.
Fixes #2499
=> internal/telemetry: export Products field

internal/telemetry/client.go, internal/telemetry/client_test.go
Do not send container and entity ID headers if empty. It's already the case for profiling, dsm and tracing transport but the telemetry client was an anomaly.
Ideally, we should have a shared transport code that takes care of this.
Fixes https://github.com/DataDog/system-tests/pull/2021
=> internal/telemetry: do not send empty container and entity headers

go.mod, go.sum, internal/apps/go.mod, internal/apps/setup-smoke-test/Dockerfile
`go get github.com/ebitengine/purego@v0.5.2`
get ebitengine/purego#189 fix from upstream
Fixes #2504 
=> go.mod: upgrade purego v0.5.0 => upgrade purego v0.5.2

.github/workflows/ecosystems-label-issue copy.yml, .github/workflows/ecosystems-label-pr.yml
Separates the workflows for PRs and issues to add the `apm:ecosystem` label. We now have two workflows to add the label:
1. Looks for PRs with files in any `contrib/*` directory
2. Looks for issues with `contrib` in the title
It's broken today, and adding the labels on _every_ issue, which we don't want. For example: https://github.com/DataDog/dd-trace-go/issues/2516.
This broke when https://github.com/DataDog/dd-trace-go/pull/2496/files# was merged, because it stopped filtering the issues based on the title, and started relying on path instead (which in hindsight, won't work). Separating the workflows allows the job to use the `if: contains(github.event.issue.title, 'contrib')` constraint for issues, and allows a check on the files with `contrib/**` in the path for pull requests.
For …
=> .github/workflows: fixes apm:ecosystem label for issues and PRs

contrib/internal/httptrace/config_test.go, ddtrace/tracer/context_test.go, ddtrace/tracer/log_test.go, ddtrace/tracer/option_test.go, ddtrace/tracer/sampler_test.go, ddtrace/tracer/span_test.go, ddtrace/tracer/textmap_test.go, ddtrace/tracer/tracer_test.go, ddtrace/tracer/transport_test.go
Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
Reference: https://pkg.go.dev/testing#T.Setenv
```go
func TestFoo(t *testing.T) {
// before
os.Setenv(key, "new value")
defer os.Unsetenv(key)
// after
t.Setenv(key, "new value")
}
```
=> test: use `t.Setenv` to set env vars in tests

contrib/confluentinc/confluent-kafka-go/kafka.v2/kafka.go, contrib/confluentinc/confluent-kafka-go/kafka.v2/kafka_test.go, contrib/confluentinc/confluent-kafka-go/kafka/kafka.go, contrib/confluentinc/confluent-kafka-go/kafka/kafka_test.go, ddtrace/mocktracer/data_streams.go, ddtrace/mocktracer/mocktracer.go, ddtrace/tracer/data_streams.go, internal/datastreams/processor.go
Track high watermark offsets along with produce and commit offsets.
This information can be used to determine Kafka lag of consumers.
So we can now get the Kafka lag by only instrumenting the consumer service, with no instrumentation on the producer side.
This also makes the Kafka lag more reliable, since we don't rely on stitching commit & produce offsets later on, but are doing it directly in the application.
The main motivation is improving the accuracy and reliability of the `data_streams.kafka.lag_seconds` metric.
Right now, the metric has edge cases in which it doesn't work great. For example when multiple Kafka topics have the same name.
=> [data streams] Track high watermark offsets

profiler/profiler_test.go
Skips `TestExecutionTraceRandom`, which is flaky, following our flaky test policy.
This test is failing more often than we'd like. Skip it for now until we can
pick more reasonable bounds (or, a better way to test this in general)
Updates #2529
=> profiler: skip flaky TestExecutionTraceRandom

ddtrace/opentelemetry/span.go, ddtrace/opentelemetry/tracer_test.go, ddtrace/tracer/textmap.go, ddtrace/tracer/tracer_test.go
Fixes #2518.
Making sure OTel spans can be used concurrently, as our `tracer.Span`.
=> ddtrace/opentelemetry: add RWMutex to handle concurrent calls to setters

ddtrace/opentelemetry/otel_test.go, ddtrace/opentelemetry/span_test.go, ddtrace/opentelemetry/tracer_test.go, ddtrace/tracer/tracer.go, ddtrace/tracer/writer.go
- Makes the mockTracerProvider return an empty JSON object on `GET` of URLs that aren't relevant to the test
- ~~Uses an atomic pointer to hold the payload in the trace writer to remove a data race~~ (this has been removed)
- The tests now marshal the trace payloads into a map that can be more easily accessed and more accurately tested, instead of checking exact string matches on the marshaled payloads.
- Removes timed contexts from all tests, and instead changes the function that waits for trace payloads to have a 10 second timer. This simplifies the code.
This removes error logs (stemming from receiving an empty response) that otherwise can confuse someone trying to diagnose a bug into looking at the wrong problems.
This also addresses data corruption that happened if multiple …
=> ddtrace/opentelemetry: refactor OTel API tests

ddtrace/tracer/tracer_test.go
Expands the current tests to verify that regardless of the value of `DD_TRACE_COMPUTE_STATS`, the `DD_TRACE_REPORT_HOSTNAME` variable is always respected.
This is important to prevent an unintentional cardinality increase when tracer stats are enabled, and would maintain inheritance of host tags. 
=> tracer: verify that hostname reporting is honored regardless of stats calculation

ddtrace/opentelemetry/span_test.go, ddtrace/opentelemetry/tracer.go
This change also includes a number of refactors, including some additional information about the trace flags.
We should maintain some of the logic in the original PR when creating the DD span link: https://github.com/DataDog/dd-trace-go/pull/2396/files#diff-328a045c801a15647d453336c495d31dcd8016d29df86de478c77769d6792567
=> opentelemetry: refactor span links code for clarity

.github/workflows/smoke-tests.yml, internal/apps/setup-smoke-test/Dockerfile
In order to prevent reoccurrences of issues where non-go files are located in places incompatible with `go mod vendor`, which the smoke test accurately detects, we are going to run the smoke tests as part of the CI suite in go-libddwaf itself. This requires being able to pin the go-libddwaf version to the commit being CI'd.
=> chore: make the smoke-test workflow usable as go-libddwaf integ test

.github/workflows/smoke-tests.yml
The default repository being checked out by `actions/checkout` is the one designated by `${{ github.repository }}`, which is the repository where the original event (at the root of the workflow call tree) started.
We however must check out the source to `dd-trace-go` and not that of the caller workflow. This requires hard-coding the repository name here.
=> chore: fix smoke test workflow_call situation

.github/workflows/appsec.yml, internal/appsec/waf_test.go
Rename DD_EXPERIMENTAL_API_SECURITY_ENABLED to DD_API_SECURITY_ENABLED
and make API Security enable by default (actually done here #2553 as an incident response)
This PR fixes a test that failed during the previous PR and also enables the good workflow to run in case the go.mod files are modified.
=> appsec: enable API Security by default

ddtrace/tracer/remote_config_test.go, internal/apps/go.mod, internal/apps/go.sum
Remove faulty appsec.Enabled() assertion in RC tests, which always fails on windows machines.
=> ddtrace/tracer: removed appsec.enabled assertion in RC test

contrib/confluentinc/confluent-kafka-go/kafka.v2/kafka.go, contrib/confluentinc/confluent-kafka-go/kafka/kafka.go
When the produce queue is full, the confluent-kafka-go producer returns a synchronous error. The span started in the wrapper for the produce call currently isn't `Finish`ed in this scenario.
Stumbled upon during reading code.
=> [DSM] Close span on produce error in ckgo

ddtrace/tracer/metrics_test.go, ddtrace/tracer/tracer_test.go, ddtrace/tracer/writer_test.go, internal/statsdtest/statsdtest.go
Moves the mock statsd client for testing out of the `tracer` package and into its own internal `statsdtest` package.
The infrastructure for testing statsd metric submission / statsd client successes was internal and lived within the `tracer` package, in the ddtrace/tracer/metrics_test.go file. In developing valuable tests for the new `StatsCarrier` type ([PR](https://github.com/DataDog/dd-trace-go/pull/2543)), which supports the "sharing" of statsd metrics between contrib packages and `tracer` package, we realized we needed access to this mock statsd client in non-tracer packages. Thus, the mock statsd client was made accessible to all packages within the repo by moving into its own internal package.
=> statsdtest: Move mock statsd client for testing into its own package

README.md, contrib/database/sql/conn.go, contrib/database/sql/internal/dsn.go, contrib/database/sql/propagation_test.go, ddtrace/tracer/sqlcomment.go, ddtrace/tracer/sqlcomment_test.go
This PR adds in the `ddh` and `dddb` peer service tags to SQL comments.
This change allows the DBM product to propagate service name information which maps with the inferred entities/services used by APM.  
=> contrib/database/sql: add in ddh, dddb propagation

.gitlab/macrobenchmarks.yml
Updates Go version for macrobenchmark runs from 1.18 + 1.19 to 1.19 + 1.22.0.
Tracer and profiler both work correctly after the change.
AppSec doesn't work in 1.22.0
For macrobenchmark 1.19 all 3 products work correctly.
Since 9th of January we have a broken macrobenchmark for Go tracer 1.18. The analysis of error has shown that some dependencies now require Go version 1.19 to compile the latest dd-trace-agent.
We need to fix macrobenchmark runs, so they continue to report relevant information.
=> Replace Go version 1.18+1.19 with 1.19+1.22.0

contrib/google.golang.org/grpc/grpc_test.go
Remove arbitrary calls to `time.Sleep`.
The test timeout will be enough to gate their exec time if they happen to fail.
gRPC tests are extremely flaky on qemu arm64.
=> contrib/google.golang.org/grpc: fix flaky tests by removing arbitrary sleeps

contrib/google.golang.org/grpc/appsec.go, contrib/google.golang.org/grpc/appsec_test.go, contrib/google.golang.org/grpc/server.go, internal/appsec/emitter/grpcsec/types/types.go, internal/appsec/listener/grpcsec/grpc.go, internal/appsec/testdata/passlist.json
Implement the `grpc.server.method` security rule address.
Tested with a custom ruleset passlist.json.
AppSec Passlist Support for gRPC, where a gRPC security rule can be passlisted according to the gRPC method name.
APPSEC-52066
=> contrib/google.golang.org/grpc: security rule passlist support

contrib/gofiber/fiber.v2/fiber.go, contrib/gofiber/fiber.v2/fiber_test.go, contrib/gofiber/fiber.v2/option.go
Thi PR is about adding functionality to gofiber trace Middleware to avoid span generation for a specific requests.
Exclude spans generation for unneeded endpoints, like `/healthcheck`, `/`, `/version` etc. and to be able to do it on an application level rather than DD Agent.
[Issue](https://github.com/DataDog/dd-trace-go/issues/2582)
=> contrib/gofiber/fiber.v2: add possibility to exclude spans generation for specific requests

contrib/database/sql/example_test.go, contrib/database/sql/option.go, contrib/database/sql/option_test.go, contrib/database/sql/sql_test.go
This feature disables the user-facing part of the DB stats feature until the tests are passing and all memory-related bugs are fixed. This PR can be reverted to add the feature back to the `database/sql` contrib.
There were some test failures related to a deadlock that are being investigated in https://github.com/DataDog/dd-trace-go/pull/2593
=> contrib/database/sql: temporarily disable DB stats feature

internal/globalconfig/globalconfig_test.go
Skips a test related to #2594 
Right now `TestPushStat` fails consistently.
=> internal/globalconfig: skip TestPushStat

.github/workflows/multios-unit-tests.yml, .github/workflows/unit-integration-tests.yml
Avoid using the default value of `DD_APPSEC_WAF_TIMEOUT` (1ms) in CI and rather use an "infinite" value, large enough for our CI runs.
Avoid getting flaky test results.
=> ci: set a large enough appsec timeout value

contrib/99designs/gqlgen/option.go, contrib/99designs/gqlgen/tracer.go, contrib/99designs/gqlgen/tracer_test.go
The `gqlgen` middleware was missing the ability to customize tags on the created spans. Implement a `WithCustomTag` option that follows the pattern of other similar packages.
I also renamed variable names for the `config` struct as `cfg`, instead of `t`, to match every other contrib package.
Fixes #2597; supports the ability to use additional tagging with `gqlgen` traces.
=> contrib/99designs/gqlgen: add WithCustomTag option

.github/workflows/main-branch-tests.yml, .github/workflows/multios-unit-tests.yml, .github/workflows/parametric-tests.yml, .github/workflows/pull-request.yml, .github/workflows/smoke-tests.yml, .gitlab-ci.yml, .gitlab/macrobenchmarks.yml, README.md, go.mod, internal/apps/go.mod
As per the [go supported version policy](https://github.com/DataDog/dd-trace-go#supported-versions). We are rotating go 1.19 from the supported versions in favor of go 1.22.
Fixes #2595 
=> go.mod: rotate go 1.19 from supported versions

internal/remoteconfig/remoteconfig.go
Explicitly setting the APM_TRACING_SAMPLING_RULES to use the correct number 29 that is reserved across all languages.
=> internal/remoteconfig/: Fixes capability APM_TRACING_SAMPLING_RULES to use the correct reserved number 29.

contrib/net/http/http_test.go, contrib/net/http/trace_test.go, ddtrace/tracer/tracer_test.go
`BenchmarkHttpServeTrace` used the `mocktracer` instead of the real tracer.
As in v2 we prefer to use the real tracer, although not completely applied, we found that we were measuring different implementations.
=> contrib/net/http: harmonize benchmarks for v2

internal/appsec/remoteconfig.go, internal/appsec/remoteconfig_test.go
Stop registering RC products, callbacks and capabilities related to blocking when DD_APPSEC_RULES is set.
This behaviour is RFC specified.
This aligns ASM's behaviour with that of the RFC specification, as well as fixes a bug where rules get
instantaneously overwritten by those received through ASM_DD even when using DD_APPSEC_RULES.
=> appsec: don't enable blocking-related RC features when using local security rules

internal/samplernames/samplernames.go
sampler name `9` was reserved for OTel ingestion but not documented. 
The new sampler for remote user rule also uses `9`. This fixes the collide.
=> internal/samplernames: fixes a colliding sampler name

ddtrace/mocktracer/mockspan.go, ddtrace/tracer/span.go, ddtrace/tracer/span_test.go
Adds `AddLink` to the span struct.
Currently span links can only be set on spans on span creation (via [WithSpanLinks](https://github.com/DataDog/dd-trace-go/blob/v1.999.0-rc.8/ddtrace/tracer/option.go#L414) option). To support many use cases we need the ability to add SpanLinks after a span has been created.
=> chore(otel): adds an API for generating span links

ddtrace/tracer/remote_config.go
- Add the proc's runtime ID to the remote config callback first introduced in #2510
In order to use Dynamic Instrumentation's probe status feature, we need to have the runtime ID.
=> Add runtime ID to Dynamic Instrumentation's remote config callback

.gitlab-ci.yml, go.mod, go.sum, internal/apps/go.mod, internal/apps/go.sum, internal/appsec/listener/graphqlsec/graphql.go, internal/appsec/listener/grpcsec/grpc.go, internal/appsec/listener/httpsec/http.go, internal/appsec/listener/sharedsec/shared.go, internal/appsec/listener/sharedsec/shared_test.go, internal/appsec/waf_test.go
This PR upgrades [go-libddwaf](https://github.com/DataDog/go-libddwaf) and adapts the API to take advantage of the changes made for a better time-budgeting of ASM APP & API Protection and better metrics from the WAF
Dogfooding issues with ASM taking too much CPU time for each requests between other feedbacks. The new metrics will give us a better outlook on what went wrong on futur issues
cf. APPSEC-51700 & APPSEC-51550
=> appsec: stricter time budget per request and better metrics for the WAF

ddtrace/ddtrace.go, ddtrace/tracer/meta_struct.go, ddtrace/tracer/meta_struct_test.go, ddtrace/tracer/span.go, ddtrace/tracer/span_msgp.go, ddtrace/tracer/span_test.go, ddtrace/tracer/transport_test.go, ddtrace/tracer/writer.go, ddtrace/tracer/writer_test.go, internal/meta_struct.go
This PR adds the ability to send metadata in spans via the field `meta_struct` (added 2 years ago, agent v7.31) to the tracer following the `v0.4` protocol. To not create a breaking change with existing code, and since this feature is still waiting to be extensively tested. We decided to restrict its usage to the internal packages of dd-trace-go using a small wrapper type like this:
```go
span.SetTag("http", internal.MetaStructValue{
Value: map[string]string{
"route": "/route/to/endpoint",
"method": "POST",
},
})
```
The way this has been done was necessary to make sure no breaking changes in the `Span.SetTag` function was introduced now but the `v2-dev` branch will have a better version of this feature once this one is finalized.
Some of appsec tags in span are hitting size limits …
=> ddtrace: tracer: support for meta_struct field in span

contrib/segmentio/kafka.go.v0/kafka.go, contrib/segmentio/kafka.go.v0/kafka_test.go, contrib/segmentio/kafka.go.v0/option.go, contrib/segmentio/kafka.go.v0/option_test.go
Add Data Streams Monitoring support to segmentio/kafka integration
We currently use segmentio/kafka for our Go projects and it was easier to update the integration than change library.
=> contrib/segmentio/kafka.go.v0: add DSM support

.github/workflows/smoke-tests.yml
This adds a if in the workflows that will fail on forks. The issue is that `go get` on dd-trace-go and go-libddwaf fails when a fork is used to run the workflow.
We received a contribution in appsec code that triggered this workflow and failed it.
=> workflows: do not run the smoke-tests on forks

.github/pull_request_template.md
Removing reference of Security Design and Guidance team in PR review template as the team no longer exists. We will work with the trace team to understand the requirements of review.
=> ASEC-131:Remove reference to SDG as the team no longer exists

.github/workflows/multios-unit-tests.yml, .github/workflows/unit-integration-tests.yml
This PR adds the `DD_APPSEC_WAF_TIMEOUT=1m` env var to more CI jobs to reduce CI flakiness.
ASM can take up a lot of each customer's app requests time of left unchecked, so multiple safe guard are baked into dd-trace-go to make sure we stop ourselves before taking too much time. This env var change the timeout from the default, 1ms, to 1. minute. Cases like [this one](https://github.com/DataDog/dd-trace-go/actions/runs/8647087390/job/23707810560#step:5:313) where only half of the security rules that should trigger have triggered should disappear. 
=> workflows: increase timeout of WAF time budget in contrib CI tests

internal/remoteconfig/remoteconfig.go
Fixes a data race when accessing capabilities by using the corresponding mutex :)
Fixes #2648
=> internal/remoteconfig: fixes data race when accessing capabilities

contrib/database/sql/example_test.go
The WithDBStats example on the contrib/database/sql go docs is inaccurate: https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1@v1.63.0/contrib/database/sql#example-package-DbStats
It's missing WithDBStats in the register function call. This PR updates the code snippet to an accurate example 
Clarity and usability for the feature
=> docs: fix dbStats example in contrib/database/sql

internal/samplernames/samplernames.go
Fixing a collision in `_dd.p.dm` where number 10 was used both by data jobs and remote user rules.
An accompanying system test change PR is also made in https://github.com/DataDog/system-tests/pull/2394.
** This is intended to be cherry-picked for patch release `1.63.1`.**
Impact of the collision:
Small - feature won't be triggered unless allowed through a feature flag (currently disabled by default).
=> internal: Fixing `_dd.p.dm` decision maker collision on number 10.

ddtrace/mocktracer/mocktracer.go, ddtrace/tracer/globaltracer_test.go, ddtrace/tracer/noop.go, ddtrace/tracer/span.go, ddtrace/tracer/spancontext.go, ddtrace/tracer/tracer.go, ddtrace/tracer/tracer_test.go
This PR tidies up the `Tracer` interface for v2. It adds some functions to allow tracers implementing the interface to integrate with our implementation.
v2 work was interrupted due to team changes. To reach release candidate quality we need to resolve pending TODOs regarding public API.
=> [v2] ddtrace/tracer: tidy up Tracer interface

.github/workflows/unit-integration-tests.yml, ddtrace/tracer/remote_config.go, ddtrace/tracer/remote_config_test.go, ddtrace/tracer/rules_sampler.go
Supporting sampling rules with tags matching from remote config.
A companion system test is added in https://github.com/DataDog/system-tests/pull/2409
=> ddtrace/tracer: adding support of tags in remote sampling rules.

internal/version/version.go
Bump the development version tag now that the v1.64.0 release process has started.
=> version: v1.65.0-dev

CODEOWNERS
Removes IDM as owner of `/ddtrace`.
IDM focuses on contribs, while `/ddtrace` is under `apm-go` scope.
=> CODEOWNERS: remove IDM as owner of /ddtrace path

internal/apps/go.mod, internal/apps/go.sum, internal/datastreams/processor.go, internal/datastreams/processor_test.go
Stop using deprecated library for Protobuf (github.com/golang/protobuf/proto)
Follow up to https://github.com/DataDog/dd-trace-go/issues/1136
=> Move to google.golang.org/protobuf

internal/datastreams/processor.go
Update mapping parameters for ddsketches to match the ones used by the Datadog backend.
This is going to avoid a conversion, which leads to precision loss & is pretty costly.
=> datastreams: Update mapping

.github/actions/dd-ci-upload/action.yml
The datadog-ci Windows release is now just 'datadog-ci_win-x64', without the '.exe' extension at the end. This means our CI no longer works for Windows on main.
Here's a failure, before this PR: https://github.com/DataDog/dd-trace-go/actions/runs/9162301098/job/25190768068#step:7:34. We can see right above the failure that fetching from the cache failed. We're already well over our cache limit so things are being bumped from the cache:
Here's a Windows CI run showing the "Upload Results to Datadog CI App" stage working with the change in this PR: https://github.com/DataDog/dd-trace-go/actions/runs/9163305530/job/25192097278
=> ci: use correct path for Windows datadog-ci release

go.mod, go.sum, internal/stacktrace/event.go, internal/stacktrace/event_test.go, internal/stacktrace/stacktrace.go, internal/stacktrace/stacktrace_test.go
This PR refactors the `internal/stacktrace` package to skip modules managed by the tracer to provide a cleaner stacktrace to users.
The default stack size is 32 and is bloated with internal code that the user does not care about
=> internal: stacktrace: skip internal packages

go.mod, go.sum
CVE associated to `github.com/mattn/go-sqlite3` reported by customer in #2693.
Reduce vulnerabilities associated to our repository.
=> go.mod: upgrade github.com/mattn/go-sqlite3 up to v1.14.18 (#2693)

contrib/net/http/http.go, contrib/net/http/http_test.go
Let's assume you want to instrument a `http.ServeMux` using the [new routing patterns in go1.22](https://tip.golang.org/doc/go1.22#enhanced_routing_patterns):
```go
mux := httptrace.NewServeMux()
mux.HandleFunc("GET /", home.HomeHandler(d))
return mux
```
Before this patch, you'll see the http methods being reported twice:
After this patch, this problem is fixed:
I'm building a little toy app which may or may not serve my blog one day, and I'm using it to compare the usability of our existing contrib instrumentations against orchestrion. While doing this I noticed the problem above and figured I should submit a fix.
=> contrib/net/http: Support go1.22 ServeMux patterns

profiler/profiler_test.go, profiler/upload_test.go
This is yet another test that hooks into internal implementation details
of the profiler. It's been mostly superseded by TestAllUploaded. The
bits that are unique to this test (asserting some of the default tags
and a few details of the event payload) can be folded into tests that
aren't (as) dependent on implementation details.
=> profiler: remove TestTryUpload

ddtrace/tracer/rules_sampler.go, ddtrace/tracer/span_test.go
Fixes a race condition bug reported by TEE, where a span was being modified concurrently to inject context and to set tags and trace sampling rules are in place.
Avoid race conditions in our code and improve reliability of our tracer.
=> ddtrace/tracer: fix concurrent map writes when applying trace sampling rules and setting tags concurrently

internal/datastreams/pathway.go
This PR fixes the SNS topic format issue raised in the [support ticket](https://datadoghq.atlassian.net/browse/DSMS-19) where SNS topics aren't detected as data streams. The customer traced the issue to the `nodeHash` function where it checks for correctly formatted tags and returned them. 
However, in the `isWellFormedEdgeTag` check, it will return false for any cases where the tag is a topic that is a full arn (such as `topic:arn:aws:sns:eu-west-1:474060719897:sre-spec-api-ops-dev-slo-consumers` in the customer's case) because the condition check (`j == i`) will return `true` only if there is **one** colon in the edge tag. 
The fix will check that 1) there is a colon, 2) the tag is a topic, and that 3) the tag string contains "arn", then return `true` for this case so that full arn …
=> [DSMS-19] Fix SNS topic format issue

ddtrace/opentelemetry/span.go, ddtrace/opentelemetry/span_test.go
In order for Otel spans to be compliant with the DD backend, `http.response.status_code` needs to be remapped to `http.status_code` for trace metrics compliance.
=> ddtrace/opentelemetry: adds http status code remapping for otel trace metrics

go.mod, go.sum, internal/apps/go.mod, internal/apps/go.sum, internal/exectracetest/go.mod, internal/exectracetest/go.sum
This PR upgrades go-libddwaf
Currently the v2 and the v3 of go-libddwaf cannot cohexist in the same binary even tho go permit this. Fix this
=> upgrade go-libddwaf: v3.2.0 -> v3.2.1

ddtrace/tracer/rules_sampler.go, ddtrace/tracer/span_test.go
This backports #2727 to the v1.64 release branch.
This is a bug with no workaround other than completely disabling tracing.
=> ddtrace/tracer: fix concurrent map writes when applying trace sampling rules and setting tags concurrently (#2727)

internal/datastreams/pathway.go, internal/datastreams/pathway_test.go
This PR removes the one colon check for well-formed edge tags.
https://dd.slack.com/archives/C06P5GB4UT1/p1717608298448609
=> Remove one colon check for well-formed edge tags

ddtrace/opentelemetry/span.go, ddtrace/opentelemetry/span_test.go
Changes code due to the unforeseen circumstance that otel values for `http.response.status_code` are int values while Datadog uses `http.status_code` as a string value
=> Fix http remapping to account for int values

internal/telemetry/client.go, internal/telemetry/telemetry_test.go
Avoid sending the telemetry request `app-dependencies-loaded` when there is no Go build info available in the running Go program.
Datadog's Software Composition Analysis (SCA) relies on program deps, sent over `app-dependencies-loaded`, which must not be sent when they are missing.
This issue appeared with Bazel which doesn't seem to include Go build info (https://github.com/bazelbuild/rules_go/issues/3090).
=> internal/telemetry: don't send app-dependencies-loaded in the absence of Go deps

.github/workflows/appsec.yml
Make CI faster and run on ARM
[APPSEC-53468](https://datadoghq.atlassian.net/browse/APPSEC-53468)
[APPSEC-53468]: https://datadoghq.atlassian.net/browse/APPSEC-53468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> appsec: fix macos native tests

appsec/events/block.go, contrib/net/http/roundtripper_test.go
This PR fix `IsSecurityError` which did not have the right behaviour and was always returning false in go 1.20
This function has 2 current uses:
* It should be used by customers to check whether the WAF blocked a ˋnet/http` outgoing request.
* It is used in the ˋnet/http` contrib to not report the error as one in the current span.
Both usages are void in go 1.20 without this PR.
=> appsec: fix IsSecurityError

ddtrace/tracer/log_test.go, ddtrace/tracer/option.go
This PR adds a small rewrite to the parsing of the DD / OTEL Sample Rate configuration so that we do not log a warning when the sample rate is empty. This also adds a regression test for the scenario.
Fixes #2749 
=> ddtrace/tracer: update sample rate configuration parsing to avoid logging a warning when empty

.github/workflows/system-tests.yml
This PR enables the `APPSEC_RASP` system-tests scenario.
Better test coverage following #2707 
=> workflows: enable APPSEC_RASP system-tests scenario

README.md
Remove 1.19 from supported versions
Fixes #2750
Confusing for readers of the README since dd-trace-go does not compile with it anymore
=> readme: drop go 1.19 from support table

.gitlab/macrobenchmarks.yml
Updates env variables for Go macrobenchmarks, so they match the new setup from [BP PR 74](https://github.com/DataDog/benchmarking-platform/pull/74/files).
The changes in this PR and linked [BP PR 74](https://github.com/DataDog/benchmarking-platform/pull/74/files) together do next:
1. Enabled RSS and CPU utilization overhead measurements.
2. Simplified LOAD_TESTS variable.
3. Separated benchmark runs into normal_operation and high_load phases more cleanly, allowing e.g. to track Linux load averages, system RSS / CPU usage, etc. during normal load and stress load _separately_.
Also, Go benchmarking dashboard was updated, so new measurements are visible.
=> Upgrade macrobenchmarks setup, add CPU / RSS utilization overhead measurements

.github/workflows/smoke-tests.yml
Adds `1.23-rc` as building image for smoke tests.
Ensure that smoke tests are always running with the latest Go release available. Running against tip would be perfect, but there is no official Go image for tip.
=> .github/workflows: run smoke tests on latest Go 1.23 release candidate

contrib/log/slog/example_test.go, contrib/log/slog/slog.go, contrib/log/slog/slog_test.go, contrib/sirupsen/logrus/logrus.go, ddtrace/ext/log_key.go, ddtrace/tracer/option.go, ddtrace/tracer/option_test.go
Adds a new instrumentation for https://pkg.go.dev/log/slog
This instrumentation provides log / trace correlation for `log/slog` users: https://docs.datadoghq.com/tracing/other_telemetry/connect_logs_and_traces/
Solves https://github.com/DataDog/dd-trace-go/issues/2077
=> contrib: add log/slog instrumentation

internal/exectracetest/exectrace_test.go
This test was sensitive to the order of map iteration, making it flaky.
Whoops!
Example flake: https://github.com/DataDog/dd-trace-go/actions/runs/9778155930/job/26994378106#step:5:362
=> internal/exectracetest: fix TestExecutionTraceSpans flakes

.gitlab-ci.yml, internal/appsec/listener/graphqlsec/graphql.go, internal/appsec/listener/grpcsec/grpc.go, internal/appsec/listener/httpsec/http.go, internal/appsec/listener/httpsec/roundtripper.go, internal/appsec/listener/sharedsec/shared.go, internal/appsec/listener/sqlsec/sql.go
This PR does a simple refactor of `internal/appsec/listener` packages. Including the following:
Doing less copy-pastes
=> internal/appsec: refactor simple WAF run operations

internal/civisibility/integrations/gotesting/testing_test.go, internal/civisibility/utils/environmentTags.go
Transform the source path from the windows represantion to the unix representation.
Implications:
- Codeowners are defined in the unix represantation, and we want to match the source files with codeowners: https://github.com/DataDog/dd-trace-go/blob/0ee003663a921b30bd2f4af6b463b17fb0261145/internal/civisibility/integrations/manual_api_ddtest.go#L144
- The working directory tag in test session event for Windows will be in the unix representation: https://github.com/DataDog/dd-trace-go/blob/0ee003663a921b30bd2f4af6b463b17fb0261145/internal/civisibility/integrations/manual_api_ddtestsession.go#L54
Also, don't assert git commit details if the provider is github, because github doesn't provide those tags, example job:
https://github.com/DataDog/dd-trace-go/actions/runs/9853630340/job/2720458604 …
=> [CI VIsibility] Fix the source path for windows

ddtrace/tracer/option.go, ddtrace/tracer/option_test.go
Fixes the issue where tracer_version was not correctly appended to statsd tags. 
Filtering by tracer_version is not available for releases v1.62.\*-v1.65.\*.
=> ddtracer/tracer: fix appending 'tracer_version' to the statsd tags

CONTRIBUTING.md, contrib/README.md
Updates our policy on how we deprecate our contribs when upstream deprecates and there is a CVE.
Setting clear expectations on how we manage the contribs when the integrated package are deprecated.
=> v2: contrib/README: add versioning and deprecation policies for contribs

ddtrace/mocktracer/mockspan.go, ddtrace/mocktracer/mocktracer_test.go
This PR fixes a panic happening when using `tracer.SetUser` with the option `WithUserMetadata` on a instance of a mocktracer.
Stacktrace:
<details>
```
panic: assignment to entry in nil map [recovered]
panic: assignment to entry in nil map
goroutine 5 [running]:
testing.tRunner.func1.2({0x10487e640, 0x104965140})
/opt/homebrew/Cellar/go/1.22.3/libexec/src/testing/testing.go:1631 +0x1c4
testing.tRunner.func1()
/opt/homebrew/Cellar/go/1.22.3/libexec/src/testing/testing.go:1634 +0x33c
panic({0x10487e640?, 0x104965140?})
/opt/homebrew/Cellar/go/1.22.3/libexec/src/runtime/panic.go:770 +0x124
github.com/DataDog/dd-source/domains/aaa/shared/libs/go/authctxhttp.Authenticate.func1.1.WithUserMetadata.4(0x1400008db18?)
/Users/kaitlyn.paglia/go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.66.0-rc.1/dd …
```
=> ddtrace/mocktracer: fix SetUser & WithUserMetadata

.gitlab/macrobenchmarks.yml
1. Adds instruction how to update Go version for macrobenchmarks.
2. Adds retries for macrobenchmarks that failed due to internal Gitlab errors (which are expected to happen 1 in ca. 900 runs on avg).
Go macrobenchmarks were broken since last Thursday due to https://github.com/DataDog/dd-trace-go/commit/e8dc9746d65d857fe557a7bc438939d110373c15, because Docker image was not updated  with newer Go versions.
I've already updated the image in background, so now the pipeline is fixed.
This PR adds more specific instructions on updating Go versions.
=> Add instruction how to update Go version for macrobenchmarks

ddtrace/tracer/otel_dd_mappings.go, ddtrace/tracer/otel_dd_mappings_test.go
The expected telemetry tags when reporting OTel env-var mapping issues now use snake-case:
```
config.datadog       -> config_datadog
config.opentelemetry -> config_opentelemetry
```
The expected tag values should also be lower-case.
The [RFC](https://docs.google.com/document/d/1gtdjhsMSIvuTnM9E4EreI7oZ-bAUoAxkhXX0-fBvdDY/edit?usp=sharing) has been revised since #2715
=> ddtrace/tracer: update the expected telemetry tags for OTel env-var mapping

ddtrace/tracer/spancontext.go, ddtrace/tracer/spancontext_test.go, ddtrace/tracer/textmap.go, ddtrace/tracer/textmap_test.go
Replaces the usage of `fmt.Sprintf` and `regex` calls in `textmap.composeTracestate` to reduce allocations and CPU consumption.
This function has been reported as a significant contributor of tracer overhead.
Original benchmark results for the worst scenario:
```
BenchmarkComposeTracestate-10       448386          2429 ns/op         589 B/op         36 allocs/op
```
Benchmark results after removing all `fmt.Sprintf` usages:
```
BenchmarkComposeTracestate-10       508797          1976 ns/op         403 B/op         24 allocs/op
```
Benchmark results after replacing `regex` usages with tailored code:
```
BenchmarkComposeTracestate-10      1749620           675.3 ns/op       240 B/op         10 allocs/op
```
Benchmark results evolving the tailored code to a reusable state machine wrapped in …
=> ddtrace/tracer: optimize textmap.composeTracestate

ddtrace/tracer/telemetry.go, ddtrace/tracer/telemetry_test.go
The `noDebugStack` tracer configuration now reports telemetry under the key `debug_stack_enabled`.
Note: New `debug_stack_enabled` field added to telemetry backend here: https://github.com/DataDog/dd-go/pull/143865
Prior to this change, the `noDebugStack` config was incorrectly reporting telemetry under the key `trace_debug_enabled`.
- [n/a] [System-Tests](https://github.com/DataDog/system-tests/) covering this feature have been added and enabled with the va.b.c-dev version tag.
- [n/a] There is a benchmark for any new code, or changes to existing code.
- [n/a ] If this interacts with the agent in a new way, a system test has been added.
- [n/a] Non-trivial go.mod changes, e.g. adding new modules, are reviewed by @DataDog/dd-trace-go-guild.
=> ddtrace/tracer: noDebugStack config reports to telemetry under distinct key debug_stack_enabled

internal/version/version.go
Bump the development version tag now that the v1.67.0 release process has started.
=> internal/version: bump to v1.68.0-dev

go.mod
Retracts some tagged versions created to dogfood our v1 shim for v2.
Keep public docs clean and let users to use release candidates if they want without `go get` pulling the experimental versions accidentally.
=> go.mod: retract experimental versions

.github/workflows/orchestrion.yml, contrib/gin-gonic/gin/gintrace.go
=> ci: setup orchestrion integration tests

ddtrace/tracer/option.go, ddtrace/tracer/option_test.go
Adds `uptrace/bun` to our telemetry's supported contribs list.
Making sure the integration is reported as imported when it's in use.
=> ddtrace/tracer: add uptrace/bun to telemetry's supported contribs

ddtrace/tracer/textmap.go, ddtrace/tracer/textmap_test.go
Currently when w3c tracestate headers are extracted by Datadog W3C Propagators:
1) The `p` value in the tracestate is stored in `SpanContext.reparentID`.
2) If the `p` value is not found in the tracestate then SpanContext.reparentID (which will be used to set `Span.meta["_dd.parent_id"]`) is set to `0000000000000000`.
The second condition is no longer required. Datadog internal services no longer handle the case where `Span.meta["_dd.parent_id"] == 0000000000000000`. `0000000000000000` is treated as an invalid value and ignored. We should avoid setting this value in client libraries.
- Simplify the extraction logic for w3c tracecontext headers. 
- Avoids unnecessary tags to the Datadog agent.
=> chore(w3c): ensure last parent id is never set to 16 zeros

.github/workflows/unit-integration-tests.yml, contrib/gocql/gocql/example_test.go, contrib/gocql/gocql/gocql.go, contrib/gocql/gocql/gocql_test.go, contrib/gocql/gocql/observer.go, contrib/gocql/gocql/observer_test.go, contrib/gocql/gocql/option.go, ddtrace/ext/db.go, docker-compose.yaml, go.mod, go.sum
- Adds `CreateTracedSession`, and `NewObserver` functions that make use of the gocql [observer apis](https://pkg.go.dev/github.com/gocql/gocql#hdr-Metrics_and_tracing):  (it only implements the query, batch and connect observers for now).
- Adds new options `WithTraceQuery`, `WithTraceBatch` and `WithTraceConnect` to enable/disable these observers individually (all are enabled by default).
- Mark the existing wrapping functions and types as deprecated.
Differences with the existing tracing method:
- The tags `cassandra.paginated` and `cassandra.consistency_level` are not set, since the required information is not available in the observer api.
- The new observer based functions set `out.host` to the actual host name instead of the cassandra host ID. The host ID is set to a new tag called …
=> contrib/gocql/gocql: implement observer api based tracing

contrib/Shopify/sarama/option.go, contrib/Shopify/sarama/sarama.go, contrib/Shopify/sarama/sarama_test.go, contrib/sirupsen/logrus/logrus.go, contrib/syndtr/goleveldb/leveldb/leveldb.go, contrib/syndtr/goleveldb/leveldb/leveldb_test.go, contrib/syndtr/goleveldb/leveldb/option.go, contrib/tidwall/buntdb/buntdb.go, contrib/tidwall/buntdb/buntdb_test.go, contrib/tidwall/buntdb/option.go, contrib/twitchtv/twirp/option.go, contrib/twitchtv/twirp/twirp.go, contrib/twitchtv/twirp/twirp_test.go, go.work.sum, instrumentation/internal/namingschematest/main_test.go, instrumentation/internal/namingschematest/shopify_sarama.go, instrumentation/internal/namingschematest/syndtr_goleveldb.go, instrumentation/internal/namingschematest/tidwall_buntdb.go, instrumentation/internal/namingschematest/twirp_test.go, instrumentation/packages.go
Migrates a subset of the contribs to use the new contrib API. Each commit is a contrib, to simplify code review.
Contrib API was created to split contribs as nested modules: see #2768 
=> v2: feat(contrib): migrate twitchtv/twirp, tidwall/buntdb, syndtr/goleveldb/leveldb, Shopify/sarama, sirupsen/logrus

ddtrace/tracer/sampler_test.go, ddtrace/tracer/span.go, ddtrace/tracer/tracer.go
This PR updates sampling logic. Now, resampling only occurs on root spans. Neither"_dd.limit_psr", nor "_dd.rule_psr" should be present on the child span. 
Locking the span after context propagation prevents re-sampling.
=> ddtrace/tracer: fixed resampling to occur on root span only

.github/workflows/orchestrion.yml
With https://github.com/DataDog/orchestrion/pull/219 merged, the branch
we pinned to for the Orchestrion test is gone. Switch back to main so
the workflow can run again.
See https://github.com/DataDog/dd-trace-go/actions/runs/10617402656/workflow
=> ci: switch Orchestrion workflow back to main

internal/appsec/emitter/httpsec/http.go
This PR fixes a case where we were supposed to call the `ResponseHeaderCopier` func but we did not
Fix cases where concurrently reading the response header map would can a panic. This fixes the fix done in #2640 
=> internal/appsec: fix missing ResponseHeaderCopier call

.github/workflows/smoke-tests.yml, .github/workflows/unit-integration-tests.yml, internal/exectracetest/go.mod
Set `GOTOOLCHAIN=local` for our unit tests.
I didn't change the `go get -u` smoke tests. Those tests are inherently
incompatible with `GOTOOLCHAIN=local`. We could perhaps make them
work with `GOTOOLCHAIN=local` by adding `go@1.xyz` to the `go get -u`
commands, like [Orhcestrion does](https://github.com/DataDog/orchestrion/blob/aee181b5ec8ac51cee000d32ecd555c35340eb08/.github/workflows/deps-update.yml#L37-L38).
Users may build our library with `GOTOOLCHAIN=local`. If they do, and our
go.mod file specifies a newer Go version than their local toolchain, their
build will break. Run our tests with `GOTOOLCHAIN=local` to ensure that
our library builds with all of the Go versions we claim to support,
without having to download a newer one.
=> ci: set GOTOOLCHAIN=local for unit tests

internal/civisibility/integrations/gotesting/instrumentation.go, internal/civisibility/integrations/gotesting/testing.go, internal/civisibility/integrations/gotesting/testingB.go, internal/civisibility/integrations/gotesting/testingT.go
This PR is a refactor of the existing code so the new methods can be used by the orchestrion instrumentation. It doesn't introduce any new functionality and the existing tests are enough for testing the refactored code.
Playing with orchestrion I realised that the current internal apis are really hard to call from an orchestrion integration, the refactor creates a new set of methods that can be easily called from methods prepend code kind of integrations. 
=> [CI Visibility] Refactor gotesting integration to be used by orchestrion

internal/globalconfig/globalconfig.go, internal/globalconfig/globalconfig_test.go
- `globalconfig.SetStatsTags(tags []string)` now makes a copy of `tags` before setting it as the value of `cfg.statsTags` 
- `globalconfig.StatsTags()` now returns a copy of `cfg.statsTags`
Failure to perform the copying specified above resulted in pollution of the globalconfig statsTags.
https://github.com/DataDog/dd-trace-go/issues/2836 
=> internal/globalconfig: make statsTags un-changeable from outside of the globalconfig package

internal/version/version.go
Bump the development version to v1.69.0-dev now that the v1.68.0 release is
starting
=> internal/version: bump to v1.69.0-dev

ddtrace/tracer/civisibility_payload.go, ddtrace/tracer/civisibility_transport.go, ddtrace/tracer/civisibility_tslv.go, ddtrace/tracer/civisibility_writer.go, internal/civisibility/integrations/gotesting/instrumentation.go, internal/civisibility/integrations/gotesting/testing.go, internal/civisibility/integrations/gotesting/testingB.go, internal/civisibility/integrations/gotesting/testingT.go, internal/civisibility/integrations/gotesting/testing_test.go
For orchestrion we are going to instrument `testing.M.Run()`, `testing.T.Run()` and `testing.B.Run()` methods, for that we need to make some fixes and add some checks to avoid multiple instrumentation over the same Func
This PR also fixes an issue found with orchestrion about Test Suite Level Visibility (tslv) objects having `ParentId != 0` this breaks the backend json schema. Now we make sure that structs like `Test`, `TestSuite`,  `TestModule` and `TestSession` never set the ParentId value (Only normal spans are allowed to have it).
While working with the orchestrion autoinstrumentation I'm hitting this issues. This PR fixes those issues.
=> internal/civisibility/integrations/gotesting: fixes for orchestrion autoinstrumentation

internal/civisibility/integrations/gotesting/instrumentation.go
This PR adds a mechanism to use the existing `DD_CIVISIBILITY_ENABLED` environment variable as a kill switch to avoid enabling CI Visibility on an instrumented process.
This is useful for `orchestrion` instrumentation to allow us control when we want ci visibility to be enabled or not.
=> internal/civisibility/integrations/gotesting: add the `DD_CIVISIBILITY_ENABLED` kill switch environment variable

internal/civisibility/integrations/gotesting/instrumentation.go
This PR fixes and issue with the `atomic.Int32` used in the `isCiVisibilityEnabled` func, also enables reporting of the code coverage data in a test session.
Iterating with orchestrion and finding issues and possible improvements.
=> internal/civisibility/integrations/gotesting: improve the isCiVisibilityEnabled and enable reporting Code Coverage percentage.

go.mod, go.sum, internal/apps/go.mod, internal/apps/go.sum, internal/appsec/listener/httpsec/roundtripper.go, internal/appsec/listener/ossec/lfi.go, internal/appsec/listener/sharedsec/shared.go, internal/appsec/listener/sharedsec/shared_test.go, internal/appsec/listener/sqlsec/sql.go, internal/exectracetest/go.mod, internal/exectracetest/go.sum
[APPSEC-54194](https://datadoghq.atlassian.net/browse/APPSEC-54194)
[APPSEC-54194]: https://datadoghq.atlassian.net/browse/APPSEC-54194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> appsec: upgrade go-libddwaf v3.3.0 -> v3.4.0

internal/civisibility/integrations/civisibility.go, internal/civisibility/utils/net/client.go, internal/civisibility/utils/net/client_test.go, internal/civisibility/utils/net/efd_api.go, internal/civisibility/utils/net/efd_api_test.go, internal/civisibility/utils/net/http.go, internal/civisibility/utils/net/http_test.go, internal/civisibility/utils/net/searchcommits_api.go, internal/civisibility/utils/net/searchcommits_api_test.go, internal/civisibility/utils/net/sendpackfiles_api.go, internal/civisibility/utils/net/sendpackfiles_api_test.go, internal/civisibility/utils/net/settings_api.go, internal/civisibility/utils/net/settings_api_test.go
This PR adds a new http client for specific use on rapid endpoints used by ci visibility with json support, exponential backoff, rate-limiting status code, gzip compression and multipart bodies (attachments).
Some CI Visibility features require getting, posting and sending multipart form data to the backend. Features like:
- Early Flake detection
- Git upload
- Intelligent test runner
- Settings api
- Retry failed tests
=> internal/civisibility/utils/net: a new http client for rapid endpoints

internal/civisibility/constants/tags.go, internal/civisibility/integrations/civisibility.go, internal/civisibility/integrations/gotesting/testing_test.go, internal/civisibility/integrations/manual_api.go, internal/civisibility/utils/environmentTags.go, internal/civisibility/utils/environmentTags_test.go
This PR adds the new `_dd.host.vcpu_count` metric to all test suite level visibility events.
This new tag will be used by the backend to do some calculations.
=> internal/civisibility: adds the new vcpu_count metric for tslv events

profiler/profile.go, profiler/profiler.go
The fix in https://github.com/DataDog/dd-trace-go/pull/2865 was intended to suppress spurious metrics profile
errors when the profiler is stopped. It did so by relaxing the
one-second duration constraint of the metrics profiler. However,
the Windows system timer resolution is about 15 milliseconds (see
https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/high-resolution-timers#controlling-timer-accuracy)
This caused the metrics profile tests from https://github.com/DataDog/dd-trace-go/pull/2865 to fail because the
metrics profiler will likely be stopped in less than 15 milliseconds,
meaning we'll see 0 duration between profile collection and log an
error.
This commit actually suppresses the error by checking whether the
profiler was stopped (meaning interruptibleSleep was …
=> profiler: suppress errors if the profiler is stopped

internal/civisibility/integrations/gotesting/instrumentation.go
Change the default value for CI Visibility enabled to be **false** at least for preview releases. So users require to opt-in using the `DD_CIVISIBILITY_ENABLED` environment variable.
We don't want to enable CI Visibility by default when we are running tests instrumented by orchestrion while we are in preview mode. We will revisit this once we go to GA.
=> internal/civisibility: change the default value for DD_CIVISIBILITY_ENABLED to false

contrib/99designs/gqlgen/tracer.go, contrib/99designs/gqlgen/tracer_test.go
Check result from graphql responseHandler is nil
related to issue https://github.com/DataDog/dd-trace-go/issues/2791
I think I need contribute to community
=> contrib/99designs/gqlgen/tracer.go: nil check response

appsec/appsec.go, go.mod, go.sum, internal/apps/go.mod, internal/apps/go.sum, internal/appsec/emitter/usersec/user.go, internal/appsec/emitter/waf/addresses/addresses.go, internal/appsec/emitter/waf/addresses/builder.go, internal/appsec/listener/usersec/usec.go, internal/appsec/remoteconfig.go, internal/appsec/testdata/fp.json, internal/appsec/waf_test.go, internal/exectracetest/go.mod, internal/exectracetest/go.sum, internal/remoteconfig/remoteconfig.go
This PR finishing to setup Attacker fingerprinting:
System-tests job: https://github.com/DataDog/dd-trace-go/actions/runs/11127586022
Implementation of the Attacker Fingerprinting [RFC](https://docs.google.com/document/d/1DivOa9XsCggmZVzMI57vyxH2_EBJ0-qqIkRHm_sEvSs/edit?pli=1)
=> appsec: Attacker Fingerprinting

.github/workflows/system-tests.yml
Prefix system tests env var to not conflict with local dev env vars
=> chore: prefix system tests env var

ddtrace/tracer/civisibility_payload.go, ddtrace/tracer/civisibility_payload_test.go, internal/civisibility/constants/env.go, internal/civisibility/constants/test_tags.go, internal/civisibility/integrations/manual_api.go, internal/civisibility/integrations/manual_api_ddtestsession.go, internal/civisibility/utils/environmentTags.go
This PR implements a new CI Visibility feature called Test session logical names. In this feature a new DD_TEST_SESSION_NAME environment variable is introduced for customer to set their custom test session name. This name is sent to the backend inside the metadata object in the CI Visibility protocol.
New feature: https://docs.google.com/document/d/1XPBDDIMUxzfkko66vXIEjoi4xbCamTz-Bv6ChSR8jys/edit
=> internal/civisibility: test session logical names

internal/civisibility/integrations/gotesting/instrumentation.go, internal/civisibility/integrations/gotesting/testing_test.go
This PR fixes the scenario when a test fail after retrying and then a test passes, before the PR we were always setting the test parent status according the current test status, so a previous failure status gets overwrote by a test passing status.
This is fix on an actual bug in the implementation.
=> internal/civisibility: fixes the test parent status when the auto-retry feature ended up with a failed test and then a successful test.

internal/civisibility/constants/test_tags.go, internal/civisibility/integrations/manual_api_ddtest.go, internal/civisibility/integrations/manual_api_mocktracer_test.go
This PR adds a logic to calcule the `test.source.end` tag with the end line number of a test function using the ast parser. It's a best effort approach, in case we cannot extract it (eg: no source code is available) then we silently bail out.
This part of the CI Visibility specs.
=> internal/civisibility: add support for the test.source.end tag

ddtrace/tracer/option.go, ddtrace/tracer/telemetry.go, ddtrace/tracer/tracer.go, ddtrace/tracer/tracer_test.go, internal/log/log.go, internal/log/log_test.go
Supports specifying a log directory for tracer logs via `DD_TRACE_LOG_DIRECTORY` env var. If directory exists on the underlying os, tracer creates log file `ddtrace.log` at specified path and all tracer logs are routed to said file. Tracer maintains default behavior (log to stdout) if directory is invalid or does not exist.
Bring dd-trace-go up to speed on feature parity (other tracing libs support this). [RFC](https://docs.google.com/document/d/1kI-gTAKghfcwI7YzKhqRv2ExUstcHqADIWA4-TZ387o/edit#heading=h.okio0dm2m6n0)
=> Implement DD_TRACE_LOG_DIRECTORY

appsec/appsec.go, contrib/dimfeld/httptreemux.v5/example_test.go, contrib/gorilla/mux/mux_test.go, contrib/julienschmidt/httprouter/example_test.go, ddtrace/ext/tags.go, ddtrace/mocktracer/mocktracer_test.go, ddtrace/tracer/span.go, ddtrace/tracer/span_test.go, ddtrace/tracer/spancontext_test.go, ddtrace/tracer/sqlcomment_test.go, ddtrace/tracer/textmap.go, ddtrace/tracer/textmap_test.go, ddtrace/tracer/tracer_test.go
Removes support for `ext.SamplingPriority`. Users should opt to use `span.SetTag(ext.ManualKeep, true)` for keeping spans/traces, and `span.SetTag(ext.ManualDrop, true)` for dropping spans/traces.
Re: PR #1082 , `ext.SamplingPriority` has been deprecated. 
=> v2: remove sampling priority

internal/civisibility/integrations/civisibility_features.go, internal/civisibility/integrations/gotesting/testcontroller_test.go, internal/civisibility/utils/environmentTags.go, internal/civisibility/utils/git.go, internal/civisibility/utils/git_test.go, internal/civisibility/utils/net/client.go, internal/civisibility/utils/net/http.go, internal/civisibility/utils/net/sendpackfiles_api.go, internal/civisibility/utils/net/sendpackfiles_api_test.go
This PR adds the Git tree upload feature to the CI Visibility library.
**specs**: https://datadoghq.atlassian.net/wiki/spaces/SDTEST/pages/3123348305/Intelligent+Test+Runner+in+CI+Visibility+Libraries#Git-tree-upload.1
All CI Visibility libraries implement this feature, we were missing it.
=> internal/civisibility: adds git tree upload feature

internal/civisibility/integrations/gotesting/instrumentation_orchestrion.go
In go 1.23, a change was made in the //go:linkname by locking down the usage, and the recommended way of doing it now is in handshake mode.
https://github.com/golang/go/issues/67401
Because the orchestrion integration uses the api using //go:linkname we are adding here the handshake support.
I want to avoid any future issue of //go:linkname missusage 
=> internal/civisibility: add handshake linkname to orchestrion api to address linkname lock down

contrib/jackc/pgx.v5/pgx.go, contrib/jackc/pgx.v5/pgx_tracer.go, contrib/jackc/pgx.v5/pgx_tracer_test.go, contrib/jackc/pgx.v5/pgxpool.go
Fixes https://github.com/DataDog/dd-trace-go/issues/2908
Wrap the previous tracer if there was one instead of replacing it.
Additionally, it adds `ConnectWithOptions` which is the traced version of the original `pgx.ConnectWithOptions`.
=> contrib/jackc/pgx.v5: wrap previous tracer

contrib/dimfeld/httptreemux.v5/httptreemux.go, contrib/dimfeld/httptreemux.v5/httptreemux_test.go
Replicates and closes #2881 #2812 
=> [godfathering] contrib/dimfeld/httptreemux.v5: failing tests for path variable replacement

internal/civisibility/integrations/gotesting/testcontroller_test.go, internal/civisibility/integrations/gotesting/testing_test.go
This PR removes tests that imports contrib packages.
This required for v2 works.
=> internal/civisibility: removes importing contrib packages from tests

internal/civisibility/integrations/gotesting/instrumentation.go, internal/civisibility/integrations/gotesting/instrumentation_orchestrion.go, internal/civisibility/integrations/gotesting/reflections.go, internal/civisibility/integrations/gotesting/testing.go
Add more nil checks on the CI Visibility library to either workaround possible crash, or panic with a better error message.
Try to increase library resilience
=> internal/civisibility: add more nil checks to increase resilience

internal/civisibility/integrations/gotesting/instrumentation.go
This PR fixes the calculation and message of auto test retries maximum number of retries for the session.
The decrement was executed during every `shouldRetry` call even if a retry is not being done at the end.
=> internal/civisibility: auto test retries max retries fix

internal/osinfo/osinfo_windows.go
This PR fix dd-trace-go build for windows
=> internal/osinfo: too many return values compile error on windows

internal/appsec/emitter/httpsec/http.go
Rework `emitter/httpsec.BeforeHandle` to make `blockAtomic` value content atomic itself 
https://github.com/DataDog/dd-trace-go/pull/2921#discussion_r1799106229
=> internal/appsec: fix blocking atomicity

ddtrace/tracer/civisibility_transport.go, ddtrace/tracer/transport.go, ddtrace/tracer/transport_test.go
This PR cleans up the `Content-Length` header in the request made to the agent. In the case of civisibility the request is made with a `*bytes.Buffer` and as indicated in the documentation the content length is computed automatically here ([cf doc](https://pkg.go.dev/net/http#NewRequestWithContext)).
In the case of the default/regular trace transport, the `Content-Length` was set manually through the header. My investigation from the agent side is that we receive a fair amount of traces from dd-trace-go without `Content-Length`, so this PR moves the content length back to the actual request field, [as suggested in the documentation](https://pkg.go.dev/net/http#Client.Do:~:text=For%20client%20requests%2C%20certain%20headers%20such%20as%20Content%2DLength%0A%09//%20and%20Connection%20are%20a …
=> fix and cleanup the `Content-Length` handling in transport

appsec/appsec.go, internal/appsec/emitter/usersec/user.go, internal/appsec/listener/usersec/usec.go
Rework user login WAF addresses passing by differentiating a simple authenticated request and a user login request
Better ATO detection
=> appsec: differentiate user login and user set event

internal/civisibility/integrations/gotesting/instrumentation.go, internal/civisibility/integrations/gotesting/testcontroller_test.go, internal/civisibility/integrations/manual_api_ddtest.go
This PR changes the behaviour when both Early Flake Detection (EFD) and Auto Test Retries (ATR) features are enabled.
Now:
- If a test if affected by EFD (is a new test) we apply only EFD feature (10 retries).
- For other known tests (not EFD) we will apply the ATR feature. 
The current behavior is weird, for each EFD retry we will do ATR, so if a EFD execution fail we will auto retry that one until it passes, and the continue with another EFD execution.
=> internal/civisibility: test with efd enabled disable atr for that test

internal/civisibility/constants/test_tags.go, internal/civisibility/integrations/gotesting/reflections_test.go, internal/civisibility/integrations/gotesting/testcontroller_test.go, internal/civisibility/integrations/gotesting/testing.go, internal/civisibility/integrations/gotesting/testing_test.go, internal/civisibility/integrations/manual_api_ddtest.go
This PR adds support for marking tests or suites as unskippable by the Intelligent Test Runner.
- A suite is marked as unskippable if at the top of the file the `//dd:suite.unskippable` comment is found.
- A single test is marked as unskippable if the test function is marked with `//dd:test.unskippable` comment.
The notation was inspired by Orchestrion custom span notation: https://datadoghq.dev/orchestrion/docs/custom-trace/#creating-custom-trace-spans
This is part of the specification for Intelligent Test Runner: https://datadoghq.atlassian.net/wiki/spaces/SDTEST/pages/3123348305/Intelligent+Test+Runner+in+CI+Visibility+Libraries#Unskippable-tests
=> internal/civisibility: add support for unskippable tests and suites

contrib/valyala/fasthttp.v1/fasthttp.go
This PR fixes the memory leak of contrib/valyala/fasthttp.v1 WrapHandler function by moving the initialization of `spanOpts` to be in the closure anonymous function that will return as a fasthttp.RequestHandler instead of WrapHandler function. So it will be garbage collected every time the request handler end.
Fixes #2961
=> contrib/valyala/fasthttp.v1: fix memory leak of spanOpts

profiler/options.go, profiler/profiler.go, profiler/profiler_test.go, profiler/telemetry.go, profiler/upload.go
This PR adds a new bool env `DD_PROFILING_FLUSH_ON_EXIT` in order to abort and upload the current profiling sessions before exiting.
- profiling short lived processes without fine-tuning the period
- profile visibility on the "exit section" of processes and applications
=> profiler: add DD_PROFILING_FLUSH_ON_EXIT to upload current profiles before exiting

ddtrace/tracer/log_test.go, ddtrace/tracer/stats.go, ddtrace/tracer/textmap_test.go, ddtrace/tracer/tracer_test.go
Also move env message to debug as it turns out the assumption that the agent always has an env configured is not correct
Stats msgp is now owned in the agent code so there's no need to generate the stats msgp code here anymore
=> whoops, no need to generate stats msgp anymore

contrib/go-chi/chi.v5/chi_test.go, contrib/go-chi/chi.v5/option.go, contrib/go-chi/chi/chi_test.go, contrib/go-chi/chi/option.go, contrib/internal/httptrace/config.go, contrib/internal/httptrace/httptrace.go, contrib/internal/httptrace/httptrace_test.go
Removes `isServerError` function from go-chi and go-chi.v5 integrations. In the case that the contribs have not been initialized with a custom error checker via `WithStatusError`, they will rely on the error checker from httptrace.
This allows go-chi and go-chi.v5 integrations to be impacted by DD_TRACE_HTTP_SERVER_ERROR_STATUSES.
Noticed the `Test_Config_HttpServerErrorStatuses_FeatureFlagCustom` system test was failing for go-chi ([link](https://github.com/DataDog/system-tests/blob/main/tests/test_config_consistency.py#L45-L60))
=> contrib/go-chi: Apply DD_TRACE_HTTP_SERVER_ERROR_STATUSES 

ddtrace/tracer/option.go, ddtrace/tracer/tracer.go, internal/appsec/appsec.go, internal/appsec/config/config.go, internal/appsec/remoteconfig_test.go, internal/appsec/telemetry.go
Adds a new tracer start option that allows to explicitly enable or disable appsec, overriding the default activation criteria (from `DD_APPSEC_ENABLED` and remote configuration).
There is a use-case in https://github.com/DataDog/datadog-agent where a tracer is started but AppSec features are undesirable (and unsupported) in this context. Explicitly disabling AppSec features allows to avoid emitting an AppSec startup error message when the agent's environment includes `DD_APPSEC_ENABLED=true`.
=> appsec: add tracer start option for appsec enablement

ddtrace/tracer/option.go, ddtrace/tracer/option_test.go
Prevents overrides to `c.httpClient` if it has been set by customers; even if the agent URL points to a unix socket
For my software to work I had to update the HTTP client of my tracer. Using the latest agent and tracer and letting other settings as default, the HTTP client override didn't work. 
This is because:
1.  Newer agent creates the socket by default (https://github.com/DataDog/datadog-agent/pull/26969)
2. As the [documentation](https://github.com/DataDog/dd-trace-go/blob/a8bb4691781d3bdbf8243153ea3e1192a148fe0c/internal/agent.go#L24-L32) states, if the socket file exists and no env var is set, the socket will be used as the agent URL
3. If the socket is used as the agent URL, [we override `c.httpClient` regardless of whether it has been previously …
=> fix(options): Don't override c.httpClient if it is set via the options

.github/workflows/v2-nightly.yml
Add missing permissions for running v2 CI jobs.
=> fix(.github/workflows): add permissions to codeql-v2 job

internal/version/version.go
Updates `main` to the next pre-release version for releasing `v1.70.0`.
=> chore: bump version.go to v1.71.0-dev

internal/civisibility/utils/git.go
Ensures we have read permissions to the git folder to be able to extract all the information we need in CI Visibility mode.
Depending of the CI configuration, running git command could lead to `detected dubious ownership in repository` error described here:
https://confluence.atlassian.com/bbkb/git-command-returns-fatal-error-about-the-repository-being-owned-by-someone-else-1167744132.html
=> internal/civisibility: ensure git permissions before extracting git info

.github/workflows/system-tests.yml
Enables weblog tests from the`TRACING_CONFIG_SCENARIOS` scenarios to run in CI against all dd-trace-go PRs. See: [link](https://github.com/DataDog/system-tests/blob/main/scenario_groups.yml#L42-L46)
A [recent PR](https://github.com/DataDog/dd-trace-go/pull/2946) caused one of the weblogs (go-chi) to fail one of the system-tests(`Test_Config_HttpServerErrorStatuses_FeatureFlagCustom`) covered by `TRACING_CONFIG_SCENARIOS`, but the issue was left undetected because the test was not run against the PR in CI.
=> CI: Add TRACING_CONFIG_SCENARIOS to system-tests.yml

ddtrace/ddtrace.go, ddtrace/tracer/context_test.go, ddtrace/tracer/spancontext.go
- Changes the (spanContext).SpanLinks() implementation to return a copy of a slice instead of the slice itself
- Removes (spanContext).SetLinks() method
- nit: Clean up a test
Ensure users cannot modify spanContext
=> ddtrace/tracer: Ensure SpanLink access is safe from corruption

internal/civisibility/integrations/gotesting/instrumentation.go
Fix `sync.RWMutex` usages.
It was wrong, the mutex was being used only on read mode.
=> internal/civisibility: fix RWMutex usages

ddtrace/tracer/option_test.go
Adds `t.Skip` to reduce friction for other teams while we fix the underlying issue.
=> chore(ddtrace/tracer): skip TestTracerOptionsDefaults/dogstatsd

internal/civisibility/constants/tags.go, internal/civisibility/utils/environmentTags.go
This PR sets a tag to let the ci visibility backend know if the DD_SERVICE value was provided by the user or auto-generated.
This required by the backend.
=> internal/civisibility: specify if the user is setting the DD_SERVICE

ddtrace/example_test.go
Add an example so customers know they can listen for SIGTERM and shutdown the tracer to avoid lost data.
I debated adding more complexity here like enforcing a timeout, or supporting a context cancellation so this go routine doesn't just hang around forever but that seems like something that "can be left as an exercise to the reader" perhaps? If others feel strongly I'm happy to update this example to be more in depth though.
See #2976 for some motivation, at some point we may attach this sort of listener automatically but there doesn't seem to be a clean way to do so currently without risking altering some customer application behavior.
=> Add example listening for sigterm to docs (APMSP-15340)

CODEOWNERS
Adds `apm-go` as owner of everything along each team. This is temporary while `v2` isn't GA.
Per the new guild guidelines for PRs, we want our internal contributors to make any new code changes to both v1 and v2.
=> feat(CODEOWNERS): new policy, all PRs require apm-go approval

ddtrace/tracer/option.go, ddtrace/tracer/option_test.go
It's a follow-up from #2931, that introduced a new behaviour to make sure metrics are reported properly by overriding any user-provided `host:port` address using the agent-reported StatsD port from the agent `/info` endpoint.
Fixing a bug causing runtime metrics to not be reported when using `WithDogstatsdAddr` with UDS paths.
=> fix(ddtrace/tracer): refactor DogStatsD URL resolution using agent-reported StatsD port

ddtrace/tracer/stats.go, ddtrace/tracer/stats_test.go, ddtrace/tracer/tracer.go, ddtrace/tracer/tracer_test.go
Porting this PR https://github.com/DataDog/dd-trace-go/pull/3007 to v2
=> propagate statsd client to stats concentrator

go.mod, go.sum, internal/apps/go.mod, internal/apps/go.sum, internal/exectracetest/go.mod, internal/exectracetest/go.sum
go.mod: Use explicit go-runtime-metrics-internal version
As suggested in
https://github.com/DataDog/go-runtime-metrics-internal/issues/10
the go-runtime-metrics-internal has been tagged with explicit versions.
This should have already fixed #3011 as future `go get -u ./...`
invocations should resolve to v0.0.3 (same as v0.0.1). See the issue
above for more details.
Fixes #3011
Fix the issue.
=> go.mod: Use explicit go-runtime-metrics-internal version

internal/telemetry/utils.go
Currently when you import `dd-trace-go`, you end up having the "testing" std package in your final binary. Not amazing.
This PR fixes this issue by removing the problematic import in `internal/telemetry/utils.go`, and replacing the usage with an interface.
If you have a better idea for `Errorfer` I'm definitely open to it.
I believe this would be fine if it was in a public API, but this is in an internal package so this change should be fine regarding exported API changes.
=> internal/telemetry: remove "testing" import from `internal/telemetry/utils.go`

ddtrace/tracer/stats.go, ddtrace/tracer/stats_test.go, ddtrace/tracer/tracer.go, ddtrace/tracer/tracer_test.go
Propagate statsd client to stats concentrator so we can emit health metrics about stats.
Turns out these stats were never actually being written as the client was always a noopClient
=> Propagate statsd client to stats concentrator (APMSP-1631)

contrib/google.golang.org/api/api_test.go, contrib/net/http/option.go, contrib/net/http/roundtripper_test.go
By default, query string is not collected on http client spans.
Without the ability to obfuscate the query string (like what DD_TRACE_OBFUSCATION_QUERY_STRING_REGEXP does for http server spans), collecting it by default poses a security risk. Thus, we are disabling it by default, allowing users to opt-in to the feature if they so choose.
=> contrib/net/http: Make DD_TRACE_HTTP_CLIENT_TAG_QUERY_STRING false by default

contrib/google.golang.org/api/api_test.go, contrib/net/http/option.go, contrib/net/http/roundtripper_test.go
By default, query string is not collected on http client spans.
Without the ability to obfuscate the query string (like what DD_TRACE_OBFUSCATION_QUERY_STRING_REGEXP does for http server spans), collecting it by default poses a security risk. Thus, we are disabling it by default, allowing users to opt-in to the feature if they so choose.
=> [v2] contrib/net/http: Make DD_TRACE_HTTP_CLIENT_TAG_QUERY_STRING false by default

contrib/log/slog/slog_test.go
Use slogtest to ensure that WrapHandler is behaving correctly. This was already the case, so this patch is merely adding additional confidence in the correctness.
I didn't know about the slogtest package and just discovered it while looking into something else. So I figured I check if our implementation passes the tests.
=> contrib/log/slog: test with slogtest

internal/version/version.go
Updates version to `1.72.0-dev`.
=> chore: update main version to 1.72.0-dev

ddtrace/tracer/option.go, ddtrace/tracer/tracer.go
This PR disables the agent features request and the remote configuration if the tracer was loaded in CI Visibility agentless mode.
**v1:** https://github.com/DataDog/dd-trace-go/pull/3026
Ticket: SDTEST-1321
In agentless mode we don't use an agent so those features are not available.
=> [v2] fix(ddtrace/tracer): Disable agent features and remote configuration in CI Visibility agentless mode

ddtrace/tracer/option.go, ddtrace/tracer/tracer.go
This PR disables the agent features request and the remote configuration if the tracer was loaded in CI Visibility agentless mode.
**v2:** https://github.com/DataDog/dd-trace-go/pull/3027
Ticket: SDTEST-1321
In agentless mode we don't use an agent so those features are not available.
=> fix(ddtrace/tracer): Disable agent features and remote configuration in CI Visibility agentless mode

internal/civisibility/utils/net/settings_api.go, internal/civisibility/utils/telemetry/telemetry.go
This PR adds a new telemetry metric for the auto test retries feature.
**v2**: https://github.com/DataDog/dd-trace-go/pull/3029
Ticket: SDTEST-1296
This metric was missing.
=> internal/civisibility: Add auto test retries telemetry metric

internal/civisibility/utils/net/settings_api.go, internal/civisibility/utils/telemetry/telemetry.go
This PR adds a new telemetry metric for the auto test retries feature.
**v1**: https://github.com/DataDog/dd-trace-go/pull/3028
Ticket: SDTEST-1296
This metric was missing.
=> [v2] internal/civisibility: Add auto test retries telemetry metric

contrib/99designs/gqlgen/tracer.go, contrib/google.golang.org/grpc/appsec.go, contrib/graph-gophers/graphql-go/graphql.go, contrib/graphql-go/graphql/graphql.go, internal/appsec/emitter/graphqlsec/request.go, internal/appsec/emitter/grpcsec/grpc.go, internal/appsec/emitter/httpsec/http.go, internal/appsec/emitter/trace/service_entry_span.go, internal/appsec/emitter/waf/context.go
This PR removes a temporary storage for span tags and instead use directly a TagSetter (e.g. a span) to store them. 
Blocks #3033 
=> appsec: stop storing span tags, directly call span.SetTag

internal/contrib/telemetrytest/telemetry_test.go
Allows other path separators to prevent flaking on Windows OS.
Test was flaking in CI due to different results from Windows vs other OS's.
=> internal/contrib: fix TestTelemetryEnabled flakiness on Windows

ddtrace/tracer/transport.go, ddtrace/tracer/transport_test.go, internal/statsdtest/statsdtest.go
Reports a `datadogtracer.api.errors` health metric when httpClient request to submit a trace payload fails or has status code >= 400, with a tag `reason` that describes why the request failed.
More data to correlated dropped traces (datadog.tracer.traces_dropped) with failed submission attempt.
=> [v2] ddtrace/tracer: report datadog.tracer.api.errors health metric

ddtrace/tracer/metrics_test.go, ddtrace/tracer/writer.go, ddtrace/tracer/writer_test.go
Reports the number of traces in the queue at a specified interval.
NOTE: This implementation does not currently differentiate between true "traces" and partial trace "chunks"
Report more data from our health metrics
=> [v2] ddtrace/tracer: Report datadog.tracer.queue.enqueued.traces as health metric

internal/remoteconfig/remoteconfig.go
Introduces a new env var called `DD_REMOTE_CONFIGURATION_ENABLED` to disable remote config client side. 
Closes #3060 
=> internal/remoteconfig: support for DD_REMOTE_CONFIGURATION_ENABLED

internal/civisibility/utils/environmentTags.go, internal/civisibility/utils/environmentTags_test.go
This PR improves the mutability over the environment tags, avoiding to re-running the Cmds (git commands) after adding new tags and avoiding race conditions.
Same PR for v2-dev: https://github.com/DataDog/dd-trace-go/pull/3077
Currently if we add a new tag we end up by re running the git command to create a new map, this PR fixes this issue.
=> (fix) internal/civisibility/utils: improve environment tags mutability

internal/civisibility/utils/environmentTags.go, internal/civisibility/utils/environmentTags_test.go
This PR improves the mutability over the environment tags, avoiding to re-running the Cmds (git commands) after adding new tags and avoiding race conditions.
Same PR for main: https://github.com/DataDog/dd-trace-go/pull/3076
Currently if we add a new tag we end up by re running the git command to create a new map, this PR fixes this issue.
=> (fix) internal/civisibility/utils: improve environment tags mutability (v2)

ddtrace/opentelemetry/span.go, ddtrace/opentelemetry/span_test.go, ddtrace/tracer/abandonedspans.go, ddtrace/tracer/otel_dd_mappings.go, ddtrace/tracer/slog.go, internal/appsec/appsec.go, internal/appsec/emitter/waf/run.go, internal/civisibility/integrations/civisibility_features.go, internal/log/log.go, internal/telemetry/client.go, internal/telemetry/client_test.go
=> [v2] fix(ddtrace/tracer): avoid tests to fail with error "non-constant format string" from upcoming Go 1.24 release (#3048)

contrib/net/http/get_pattern.go, contrib/net/http/get_pattern_go122.go, contrib/net/http/http.go, contrib/net/http/http_test.go, contrib/net/http/pattern.go, contrib/net/http/pattern_test.go
This PR add support for importing path params into `dd-trace-go/contrib/internal/httptrace` data pipeline as multiple other contribs already do.
In details I did:
* Better coverage for ASM WAF.
* Enabling a big bunch for tests in the system-tests that work with path params
=> contrib/net/http: support for path params from go 1.22 proposal

internal/civisibility/integrations/gotesting/coverage/coverage_writer_test.go, internal/civisibility/utils/net/client.go, internal/civisibility/utils/net/coverage.go, internal/civisibility/utils/net/efd_api.go, internal/civisibility/utils/net/searchcommits_api.go, internal/civisibility/utils/net/sendpackfiles_api.go, internal/civisibility/utils/net/settings_api.go, internal/civisibility/utils/net/skippable.go
This PR add some checks before performing the http requests and also add support for sending code coverage data in a different format.
PR for V2: https://github.com/DataDog/dd-trace-go/pull/3088
I saw some http client response with status code 400 when testing on a Go project without a git repo.
=> (fix) internal/civisibility: add some checks before performing the http requests.

internal/civisibility/integrations/gotesting/coverage/coverage_writer_test.go, internal/civisibility/utils/net/client.go, internal/civisibility/utils/net/coverage.go, internal/civisibility/utils/net/efd_api.go, internal/civisibility/utils/net/searchcommits_api.go, internal/civisibility/utils/net/sendpackfiles_api.go, internal/civisibility/utils/net/settings_api.go, internal/civisibility/utils/net/skippable.go
This PR add some checks before performing the http requests and also add support for sending code coverage data in a different format.
PR for V1: https://github.com/DataDog/dd-trace-go/pull/3087
I saw some http client response with status code 400 when testing on a Go project without a git repo.
=> (fix) internal/civisibility: add some checks before performing the http requests. (V2)

contrib/envoyproxy/go-control-plane/envoy.go, contrib/envoyproxy/go-control-plane/envoy_test.go
This PR fixes an issue that could cause a crash when a response was processed without any corresponding request being received.
This can happen when Envoy fails to send a request headers processing and only send the processing of the response.
Related issue opened in the envoy repo: https://github.com/envoyproxy/envoy/issues/38022
=> contrib/envoyproxy: fix empty request

contrib/jackc/pgx.v5/example_test.go, contrib/labstack/echo.v4/appsec_test.go, internal/utils_test.go
This PR fixes triage issues in the codebase that has been identified by the `go vet` tool.
```text
contrib/labstack/echo.v4/appsec_test.go:274:5: unreachable code
contrib/jackc/pgx.v5/example_test.go:48:1: ExamplePool refers to unknown identifier: Pool
internal/utils_test.go:29:7: the cancel function returned by context.WithTimeout should be called, not discarded, to avoid a context leak
```
=> fix(staticcheck): Fix trivial go vet issues

contrib/envoyproxy/go-control-plane/go.mod, contrib/envoyproxy/go-control-plane/go.sum, contrib/julienschmidt/httprouter/go.mod, go.mod, internal/apps/go.mod, internal/apps/go.sum, internal/setup-smoke-test/go.mod, internal/traceprof/traceproftest/go.mod, internal/traceprof/traceproftest/go.sum, tools/fixmodules/go.mod, tools/fixmodules/go.sum, tools/fixmodules/main.go
The `tools/fixmodules` script is used to fix the modules in the repository recursively, adding replace directives for imports of other modules in the same repository + using the same go version as the root module.
It had a bug where it was injecting some unnecessary replace since to the logic of inspecting go source files and checking import statement was broken. 
=> [v2] tools: fix fixmodules script

internal/civisibility/integrations/gotesting/instrumentation_orchestrion.go, internal/civisibility/integrations/gotesting/testcontroller_test.go, internal/civisibility/integrations/gotesting/testify.go, internal/civisibility/integrations/gotesting/testify_test.go, internal/civisibility/integrations/gotesting/testify_utils_test.go
This PR adds support for testify Suite kind of tests.
**Ticket**: SDTEST-1435
**V1 PR**: https://github.com/DataDog/dd-trace-go/pull/3094
**Note**: This improvements will require a new orchestrion integration to intercept `suite.Run` calls
Example:
```go
....
type USMSuite struct {
suite.Suite
}
func TestUSMSuite(t *testing.T) {
suite.Run(t, new(USMSuite))
}
func (s *USMSuite) TestEnableHTTPMonitoring() {
}
func (s *USMSuite) TestDisableUSM() {
}
....
```
Currently the support lacks the correct identification of the Suite name, Module name and Test source affecting features like Codeowners and Impact Analysis
**From**:
**To**:
=> (feat) internal/civisibility: add support for testify Suites (v2)

internal/civisibility/integrations/gotesting/instrumentation_orchestrion.go, internal/civisibility/integrations/gotesting/testcontroller_test.go, internal/civisibility/integrations/gotesting/testify.go, internal/civisibility/integrations/gotesting/testify_test.go, internal/civisibility/integrations/gotesting/testify_utils_test.go
This PR adds support for testify Suite kind of tests.
**Ticket**: SDTEST-1435
**V2 PR**: https://github.com/DataDog/dd-trace-go/pull/3097
**Note**: This improvement will require a new orchestrion integration to intercept `suite.Run` calls
Example:
```go
....
type USMSuite struct {
suite.Suite
}
func TestUSMSuite(t *testing.T) {
suite.Run(t, new(USMSuite))
}
func (s *USMSuite) TestEnableHTTPMonitoring() {
}
func (s *USMSuite) TestDisableUSM() {
}
....
```
Currently the support lacks the correct identification of the Suite name, Module name and Test source affecting features like Codeowners and Impact Analysis
**From**:
**To**:
=> (feat) internal/civisibility: add support for testify Suites

internal/appsec/emitter/waf/context.go
Change the log of too many Appsec WAF event from Warn to Error.
The log can be sometimes spammy (cf run inside macrobenchmarks). Setting this log to Error can use the deduplication of errors.
=> appsec: change log WAF 'too many event' from Warn to Error

internal/telemetry/client.go
=> internal/telemetry: revert hostname.Get() -> os.Hostname()

contrib/Shopify/sarama/go.mod, contrib/Shopify/sarama/sarama.go, go.work.sum
Pins `Shopify/sarama` to `v1.38.1` using a `replace` directive.
To reduce CI times and noise in smoke tests' logs, we pin `github.com/Shopify/sarama` to `v1.38.1`, the last version released under Shopify’s organization.
Without this, running our smoke tests that rely on `go get -u` tend to run longer due to Go's toolchain mechanism to try to find the right version that fits the import URL. Versions higher than `v1.38.1` use `github.com/IBM/samara` instead.
=> [v2] fix(contrib/Shopify/sarama): pin Shopify/sarama to v1.38.1

contrib/hashicorp/consul/go.mod, contrib/hashicorp/consul/go.sum, contrib/hashicorp/vault/go.mod
Pins `armon/go-metrics` to `v0.4.1` using a `replace` directive.
To reduce CI times and noise in smoke tests' logs, we pin `github.com/armon/go-metrics` to `v0.4.1`, the last version released before it was migirated to Hashicorp's organization.
Without this, running our smoke tests that rely on `go get -u` tend to run longer due to Go's toolchain mechanism to try to find the right version that fits the import URL. Versions higher than `v0.4.1` use `github.com/hashicorp/go-metrics` instead.
=> [v2] fix(contrib/hashicorp/{consul,vault}): pin armon/go-metrics to v0.4.1

.github/workflows/orchestrion.yml
Switches hard-coded branch name in `orchestrion.yml` to be `main`.
=> chore: switch orchestrion CI to refer to main branch

.gitlab/macrobenchmarks.yml
- Add Macro Benchmarks for [Service Extensions](https://datadoghq.atlassian.net/wiki/spaces/SAAL/pages/4270622327/ASM+-+GCP+Services+Extensions).
[This PR](https://github.com/DataDog/benchmarking-platform/pull/124) from Benchmarking Platform merge the changes that adds scenarios for Service Extensions into the [go/go-prof-app](https://github.com/DataDog/benchmarking-platform/tree/go/go-prof-app) branch.
- It also updates the base image name to the new one that includes Envoy.
QA feedbacks on each main commits.
=> Add Service Extensions Macro Benchmarks

ddtrace/tracer/span.go, ddtrace/tracer/tracer.go, ddtrace/tracer/transport.go, instrumentation/httptrace/before_handle.go, instrumentation/instrumentation.go, instrumentation/internal/namingschema/namingschema.go
Fixes multiple regressions on `v2-dev`, resulting on appropriate performance - at par with `main` - in multiple areas.
=> [v2] fix: improved performance on multiple benchmarks

contrib/internal/httptrace/httptrace.go
Adds telemetry for inferred span tracking only if the env var `DD_TRACE_INFERRED_PROXY_SERVICES_ENABLED` is set to true
Track usage of new inferred proxy spans
=> contrib/internal/httptrace: add telemetry for inferred spans

contrib/net/http/orchestrion.client.yml, internal/orchestrion/_integration/aws.v2/base.go
Retrofits #3071 into the orchestrion specification.
This puts automatic instrumentation on par with manual instrumentation.
This is necessary for the upcoming orchestrion system tests to pass.
=> fix(net/http: orchestrion): obfuscate query string parameters when auto-instrumenting

internal/orchestrion/gls.go
Current GLS accessors for V1 and V2 conflict because they use the same slot to store different value types. Renaming those accessors means orchestrion will stop populating the accessors for V2, which will address the crasher reported at https://github.com/DataDog/orchestrion/issues/520
=> fix: use different symbol for orchestrion GLS accessors

ddtrace/tracer/stats.go, ddtrace/tracer/stats_test.go, go.mod
Only fetch the git commit sha when CI visibility is enabled.
Fetching (And therefore initializing) the CI tags here can create subprocesses and incur a performance cost or create SIGCHLD issues. Given this tag only exists when inside CI Visibility we can safely not attach it when CI Visibility is disabled. 
=> tracer/stats: Only get CI tags when CI Visibility is enabled

internal/civisibility/utils/net/client.go, internal/civisibility/utils/net/http.go, internal/civisibility/utils/net/http_test.go
This PR changes the defaults of the CI Visibility http clients, Currently in the worst case scenario the client were blocking the test process up to 60 seconds. This PR reduces this time by changing the constant default values. As a direct impact, this change reduces the time for testing the package.
**V1**: https://github.com/DataDog/dd-trace-go/pull/3134
The current defaults are too large...
=> (fix) internal/civisibility: change http default values and reduce test time (V2)

internal/civisibility/utils/net/client.go, internal/civisibility/utils/net/http.go, internal/civisibility/utils/net/http_test.go
This PR changes the defaults of the CI Visibility http clients, Currently in the worst case scenario the client were blocking the test process up to 60 seconds. This PR reduces this time by changing the constant default values. As a direct impact, this change reduces the time for testing the package.
**V2**: https://github.com/DataDog/dd-trace-go/pull/3135
The current defaults are too large...
=> (fix) internal/civisibility: change http default values and reduce test time.

ddtrace/tracer/textmap.go, ddtrace/tracer/textmap_test.go
Fixes a panic caused by [this line of code](https://github.com/DataDog/dd-trace-go/blob/v1.71.0/ddtrace/tracer/textmap.go#L284): `return extractedCtx.(*spanContext), nil`, when `extractedCtx` is `nil`.
Bug was detected when configuring `DD_TRACE_PROPAGATION_EXTRACT_FIRST=true` and no tracing-related keys are found in carrier. To reproduce this, you can paste the `TestExtractNoHeaders` to the v1.71.0 branch and watch it panic.
Bug was introduced in v1.71.0 as a result of this [PR](https://github.com/DataDog/dd-trace-go/pull/2948).
=> ddtrace/tracer: Fix panic on Extract when DD_TRACE_PROPAGATION_EXTRACT_FIRST=true and no trace headers present

ddtrace/tracer/option.go, ddtrace/tracer/option_test.go
Upon reading the info response from the Agent, we must store the peer_tags internally, which are used for Client-Stats computation.
Client-Side Stats require peer tags aggregation. Agent e2e tests revealed that these were missing.
=> Fix peer tags configuration

.github/actions/add-codeowners/codeowners.sh, .github/actions/dd-ci-upload/action.yml
ports #3118 to v2
Contrib `CODEOWNERS`
Other `CODEOWNERS`
Add `CODEOWNERS` support to v2.
=> [v2] ci: add codeowners to gotestsum report (#3118)

ddtrace/tracer/textmap.go, ddtrace/tracer/textmap_test.go
Cherry-picks commit 2ee7731c7ad9833b771f2b338d640c6c472215de from PR #3128 onto release branch release-v1.71.x
dd-trace-go v1.71.0 crashes on trace context extraction when `DD_TRACE_PROPAGATION_EXTRACT_FIRST` set to `true` and no tracing-related keys are found in carrier, with no workaround other than disabling the feature. 
=> ddtrace/tracer: Fix panic on Extract when DD_TRACE_PROPAGATION_EXTRACT_FIRST=true and no trace headers present [1.71 backport]

ddtrace/tracer/stats.go, ddtrace/tracer/stats_test.go, go.mod
Cherry-picks ec054a5cbf955e0f018ff9d2fb41a63c645558fb from PR #3129 onto release branch release-v1.71.x
CI tags 
We were fetching and initializing CI tags even when CI visibility was disabled, leading to unnecessary subprocesses that impacted performance and could trigger SIGCHLD issues. In this PR, we've ensured that tags are only attached when CI visibility is enabled
=> tracer/stats: Only get CI tags when CI Visibility is enabled [1.71 backport]

ddtrace/tracer/slog.go, ddtrace/tracer/slog_test.go
* Fix the slog handler
This is a complete no-op since these methods are not used currently. This is more of a "see something say something" fix in case this logger becomes load-bearing in the feature, so that the implementation is correct.
=> ddtrace/tracer/slog: fix slog handler

.github/workflows/service-extensions-publish.yml
This PR fixes some issues when publishing manually images of the Service Extension.
- The commit sha selected wasn't properly applied (defaulting to the selected branch everytime)
- The docker push failed when the `set_as_latest` was false? The string "false" was evaluated into the command line thus making the process failing
Publish release/dev/test image manually by triggering the workflow.
This was tested locally by running the workflow with the github CLI.
=> fix: manual publish of Service Extension image

internal/civisibility/utils/net/client.go
This PR fixes backend transactions when CI Visibility is running on a git detached head
V1: [(fix) internal/civisibility: add support for detached heads in civisibility backend transactions](https://github.com/DataDog/dd-trace-go/pull/3157)
Currently no ancillary feature can be enabled on detached heads.
=> (fix) internal/civisibility: add support for detached heads in civisibility backend transactions

.github/workflows/main-branch-tests.yml, .github/workflows/unit-integration-tests.yml
Bumps the version of `golangci-lint` being used in CI to the latest version (`v1.63.4`). We were previously at `v1.59.1`. Also replaces a deprecated function (`fail_on_error`) with its up to date version (`fail_level`).
Linting rules were failing in CI for Go v1.23. The first version of `golangci-lint` that supports v1.23 is `v1.60` ([source](https://github.com/golangci/golangci-lint/issues/4837))
Tested by running `Pull Request Tests` and `Main Branch and Release Tests` pipelines against this branch. `Pull Request Tests` only runs on Go v1.22 (min support version for `dd-trace-go`), while `Main Branch and Release Tests` lints both Go v1.22 and v1.23. `Main Branch and Release Tests` now passes lint:
=> fix: bump version of golangci-lint

contrib/miekg/dns/dns_test.go
Attempt to fix flaky test by using a random port instead of `2020`.
```
Failed
=== RUN   TestExchangeContext
dns_test.go:47: listen udp 127.0.0.1:2020: bind: address already in use
dns_test.go:85: 
Error Trace:	/home/runner/work/dd-trace-go/dd-trace-go/contrib/miekg/dns/dns_test.go:85
Error:      	Received unexpected error:
read udp 127.0.0.1:45449->127.0.0.1:2020: read: connection refused
Test:       	TestExchangeContext
dns_test.go:53: 
Error Trace:	/home/runner/work/dd-trace-go/dd-trace-go/contrib/miekg/dns/dns_test.go:53
/home/runner/work/dd-trace-go/dd-trace-go/contrib/miekg/dns/dns_test.go:90
Error:      	Received unexpected error:
dns: server not started
Test:       	TestExchangeContext
--- FAIL: TestExchangeContext (10.05s)
```
In addition, it changes the way the local server is …
=> contrib/miekg/dns: use random port for test

internal/civisibility/integrations/gotesting/coverage/test_coverage.go, internal/civisibility/integrations/gotesting/coverage/test_coverage_test.go
This PR fixes a race condition in TestCollectCoverageAfterTestExecution due removing the file inside a goroutine
**V2**: https://github.com/DataDog/dd-trace-go/pull/3170
The test was a flaky test
=> (fix) internal/civisibility/coverage: [APMLP-379] fix TestCollectCoverageAfterTestExecution flaky test

internal/civisibility/integrations/gotesting/coverage/test_coverage.go, internal/civisibility/integrations/gotesting/coverage/test_coverage_test.go
This PR fixes a race condition in TestCollectCoverageAfterTestExecution due removing the file inside a goroutine
**V1**: https://github.com/DataDog/dd-trace-go/pull/3169
The test was a flaky test
=> (fix) internal/civisibility/coverage: [APMLP-379] fix TestCollectCoverageAfterTestExecution flaky test - v2

ddtrace/tracer/metrics_test.go
Increases the wait time for reporting metrics in `TestTracerMetrics` from `100` milliseconds to `500` milliseconds. 
The test was flaking, leading to intermittent failures on Windows. The issue was caused because the `tg.Wait()` function was not waiting long enough for metrics to be reported. Running the test `5000` times on both Windows and Mac succeeded.
The `Wait()` function returns either when the time runs out or when `n` metrics have been reported. When running tests on MacOS, which was previously succeeding, there should be no change in runtime. On Windows, we might see a slight increase in time taken to run the test, as it was previously taking more than `100` milliseconds to fetch all expected metrics. This change does not impact anything outside of testing code.
Unsure? Have a …
=> ddtrace/tracer: fix flake in TestTracerMetrics

internal/civisibility/integrations/gotesting/reflections.go, internal/civisibility/integrations/manual_api_ddtest.go, internal/civisibility/integrations/manual_api_mocktracer_test.go
This PR fixes Test Visibility on Go 1.24
**V2**: [(fix) internal/civisibility: Fix test visibility on Go 1.24 - v2](https://github.com/DataDog/dd-trace-go/pull/3180)
Test visibility instrumentation depends on some internal Go fields. Go 1.24 came with some changes on those internals, this PR fixes that.
- This PR also fixes an existing bug we had by casting a `sync.Mutex` to `sync.RWMutex`
=> (fix) internal/civisibility: Fix test visibility on Go 1.24

internal/civisibility/constants/tags.go, internal/civisibility/integrations/civisibility_features.go, internal/civisibility/integrations/gotesting/testcontroller_test.go
This PR implements the feature to tag tests with the capabilities of the library
**V2**: [(feat) internal/civisibility: add capabilities tagging - V2](https://github.com/DataDog/dd-trace-go/pull/3183)
https://datadoghq.atlassian.net/wiki/spaces/SDTEST/pages/4713481036/Libraries+capabilities+tagging
=> (feat) internal/civisibility: add capabilities tagging

.github/workflows/apps/gen_supported_versions_doc.go
Modified the `GetPackages` method in #3078, small fix to reflect the new method return type.
=> internal: update gen supported versions workflow for v2

.github/workflows/orchestrion.yml, internal/orchestrion/_integration/go-elasticsearch/v6.go, internal/orchestrion/_integration/go-elasticsearch/v7.go, internal/orchestrion/_integration/go-elasticsearch/v8.go, internal/orchestrion/_integration/internal/containers/aws-dynamodb.go, internal/orchestrion/_integration/internal/containers/kafka.go, internal/orchestrion/_integration/internal/containers/redis.go, internal/orchestrion/_integration/pgx/pgx.go, internal/orchestrion/_integration/vault/vault.go
This aims to avoid having image pull times have to fit within the tests timeout, and hopefully will reduce flakiness.
=> internal/orchestrion/_integration: pull container images before running tests

internal/orchestrion/_integration/go-redis.v0/go-redis.go, internal/orchestrion/_integration/go-redis.v7/go-redis.go, internal/orchestrion/_integration/go-redis.v8/go-redis.go, internal/orchestrion/_integration/go-redis.v9/go-redis.go
There are frequent flakes on these tests caused by networking errors that typically arise from the server not being completely ready before the tests start. To alleviate this issue, we now wait for a successful ping during the setup phase to make sure we have a valid client before proceeding to tests.
=> internal/orchestrion/_integration: go-redis tests now wait for successful Ping

.github/workflows/orchestrion.yml
This is necessary to safely operate a REDIS server, as it will easily trigger the OOM reaper under tight memory conditions (often the case on CI machines...), but these are artificial because the process maps for fork children is copy-on-write, and should be much leaner than they appear to be. Hopefully this reduces/removes flakes.
=> internal/orchestrion/_integration: enable vm.overcommit_memory

.github/workflows/unit-integration-tests.yml
Bumps the version of `golangci-lint` being used to be the latest version.
The earliest version of golangci-lint to support Go v1.24 is [v1.64](https://github.com/golangci/golangci-lint/issues/5225), whereas we were previously at v1.63. To prevent failures on the main branch, we should upgrade the linter.
=> [go1.24 support] bump golangcilint

appsec/appsec.go, appsec/appsec_test.go, ddtrace/tracer/option.go, ddtrace/tracer/span.go, instrumentation/appsec/emitter/waf/addresses/addresses.go, instrumentation/appsec/emitter/waf/addresses/builder.go, internal/appsec/emitter/usersec/user.go, internal/appsec/listener/usersec/usec.go
Replaced the previous functions for login success and failure tracking with the new standard API that works off user login, and not just user ID.
This is the V2 port of #3192; except deprecated APIs were removed.
=> appsec: update ATO SDK

internal/newtelemetry/client_test.go, internal/newtelemetry/internal/mapper/default.go
Rework the order we decide which heartbeat to send so we don't need to set config values that would send the wrong heartbeat in case of a flake
Signed-off-by: Eliott Bouhana <eliott.bouhana@datadoghq.com>
=> internal/newtelemetry: reduce flakiness of the heartbeat

contrib/net/http/internal/wrap/roundtrip.go, contrib/net/http/roundtripper_test.go
The span was left un-finished and hence was missing from the trace at the end.
=> fix(net/http): finish the request span when RASP blocking triggers

CODEOWNERS, civisibility/linker.go, internal/civisibility/integrations/gotesting/instrumentation.go
This PR adds:
**V1**: [civisibility: add civisibility folder and fix a race condition](https://github.com/DataDog/dd-trace-go/pull/3235)
I'm working on a shim layer in dd-go to be able to instrument tests using the test optimization product.
=> civisibility: add `civisibility` folder and fix a race condition - v2

ddtrace/tracer/span.go, ddtrace/tracer/util.go, ddtrace/tracer/util_test.go, internal/utils.go, internal/utils_test.go
This PR promotes the helper `toFloat64` from the tracer to an internal method by moving it to `internal/utils.go`
This will be used to get data that is currently used as span metric to telemetry metrics
=> internal: promote toFloat64 from ddtrace/tracer

internal/civisibility/integrations/gotesting/orchestrion.yml
This PR adds the missing orchestrion integration for the testify `suite.Run` function. Improving the visibility of testify suites.
V1: [(feat) internal/civisibility: adds the orchestrion integration for testify suite.Run function](https://github.com/DataDog/dd-trace-go/pull/3247)
Before:
After:
Part of the work was done before, but we were missing the orchestrion part.
=> (feat) internal/civisibility: adds the orchestrion integration for testify suite.Run function v2

internal/civisibility/integrations/gotesting/orchestrion.yml
This PR adds the missing orchestrion integration for the testify `suite.Run` function. Improving the visibility of testify suites.
V1: [(feat) internal/civisibility: adds the orchestrion integration for testify suite.Run function v2](https://github.com/DataDog/dd-trace-go/pull/3248)
Before:
After:
Part of the work was done before, but we were missing the orchestrion part.
=> (feat) internal/civisibility: adds the orchestrion integration for testify suite.Run function

contrib/99designs/gqlgen/appsec_test.go, instrumentation/appsec/dyngo/operation.go, instrumentation/appsec/trace/service_entry_span.go, instrumentation/appsec/trace/span.go
The GraphQL subscription propagates a `nil` span to avoid creating an indefinitely long-running span. This results in a nil-panic later on as tags are being set on this.
To address this, override the `TagSetter` with a `NoopTagSetter` to avoid dealing with nil checks everywhere.
Added a subscriptions test on the gqlgen contrib that I used to validate the panic no longer triggers.
=> fix(appsec/gqlgen): recovered from an unexpected panic from an event listener

internal/civisibility/constants/env.go, internal/civisibility/integrations/manual_api_ddtestsession.go, internal/civisibility/utils/telemetry/telemetry.go, internal/civisibility/utils/telemetry/telemetry_count.go
This PR adds the `test_session` telemetry metric to the test optimization product.
**V2**: [(feat) internal/civisibility: adds the test_session telemetry metric - v2](https://github.com/DataDog/dd-trace-go/pull/3269)
The metric was missing
=> (feat) internal/civisibility: adds the `test_session` telemetry metric

internal/civisibility/constants/env.go, internal/civisibility/integrations/manual_api_ddtestsession.go, internal/civisibility/utils/telemetry/telemetry.go, internal/civisibility/utils/telemetry/telemetry_count.go
This PR adds the `test_session` telemetry metric to the test optimization product.
**V1**: [(feat) internal/civisibility: adds the test_session telemetry metric](https://github.com/DataDog/dd-trace-go/pull/3268)
The metric was missing
=> (feat) internal/civisibility: adds the test_session telemetry metric - v2

internal/version/version.go
Sets the version to `v1.74.0-dev` after cutting `v1.73.0` release branch.
=> chore: bump version to v1.74.0-dev

datastreams/options/options.go, internal/datastreams/pathway_test.go, internal/datastreams/payload.go, internal/datastreams/payload_msgp.go, internal/datastreams/processor.go, internal/datastreams/processor_test.go, internal/datastreams/transport_test.go
=> Piotr wolski/2.0 service names

instrumentation/packages.go
Fix Rueidis test.
<details><summary>error</summary>
```log
go run github.com/DataDog/orchestrion go test ./rueidis/...
INFO:ddapm_test_agent.agent:Trace request stall seconds setting set to 0.0.
WARNING:ddapm_test_agent.agent:default snapshot directory '/home/ubuntu/workspace/dd-trace-go/internal/orchestrion/_integration/rueidis/snapshots' does not exist or is not readable. Snapshotting will not work.
--- FAIL: Test (5.25s)
agent.go:67: Starting /home/ubuntu/.pyenv/shims/ddapm-test-agent on port 38227
generated_test.go:19: Running setup
docker.go:1392: Failed to get image auth for https://index.docker.io/v1/. Setting empty credentials for the image: redis:7-alpine. Error is: credentials not found in native keychain
lifecycle.go:77: 🐳 Creating container for image redis:7-alpine …
```
=> Fix Rueidis test

internal/civisibility/integrations/civisibility_features.go, internal/civisibility/integrations/gotesting/testcontroller_test.go, internal/civisibility/utils/net/client.go, internal/civisibility/utils/net/test_management_tests_api.go
This PR changes the way the attempt_to_fix workflow works following the v2 spec.
**V2**: [(feat) internal/civisibility: add support for attempt_to_fix v2 workflow - v2](https://github.com/DataDog/dd-trace-go/pull/3289)
https://datadoghq.atlassian.net/wiki/spaces/SDTEST/pages/4714201218/Flaky+test+management+flow
=> (feat) internal/civisibility: add support for attempt_to_fix v2 workflow

internal/civisibility/integrations/civisibility_features.go, internal/civisibility/integrations/gotesting/testcontroller_test.go, internal/civisibility/utils/net/client.go, internal/civisibility/utils/net/test_management_tests_api.go
This PR changes the way the attempt_to_fix workflow works following the v2 spec.
**V1**: [(feat) internal/civisibility: add support for attempt_to_fix v2 workflow](https://github.com/DataDog/dd-trace-go/pull/3288)
https://datadoghq.atlassian.net/wiki/spaces/SDTEST/pages/4714201218/Flaky+test+management+flow
=> (feat) internal/civisibility: add support for attempt_to_fix v2 workflow - v2

.github/ISSUE_TEMPLATE/config.yml
Adds a catch-all "Other Discussion (Low Priority)" option to our issue creation modal.
Allow people to ask questions about APIs or give other feedback easily. See [2025-03-12 guild meeting notes](https://docs.google.com/document/d/1YvhcWdYWwXI51hlMyjx1Jr4kORKtdzxbc0L1Pk9SKLw/edit?tab=t.0#task=SjZ5UYmG_uyR9Hyh).
=> gh issue template: add other discussion option

internal/civisibility/utils/git.go
This PR changes the way we extract the source root using git.
From:  `git rev-parse --absolute-git-dir`
To: `git rev-parse --show-toplevel` 
V1: [(fix) internal/civisibility: Fix git command to extract the source root](https://github.com/DataDog/dd-trace-go/pull/3306)
The current `--absolute-git-dir` doesn't work on submodules nor git worktrees
`show-toplevel` fixes that.
>--show-toplevel
Show the (by default, absolute) path of the top-level directory of the working tree. If there is no working tree, report an error.
=> (fix) internal/civisibility: Fix git command to extract the source root - v2

internal/telemetry/api.go, internal/telemetry/client.go, internal/telemetry/globalclient.go, internal/telemetry/telemetrytest/mock.go, internal/telemetry/telemetrytest/record.go
=> internal/telemetry: add support for submitting values at every flush

ddtrace/tracer/span.go, ddtrace/tracer/spancontext.go, ddtrace/tracer/tracer.go
- Added mutex locks to ensure safe concurrent access to span context and trace data.
- Replaced atomic operations with mutexes for error counting and sampling priority management.
- Introduced new methods for keeping and dropping spans to encapsulate logic and improve readability.
=> refactor(ddtrace/tracer): improve concurrency handling and clean up span context management

.github/workflows/v2-nightly.yml
Fixes broken `v2 nightly` workflow execution by using the right argument for branch ref.
=> fix(.github/workflows): update branch reference in nightly workflow configuration

.github/actions/dd-ci-upload/action.yml, .github/actions/setup-go/action.yml, .github/dependabot.yml
Followed up on https://github.com/DataDog/dd-trace-go/pull/3146
- Composite actions under `.github/actions/*` are not pinned
- Dependabot is only configured to scanned `.github/workflows` 
- Pin actions under `.github/actions/*`
- Configure Dependabot to scan composite actions
=> ci: Pin composite actions SHA

contrib/envoyproxy/go-control-plane/cmd/serviceextensions/main.go, contrib/envoyproxy/go-control-plane/envoy.go, contrib/envoyproxy/go-control-plane/envoy_test.go
This PR adds change the default component tag from the envoy proxy integration from `envoyproxy/go-control-plane` to `gcp-service-extension` when the grpc server register the envoy integration as a GCP Service Extension.
This change should actually only affect the `serviceextension` docker image. 
Possibility to differentiate an installation from the Envoy integration and from the GCP Service Extension docker image.
=> appsec: add GCP Service Extension component tag

internal/appsec/listener/waf/tags.go, internal/appsec/listener/waf/tags_test.go
Fix truncation span tags logic. Current truncation span tags look like `_dd.appsec.truncated.1: [100 2000 333]` while the key should be `_dd.appsec.truncated.string_length` and the value should be the maximum of the list.
https://docs.google.com/document/d/1D4hkC0jwwUyeo0hEQgyKP54kM1LZU98GL8MaP60tQrA/edit?pli=1&tab=t.0
=> internal/appsec: fix truncation span tags

ddtrace/tracer/span.go, ddtrace/tracer/span_test.go, ddtrace/tracer/spancontext_test.go
This PR adds a sentinel value to ensure that calling `Finish` on any given span will only trigger the finishing flow once.
A potential source of data races is when a user misuses the tracer, as finishing the same span multiple times by calling `Finish` more than once, concurrently or serially in a tight loop.
=> [v2] fix: implement single-call enforcement for Span.Finish

.gitlab/macrobenchmarks.yml
Adds a new macrobenchmark configuration that enables only tracing and runtime metrics.
We are investigating turning on runtime metrics by default. This parallel macrobenchmark configuration will help us understand the relative performance overhead of enabling the feature, so we can ensure that the feature overhead is acceptable.
=> chore: add tracing macrobenchmark with runtime metrics enabled

profiler/profiler.go
(cherry picked from commit e45f665a4ebb9027a9ac79bf01dbf0699ef753af)
v2-dev equivalent of https://github.com/DataDog/dd-trace-go/pull/3304
--- 
This PR makes sure the completed profiles list is cleared before re-using it. The goal is to release the pointers to old profiles to the garbage collector instead of keeping them reachable during the new profiling loop.
This is especially important when execution-trace is enabled because this profile type is not collected at every run of the loop, meaning that you can have old profiles remaining in the underlying array for multiple profiling cycles.
=> profiler: clear old completed list before re-using it

CODEOWNERS
This PR puts all go.mod related files under the same banner to cope with v2 large number of modules ans changes related to this that will happen on each small dependency upgrade to the main module.
Guild meeing decision: Currently any dependency upgrade of the main module require a whole lot of approval with should not be feasble in the long run:
=> CODEOWNERS: broaden go.mod/go.sum statement to **/go.mod, **/go.sum, go.work and go.work.sum files

internal/civisibility/constants/env.go, internal/civisibility/utils/codeowners.go, internal/civisibility/utils/environmentTags.go, internal/civisibility/utils/file_environmental_data.go, internal/civisibility/utils/file_environmental_data_test.go
V2: [(fix) internal/civisibility: add support for file environmental data - v2](https://github.com/DataDog/dd-trace-go/pull/3321)
This pull request introduces significant changes to handle environmental data more effectively in the CI visibility module. The changes include adding a new environment variable, refactoring the code to improve the handling of `CODEOWNERS` files, and implementing functions to read, apply, and write environmental data.
* Added a new environment variable `CIVisibilityEnvironmentDataFilePath` to store the path to the environmental data file (`internal/civisibility/constants/env.go`).
* Implemented functions to read and apply environmental data from a file, including `getEnvironmentalData`, `applyEnvironmentalDataIfRequired`, and `writeEnvironmentalDataToFile` …
=> (feat) internal/civisibility: add support for file environmental data

ddtrace/tracer/tracer.go
This change the language reported to be `go` instead of `golang` to be coherent with the RFC and the telemetry module.
=> fix(service-discovery): report `go` instead of `golang`

contrib/graphql-go/graphql/graphql_test.go, contrib/internal/graphql/graphql.go, contrib/internal/graphql/graphql_test.go
Fix typo in the graphql span events (the correct name is `locations`, not `location`).
=> contrib/internal/graphql: rename location -> locations

go.work.sum, internal/orchestrion/_integration/internal/agent/agent.go, internal/orchestrion/_integration/internal/agent/apmtestagent.go, internal/orchestrion/_integration/internal/agent/apmtestagent_test.go
There is a race condition on the port selection for starting the ddapm-test-agent service; as this cannot be done atomically. This PR adds a special condition to wait until the agent is ready to serve (or fails to start) before returning; which allows fixing this race.
=> chore(orchestrion/integration): fix race on ddapm-test-agent port

ddtrace/tracer/noop.go, ddtrace/tracer/tracer_test.go, instrumentation/httptrace/httptrace_test.go
=> tracer: Log a warning on NoopTracer.StartSpan() (#2991)

contrib/log/slog/orchestrion.yml, internal/orchestrion/_integration/slog/slog.go
contrib/log/slog: fix orchestrion aspect by changing the aspect to instrument library-side.
We introduced a bug in https://github.com/DataDog/dd-trace-go/pull/3376 that triggered the following error:
```
<generated>:4: __dd_slogtrace_WrapHandler redeclared in this block
<generated>:1[/tmp/go-build1833941632/b861/orchestrion/src/cloud.google.com/go/compute/metadata/metadata.go:894:6]: other declaration of __dd_slogtrace_WrapHandler
exit status 2
<generated>:4: __dd_slogtrace_WrapHandler redeclared in this block
<generated>:1[/tmp/go-build1833941632/b876/orchestrion/src/github.com/googleapis/gax-go/v2/internallog/internal/internal.go:154:6]: other declaration of __dd_slogtrace_WrapHandler
exit status 2
✖  confluent-kafka-go.v1 (12.552s) (-test.shuffle 1743754855488201333)
```
Unsure? Have a …
=> contrib/log/slog: fix orchestrion aspect

internal/civisibility/integrations/gotesting/testcontroller_test.go
This fixes the impacted tests test by using two well known shas, allowing us to have a deterministic git diff in every run.
Currently it depends on a sha from another branch (v2-dev) and the current sha, so the git diff would behave different in every run (different current shas while the git history increases).
=> (fix) internal/civisibility: impacted tests test

.github/workflows/orchestrion.yml
This would prevent the `go.mod` file from becoming out-of-sync with the `go.work` file, resulting in subsequent failures...
=> orchestrion/CI: prevent go mod edit from changing go directive

internal/civisibility/constants/test_tags.go, internal/civisibility/integrations/gotesting/instrumentation.go, internal/civisibility/integrations/gotesting/instrumentation_orchestrion.go, internal/civisibility/integrations/gotesting/testcontroller_test.go, internal/civisibility/integrations/gotesting/testing.go, internal/civisibility/integrations/gotesting/testingT.go
This pull request introduces several enhancements and refactors to the test instrumentation and tagging logic within the `internal/civisibility` package. The main changes include the addition of new constants for retry reasons, refactoring of metadata propagation and tagging logic, and updates to test cases to reflect the new retry reasons.
* **New Constants for Retry Reasons:**
* Added new constants to represent different retry reasons such as `attempt_to_fix`, `early_flake_detection`, `auto_test_retry`, and `unknown`. (`internal/civisibility/constants/test_tags.go`)
* **Refactoring Metadata Propagation and Tagging Logic:**
* Refactored the `instrumentTestingTFunc` function to use a new helper function `propagateTestExecutionMetadataFlags` for propagating metadata flags and …
=> (feat) internal/civisibility: Improve additional features integrations.

instrumentation/appsec/emitter/waf/addresses/rasp_rule_type.go, internal/appsec/appsec.go, internal/appsec/config/config.go, internal/appsec/emitter/waf/metrics.go, internal/appsec/listener/waf/tags.go, internal/appsec/remoteconfig.go, internal/appsec/remoteconfig_test.go, internal/appsec/telemetry.go, internal/appsec/telemetry_nocgo.go, internal/appsec/waf_test.go
=> internal/appsec: rework appsec telemetry

.github/pull_request_template.md
Removing the `v2-dev` part of the checklist for Pull Requests
V2 has been merged to main and does not require a matching PR anymore.
=> chore: remove v2 from pull request template

internal/civisibility/integrations/manual_api_ddtest.go, internal/civisibility/integrations/manual_api_ddtestmodule.go, internal/civisibility/integrations/manual_api_ddtestsuite.go
This PR fixes a race condition due to using `append` over a read only tags array. Because the behavior of `append` is to reuse the same internal array if there's capacity we are falling in to a race condition over multiple `append` executions.
Now, with the change, we clone the readonly tags array before appending to avoid the race condition. 
Fixes issues found while reproducing #3413 
=> (fix) internal/civisibility: fix data race due the usage of append over a read only tags

internal/appsec/waf_unit_test.go, internal/civisibility/integrations/manual_api_ddtest.go, internal/civisibility/integrations/manual_api_ddtestmodule.go, internal/civisibility/integrations/manual_api_ddtestsuite.go
This PR fixes a race condition due to using `append` over a read only tags array. Because the behavior of `append` is to reuse the same internal array if there's capacity we are falling in to a race condition over multiple `append` executions.
Now, with the change, we clone the readonly tags array before appending to avoid the race condition. 
Fixes issues found while reproducing #3413 
=> (fix) internal/civisibility: fix data race due the usage of append over a read only tags (v1)

internal/telemetry/client.go, internal/telemetry/metrics.go
This PR remove the sync.Pool usage in telemetry metrics because it created a data race 
Fixes #3413 
=> internal/telemetry: fix telemetry metric submit datarace double pool insertion

ddtrace/tracer/span.go, ddtrace/tracer/spancontext_test.go
Related to incident 37240; moves span events/links serialization to later to ensure proper locking is in place when calling these functions.
It also cherry-picks from #3427.
Supersedes #3334.
=> fix(ddtrace/tracer): postpone span events/links serialization

ddtrace/tracer/span.go, ddtrace/tracer/spancontext_test.go
Cherry-picks #3429 to `v1.73.0` upcoming release.
=> fix(ddtrace/tracer): postpone span events/links serialization (#3429)

ddtrace/tracer/propagating_tags.go
This PR fixes a potential concurrency bug introduced in #3230, the tag setting logic is using the read lock instead of write.
=> tracer: fix potential concurrency bug for trace source tag

ddtrace/tracer/span.go, ddtrace/tracer/spancontext_test.go
Follow-up from #3435 & #3427. Adds a check on `span.finished` when applying `NoDebugStack`.
Adds an extra layer of resilience on high concurrency scenarios.
=> fix(ddtrace/tracer): add finished check on NoDebugStack and WithError code branches

ddtrace/tracer/span.go
Reduces to a single locking operation everything in `Finish`'s `NoDebugStack`.
Per @felixge's [comment](https://github.com/DataDog/dd-trace-go/pull/3441/files/1b718c17e6dcce3ea626f23d8bbe152c00918d63#diff-25c42ba867d01ba68aa500adcf133d6b446bddb2b0120b20fd2f3e67b6cf62e5), there is a potential race condition in the `NoDebugStack` when finishing a span.
=> fix(ddtrace/tracer): replace RLock with Lock for NoDebugStack check to prevent race condition

ddtrace/tracer/span.go, ddtrace/tracer/span_test.go, ddtrace/tracer/stats.go, ddtrace/tracer/stats_test.go
We must ensure all internal normalization happening in the Finish() call is performed before passing the Span to the SpanConcentrator. This ensures the StatSpan has a representation of the Span after being fully finalized.
This PR is a remediation for the following 2 issues from [this list](https://docs.google.com/document/d/10ect0b8BLS9_lmO_u9rr191tJcEy0aTEbcN4zm6S1XU/edit?pli=1&tab=t.0):
* [Stats by Kind Not Computed on dd-trace-go ](https://docs.google.com/document/d/10ect0b8BLS9_lmO_u9rr191tJcEy0aTEbcN4zm6S1XU/edit?pli=1&tab=t.0#bookmark=id.pq6hidir7n84)
* [Stats Computation Performed Before Final Span Normalizations](https://docs.google.com/document/d/10ect0b8BLS9_lmO_u9rr191tJcEy0aTEbcN4zm6S1XU/edit?pli=1&tab=t.0#bookmark=id.5q1tvnlm3ppg)
See above link
Unsure? Have a question? …
=> [APM] Compute stats after span is fully finished

ddtrace/tracer/abandonedspans_test.go, ddtrace/tracer/civisibility_tslv.go, ddtrace/tracer/rules_sampler.go, ddtrace/tracer/span.go, ddtrace/tracer/tracer.go
Unexports `Span.{,R}{,Un}Lock` functions, as they were exposed in `v2` as side effect of changing `span` to `Span`.
=> fix(ddtrace/tracer): unexport Span.{,R}{,Un}Lock functions

.github/workflows/unit-integration-tests.yml, .golangci.yml, ddtrace/mocktracer/mockspan.go, ddtrace/tracer/logger_test.go, ddtrace/tracer/option.go, ddtrace/tracer/option_test.go, ddtrace/tracer/span_test.go, ddtrace/tracer/spancontext_test.go, ddtrace/tracer/telemetry.go, ddtrace/tracer/textmap_test.go, ddtrace/tracer/transport_test.go, instrumentation/appsec/dyngo/operation.go, instrumentation/instrumentation.go, internal/civisibility/integrations/gotesting/instrumentation.go, internal/civisibility/utils/ci_providers.go, internal/civisibility/utils/file_environmental_data.go, internal/civisibility/utils/impactedtests/impacted_tests.go, internal/civisibility/utils/net/http.go, internal/civisibility/utils/telemetry/telemetry_count.go, internal/contrib/telemetrytest/telemetry_test.go, internal/remoteconfig/remoteconfig.go, profiler/metrics.go
- Updated .golangci.yml to set version to "2" and adjusted linters and exclusions.
- Updated golangci-lint version in GitHub workflows from v2.7.0 to v2.8.0 and golangci_lint_version from v1.64.5 to v2.1.2.
- Made minor adjustments to put the linter at ease.
=> chore(ci): update golangci-lint configuration and version (v2) in workflows

.golangci.yml, instrumentation/instrumentation.go, internal/remoteconfig/remoteconfig.go
- Updated .golangci.yml to enable all govet checks while disabling specific checks for field alignment and shadowing (requires too many changes).
- Modified the Register function signature to accept a pointer to fix linter pointed issue.
- Added comments in remoteconfig.go to address potential issues with reflect.Value comparison in UnregisterCallback.
=> chore(ci): Enable go vet for golangci-lint

.github/workflows/system-tests.yml
Removes `APM_TRACING_E2E` scenario from `system-tests`, as it was removed in https://github.com/DataDog/system-tests/pull/4537/.
=> chore(.github/workflows): remove APM_TRACING_E2E scenario from system-tests

ddtrace/tracer/sampler_test.go
Changes the traceID given in the unit test from `5826373039044427785` to `9223372036854775808`
In #3423 I introduced a new traceID in a sampler unit test, unfortunately I used `MaxUint64/2` instead of `MaxUint*0.5` when I wrote some code to find which `TraceID * KNUTH == MaxUint64 * 0.5`.
```
maxUint64 * 0.5 9223372036854775808 (round)
maxUint64 / 2 9223372036854775807 (truncate)
```
=> sampling: fix unit test traceID for sampling

contrib/redis/go-redis.v9/go.mod, contrib/redis/go-redis.v9/go.sum, go.work.sum, instrumentation/internal/namingschematest/go.mod, instrumentation/internal/namingschematest/go.sum, internal/orchestrion/_integration/go.mod, internal/orchestrion/_integration/go.sum, orchestrion/all/go.mod, orchestrion/all/go.sum
Upgrade go-redis v9 to v9.7.3
https://github.com/DataDog/dd-trace-go/security/dependabot/64
=> [chore] upgrade go redis to v9.7.3

ddtrace/tracer/rules_sampler.go, ddtrace/tracer/span.go, ddtrace/tracer/spancontext_test.go
=> fix(ddtrace/tracer): prevent applying rate to finished spans and add test coverage for this finishing code path (#3474 backport)

contrib/net/http/http_test.go, contrib/net/http/option.go, contrib/net/http/roundtripper_test.go
Adds suggested `RTWithStatusCheck` in #3422. Also increases coverage by adding tests to the currently available `WithStatusCheck`.
Ensure that #3422 has proper tests, and it's branched out from `release-v1.73.x`.
=> feat(http): add round tripper option for status check functionality and corresponding tests

.github/workflows/all-green.yml
Add a job in the CI that runs in PR. The job will be a success if all other jobs are skipped/success, and fails otherwise
While it's possible to enforce a green CI policy using GitHub's native "required status checks" feature, doing so requires explicitly listing all job names under branch protection rules. This approach has two key drawbacks:
- It does not support optional jobs
- It introduces ongoing maintenance overhead as the job list evolves
This jobs will check ALL other job, and we'll be able to set this as a requirement. The action used offers a `ignored-name-patterns` parameters`, if at some point a job is flaky. But right now, I think all jobs are healthy.
the plan is to merge this PR, wait few days to be sure that everything is fine. Then add it as a requirement.
Unsure? Have a …
=> chore(ci): Ensure that PR are merged with a green CI

.github/workflows/system-tests.yml
Introduced in #2902, they've been deprecated.
=> chore(.github/workflows): remove unused AWS credentials from system tests

internal/civisibility/integrations/civisibility_features.go
Fix a race condition produced by modifying the ciVisibilitySettings instance from a goroutine while reading in the main thread.
The fix refactor the code to only write in the `ciVisibilitySettings` instance from `settingsInitializationOnce` other goroutines only read the settings. Also, `ciVisibilitySettings` is set only at the end of `settingsInitializationOnce` func.
fix #3500 
=> fix (internal/civisibility): Fix features load race condition [release v1.73.x]

CODEOWNERS
CODEOWNERS files always select the last place where a file is mentioned, not the first, meaning setting `**/go.{mod,sum}` before other folders does not work
Less PRs with the guild-dd-trace-go team as reviewer
=> fix codeowners order

contrib/google.golang.org/api/api_test.go
Replaces the [deprecated `Representatives` API](https://github.com/googleapis/google-api-go-client/commit/25f8d4abda5f98d9ea4dcae64dc5ac51dc296a19#diff-6a6c97dd574f01809e7dc3ab456d35a453c8ffa75ec9e51a8f689ef472a60f78L460) from `google.golang.org/api/civicinfo/v2` with `Election` API, which exists in previous versions and the current one.
Smoke tests are failing: https://github.com/DataDog/dd-trace-go/actions/runs/14881053781/job/41789069646?pr=3482#step:7:341
```
=== FAIL: .  (0.00s)
FAIL	github.com/DataDog/dd-trace-go/contrib/google.golang.org/api/v2 [build failed]
=== Errors
Error: ./api_test.go:80:6: svc.Representatives undefined (type *civicinfo.Service has no field or method Representatives)
Error: ./api_test.go:134:6: svc.Representatives undefined (type *civicinfo.Service has no …
```
=> fix(contrib/google.golang.org/api): update tests to use ElectionQuery instead of RepresentativeInfoByAddress

.github/workflows/smoke-tests.yml, internal/orchestrion/_integration/go.sum, orchestrion/all/go.mod, orchestrion/all/go.sum
Revamps smoke tests for contribs.
This builds off the work in [[ci] improve testing times for contrib tests](https://github.com/DataDog/dd-trace-go/pull/3493) to also make the contrib tests within our `Smoke Tests` run faster. This does mean using more runners, but as mentioned in the other PR, `dd-trace-go` is not a huge spender (yet), and taking up slightly more runners should have enough benefit to offset potential (minimal) costs. 
This change decreases the time for `Smoke Tests` by approx 10 minutes.
Before:
After:
=> [ci] make contrib smoke tests faster

ddtrace/internal/globaltracer.go, ddtrace/tracer/tracer_test.go
Sets the log level to debug for warning about tracer not being started when starting spans to once.
=> fix(ddtrace/internal): log to debug instead of warning when starting spans without an active tracer

instrumentation/testutils/testutils.go
Set a rate limit on the number of traces in `appsec`.
When running certain benchmarks, our logs would often get spammed with this error:
```
ERROR: appsec: too many WAF events, stopping further reporting...
```
This had several side effects, such as noise and misformating our logs (which would prevent test results from being processed correctly in CI). Since our tests do not aim (yet?) to look at _limited_ tracing, we can remove our rate limit to silence these logs.
Benchmark logs for `BenchmarkGraphQL` are [here](https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-go/-/jobs/938084350#L312).
Note: further down in the logs we have our benchmarks running on main, which we use as a point of comparison. Since this PR is not merged yet, the error logs will still appear while running …
=> [appsec] Set large appsec trace rate limit while benchmarking

profiler/compression.go, profiler/compression_test.go, profiler/metrics.go, profiler/profile.go, profiler/profile_test.go, profiler/profiler.go
For historical reasons, the profiler has used varying levels of
compression for different profile types (no compression, gzip-1 and
gzip-6). This has been identified as target for cost optimization,
see PROF-11815.
Refactor the compression related code in order to pave the path for
introducing a new compression strategy, which will most likely be based
on zstd.
This patch should not have any observable impact. Profiles are expected
to be uploaded with exactly the same compression settings as before, and
the performance is expected to stay exactly the same as well.
Introduce a dedicated compressor for each profile type that handles
converting the profile data produced by it from the existing compression
(gzip-1 or no compression) to the desired output compression.
Update delta profiles and …
=> refactor(profiler): centralize compression logic

ddtrace/tracer/api.txt, scripts/apiextractor/.gitignore, scripts/apiextractor/_testdata/dummy/dummy.go, scripts/apiextractor/_testdata/expected_output.txt, scripts/apiextractor/api_extractor.go
Addresses the issue on https://github.com/DataDog/dd-trace-go/actions/runs/15140015964/job/42565830420
Follow-up to https://github.com/DataDog/dd-trace-go/pull/3526
Fixes the API extractor to format array types without including AST position information. This prevents unnecessary diffs in the API stability check caused by internal compiler data.
- Changed the return type of the TraceIDBytes method in the SpanContext interface from a specific literal to a fixed-size byte array.
- Added a new .gitignore file for the apiextractor directory to exclude generated files.
- Enhanced api_extractor.go to handle BasicLit expressions in formatExpr.
- Introduced ArrayTestType with array fields in expected_output.txt and dummy.go for testing …
=> fix(tools/apiextractor): Add better support for type literals

internal/civisibility/integrations/gotesting/coverage/test_coverage.go, internal/civisibility/integrations/gotesting/instrumentation_orchestrion.go
This PR enables the internal api used to get the global code coverage value on Test Impact Analysis scenario to a normal code coverage scenario.
This Go `testing.Coverage()` api is returning a different percentage from the one reported in the stdout. This issue started when the new code coverage algorithm started to be the default algorithm.
See: https://github.com/golang/go/issues/62212
Example:
```log
--- PASS: TestValue (0.00s)
PASS
coverage: 100.0% of statements
testing.Coverage() 25
....
2025/05/22 15:23:38 Datadog Tracer v2.1.0-dev.2 DEBUG: civisibility: done.
ok      awesomeProject10/package1       1.092s  coverage: 100.0% of statements
```
By switching to our internal api (the internal api uses the same mechanism as the stdout format)
=> fix (internal/civisibility): use internal code coverage api to get the total percentage.

ddtrace/opentelemetry/otel_test.go
Adapts assertions to allow `otelhttp` related test according to its version, as `v0.61.0` introduces a new default semantic conventions version. 
Allow our smoke tests to handle the breaking change.
=> feat(ddtrace/opentelemetry): update expected span names based on `otelhttp` version

ddtrace/tracer/api.txt, ddtrace/tracer/tracer.go
These functions are exported and not used in our repository. They were introduced during `v2` development, and have been deemed as not needed.
[Chunk](https://github.com/DataDog/dd-trace-go/pull/2408/files#diff-ad86e517e9501587fea706a500cf65dbf92b14f3c3bfc3f821194125a3c79d46R449) was exported in #2408. Its fields were unexported later, so it's an opaque type that needs to be exported for `mocktracer`.
Once we remove/improve the `mocktracer`, we'll be able to unexport it again. As it's opaque and there isn't public API using it, it won't be a breaking change for external users.
Reduce API.
=> chore(ddtrace/tracer): remove unused exported functions

ddtrace/tracer/tracer.go, ddtrace/tracer/tracer_test.go
This commit fixes a regression on v2 where empty TraceChunks may be flushed and sent to the trace-agent.
The fix is to check whether there are spans to the added to the trace writer, and never add empty spans. This was how v1 handled this logic as well.
Summary of the issue:
* After the merge on dd-go last Friday, the agent starts reporting considerably more traces from service:datadog-agent. See [here](https://app.datadoghq.com/metric/explorer?fromUser=false&state=H4sIAAAAAAAAE12R62rDMAyF30U_hylJ2q2dX2UUY2I5FfiSWk4hDXn3ofQy2D_p8PnoSF7ghoUpJ9DQNd3BtK1pWlAwFDteGPTPAg49JaobtEClGhA0gHqUhukuffv1VmygQQwD-iriPApQKSJjIWRQUPA6IdfHgII85sRofC7R1v_sdXpUgiYbxUukWWI6W63hPJVe5Ii1UP96M4MGexs0z1wx7vpx2k2MZflYYT0rkGFTsA_fZ_NnvZ7X8yoYj4GqcRQxyZ0Ef6t9Tp6GzSBQpAq6bRRwLlUulYvDAhoccg-bl6zly7bCAlytcO3xcPzuTl3XfD …
=> [APM] Ensure empty chunks are not flushed

profiler/compression.go
For https://github.com/DataDog/dd-trace-go/pull/3555
This avoids the need for the lazy initialization of the err channel, and also reuses the writer instances which has a small (but probably non-significant) performance benefit.
=> refactor(profiler): simplify the compressionStrategy parsing

contrib/net/http/orchestrion.client.yml, ddtrace/tracer/option.go, ddtrace/tracer/option_test.go, internal/civisibility/utils/net/http.go, internal/orchestrion/_integration/internal/agent/agent.go, internal/orchestrion/_integration/internal/harness/harness.go, internal/telemetry/internal/writer.go
This PR was originally made to fix an issue where traces where generated on orchestrion apps from the calls made inside dd-trace-go's telemetry client. Which later revealed that any part of the tracer was susceptible to auto-tracing if a call to `tracer.Start` is made using the option `WithHTTPClient` 
This PR also add tests at the orchestrion testing framework harness level to make sure this does not happen anymore.
=> orchestrion: don't trace the tracer even if tracer.Start(tracer.WithHTTPClient(...)) is called

.gitlab/benchmarks.yml
Changes the branch off which we run our benchmarks
**IMPORTANT**: Reviewers should look at the new benchmarking-platform branch linked below, as that is where the changes to code have been made. This PR only updates our CI to point at this new branch. The new benchmarking-platform code has been branched off of `hannahkm/bp-runner-2` ([link](https://github.com/DataDog/benchmarking-platform/blob/hannahkm/bp-runner-2/steps/run-benchmarks.sh))
The new `benchmarking-platform` [branch](https://github.com/DataDog/benchmarking-platform/blob/hannahkm/parallel2/steps/run-benchmarks.sh) introduces a few checks that allows us to run benchmarks a little quicker. The changes being:
1. Automatically running through valid directories to run benchmarks in, rather than hardcoding them ourselves
2. Checking …
=> ci: run benchmarks in parallel (part 2)

ddtrace/tracer/span.go, ddtrace/tracer/span_test.go, ddtrace/tracer/spancontext.go
Replaces `atomic.*Int32` functions with `atomic.Int32` value and functions to avoid race conditions.
=> refactor: replace atomic operations with atomic.Int32 for error tracking in SpanContext

ddtrace/tracer/remote_config_test.go, internal/remoteconfig/remoteconfig.go
Fix deadlock reported in #3541.
=> fix(ddtrace/tracer): add test and fix for deadlock issue #3541 in remote configuration

internal/civisibility/integrations/gotesting/coverage/test_coverage.go, internal/civisibility/integrations/gotesting/coverage/test_coverage_test.go
Removes the stdout replacement while extracting the coverage of a test due to a possible race condition with any function writing to stdout at the same time.
```log
Read at 0x000002334aa8 by goroutine 54:
fmt.Printf()
/opt/hostedtoolcache/go/1.23.10/x64/src/fmt/print.go:233 +0x145
github.com/DataDog/dd-trace-go/v2/internal/civisibility/integrations/gotesting.setUpHTTPServer.func1()
/home/runner/work/dd-trace-go/dd-trace-go/internal/civisibility/integrations/gotesting/testcontroller_test.go:995 +0xa8
net/http.HandlerFunc.ServeHTTP()
/opt/hostedtoolcache/go/1.23.10/x64/src/net/http/server.go:2220 +0x47
net/http.serverHandler.ServeHTTP()
/opt/hostedtoolcache/go/1.23.10/x64/src/net/http/server.go:3210 +0x2a1
net/http.(*conn).serve() …
```
=> fix (internal/civisibility): fix code coverage stdout data race

internal/telemetry/globalclient.go
This PR fix a case where, inside the `sync.Once.Do` a call to the same `sync.Once` was done, ending up in a deadload.
Fix tests timeout-ing
=> internal/telemetry: fix deadlock when recorder queue is full

instrumentation/logger.go
This PR stops reporting all contriberrors that would be on stdout to telemetry.
Partial revert of: https://github.com/DataDog/dd-trace-go/pull/3294/files
Some logs can incluse sensitive data. 
=> instrumentation: stop sending telemetry logs for each log a contrib would send to stdout

contrib/database/sql/internal/dsn.go, contrib/database/sql/internal/dsn_test.go
This PR enhances error handling in the database/sql contrib package by ensuring that sensitive information in database connection strings is properly sanitized before being logged or included in error messages.
- Added comprehensive sanitization functions for various DSN formats (MySQL, PostgreSQL, SQL Server)
- Enhanced error logging to prevent credential exposure in application logs
- Implemented robust pattern matching for different connection string formats
- Added test coverage for edge cases and different DSN patterns
This change proactively ensures that database credentials and other sensitive connection details are never exposed in error messages or debug logs, following security best practices for credential handling.
- New test cases covering various DSN formats and edge cases
- …
=> contrib/database/sql: sanitize sensitive data in error messages

CONTRIBUTING.md
This change adds brief and generic documentation about how to handle test unreliability
This change aims to make it easier for new contributors to become effective in this repo.
=> add recipe for handling flaky tests [LANGPLAT-352]

contrib/aws/aws-sdk-go-v2/aws/aws.go, contrib/aws/aws-sdk-go-v2/aws/aws_test.go
Moves `span.Finish()` back to the middleware func where the span is created.
The span finish was moved to its current location in https://github.com/DataDog/dd-trace-go/pull/3083, but in cases where the entire middleware stack is not traversed (e.g. [presign requests](https://github.com/aws/aws-sdk-go-v2/blob/29bbb566e87daa8cf4b0ea93546b92f19c15cf39/aws/signer/v4/presign_middleware.go#L69)) the span may never be finished.
see https://github.com/DataDog/dd-trace-go/issues/3696
=> [contrib/aws] finish span in middleware func where it was created

.golangci.yml
Add depguard configuration to prevent usage of standard "log" package
and enforce usage of "github.com/DataDog/dd-trace-go/v2/internal/log"
instead. This ensures consistent logging standards across the codebase.
Exceptions are configured for:
- Scripts and tools that need standard logging
- Test files including example tests
- The internal/log/log.go wrapper itself
- log/slog structured logging package (different from standard log)
=> chore(linter): add depguard linter to enforce logging standards

internal/civisibility/integrations/gotesting/instrumentation_orchestrion.go, internal/civisibility/integrations/gotesting/testing.go
We are incorrectly tagging the tests with the `TestAttemptToFixPassed` flag when we are not in an `Attempt to fix` execution, this PR solves that.
Fix the tagging issue.
=> (fix) internal/civisibility: fix the attempt-to-fix-passed tag

scripts/ci-test-contrib.sh
Pins `kube-openapi` to a previous version.
`kube-openapi` recently upgraded their version of `structured-merge-diff` from `v4` to `v6`. However, `apimachinery` , which imports both `kube-openapi` and `structured-merge-diff` is still using `structured-merge-diff@v4`. This was causing our smoke tests to fail. To temporarily resolve this issue and unblock CI, we pin the version of `kube-openapi` when running smoke tests to the latest version before they upgraded.
The error:
```
Error: /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.33.2/pkg/util/managedfields/internal/typeconverter.go:51:61: cannot use typeSchema.Types (variable of type []"sigs.k8s.io/structured-merge-diff/v6/schema".TypeDef) as []"sigs.k8s.io/structured-merge-diff/v4/schema".TypeDef value in struct literal
```
This …
=> [chore] pin k8s version to prevent incompatible types

.github/workflows/orchestrion.yml
This PR sets the usage of `ubuntu-8-cores-latest` runners for Orchestrion - Integration Tests (ubuntu)
=> ci: Use ubuntu-8-core-latest for Orchestrion - Integration Tests (ubuntu)

.github/workflows/docker-build-and-push.yml, .github/workflows/docker-images-release.yml, contrib/envoyproxy/go-control-plane/cmd/serviceextensions/Dockerfile, contrib/envoyproxy/go-control-plane/cmd/serviceextensions/main.go
This PR:
- refactor the way default environment variables are set
- enable appsec standalone
- set the default waf timeout for proxy to `10ms`
- enable the API Security proxy sampler
- set the DD_VERSION tag from the release process to correctly set custom tags that doesn't follow the tracer version (ex: `-docker.0`)
=> contrib/envoyproxy: update default env vars

.github/workflows/appsec.yml, .github/workflows/docker-build-and-push.yml
This PR updates the runner for ARM builds to use the new `ubuntu-24.04-arm` runner from GitHub.
Using a new runner image to improve CI.
=> chore(ci): use new ubuntu-24.0.4-arm runner

ddtrace/tracer/span_test.go
Skips checks related to time.Duration when running on Windows.
https://github.com/DataDog/dd-trace-go/pull/3709 introduced a new metric that does not have accurate counting on Windows.
=> fix: errorstack duration checks failing on Windows

contrib/hashicorp/vault/option.go, contrib/hashicorp/vault/vault.go
Improve Go doc of package `contrib/hashicorp/vault` by using [godoc links](https://go.dev/doc/comment#doclinks).
Improved readability of the documentation thanks to cross links.
=> contrib/hashicorp/vault: add godoc links

CONTRIBUTING.md, ddtrace/mocktracer/mocktracer.go, ddtrace/mocktracer/mocktracer_test.go, ddtrace/tracer/civisibility_transport_test.go, ddtrace/tracer/civisibility_writer_test.go, ddtrace/tracer/metrics_test.go, ddtrace/tracer/option.go, ddtrace/tracer/option_test.go, ddtrace/tracer/sampler_test.go, ddtrace/tracer/span_test.go, ddtrace/tracer/spancontext_test.go, ddtrace/tracer/telemetry.go, ddtrace/tracer/textmap_test.go, ddtrace/tracer/tracer.go, ddtrace/tracer/tracer_test.go, ddtrace/tracer/transport.go, ddtrace/tracer/transport_test.go, ddtrace/tracer/writer_test.go
Check that `ddtrace/tracer` tests don't leak goroutines using `go.uber.org/goleak`. This required fixing a lot of code, see the individual commits for details. It's possible that some of these goroutines leaks could have impacted customers, but I suspect most of them are just issues for testing.
I keep having the following experience while working on enabling runtime metrics v2 by default:
* Make a change
* Run the `ddtrace/tracer` tests and observe a failing test case
* Re-run the individual test case that failed
* Observe that the test case doesn't fail now
The root cause is always the same: Global state pollution by some previous test interfering with the assertions made by the current test.
There are two primary types of global state pollution in our tests:
1. Package level variables …
=> chore(ddtrace/tracer): check for goroutine leaks

internal/civisibility/integrations/gotesting/testcontroller_test.go, internal/civisibility/integrations/manual_api_ddtest.go
This PR adds the test source file and codeowners tag to the suite span in Test Optimization.
A customer is asking for this and it is a low hanging fruit.
Jira: https://datadoghq.atlassian.net/browse/SDTEST-2375
=> feat(internal/civisibility): add source file and codeowners tags to the suite span

internal/civisibility/utils/ci_providers.go, internal/civisibility/utils/testdata/fixtures/providers/awscodepipeline.json, internal/civisibility/utils/testdata/fixtures/providers/azurepipelines.json, internal/civisibility/utils/testdata/fixtures/providers/buildkite.json, internal/civisibility/utils/testdata/fixtures/providers/circleci.json, internal/civisibility/utils/testdata/fixtures/providers/github.json, internal/civisibility/utils/testdata/fixtures/providers/gitlab.json
This PR fixes the `ci.job.id` span tag for the BuildKite CI provider. Also updates the providers json testdata
The spec tests were failing because of this bug.
=> fix(internal/civisibility): fix buildkite ci.job.id tag

internal/civisibility/constants/git.go, internal/civisibility/utils/ci_providers.go, internal/civisibility/utils/ci_providers_test.go
This PR fixes the use of the base branch sha value, we thought this sha was the BASE sha, but we realized it is the HEAD sha of the base branch.
JIRA: https://datadoghq.atlassian.net/browse/SDTEST-2353
=> fix(internal/civisibility): fix base branch SHA usage.

.github/chainguard/self.ecosystems-label-issue.sts.yaml, .github/chainguard/self.ecosystems-label-pr.sts.yaml
Add two new policies needed to migrate `ecosystems-label-pr.yml` and `ecosystems-label-issue.yml` workflows away from PAT.
=> ci: add new sts policies for ecosystems-label checks

contrib/envoyproxy/go-control-plane/cmd/serviceextensions/main.go, contrib/envoyproxy/go-control-plane/envoy.go, contrib/envoyproxy/go-control-plane/envoy_test.go, contrib/envoyproxy/go-control-plane/example_test.go, contrib/envoyproxy/go-control-plane/message_processor.go, contrib/envoyproxy/go-control-plane/request_state.go, go.work.sum
This PR refines how the value of the component tag is selected for the GCP Service Extension/Envoy/Istio integration.
#### Changes
- The `AppsecEnvoyConfig` is now taking an `Integration` value instead of an `IsGCPServiceExtension` bool.
- Updated the envoy component from `envoyproxy/go-control-plane` to `envoy` (The UI currently doesn't use any of the tag component to show the correct proxy icon in the service catalog, so it's safe to change)
At first, the Service Extension callout image was only used for GCP Service Extension. However today it's also used and advertised for an Envoy integration. The component tag could be used to determine which integration type is it in the UI.
This could be configured in 2 ways:
- By code: When registering the `ExternalProcessorServer`, the …
=> contrib/envoyproxy: refine component detection

.github/workflows/smoke-tests.yml, internal/setup-smoke-test/Dockerfile
Migrates `CMD`/`ENTRYPOINT` instructions to use JSON arguments, and changes the non-complaint alias on `FROM scratch` instruction, as warned by Docker while building images on our smoke tests.
=> fix(internal/setup-smoke-test): use JSON arguments for CMD/ENTRYPOINT and change alias in FROM scratch

.github/workflows/docker-build-and-push.yml, .github/workflows/docker-images-release.yml, contrib/envoyproxy/go-control-plane/cmd/serviceextensions/Dockerfile, contrib/k8s.io/gateway-api/cmd/request-mirror/Dockerfile
This PR removes the commit sha tag that is added to all docker images released (service extension callout and request mirror). The commit sha is now set as a label.
Less orhpan tags in the registry for a better visibility of all released versions tags.
=> ci: remove commit sha tag from released images and add it as container label

.github/chainguard/self.outdated-integrations.sts.yaml
Migrates the last pending PAT usage in `dd-trace-go`: `outdated-integrations` workflow.
=> feat(.github/chainguard): add outdated integrations policy for STS migration

.github/workflows/needs-triage.yml, .github/workflows/outdated-integrations.yml
Depens on #3842.
Migrates GitHub workflow `outdated-integrations.yml` to use STS.
=> feat(.github/workflows): Migrate outdated integrations to use STS

.github/workflows/multios-unit-tests.yml
Fixes `.github/workflows/multios-unit-tests.yml` to work on Windows runners.
CI is unhappy. Enter evidences [A](https://github.com/DataDog/dd-trace-go/actions/runs/16723754002/job/47333990045#step:3:107) & [B](https://github.com/DataDog/dd-trace-go/actions/runs/16723754002/job/47333990044#step:3:104).
=> fix(.github/workflows): Add path normalization function to convert forward slashes to backslashes on Windows runners

ddtrace/tracer/payload.go
Modifies `payload.push` function signature to internalize the usage of `spanList` into the function.
This PR supports a new trace protocol encoding. The proposed protocol change is expected to improve message size and flexibility, leading to bandwidth savings and easier addition of new features, while also offering significant improvements in serialization time, memory allocations, and compressed data output.
At tracer initialization we'll detect which trace protocol to use, and therefore switch over one encoding or the other by wrapping the `[]*Span` value as `spanList` or the newer encoding type. It's also nicer to use the API types instead of an internal one that's an alias.
No benchmark impact was detected locally.
=> refactor(ddtrace/tracer): prepare payload.push for supporting v1 trace protocol

.github/chainguard/self.outdated-integrations.sts.yaml
Removes `event_name` in `.github/chainguard/self.outdated-integrations.sts.yml` to ensure the policy works for the script's requirements.
=> fix(.github/chainguard): Remove event_name field in outdated integrations policy

.github/workflows/docker-build-and-push.yml
This PR removes the installation of Docker inside the arm64 runner.
The release of the docker images linked to the release of the go tracer [failed](https://github.com/DataDog/dd-trace-go/actions/runs/16882325191). The job building running in the arm64 runner was failing when installing docker. This was previously required because we were using the runner image `arm-4core-linux` and it has been changed to use `ubuntu-24.04-arm` in this [PR](https://github.com/DataDog/dd-trace-go/pull/3783).
However now in the new runner, docker is already installed by default (everything listed [here](https://github.com/actions/partner-runner-images/blob/main/images/arm-ubuntu-24-image.md)).
This issue was not detected before while building and running the system tests because the system tests are running …
=> ci: fix docker images releases

internal/civisibility/integrations/gotesting/testcontroller_test.go
This PR reduce the logs verbosity in the gotesting tests. It also execute the test in serial mode to reduce the chance of the git shallow lock warning message to happen.
When something fails it's hard to read the CI logs due too much logs entries.
=> chore(internal/civisibility): reduce civisibility gotesting tests verbosity

contrib/net/http/orchestrion.client.yml, internal/orchestrion/_integration/net_http/generated_test.go, internal/orchestrion/_integration/net_http/global_functions.go
Fixes https://github.com/DataDog/orchestrion/issues/670
The core issue is solved in https://github.com/DataDog/orchestrion/pull/678, but this should make it work even if using older Orchestrion versions.
=> fix(contrib/net/http): workaround to fix symbol collision in Orchestrion

profiler/profile.go, profiler/profile_test.go
This change supports configuration use cases where the profile type is parsed from text sources like environment variables or config file, such that the parsed values can be passed to `profiler.WithProfileTypes`.
Question for reviewers, should I implement a `MarshalText` method as well for completeness? These methods are related because `UnmarshalText` is expected to be able to unmarshal the output from `MarshalText`.
Related to discussion: https://github.com/DataDog/dd-trace-go/discussions/3872
=> feat(profiler): implement ProfileType.UnmarshalText method

.github/workflows/smoke-tests.yml, contrib/gorilla/mux/mux_test.go
Adds `fail-fast: false` to smoke tests running contribs.
Previously, failing one contrib test would cause all contrib smoke tests to be cancelled and end early. This prevents us from seeing other failures that might exist. 
=> chore: prevent smoke tests from failing-fast

.gitlab/bp-runner.fail-on-breach.yml
Aligns bp-runner.fail-on-breach names to macrobenchmarks. Follow up of #3875.
=> chore(.gitlab): align bp-runner.fail-on-breach names to macrobenchmarks

.github/workflows/pull-request-title-validation.yml
Fixes the regexp used to validate PR titles in conventional commits.
This [PR](https://github.com/DataDog/dd-trace-go/pull/3928) is failing. Here is the [job passing](https://github.com/DataDog/dd-trace-go/actions/runs/17323072380/job/49180546106?pr=3929) with the fix (same title used)
=> ci: fix PR title validation regexp

ddtrace/tracer/tracer.go
This PR moves the tracer startup log AFTER appsec has started to be able to log the right value of it being enabled or not
To be able to log the right value of appsec being enabled or not.
=> fix(ddtrace/tracer): move startup log after appsec has started

.github/workflows/all-green.yml, .github/workflows/api-check.yml, .github/workflows/appsec.yml, .github/workflows/codeql-analysis.yml, .github/workflows/ecosystems-label-pr.yml, .github/workflows/generate.yml, .github/workflows/govulncheck.yml, .github/workflows/main-branch-tests.yml, .github/workflows/multios-unit-tests.yml, .github/workflows/orchestrion.yml, .github/workflows/parametric-tests.yml, .github/workflows/pull-request-title-validation.yml, .github/workflows/pull-request.yml, .github/workflows/smoke-tests.yml, .github/workflows/static-checks.yml, .github/workflows/system-tests.yml, .github/workflows/unit-integration-tests.yml, .github/workflows/update-supported-versions-doc.yml
Updates workflows so `main` CI checks happen during a merge queue run. Specifically it marks all workflows that run in push events to `main` to run on those events on branches starting with `mq-working-branch`.
Additionally:
- Standardises `pull_request` triggers to explicitly set `opened`, `reopened`, and `synchronized` default states.
- Standardises `tags-ignore` for `push` triggers to ignore all nested modules' version tags.
- Removes `merge_group` triggers.
- Removes `synchronized` event on `pull-request-title-validation`.
- Updates Go version to the highest supported one on `pull-request` workflow.
- Swaps `main-branch-tests` with `pull-requests`, making sure any flakiness is early detected.
- `main-branch-tests` run only high-signal `unit-integration-tests` with a smaller set.
- …
=> chore(.github/workflowsw): move `main` CI checks to merge queue runs

.gitlab/macrobenchmarks.yml
- Simplify `check-slo-breaches` by using a template: https://github.com/DataDog/benchmarking-platform-tools/blob/main/images/templates/gitlab/check-slo-breaches.template.yml.
https://datadoghq.atlassian.net/browse/APMSP-2198
Here's a successful `check-slo-breaches` run: https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-go/-/jobs/1110708892
=> feat(ci): update check-slo-breaches to use a template

.gitlab/configuration-central-validation.yml
We found a bug in the libdatadog CI scripts related to config centralization. The CI job ran upon tagging a release with the current import URL has an hardcoded language value to `nodejs`. 
I fixed it on the script and we need to import the new ones to have it correctly tagged.
⚠️  This will need to be cherry-picked into the ongoing release to avoid tagging golang keys are nodejs (with our tags, this would create a mess)
=> ci: update import url for one-pipeline scripts

ddtrace/tracer/metrics_test.go
PR by [Bits](https://app.datadoghq.com/code?session_id=475f81a8-71b6-464b-8798-a6512321592f) : [Fix test TestSpansStartedTags](https://app.datadoghq.com/code/f199aa20-40f5-4f60-abb5-5edb355812e8) automatically detected by [Flaky Test monitoring](https://app.datadoghq.com/ci/test/flaky?query=%40git.repository.id_v2%3A%22github.com%2Fdatadog%2Fdd-trace-go%22+%40test.name%3A%22TestSpansStartedTags%22).
You can ask for changes by mentioning @Datadog in a comment.
Feedback (especially what can be better) welcome in [#code-gen-feedback](https://dd.enterprise.slack.com/archives/C07JA5N2D25)!
---
Replaces the fixed-time wait in TestSpansStartedTags with assert.Eventually to wait for the spans_started metric to reach 1. This change is applied in two places in ddtrace/tracer/metrics_test.go.
The …
=> fix(ddtrace/tracer): TestSpansStartedTags

instrumentation/net/http/pattern/pattern.go, instrumentation/net/http/pattern/pattern_test.go
The `instrumentation/net/http/pattern` package was moved by #3853. The
`contrib/net/http/v2` module depends on that package at version v2.2.3. As a
result, that verison of `contrib/net/http/v2` won't be able to use newer
versions of the main module. This is a breaking change. This PR restores the
deleted package. While the current `contrib/net/http/v2` package doesn't use it
any more, this maintains compatibility with previous versions.
=> fix(instrumentation): restore deleted net/http/pattern package

ddtrace/tracer/context.go, internal/llmobs/span.go, llmobs/eval_metrics.go, llmobs/llmobs.go
Refactors all the public API for `llmobs` to avoid returning interfaces in favour of concrete values.
Interfaces are contracts. Changing them is a breaking change.
It's true that @rarguelloF's implementation adds an unexported function to the interface (`sealed`) to avoid people using the interface, but another reason for preferring concrete types is that other packages across the same API are returning concrete types. An API with mixed signatures, some returning interfaces and other concrete values, doesn't feel properly designed.
It also allows to remove multiple interfaces and supporting code that was required to work around the interfaces.
As a downside, I recognize that the nil handling isn't convenient for developers, and I couldn't return nil values from some functions due to all …
=> feat(llmobs): refactor public API to use concrete types

.github/workflows/all-green.yml
Adds `label_issues` to the ignored jobs so `all-jobs-are-green` don't fail on it.
=> chore(.github/workflows): ignore label_issues in all-jobs-are-green job

ddtrace/tracer/sampler_test.go
When a span is finished writes to meta/metrics require the lock to be held. This is due to first span of the first chunk calling `setMeta` which both calls a delete on metrics map and inserts in meta map.
Test calls need to be protected to avoid the flake
=> fix: flaky test
